export const database: unknown[] = [
  {
    "Agricultural Fields Mosaic": {
      environment_title: "Agricultural Fields Mosaic",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Agricultural Fields Mosaic (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11377757,
          file_size_megabytes: 10.85,
          width: 3072,
          height: 5472,
          primary: "#7b5731",
          secondary: "#9b7248",
          tertiary: "#253411",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#564025",
          hex_5: "#4f682c",
          hex_6: "#07120e",
          hex_7: "#84905f",
          hex_8: "#283d3e",
          hex_9: "#837f6f"
        },
        {
          original_file_name: "Agricultural Fields Mosaic (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11234783,
          file_size_megabytes: 10.71,
          width: 3072,
          height: 5472,
          primary: "#79572d",
          secondary: "#183416",
          tertiary: "#a97d34",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#514621",
          hex_5: "#828970",
          hex_6: "#68727d",
          hex_7: "#213f52",
          hex_8: "#526735",
          hex_9: "#9c5c34"
        },
        {
          original_file_name: "Agricultural Fields Mosaic (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11601873,
          file_size_megabytes: 11.06,
          width: 3072,
          height: 5472,
          primary: "#5a5426",
          secondary: "#173417",
          tertiary: "#997438",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#c09e70",
          hex_5: "#696f66",
          hex_6: "#7b8625",
          hex_7: "#8c9b93",
          hex_8: "#36230b",
          hex_9: "#a3b29c"
        },
        {
          original_file_name: "Agricultural Fields Mosaic (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11842200,
          file_size_megabytes: 11.29,
          width: 3072,
          height: 5472,
          primary: "#1b3f1c",
          secondary: "#7b4218",
          tertiary: "#9c6330",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#58321f",
          hex_5: "#5a672f",
          hex_6: "#849066",
          hex_7: "#380e11",
          hex_8: "#5c5b4c",
          hex_9: "#80847c"
        }
      ]
    },
    "Autumn Forest Canopy": {
      environment_title: "Autumn Forest Canopy",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Autumn Forest Canopy (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10657157,
          file_size_megabytes: 10.16,
          width: 3072,
          height: 5472,
          primary: "#d37a1a",
          secondary: "#432910",
          tertiary: "#954d16",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#10150f",
          hex_5: "#958b20",
          hex_6: "#733812",
          hex_7: "#686622",
          hex_8: "#bd2724",
          hex_9: "#6e6765"
        },
        {
          original_file_name: "Autumn Forest Canopy (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10111408,
          file_size_megabytes: 9.64,
          width: 3072,
          height: 5472,
          primary: "#d58716",
          secondary: "#221a0d",
          tertiary: "#965012",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6f3f12",
          hex_5: "#918b24",
          hex_6: "#515d22",
          hex_7: "#53270f",
          hex_8: "#be371c",
          hex_9: "#3e3a48"
        },
        {
          original_file_name: "Autumn Forest Canopy (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10067155,
          file_size_megabytes: 9.6,
          width: 3072,
          height: 5472,
          primary: "#d97f18",
          secondary: "#914b15",
          tertiary: "#19170c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5f6020",
          hex_5: "#622e0f",
          hex_6: "#43260e",
          hex_7: "#9a8e34",
          hex_8: "#c9291c",
          hex_9: "#74444c"
        },
        {
          original_file_name: "Autumn Forest Canopy (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10048891,
          file_size_megabytes: 9.58,
          width: 3072,
          height: 5472,
          primary: "#dc861d",
          secondary: "#914b14",
          tertiary: "#18140b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#632e0e",
          hex_5: "#5c6424",
          hex_6: "#43240d",
          hex_7: "#919338",
          hex_8: "#c33524",
          hex_9: "#1a3449"
        }
      ]
    },
    "Coastal Island Archipelago": {
      environment_title: "Coastal Island Archipelago",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Coastal Island Archipelago (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8934684,
          file_size_megabytes: 8.52,
          width: 3072,
          height: 5472,
          primary: "#639fc8",
          secondary: "#0d3c55",
          tertiary: "#d0d0c0",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3a76a0",
          hex_5: "#60663f",
          hex_6: "#5c8264",
          hex_7: "#41b2ad",
          hex_8: "#2f3a12",
          hex_9: "#9e9456"
        },
        {
          original_file_name: "Coastal Island Archipelago (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7544442,
          file_size_megabytes: 7.19,
          width: 3072,
          height: 5472,
          primary: "#0c3754",
          secondary: "#bbcbc2",
          tertiary: "#5ca6c4",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#418f9d",
          hex_5: "#556c69",
          hex_6: "#306898",
          hex_7: "#69b2ab",
          hex_8: "#4c531f",
          hex_9: "#9a9157"
        },
        {
          original_file_name: "Coastal Island Archipelago (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10565594,
          file_size_megabytes: 10.08,
          width: 3072,
          height: 5472,
          primary: "#cddac3",
          secondary: "#4489c5",
          tertiary: "#2c4433",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#1c649b",
          hex_5: "#5c9085",
          hex_6: "#84babe",
          hex_7: "#6d7248",
          hex_8: "#205c6e",
          hex_9: "#071a31"
        },
        {
          original_file_name: "Coastal Island Archipelago (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9172308,
          file_size_megabytes: 8.75,
          width: 3072,
          height: 5472,
          primary: "#1a343a",
          secondary: "#c3c4b5",
          tertiary: "#2f7394",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4c94be",
          hex_5: "#5c6439",
          hex_6: "#11536f",
          hex_7: "#5c846f",
          hex_8: "#73b1a2",
          hex_9: "#a48c54"
        }
      ]
    },
    "Coastal Shoreline Pattern": {
      environment_title: "Coastal Shoreline Pattern",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Coastal Shoreline Pattern (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9388379,
          file_size_megabytes: 8.95,
          width: 3072,
          height: 5472,
          primary: "#cabdb0",
          secondary: "#105166",
          tertiary: "#7f827d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#93b6c7",
          hex_5: "#4a3e2d",
          hex_6: "#0c6297",
          hex_7: "#af7c51",
          hex_8: "#428893",
          hex_9: "#9ab4b2"
        },
        {
          original_file_name: "Coastal Shoreline Pattern (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8894878,
          file_size_megabytes: 8.48,
          width: 3072,
          height: 5472,
          primary: "#a89988",
          secondary: "#0e5569",
          tertiary: "#587572",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#735735",
          hex_5: "#d2dfe7",
          hex_6: "#dec7b3",
          hex_7: "#ead9c4",
          hex_8: "#5d5247",
          hex_9: "#368bb7"
        },
        {
          original_file_name: "Coastal Shoreline Pattern (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9175998,
          file_size_megabytes: 8.75,
          width: 3072,
          height: 5472,
          primary: "#c9c0b3",
          secondary: "#104e5d",
          tertiary: "#388e8c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#636257",
          hex_5: "#222623",
          hex_6: "#75b3ae",
          hex_7: "#78a1b7",
          hex_8: "#071a39",
          hex_9: "#946c4c"
        },
        {
          original_file_name: "Coastal Shoreline Pattern (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8700557,
          file_size_megabytes: 8.3,
          width: 3072,
          height: 5472,
          primary: "#c8c3ba",
          secondary: "#0b3740",
          tertiary: "#5a93b8",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#61858d",
          hex_5: "#86b2cb",
          hex_6: "#1f668c",
          hex_7: "#6c5f4d",
          hex_8: "#196464",
          hex_9: "#9c6c46"
        }
      ]
    },
    "Desert Dunes In Perspective": {
      environment_title: "Desert Dunes In Perspective",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Desert Dunes In Perspective (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9234505,
          file_size_megabytes: 8.81,
          width: 3072,
          height: 5472,
          primary: "#a06c3d",
          secondary: "#253543",
          tertiary: "#f2c684",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#e6a45f",
          hex_5: "#603e24",
          hex_6: "#55280e",
          hex_7: "#6a9cb9",
          hex_8: "#8d8381",
          hex_9: "#4494b0"
        },
        {
          original_file_name: "Desert Dunes In Perspective (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7775806,
          file_size_megabytes: 7.42,
          width: 3072,
          height: 5472,
          primary: "#7e593c",
          secondary: "#19222f",
          tertiary: "#f3ce96",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#eaa75d",
          hex_5: "#7aa3c5",
          hex_6: "#757985",
          hex_7: "#b69a80",
          hex_8: "#49220d",
          hex_9: "#3b7cae"
        },
        {
          original_file_name: "Desert Dunes In Perspective (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7555963,
          file_size_megabytes: 7.21,
          width: 3072,
          height: 5472,
          primary: "#d09150",
          secondary: "#171f2a",
          tertiary: "#5a3723",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6d4e39",
          hex_5: "#86bedd",
          hex_6: "#fbce84",
          hex_7: "#f0bc80",
          hex_8: "#8a5733",
          hex_9: "#329bc8"
        },
        {
          original_file_name: "Desert Dunes In Perspective (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8520399,
          file_size_megabytes: 8.13,
          width: 3072,
          height: 5472,
          primary: "#d3955d",
          secondary: "#2d211a",
          tertiary: "#764f33",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5f371d",
          hex_5: "#f5ce98",
          hex_6: "#955f37",
          hex_7: "#fbc887",
          hex_8: "#935520",
          hex_9: "#49545c"
        }
      ]
    },
    "Desert Road Through Dunes": {
      environment_title: "Desert Road Through Dunes",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Desert Road Through Dunes (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8383529,
          file_size_megabytes: 8.0,
          width: 3072,
          height: 5472,
          primary: "#e3a972",
          secondary: "#2c201a",
          tertiary: "#916241",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#663f26",
          hex_5: "#6a635f",
          hex_6: "#a5978c",
          hex_7: "#918785",
          hex_8: "#535155",
          hex_9: "#b45c1c"
        },
        {
          original_file_name: "Desert Road Through Dunes (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8353421,
          file_size_megabytes: 7.97,
          width: 3072,
          height: 5472,
          primary: "#93623c",
          secondary: "#261e18",
          tertiary: "#ecb981",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#d8965b",
          hex_5: "#5b3d26",
          hex_6: "#8d949f",
          hex_7: "#a18874",
          hex_8: "#c18c5a",
          hex_9: "#4f2208"
        },
        {
          original_file_name: "Desert Road Through Dunes (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8690218,
          file_size_megabytes: 8.29,
          width: 3072,
          height: 5472,
          primary: "#251f1f",
          secondary: "#926342",
          tertiary: "#f8bc70",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#da9051",
          hex_5: "#513828",
          hex_6: "#49210b",
          hex_7: "#753f16",
          hex_8: "#af907f",
          hex_9: "#bd8e66"
        },
        {
          original_file_name: "Desert Road Through Dunes (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7672253,
          file_size_megabytes: 7.32,
          width: 3072,
          height: 5472,
          primary: "#c18959",
          secondary: "#18191f",
          tertiary: "#f9d79d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7a4d2c",
          hex_5: "#673819",
          hex_6: "#facb82",
          hex_7: "#915832",
          hex_8: "#955420",
          hex_9: "#545450"
        }
      ]
    },
    "Frozen Tundra Landscape": {
      environment_title: "Frozen Tundra Landscape",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Frozen Tundra Landscape (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8532012,
          file_size_megabytes: 8.14,
          width: 3072,
          height: 5472,
          primary: "#1f5476",
          secondary: "#a1a9b2",
          tertiary: "#dddcda",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5f7b90",
          hex_5: "#c6d6dc",
          hex_6: "#757b87",
          hex_7: "#aec9dc",
          hex_8: "#4c5461",
          hex_9: "#525d63"
        },
        {
          original_file_name: "Frozen Tundra Landscape (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7711488,
          file_size_megabytes: 7.35,
          width: 3072,
          height: 5472,
          primary: "#8f99a6",
          secondary: "#15476b",
          tertiary: "#dcdedd",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#536d85",
          hex_5: "#b9d1df",
          hex_6: "#8cb6d8",
          hex_7: "#656b78",
          hex_8: "#4b535a",
          hex_9: "#444452"
        },
        {
          original_file_name: "Frozen Tundra Landscape (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8500397,
          file_size_megabytes: 8.11,
          width: 3072,
          height: 5472,
          primary: "#7a8693",
          secondary: "#184262",
          tertiary: "#ddd7cf",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#b6b6b7",
          hex_5: "#b9cfd5",
          hex_6: "#98afba",
          hex_7: "#9ac0d6",
          hex_8: "#4c545b",
          hex_9: "#454b5a"
        },
        {
          original_file_name: "Frozen Tundra Landscape (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8121977,
          file_size_megabytes: 7.75,
          width: 3072,
          height: 5472,
          primary: "#9ba4af",
          secondary: "#1a3147",
          tertiary: "#dddcd8",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#596e81",
          hex_5: "#cad5d9",
          hex_6: "#6c7380",
          hex_7: "#bdcadc",
          hex_8: "#4f565c",
          hex_9: "#4c4c59"
        }
      ]
    },
    "Island Chain Overview": {
      environment_title: "Island Chain Overview",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Island Chain Overview (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9076763,
          file_size_megabytes: 8.66,
          width: 3072,
          height: 5472,
          primary: "#b9d1da",
          secondary: "#163b54",
          tertiary: "#79b7c6",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#374420",
          hex_5: "#708c90",
          hex_6: "#6db2ad",
          hex_7: "#408697",
          hex_8: "#3c6993",
          hex_9: "#316970"
        },
        {
          original_file_name: "Island Chain Overview (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9201156,
          file_size_megabytes: 8.77,
          width: 3072,
          height: 5472,
          primary: "#1b3435",
          secondary: "#5892b4",
          tertiary: "#2f688d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#d1d2b9",
          hex_5: "#616e4b",
          hex_6: "#0e4f66",
          hex_7: "#6fafa1",
          hex_8: "#759492",
          hex_9: "#2d7770"
        },
        {
          original_file_name: "Island Chain Overview (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8462525,
          file_size_megabytes: 8.07,
          width: 3072,
          height: 5472,
          primary: "#b0b3a1",
          secondary: "#062746",
          tertiary: "#39b2b2",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#487887",
          hex_5: "#456b53",
          hex_6: "#4c5541",
          hex_7: "#264d60",
          hex_8: "#263214",
          hex_9: "#1b93ac"
        },
        {
          original_file_name: "Island Chain Overview (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8376625,
          file_size_megabytes: 7.99,
          width: 3072,
          height: 5472,
          primary: "#12343f",
          secondary: "#5a91bb",
          tertiary: "#c4d9de",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#59877e",
          hex_5: "#7fb4c2",
          hex_6: "#20668a",
          hex_7: "#5d6b50",
          hex_8: "#34635d",
          hex_9: "#9c7c58"
        }
      ]
    },
    "Mountain Lake From Above": {
      environment_title: "Mountain Lake From Above",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Mountain Lake From Above (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10415621,
          file_size_megabytes: 9.93,
          width: 3072,
          height: 5472,
          primary: "#182f22",
          secondary: "#b2bfae",
          tertiary: "#3f8bb0",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#82b8da",
          hex_5: "#688745",
          hex_6: "#646b2c",
          hex_7: "#1c5e75",
          hex_8: "#2d6236",
          hex_9: "#9d8c85"
        },
        {
          original_file_name: "Mountain Lake From Above (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10714410,
          file_size_megabytes: 10.22,
          width: 3072,
          height: 5472,
          primary: "#1f493c",
          secondary: "#c1c6b1",
          tertiary: "#6297b7",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6c875f",
          hex_5: "#85aebe",
          hex_6: "#266b7b",
          hex_7: "#66682d",
          hex_8: "#0d140b",
          hex_9: "#9c8c40"
        },
        {
          original_file_name: "Mountain Lake From Above (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11120592,
          file_size_megabytes: 10.61,
          width: 3072,
          height: 5472,
          primary: "#172f26",
          secondary: "#aeaa69",
          tertiary: "#5e7a49",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6baa9c",
          hex_5: "#5a5d31",
          hex_6: "#2d8691",
          hex_7: "#095c65",
          hex_8: "#385637",
          hex_9: "#967458"
        },
        {
          original_file_name: "Mountain Lake From Above (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10786507,
          file_size_megabytes: 10.29,
          width: 3072,
          height: 5472,
          primary: "#b8bf97",
          secondary: "#142921",
          tertiary: "#748247",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#74afbe",
          hex_5: "#275a6d",
          hex_6: "#5390a8",
          hex_7: "#495a36",
          hex_8: "#69682c",
          hex_9: "#414723"
        }
      ]
    },
    "Mountain Range Panorama": {
      environment_title: "Mountain Range Panorama",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Mountain Range Panorama (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8880323,
          file_size_megabytes: 8.47,
          width: 3072,
          height: 5472,
          primary: "#c3c3bc",
          secondary: "#151e22",
          tertiary: "#86a4b2",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#746953",
          hex_5: "#7391a2",
          hex_6: "#3f494b",
          hex_7: "#445667",
          hex_8: "#516573",
          hex_9: "#9c6424"
        },
        {
          original_file_name: "Mountain Range Panorama (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8376395,
          file_size_megabytes: 7.99,
          width: 3072,
          height: 5472,
          primary: "#bdb0a3",
          secondary: "#1b2931",
          tertiary: "#647e8b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8aa8b4",
          hex_5: "#7496a8",
          hex_6: "#725840",
          hex_7: "#40657a",
          hex_8: "#3a5765",
          hex_9: "#9f5c2c"
        },
        {
          original_file_name: "Mountain Range Panorama (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7729142,
          file_size_megabytes: 7.37,
          width: 3072,
          height: 5472,
          primary: "#1b2934",
          secondary: "#b7b9b5",
          tertiary: "#567c90",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#86a9b2",
          hex_5: "#6f9aac",
          hex_6: "#385265",
          hex_7: "#665952",
          hex_8: "#797169",
          hex_9: "#9c7c68"
        },
        {
          original_file_name: "Mountain Range Panorama (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8516591,
          file_size_megabytes: 8.12,
          width: 3072,
          height: 5472,
          primary: "#b7a686",
          secondary: "#152227",
          tertiary: "#66879d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#81a4b1",
          hex_5: "#596c6f",
          hex_6: "#665028",
          hex_7: "#38566c",
          hex_8: "#3a494e",
          hex_9: "#944c04"
        }
      ]
    },
    "Rice Terraces From The Sky": {
      environment_title: "Rice Terraces From The Sky",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Rice Terraces From The Sky (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10727359,
          file_size_megabytes: 10.23,
          width: 3072,
          height: 5472,
          primary: "#caba5f",
          secondary: "#878126",
          tertiary: "#172617",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#9ca83e",
          hex_5: "#50561d",
          hex_6: "#5d712a",
          hex_7: "#364d56",
          hex_8: "#8d9196",
          hex_9: "#ac840c"
        },
        {
          original_file_name: "Rice Terraces From The Sky (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10877999,
          file_size_megabytes: 10.37,
          width: 3072,
          height: 5472,
          primary: "#cbb96b",
          secondary: "#777225",
          tertiary: "#0d1812",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#89991d",
          hex_5: "#404315",
          hex_6: "#4e6025",
          hex_7: "#3c4e50",
          hex_8: "#9c640c",
          hex_9: "#8c8c8c"
        },
        {
          original_file_name: "Rice Terraces From The Sky (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10681458,
          file_size_megabytes: 10.19,
          width: 3072,
          height: 5472,
          primary: "#d0c148",
          secondary: "#142015",
          tertiary: "#76762e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4f700e",
          hex_5: "#899f2b",
          hex_6: "#484c19",
          hex_7: "#27475a",
          hex_8: "#898989",
          hex_9: "#9e7424"
        },
        {
          original_file_name: "Rice Terraces From The Sky (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11609984,
          file_size_megabytes: 11.07,
          width: 3072,
          height: 5472,
          primary: "#c9b73a",
          secondary: "#88821a",
          tertiary: "#14210e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#81aa0d",
          hex_5: "#596e17",
          hex_6: "#4f5113",
          hex_7: "#48525e",
          hex_8: "#a47c14",
          hex_9: "#68708c"
        }
      ]
    },
    "River Meandering Through Forest": {
      environment_title: "River Meandering Through Forest",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "River Meandering Through Forest (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11342620,
          file_size_megabytes: 10.82,
          width: 3072,
          height: 5472,
          primary: "#1c2a1c",
          secondary: "#97aab3",
          tertiary: "#5b6d59",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7b8d9a",
          hex_5: "#3f5132",
          hex_6: "#455560",
          hex_7: "#2e3c43",
          hex_8: "#849387",
          hex_9: "#545c3f"
        },
        {
          original_file_name: "River Meandering Through Forest (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11065450,
          file_size_megabytes: 10.55,
          width: 3072,
          height: 5472,
          primary: "#192718",
          secondary: "#98b0a7",
          tertiary: "#5a734f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6d8899",
          hex_5: "#315063",
          hex_6: "#3e522d",
          hex_7: "#173745",
          hex_8: "#545a3a",
          hex_9: "#908858"
        },
        {
          original_file_name: "River Meandering Through Forest (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11205057,
          file_size_megabytes: 10.69,
          width: 3072,
          height: 5472,
          primary: "#1a271a",
          secondary: "#829fa7",
          tertiary: "#516544",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#738a55",
          hex_5: "#35472d",
          hex_6: "#465033",
          hex_7: "#2c4f58",
          hex_8: "#6d784c",
          hex_9: "#1c383e"
        },
        {
          original_file_name: "River Meandering Through Forest (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10749548,
          file_size_megabytes: 10.25,
          width: 3072,
          height: 5472,
          primary: "#8cada7",
          secondary: "#152417",
          tertiary: "#537153",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5c889c",
          hex_5: "#364b29",
          hex_6: "#2c5465",
          hex_7: "#4d5931",
          hex_8: "#113442",
          hex_9: "#859257"
        }
      ]
    },
    "Rolling Hills And Forest Patches": {
      environment_title: "Rolling Hills And Forest Patches",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Rolling Hills And Forest Patches (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 12277628,
          file_size_megabytes: 11.71,
          width: 3072,
          height: 5472,
          primary: "#202f1b",
          secondary: "#aea953",
          tertiary: "#787a36",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#65797a",
          hex_5: "#415654",
          hex_6: "#4f5928",
          hex_7: "#919d62",
          hex_8: "#5a6d4b",
          hex_9: "#9c7c32"
        },
        {
          original_file_name: "Rolling Hills And Forest Patches (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11756132,
          file_size_megabytes: 11.21,
          width: 3072,
          height: 5472,
          primary: "#acae47",
          secondary: "#202b1c",
          tertiary: "#7e842d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#617785",
          hex_5: "#5d6422",
          hex_6: "#909d40",
          hex_7: "#697522",
          hex_8: "#47573d",
          hex_9: "#304654"
        },
        {
          original_file_name: "Rolling Hills And Forest Patches (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 12195978,
          file_size_megabytes: 11.63,
          width: 3072,
          height: 5472,
          primary: "#1f2918",
          secondary: "#afb652",
          tertiary: "#788136",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#72868c",
          hex_5: "#4c5c5e",
          hex_6: "#95993c",
          hex_7: "#515a27",
          hex_8: "#666933",
          hex_9: "#8ca4a6"
        },
        {
          original_file_name: "Rolling Hills And Forest Patches (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11664652,
          file_size_megabytes: 11.12,
          width: 3072,
          height: 5472,
          primary: "#252e13",
          secondary: "#a69e48",
          tertiary: "#7e7c31",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5e798f",
          hex_5: "#8b9767",
          hex_6: "#3c5158",
          hex_7: "#656f32",
          hex_8: "#5a5e21",
          hex_9: "#495522"
        }
      ]
    },
    "SnowCovered Landscape": {
      environment_title: "SnowCovered Landscape",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "SnowCovered Landscape (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7938187,
          file_size_megabytes: 7.57,
          width: 3072,
          height: 5472,
          primary: "#1e496f",
          secondary: "#bdc2c6",
          tertiary: "#6f879e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#efede5",
          hex_5: "#8c8b92",
          hex_6: "#929493",
          hex_7: "#62666b",
          hex_8: "#5c5c62",
          hex_9: "#549ccc"
        },
        {
          original_file_name: "SnowCovered Landscape (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7922616,
          file_size_megabytes: 7.56,
          width: 3072,
          height: 5472,
          primary: "#cecfcd",
          secondary: "#2d4a68",
          tertiary: "#697c90",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#91a0ad",
          hex_5: "#878a92",
          hex_6: "#55535c",
          hex_7: "#497493",
          hex_8: "#5b5d5b",
          hex_9: "#98958b"
        },
        {
          original_file_name: "SnowCovered Landscape (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7463418,
          file_size_megabytes: 7.12,
          width: 3072,
          height: 5472,
          primary: "#4e6984",
          secondary: "#dadbd8",
          tertiary: "#9ca4ae",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#acbfcc",
          hex_5: "#1b3f61",
          hex_6: "#9db0c6",
          hex_7: "#0d2741",
          hex_8: "#1d364a",
          hex_9: "#bcb4b5"
        },
        {
          original_file_name: "SnowCovered Landscape (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7079160,
          file_size_megabytes: 6.75,
          width: 3072,
          height: 5472,
          primary: "#335471",
          secondary: "#d5d7da",
          tertiary: "#70869c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a2adb9",
          hex_5: "#94939c",
          hex_6: "#5c5c68",
          hex_7: "#5484a7",
          hex_8: "#5d6464",
          hex_9: "#979c94"
        }
      ]
    },
    "Urban Grid From Above": {
      environment_title: "Urban Grid From Above",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Urban Grid From Above (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9398759,
          file_size_megabytes: 8.96,
          width: 3072,
          height: 5472,
          primary: "#c4712e",
          secondary: "#10151f",
          tertiary: "#663a23",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2a688f",
          hex_5: "#19405e",
          hex_6: "#f5c884",
          hex_7: "#263742",
          hex_8: "#285772",
          hex_9: "#5a97b8"
        },
        {
          original_file_name: "Urban Grid From Above (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9675743,
          file_size_megabytes: 9.23,
          width: 3072,
          height: 5472,
          primary: "#b86526",
          secondary: "#0f1621",
          tertiary: "#6a381f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#28638a",
          hex_5: "#3982aa",
          hex_6: "#3e2218",
          hex_7: "#295068",
          hex_8: "#1b3d5a",
          hex_9: "#eead50"
        },
        {
          original_file_name: "Urban Grid From Above (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9992299,
          file_size_megabytes: 9.53,
          width: 3072,
          height: 5472,
          primary: "#c76f23",
          secondary: "#0f1724",
          tertiary: "#6d361b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#133f5f",
          hex_5: "#3e1f17",
          hex_6: "#296189",
          hex_7: "#285774",
          hex_8: "#f8bf62",
          hex_9: "#848c8c"
        },
        {
          original_file_name: "Urban Grid From Above (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9072979,
          file_size_megabytes: 8.65,
          width: 3072,
          height: 5472,
          primary: "#b7733e",
          secondary: "#161d24",
          tertiary: "#71462d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#462d22",
          hex_5: "#304c61",
          hex_6: "#406173",
          hex_7: "#557e92",
          hex_8: "#f2c993",
          hex_9: "#6298aa"
        }
      ]
    },
    "Urban Park From Above": {
      environment_title: "Urban Park From Above",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Urban Park From Above (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10796380,
          file_size_megabytes: 10.3,
          width: 3072,
          height: 5472,
          primary: "#dad1ae",
          secondary: "#182614",
          tertiary: "#7f8045",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#515420",
          hex_5: "#8e949b",
          hex_6: "#4f724d",
          hex_7: "#96a576",
          hex_8: "#3e5a5b",
          hex_9: "#ac7444"
        },
        {
          original_file_name: "Urban Park From Above (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10024543,
          file_size_megabytes: 9.56,
          width: 3072,
          height: 5472,
          primary: "#e0dbb5",
          secondary: "#1a2714",
          tertiary: "#7b7f42",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4b5a64",
          hex_5: "#606e57",
          hex_6: "#7f8899",
          hex_7: "#52571d",
          hex_8: "#9ba45b",
          hex_9: "#a4846c"
        },
        {
          original_file_name: "Urban Park From Above (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11066681,
          file_size_megabytes: 10.55,
          width: 3072,
          height: 5472,
          primary: "#cbc784",
          secondary: "#78782b",
          tertiary: "#102111",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#466b91",
          hex_5: "#264660",
          hex_6: "#4a4e15",
          hex_7: "#516754",
          hex_8: "#919d60",
          hex_9: "#9c8410"
        },
        {
          original_file_name: "Urban Park From Above (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9674640,
          file_size_megabytes: 9.23,
          width: 3072,
          height: 5472,
          primary: "#27311a",
          secondary: "#d6d1a8",
          tertiary: "#8b8949",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4f616c",
          hex_5: "#83929f",
          hex_6: "#9db09a",
          hex_7: "#656423",
          hex_8: "#6d7e59",
          hex_9: "#ac8c6a"
        }
      ]
    },
    "Urban Park Layout": {
      environment_title: "Urban Park Layout",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Urban Park Layout (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10235168,
          file_size_megabytes: 9.76,
          width: 3072,
          height: 5472,
          primary: "#d5c9b2",
          secondary: "#1d2e1d",
          tertiary: "#7d7650",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#517458",
          hex_5: "#555625",
          hex_6: "#82939a",
          hex_7: "#86aa9a",
          hex_8: "#3a5b63",
          hex_9: "#a4643c"
        },
        {
          original_file_name: "Urban Park Layout (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8982395,
          file_size_megabytes: 8.57,
          width: 3072,
          height: 5472,
          primary: "#b8b678",
          secondary: "#17291f",
          tertiary: "#757529",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8ca298",
          hex_5: "#6e89a0",
          hex_6: "#455121",
          hex_7: "#4d6857",
          hex_8: "#2b4e66",
          hex_9: "#9c7c14"
        },
        {
          original_file_name: "Urban Park Layout (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9343854,
          file_size_megabytes: 8.91,
          width: 3072,
          height: 5472,
          primary: "#e6e0c1",
          secondary: "#192610",
          tertiary: "#778556",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4f571b",
          hex_5: "#5f7443",
          hex_6: "#414e5c",
          hex_7: "#7d8392",
          hex_8: "#96a56f",
          hex_9: "#a48470"
        },
        {
          original_file_name: "Urban Park Layout (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9653400,
          file_size_megabytes: 9.21,
          width: 3072,
          height: 5472,
          primary: "#d1c8ad",
          secondary: "#1d2718",
          tertiary: "#7b8054",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6a663d",
          hex_5: "#3e5260",
          hex_6: "#445b27",
          hex_7: "#7d8d9d",
          hex_8: "#89a988",
          hex_9: "#9c7c6c"
        }
      ]
    },
    "Urban Skyline At Night": {
      environment_title: "Urban Skyline At Night",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Urban Skyline At Night (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8684459,
          file_size_megabytes: 8.28,
          width: 3072,
          height: 5472,
          primary: "#ba7742",
          secondary: "#13171f",
          tertiary: "#5d6771",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#663c26",
          hex_5: "#54809e",
          hex_6: "#6d9eb8",
          hex_7: "#304a62",
          hex_8: "#d0d9d5",
          hex_9: "#393f48"
        },
        {
          original_file_name: "Urban Skyline At Night (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8659467,
          file_size_megabytes: 8.26,
          width: 3072,
          height: 5472,
          primary: "#15191f",
          secondary: "#b28c70",
          tertiary: "#60686a",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#64402c",
          hex_5: "#374146",
          hex_6: "#75a0ab",
          hex_7: "#3d505e",
          hex_8: "#698896",
          hex_9: "#913808"
        },
        {
          original_file_name: "Urban Skyline At Night (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8803683,
          file_size_megabytes: 8.4,
          width: 3072,
          height: 5472,
          primary: "#bf906a",
          secondary: "#10151d",
          tertiary: "#646a6a",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5e3f30",
          hex_5: "#75a0a8",
          hex_6: "#344245",
          hex_7: "#3f4f5f",
          hex_8: "#6b8698",
          hex_9: "#93390e"
        },
        {
          original_file_name: "Urban Skyline At Night (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9057936,
          file_size_megabytes: 8.64,
          width: 3072,
          height: 5472,
          primary: "#ca906b",
          secondary: "#14161d",
          tertiary: "#6e4e44",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#453331",
          hex_5: "#7da1af",
          hex_6: "#728698",
          hex_7: "#44626b",
          hex_8: "#3e4e60",
          hex_9: "#983911"
        }
      ]
    },
    "Verdant Forest Canopy": {
      environment_title: "Verdant Forest Canopy",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Verdant Forest Canopy (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11979164,
          file_size_megabytes: 11.42,
          width: 3072,
          height: 5472,
          primary: "#a9b75f",
          secondary: "#62772d",
          tertiary: "#0f200c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#869f43",
          hex_5: "#384e1a",
          hex_6: "#565a21",
          hex_7: "#353a13",
          hex_8: "#465646",
          hex_9: "#839274"
        },
        {
          original_file_name: "Verdant Forest Canopy (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 12625277,
          file_size_megabytes: 12.04,
          width: 3072,
          height: 5472,
          primary: "#11230c",
          secondary: "#677c2a",
          tertiary: "#aabb4f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#879f39",
          hex_5: "#3f551c",
          hex_6: "#566122",
          hex_7: "#788d67",
          hex_8: "#303f3e",
          hex_9: "#948c34"
        },
        {
          original_file_name: "Verdant Forest Canopy (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 12191599,
          file_size_megabytes: 11.63,
          width: 3072,
          height: 5472,
          primary: "#12230f",
          secondary: "#98ae42",
          tertiary: "#667c2b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3f561c",
          hex_5: "#556227",
          hex_6: "#8c9348",
          hex_7: "#455b46",
          hex_8: "#749c30",
          hex_9: "#7c8e74"
        },
        {
          original_file_name: "Verdant Forest Canopy (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 12241684,
          file_size_megabytes: 11.67,
          width: 3072,
          height: 5472,
          primary: "#13260d",
          secondary: "#a9b951",
          tertiary: "#687c2c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#879f3b",
          hex_5: "#3f551d",
          hex_6: "#566127",
          hex_7: "#828e71",
          hex_8: "#31413c",
          hex_9: "#948404"
        }
      ]
    },
    "Vineyard Rows In Summer": {
      environment_title: "Vineyard Rows In Summer",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Vineyard Rows In Summer (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9719493,
          file_size_megabytes: 9.27,
          width: 3072,
          height: 5472,
          primary: "#c2a858",
          secondary: "#191e0e",
          tertiary: "#787e27",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8f9f36",
          hex_5: "#546315",
          hex_6: "#494819",
          hex_7: "#858468",
          hex_8: "#37323c",
          hex_9: "#9c6434"
        },
        {
          original_file_name: "Vineyard Rows In Summer (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11520589,
          file_size_megabytes: 10.99,
          width: 3072,
          height: 5472,
          primary: "#c19d4f",
          secondary: "#8e9f21",
          tertiary: "#1b1e10",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7f7124",
          hex_5: "#58680f",
          hex_6: "#4f4318",
          hex_7: "#8b8066",
          hex_8: "#30313d",
          hex_9: "#a45c34"
        },
        {
          original_file_name: "Vineyard Rows In Summer (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 12133504,
          file_size_megabytes: 11.57,
          width: 3072,
          height: 5472,
          primary: "#7f6c2b",
          secondary: "#c58b52",
          tertiary: "#1d2012",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#849c30",
          hex_5: "#586f13",
          hex_6: "#554919",
          hex_7: "#384d0b",
          hex_8: "#625e5e",
          hex_9: "#a4543c"
        },
        {
          original_file_name: "Vineyard Rows In Summer (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10488624,
          file_size_megabytes: 10.0,
          width: 3072,
          height: 5472,
          primary: "#b6a146",
          secondary: "#1e2015",
          tertiary: "#797a1f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8ea025",
          hex_5: "#4d4a14",
          hex_6: "#57680f",
          hex_7: "#36480a",
          hex_8: "#867c5f",
          hex_9: "#9c5439"
        }
      ]
    }
  }
];
