export const database: unknown[] = [
  {
    "Cliffside Beach Panorama": {
      environment_title: "Cliffside Beach Panorama",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Cliffside Beach Panorama (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10305848,
          file_size_megabytes: 9.83,
          width: 3072,
          height: 5472,
          primary: "#ccbeaf",
          secondary: "#20322e",
          tertiary: "#97bac9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#837458",
          hex_5: "#6893ad",
          hex_6: "#276889",
          hex_7: "#4e8681",
          hex_8: "#30645a",
          hex_9: "#ac5c34"
        },
        {
          original_file_name: "Cliffside Beach Panorama (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8977866,
          file_size_megabytes: 8.56,
          width: 3072,
          height: 5472,
          primary: "#2b3530",
          secondary: "#d0c9bf",
          tertiary: "#a7c2cc",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#86acc1",
          hex_5: "#998e7d",
          hex_6: "#6794a8",
          hex_7: "#397293",
          hex_8: "#54746b",
          hex_9: "#bc7442"
        },
        {
          original_file_name: "Cliffside Beach Panorama (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8921068,
          file_size_megabytes: 8.51,
          width: 3072,
          height: 5472,
          primary: "#d4bea9",
          secondary: "#1a2525",
          tertiary: "#89b0c0",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#827154",
          hex_5: "#5391ad",
          hex_6: "#377373",
          hex_7: "#1c5351",
          hex_8: "#1b5b68",
          hex_9: "#ae6429"
        },
        {
          original_file_name: "Cliffside Beach Panorama (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8280301,
          file_size_megabytes: 7.9,
          width: 3072,
          height: 5472,
          primary: "#d2c2b0",
          secondary: "#2c3c36",
          tertiary: "#9b9181",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#aac0ca",
          hex_5: "#8faec2",
          hex_6: "#44718f",
          hex_7: "#6b92a6",
          hex_8: "#547157",
          hex_9: "#bc8c64"
        }
      ]
    },
    "Clifftop Beach View": {
      environment_title: "Clifftop Beach View",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Clifftop Beach View (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9059888,
          file_size_megabytes: 8.64,
          width: 3072,
          height: 5472,
          primary: "#266374",
          secondary: "#d1d7da",
          tertiary: "#9bbfd2",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#293221",
          hex_5: "#80acc7",
          hex_6: "#859fa2",
          hex_7: "#5e99b2",
          hex_8: "#092b40",
          hex_9: "#ac8c70"
        },
        {
          original_file_name: "Clifftop Beach View (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9466057,
          file_size_megabytes: 9.03,
          width: 3072,
          height: 5472,
          primary: "#336c75",
          secondary: "#d3d1cc",
          tertiary: "#121c1c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#66a7cf",
          hex_5: "#96c2dc",
          hex_6: "#404426",
          hex_7: "#909990",
          hex_8: "#649d9b",
          hex_9: "#ac7c5c"
        },
        {
          original_file_name: "Clifftop Beach View (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9169308,
          file_size_megabytes: 8.74,
          width: 3072,
          height: 5472,
          primary: "#d0cfc9",
          secondary: "#27596c",
          tertiary: "#232719",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#77a6c2",
          hex_5: "#90b8cb",
          hex_6: "#809197",
          hex_7: "#4d85a3",
          hex_8: "#0e2a43",
          hex_9: "#a47c59"
        },
        {
          original_file_name: "Clifftop Beach View (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9820360,
          file_size_megabytes: 9.37,
          width: 3072,
          height: 5472,
          primary: "#cec0ae",
          secondary: "#1f657b",
          tertiary: "#75a3c1",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#1c1f18",
          hex_5: "#424324",
          hex_6: "#87928b",
          hex_7: "#9dc0cc",
          hex_8: "#5399a3",
          hex_9: "#ac7c59"
        }
      ]
    },
    "Foggy Mountain Shoreline": {
      environment_title: "Foggy Mountain Shoreline",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Foggy Mountain Shoreline (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8030921,
          file_size_megabytes: 7.66,
          width: 3072,
          height: 5472,
          primary: "#313d43",
          secondary: "#aebfcb",
          tertiary: "#a1b1bf",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8fa0ac",
          hex_5: "#d5e2eb",
          hex_6: "#758a95",
          hex_7: "#bcc4d3",
          hex_8: "#677986",
          hex_9: "#5e6f78"
        },
        {
          original_file_name: "Foggy Mountain Shoreline (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7344904,
          file_size_megabytes: 7.0,
          width: 3072,
          height: 5472,
          primary: "#36454f",
          secondary: "#b1c7d9",
          tertiary: "#879fb5",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6b8599",
          hex_5: "#566d82",
          hex_6: "#0a0c0d",
          hex_7: "#8facb4",
          hex_8: "#9498a4",
          hex_9: "#646c74"
        },
        {
          original_file_name: "Foggy Mountain Shoreline (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7675716,
          file_size_megabytes: 7.32,
          width: 3072,
          height: 5472,
          primary: "#acbecb",
          secondary: "#262d30",
          tertiary: "#3f4e59",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5d6e78",
          hex_5: "#4a5e68",
          hex_6: "#6e818e",
          hex_7: "#83949e",
          hex_8: "#738d9a",
          hex_9: "#70644c"
        },
        {
          original_file_name: "Foggy Mountain Shoreline (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7958984,
          file_size_megabytes: 7.59,
          width: 3072,
          height: 5472,
          primary: "#8fa0ae",
          secondary: "#272d31",
          tertiary: "#504a43",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#364851",
          hex_5: "#555e65",
          hex_6: "#ccdbe7",
          hex_7: "#5e6c7c",
          hex_8: "#bacbdc",
          hex_9: "#c4cbd7"
        }
      ]
    },
    "Golden Hour Mountain Beach": {
      environment_title: "Golden Hour Mountain Beach",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Golden Hour Mountain Beach (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8332481,
          file_size_megabytes: 7.95,
          width: 3072,
          height: 5472,
          primary: "#826044",
          secondary: "#323e40",
          tertiary: "#edd2ad",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5d3116",
          hex_5: "#aba494",
          hex_6: "#e1a669",
          hex_7: "#be8959",
          hex_8: "#c3b9ac",
          hex_9: "#a1947a"
        },
        {
          original_file_name: "Golden Hour Mountain Beach (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8093381,
          file_size_megabytes: 7.72,
          width: 3072,
          height: 5472,
          primary: "#79573e",
          secondary: "#e7cba1",
          tertiary: "#353537",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#94a5a6",
          hex_5: "#db9a56",
          hex_6: "#a08e7f",
          hex_7: "#b66e30",
          hex_8: "#b78e67",
          hex_9: "#512a14"
        },
        {
          original_file_name: "Golden Hour Mountain Beach (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8226475,
          file_size_megabytes: 7.85,
          width: 3072,
          height: 5472,
          primary: "#ecca97",
          secondary: "#735037",
          tertiary: "#9da49b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2f2a27",
          hex_5: "#d4a067",
          hex_6: "#ac9679",
          hex_7: "#887a70",
          hex_8: "#ad723f",
          hex_9: "#48220b"
        },
        {
          original_file_name: "Golden Hour Mountain Beach (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8039238,
          file_size_megabytes: 7.67,
          width: 3072,
          height: 5472,
          primary: "#8e5a32",
          secondary: "#2f3537",
          tertiary: "#eed7aa",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#908270",
          hex_5: "#d49656",
          hex_6: "#a7a19a",
          hex_7: "#4f473c",
          hex_8: "#bb8e58",
          hex_9: "#481f0b"
        }
      ]
    },
    "Golden Sands And Snowy Peaks": {
      environment_title: "Golden Sands And Snowy Peaks",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Golden Sands And Snowy Peaks (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7733339,
          file_size_megabytes: 7.38,
          width: 3072,
          height: 5472,
          primary: "#958c80",
          secondary: "#7a4f2f",
          tertiary: "#e4c9aa",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#304d61",
          hex_5: "#643a20",
          hex_6: "#506e7f",
          hex_7: "#c0c4ba",
          hex_8: "#7e5a48",
          hex_9: "#b2b8c5"
        },
        {
          original_file_name: "Golden Sands And Snowy Peaks (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8321339,
          file_size_megabytes: 7.94,
          width: 3072,
          height: 5472,
          primary: "#88674f",
          secondary: "#63a3c4",
          tertiary: "#deb889",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#252f39",
          hex_5: "#858b94",
          hex_6: "#48484a",
          hex_7: "#9ebfc9",
          hex_8: "#402814",
          hex_9: "#af9674"
        },
        {
          original_file_name: "Golden Sands And Snowy Peaks (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7891043,
          file_size_megabytes: 7.53,
          width: 3072,
          height: 5472,
          primary: "#294d6c",
          secondary: "#d1c1b0",
          tertiary: "#895729",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#55758f",
          hex_5: "#aa815b",
          hex_6: "#8596a4",
          hex_7: "#88644d",
          hex_8: "#623918",
          hex_9: "#a2887b"
        },
        {
          original_file_name: "Golden Sands And Snowy Peaks (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7983643,
          file_size_megabytes: 7.61,
          width: 3072,
          height: 5472,
          primary: "#2d4457",
          secondary: "#77563d",
          tertiary: "#e1af74",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#cfcfc7",
          hex_5: "#7e95a2",
          hex_6: "#5a381e",
          hex_7: "#b38351",
          hex_8: "#5e6c78",
          hex_9: "#c0beb0"
        }
      ]
    },
    "Island Mountain Peninsula": {
      environment_title: "Island Mountain Peninsula",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Island Mountain Peninsula (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10010589,
          file_size_megabytes: 9.55,
          width: 3072,
          height: 5472,
          primary: "#c0ccd3",
          secondary: "#1d362f",
          tertiary: "#258095",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5e96c1",
          hex_5: "#6eb6c7",
          hex_6: "#1f566e",
          hex_7: "#6c6040",
          hex_8: "#50826e",
          hex_9: "#9c6c54"
        },
        {
          original_file_name: "Island Mountain Peninsula (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8132665,
          file_size_megabytes: 7.76,
          width: 3072,
          height: 5472,
          primary: "#b9ccd8",
          secondary: "#113741",
          tertiary: "#5f8fbb",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#89b2d4",
          hex_5: "#628677",
          hex_6: "#266586",
          hex_7: "#63633a",
          hex_8: "#1d6064",
          hex_9: "#9c7460"
        },
        {
          original_file_name: "Island Mountain Peninsula (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9206522,
          file_size_megabytes: 8.78,
          width: 3072,
          height: 5472,
          primary: "#b9c6c6",
          secondary: "#0e2d40",
          tertiary: "#5991ba",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#567867",
          hex_5: "#69adc5",
          hex_6: "#5c583e",
          hex_7: "#1a5b7f",
          hex_8: "#141d0d",
          hex_9: "#9c6c54"
        },
        {
          original_file_name: "Island Mountain Peninsula (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10628076,
          file_size_megabytes: 10.14,
          width: 3072,
          height: 5472,
          primary: "#25484d",
          secondary: "#acc8dc",
          tertiary: "#79b3cd",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3f9288",
          hex_5: "#296587",
          hex_6: "#6d6a48",
          hex_7: "#669ac7",
          hex_8: "#091517",
          hex_9: "#363316"
        }
      ]
    },
    "Island With Mountain Peninsula": {
      environment_title: "Island With Mountain Peninsula",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Island With Mountain Peninsula (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8990368,
          file_size_megabytes: 8.57,
          width: 3072,
          height: 5472,
          primary: "#1b506a",
          secondary: "#bed3d4",
          tertiary: "#2e3b1b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#78a1c4",
          hex_5: "#6a888d",
          hex_6: "#89b7cd",
          hex_7: "#358e9b",
          hex_8: "#072343",
          hex_9: "#9d8c55"
        },
        {
          original_file_name: "Island With Mountain Peninsula (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8375074,
          file_size_megabytes: 7.99,
          width: 3072,
          height: 5472,
          primary: "#0f516b",
          secondary: "#b2c5c6",
          tertiary: "#5597c8",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#329891",
          hex_5: "#5f725f",
          hex_6: "#58c1c6",
          hex_7: "#28351e",
          hex_8: "#041b3d",
          hex_9: "#947c51"
        },
        {
          original_file_name: "Island With Mountain Peninsula (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9120538,
          file_size_megabytes: 8.7,
          width: 3072,
          height: 5472,
          primary: "#bacfd6",
          secondary: "#143c51",
          tertiary: "#82b4d4",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5495c4",
          hex_5: "#267194",
          hex_6: "#66814a",
          hex_7: "#5c6342",
          hex_8: "#213014",
          hex_9: "#9c7c6c"
        },
        {
          original_file_name: "Island With Mountain Peninsula (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7800315,
          file_size_megabytes: 7.44,
          width: 3072,
          height: 5472,
          primary: "#b7d4e7",
          secondary: "#0a374b",
          tertiary: "#79b4d6",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4096c1",
          hex_5: "#257e87",
          hex_6: "#176484",
          hex_7: "#5a5d37",
          hex_8: "#1e2813",
          hex_9: "#946c2c"
        }
      ]
    },
    "Mountain Reflection On Calm Waters": {
      environment_title: "Mountain Reflection On Calm Waters",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Mountain Reflection On Calm Waters (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9101210,
          file_size_megabytes: 8.68,
          width: 3072,
          height: 5472,
          primary: "#325051",
          secondary: "#cdcbc4",
          tertiary: "#6f9dc0",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#90bbd5",
          hex_5: "#668b96",
          hex_6: "#467492",
          hex_7: "#0c1713",
          hex_8: "#766e4f",
          hex_9: "#303112"
        },
        {
          original_file_name: "Mountain Reflection On Calm Waters (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8727285,
          file_size_megabytes: 8.32,
          width: 3072,
          height: 5472,
          primary: "#425a5b",
          secondary: "#72a4cc",
          tertiary: "#cfd4d5",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#95bed7",
          hex_5: "#8198a0",
          hex_6: "#4b7b98",
          hex_7: "#0e1713",
          hex_8: "#787b6a",
          hex_9: "#2f341c"
        },
        {
          original_file_name: "Mountain Reflection On Calm Waters (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9552333,
          file_size_megabytes: 9.11,
          width: 3072,
          height: 5472,
          primary: "#bcd1e0",
          secondary: "#374c57",
          tertiary: "#96bbdb",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#79a1c5",
          hex_5: "#738c99",
          hex_6: "#58758b",
          hex_7: "#393c13",
          hex_8: "#0b1814",
          hex_9: "#78744c"
        },
        {
          original_file_name: "Mountain Reflection On Calm Waters (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9548549,
          file_size_megabytes: 9.11,
          width: 3072,
          height: 5472,
          primary: "#283e41",
          secondary: "#cacdcb",
          tertiary: "#82a6be",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6c7e84",
          hex_5: "#4f6877",
          hex_6: "#7d9ab2",
          hex_7: "#676750",
          hex_8: "#071219",
          hex_9: "#9c7c7c"
        }
      ]
    },
    "Mountain Reflections On Beach": {
      environment_title: "Mountain Reflections On Beach",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Mountain Reflections On Beach (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10072175,
          file_size_megabytes: 9.61,
          width: 3072,
          height: 5472,
          primary: "#4d5957",
          secondary: "#d3cabe",
          tertiary: "#6e99bd",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#121a13",
          hex_5: "#363a19",
          hex_6: "#919188",
          hex_7: "#9db6c7",
          hex_8: "#5a7a90",
          hex_9: "#73909f"
        },
        {
          original_file_name: "Mountain Reflections On Beach (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10387272,
          file_size_megabytes: 9.91,
          width: 3072,
          height: 5472,
          primary: "#c7ced2",
          secondary: "#1d3028",
          tertiary: "#90bce0",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#628fac",
          hex_5: "#416277",
          hex_6: "#7b8268",
          hex_7: "#716e48",
          hex_8: "#5b6137",
          hex_9: "#a48473"
        },
        {
          original_file_name: "Mountain Reflections On Beach (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8385111,
          file_size_megabytes: 8.0,
          width: 3072,
          height: 5472,
          primary: "#243844",
          secondary: "#c8c5c1",
          tertiary: "#7999b2",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#94b1c1",
          hex_5: "#6a8699",
          hex_6: "#4c6d82",
          hex_7: "#46606f",
          hex_8: "#75655e",
          hex_9: "#a46c54"
        },
        {
          original_file_name: "Mountain Reflections On Beach (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8951774,
          file_size_megabytes: 8.54,
          width: 3072,
          height: 5472,
          primary: "#2a393b",
          secondary: "#cfd0cf",
          tertiary: "#8cb1d0",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6c99bf",
          hex_5: "#868988",
          hex_6: "#4b6c82",
          hex_7: "#5f8296",
          hex_8: "#566367",
          hex_9: "#ad947e"
        }
      ]
    },
    "Rocky Shore With Mountain Silhouette": {
      environment_title: "Rocky Shore With Mountain Silhouette",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Rocky Shore With Mountain Silhouette (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8240766,
          file_size_megabytes: 7.86,
          width: 3072,
          height: 5472,
          primary: "#d5a175",
          secondary: "#2f3744",
          tertiary: "#7f6965",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7190ae",
          hex_5: "#8ba9c5",
          hex_6: "#56738a",
          hex_7: "#07070c",
          hex_8: "#3f5d79",
          hex_9: "#a45439"
        },
        {
          original_file_name: "Rocky Shore With Mountain Silhouette (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8012437,
          file_size_megabytes: 7.64,
          width: 3072,
          height: 5472,
          primary: "#44647d",
          secondary: "#ccb1b0",
          tertiary: "#120f12",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8a8d9d",
          hex_5: "#182838",
          hex_6: "#303943",
          hex_7: "#94a7bf",
          hex_8: "#aa6844",
          hex_9: "#9aacb3"
        },
        {
          original_file_name: "Rocky Shore With Mountain Silhouette (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8286898,
          file_size_megabytes: 7.9,
          width: 3072,
          height: 5472,
          primary: "#293643",
          secondary: "#d19273",
          tertiary: "#799cb3",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7f5f60",
          hex_5: "#476f85",
          hex_6: "#0f0a0b",
          hex_7: "#c1c2cc",
          hex_8: "#929d9b",
          hex_9: "#5d6c6a"
        },
        {
          original_file_name: "Rocky Shore With Mountain Silhouette (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8059766,
          file_size_megabytes: 7.69,
          width: 3072,
          height: 5472,
          primary: "#ccaa9e",
          secondary: "#84a6c3",
          tertiary: "#0f141b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#64778a",
          hex_5: "#74585e",
          hex_6: "#364459",
          hex_7: "#969ca0",
          hex_8: "#4a5c69",
          hex_9: "#ac684c"
        }
      ]
    },
    "Serene Beach With Mountain Backdrop": {
      environment_title: "Serene Beach With Mountain Backdrop",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Serene Beach With Mountain Backdrop (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6660044,
          file_size_megabytes: 6.35,
          width: 3072,
          height: 5472,
          primary: "#35688e",
          secondary: "#b8b4a9",
          tertiary: "#6990ad",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#bbd3e9",
          hex_5: "#888788",
          hex_6: "#e6dece",
          hex_7: "#72716b",
          hex_8: "#dbdcce",
          hex_9: "#5c5e60"
        },
        {
          original_file_name: "Serene Beach With Mountain Backdrop (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7386228,
          file_size_megabytes: 7.04,
          width: 3072,
          height: 5472,
          primary: "#9fadb2",
          secondary: "#33708c",
          tertiary: "#dbdcda",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#588fae",
          hex_5: "#bacfdd",
          hex_6: "#cadce3",
          hex_7: "#64645d",
          hex_8: "#74797b",
          hex_9: "#525353"
        },
        {
          original_file_name: "Serene Beach With Mountain Backdrop (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7297455,
          file_size_megabytes: 6.96,
          width: 3072,
          height: 5472,
          primary: "#979a99",
          secondary: "#315f88",
          tertiary: "#5385aa",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#e5e6e4",
          hex_5: "#8ab9dc",
          hex_6: "#515232",
          hex_7: "#b3dbf5",
          hex_8: "#474b58",
          hex_9: "#706968"
        },
        {
          original_file_name: "Serene Beach With Mountain Backdrop (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7185975,
          file_size_megabytes: 6.85,
          width: 3072,
          height: 5472,
          primary: "#a6a197",
          secondary: "#355e79",
          tertiary: "#89b8d9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#e9e5dd",
          hex_5: "#3b4330",
          hex_6: "#588eaf",
          hex_7: "#4f5a56",
          hex_8: "#87785f",
          hex_9: "#c6d4cc"
        }
      ]
    },
    "Serene Lagoon With Mountain Backdrop": {
      environment_title: "Serene Lagoon With Mountain Backdrop",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Serene Lagoon With Mountain Backdrop (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9087122,
          file_size_megabytes: 8.67,
          width: 3072,
          height: 5472,
          primary: "#578894",
          secondary: "#d3dee5",
          tertiary: "#202e23",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#0e707d",
          hex_5: "#364e3b",
          hex_6: "#87b2cf",
          hex_7: "#99c5d2",
          hex_8: "#8aa8af",
          hex_9: "#3b555d"
        },
        {
          original_file_name: "Serene Lagoon With Mountain Backdrop (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9051559,
          file_size_megabytes: 8.63,
          width: 3072,
          height: 5472,
          primary: "#548d9d",
          secondary: "#ccd2d7",
          tertiary: "#17201b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3d4e36",
          hex_5: "#2e5760",
          hex_6: "#8ea2a7",
          hex_7: "#8fb5d6",
          hex_8: "#3e6965",
          hex_9: "#98ccbe"
        },
        {
          original_file_name: "Serene Lagoon With Mountain Backdrop (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8999191,
          file_size_megabytes: 8.58,
          width: 3072,
          height: 5472,
          primary: "#5a7c83",
          secondary: "#c5d9e4",
          tertiary: "#182923",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8cb7d6",
          hex_5: "#a8cde5",
          hex_6: "#96aead",
          hex_7: "#364a35",
          hex_8: "#1a575f",
          hex_9: "#82acae"
        },
        {
          original_file_name: "Serene Lagoon With Mountain Backdrop (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9394945,
          file_size_megabytes: 8.96,
          width: 3072,
          height: 5472,
          primary: "#386265",
          secondary: "#bfcfda",
          tertiary: "#7ea5c4",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#9cbece",
          hex_5: "#0f2320",
          hex_6: "#85a0a2",
          hex_7: "#699b9f",
          hex_8: "#3c4521",
          hex_9: "#5b88a3"
        }
      ]
    },
    "Snowy Peaks By The Seaside": {
      environment_title: "Snowy Peaks By The Seaside",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Snowy Peaks By The Seaside (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8852125,
          file_size_megabytes: 8.44,
          width: 3072,
          height: 5472,
          primary: "#5a7987",
          secondary: "#d4d9dc",
          tertiary: "#272321",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a0c9df",
          hex_5: "#80b5d0",
          hex_6: "#194b63",
          hex_7: "#96999b",
          hex_8: "#6ea6be",
          hex_9: "#0c3147"
        },
        {
          original_file_name: "Snowy Peaks By The Seaside (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8663861,
          file_size_megabytes: 8.26,
          width: 3072,
          height: 5472,
          primary: "#c7c8c8",
          secondary: "#355971",
          tertiary: "#9ab9ce",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#0f151c",
          hex_5: "#8898a6",
          hex_6: "#83a8c6",
          hex_7: "#5b8eac",
          hex_8: "#0e293f",
          hex_9: "#718c9a"
        },
        {
          original_file_name: "Snowy Peaks By The Seaside (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9208715,
          file_size_megabytes: 8.78,
          width: 3072,
          height: 5472,
          primary: "#3b5260",
          secondary: "#d9ccbe",
          tertiary: "#8e8f92",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#9eb9c5",
          hex_5: "#7ca5be",
          hex_6: "#3f7d9f",
          hex_7: "#112324",
          hex_8: "#5d92ad",
          hex_9: "#b48c74"
        },
        {
          original_file_name: "Snowy Peaks By The Seaside (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8534203,
          file_size_megabytes: 8.14,
          width: 3072,
          height: 5472,
          primary: "#415c6e",
          secondary: "#ccd6dd",
          tertiary: "#69a8c9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#96c2dd",
          hex_5: "#5291b3",
          hex_6: "#8c97a0",
          hex_7: "#2e2c2c",
          hex_8: "#0d293f",
          hex_9: "#ae9485"
        }
      ]
    },
    "Stormy Sea And Mountain Range": {
      environment_title: "Stormy Sea And Mountain Range",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Stormy Sea And Mountain Range (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7208296,
          file_size_megabytes: 6.87,
          width: 3072,
          height: 5472,
          primary: "#bcd2dc",
          secondary: "#132b36",
          tertiary: "#89acb6",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#617d8a",
          hex_5: "#7f98a6",
          hex_6: "#375562",
          hex_7: "#486274",
          hex_8: "#546373",
          hex_9: "#9ca4ac"
        },
        {
          original_file_name: "Stormy Sea And Mountain Range (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7792313,
          file_size_megabytes: 7.43,
          width: 3072,
          height: 5472,
          primary: "#172f3b",
          secondary: "#b9ccd5",
          tertiary: "#8caab3",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#678591",
          hex_5: "#3f5d67",
          hex_6: "#809aad",
          hex_7: "#556b7c",
          hex_8: "#9ca4ad",
          hex_9: "#5c6b73"
        },
        {
          original_file_name: "Stormy Sea And Mountain Range (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7447358,
          file_size_megabytes: 7.1,
          width: 3072,
          height: 5472,
          primary: "#162e39",
          secondary: "#b8c9cd",
          tertiary: "#637c87",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#84a2ab",
          hex_5: "#7991a5",
          hex_6: "#3e5863",
          hex_7: "#496275",
          hex_8: "#556168",
          hex_9: "#949495"
        },
        {
          original_file_name: "Stormy Sea And Mountain Range (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7602027,
          file_size_megabytes: 7.25,
          width: 3072,
          height: 5472,
          primary: "#bdd0d8",
          secondary: "#122834",
          tertiary: "#5a7781",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#85a2ab",
          hex_5: "#33505c",
          hex_6: "#42596d",
          hex_7: "#7e93a4",
          hex_8: "#949ca5",
          hex_9: "#545c64"
        }
      ]
    },
    "Sunlit Rocky Shoreline": {
      environment_title: "Sunlit Rocky Shoreline",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Sunlit Rocky Shoreline (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8153875,
          file_size_megabytes: 7.78,
          width: 3072,
          height: 5472,
          primary: "#c9d3d4",
          secondary: "#232829",
          tertiary: "#85aecb",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#588db3",
          hex_5: "#7d7e76",
          hex_6: "#4d7388",
          hex_7: "#3a6078",
          hex_8: "#534d43",
          hex_9: "#a48474"
        },
        {
          original_file_name: "Sunlit Rocky Shoreline (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8531166,
          file_size_megabytes: 8.14,
          width: 3072,
          height: 5472,
          primary: "#d8d0bc",
          secondary: "#282926",
          tertiary: "#94abae",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7996a6",
          hex_5: "#5c7889",
          hex_6: "#83827a",
          hex_7: "#435f76",
          hex_8: "#5c5448",
          hex_9: "#ac7c54"
        },
        {
          original_file_name: "Sunlit Rocky Shoreline (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10791078,
          file_size_megabytes: 10.29,
          width: 3072,
          height: 5472,
          primary: "#c9b593",
          secondary: "#1a1c1b",
          tertiary: "#776c54",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3d6e85",
          hex_5: "#48809e",
          hex_6: "#89a4a5",
          hex_7: "#30536a",
          hex_8: "#4d3c29",
          hex_9: "#9c5c1c"
        },
        {
          original_file_name: "Sunlit Rocky Shoreline (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9370578,
          file_size_megabytes: 8.94,
          width: 3072,
          height: 5472,
          primary: "#cac9bf",
          secondary: "#272721",
          tertiary: "#588eba",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#88b6d6",
          hex_5: "#72817f",
          hex_6: "#436170",
          hex_7: "#7a5e3a",
          hex_8: "#4c5a50",
          hex_9: "#a45c3c"
        }
      ]
    },
    "Sunrise Over Rocky Beach": {
      environment_title: "Sunrise Over Rocky Beach",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Sunrise Over Rocky Beach (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8625605,
          file_size_megabytes: 8.23,
          width: 3072,
          height: 5472,
          primary: "#e19c6f",
          secondary: "#291d1d",
          tertiary: "#797b87",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#905f51",
          hex_5: "#664641",
          hex_6: "#61666f",
          hex_7: "#434f5f",
          hex_8: "#a49c99",
          hex_9: "#b44404"
        },
        {
          original_file_name: "Sunrise Over Rocky Beach (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8592999,
          file_size_megabytes: 8.19,
          width: 3072,
          height: 5472,
          primary: "#d18c5f",
          secondary: "#2d2323",
          tertiary: "#8b6460",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#87899c",
          hex_5: "#51596c",
          hex_6: "#697081",
          hex_7: "#674843",
          hex_8: "#a2a4b2",
          hex_9: "#b44404"
        },
        {
          original_file_name: "Sunrise Over Rocky Beach (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8940242,
          file_size_megabytes: 8.53,
          width: 3072,
          height: 5472,
          primary: "#d48563",
          secondary: "#2b2423",
          tertiary: "#7c7789",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8b5950",
          hex_5: "#54505d",
          hex_6: "#5c3e34",
          hex_7: "#9e9494",
          hex_8: "#65656f",
          hex_9: "#ae3b0d"
        },
        {
          original_file_name: "Sunrise Over Rocky Beach (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8794552,
          file_size_megabytes: 8.39,
          width: 3072,
          height: 5472,
          primary: "#da8968",
          secondary: "#2d2123",
          tertiary: "#916663",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#828b9d",
          hex_5: "#545766",
          hex_6: "#96acc1",
          hex_7: "#677282",
          hex_8: "#663a31",
          hex_9: "#b4440e"
        }
      ]
    },
    "Sunset Over Rocky Cliffs": {
      environment_title: "Sunset Over Rocky Cliffs",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Sunset Over Rocky Cliffs (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9147555,
          file_size_megabytes: 8.72,
          width: 3072,
          height: 5472,
          primary: "#dc9264",
          secondary: "#272526",
          tertiary: "#90645c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#798999",
          hex_5: "#624646",
          hex_6: "#62727b",
          hex_7: "#9f9fa4",
          hex_8: "#505d69",
          hex_9: "#b64419"
        },
        {
          original_file_name: "Sunset Over Rocky Cliffs (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9894669,
          file_size_megabytes: 9.44,
          width: 3072,
          height: 5472,
          primary: "#d58e5c",
          secondary: "#24221e",
          tertiary: "#895540",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8ba8b1",
          hex_5: "#6d8d9a",
          hex_6: "#507075",
          hex_7: "#5f372b",
          hex_8: "#3c5661",
          hex_9: "#b5380d"
        },
        {
          original_file_name: "Sunset Over Rocky Cliffs (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9298058,
          file_size_megabytes: 8.87,
          width: 3072,
          height: 5472,
          primary: "#dd845a",
          secondary: "#292527",
          tertiary: "#9b6254",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8b94a8",
          hex_5: "#4d6279",
          hex_6: "#6b443f",
          hex_7: "#d6b6b6",
          hex_8: "#ab9590",
          hex_9: "#74655f"
        },
        {
          original_file_name: "Sunset Over Rocky Cliffs (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9066899,
          file_size_megabytes: 8.65,
          width: 3072,
          height: 5472,
          primary: "#dd8c57",
          secondary: "#2f2d2e",
          tertiary: "#946355",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#616e7c",
          hex_5: "#8a92a3",
          hex_6: "#6f4842",
          hex_7: "#d5b5aa",
          hex_8: "#a0948d",
          hex_9: "#6f655f"
        }
      ]
    },
    "Tropical Beach With Mountain Range": {
      environment_title: "Tropical Beach With Mountain Range",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Tropical Beach With Mountain Range (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10204728,
          file_size_megabytes: 9.73,
          width: 3072,
          height: 5472,
          primary: "#3a8fa7",
          secondary: "#33381c",
          tertiary: "#cdc9bb",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#415e57",
          hex_5: "#8cc6dc",
          hex_6: "#8daca8",
          hex_7: "#6ab8dc",
          hex_8: "#133948",
          hex_9: "#ac8c4c"
        },
        {
          original_file_name: "Tropical Beach With Mountain Range (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10289694,
          file_size_megabytes: 9.81,
          width: 3072,
          height: 5472,
          primary: "#ded1c0",
          secondary: "#429cc4",
          tertiary: "#35361e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7bc6cc",
          hex_5: "#6f9683",
          hex_6: "#3e707f",
          hex_7: "#887856",
          hex_8: "#5a6b43",
          hex_9: "#b48c72"
        },
        {
          original_file_name: "Tropical Beach With Mountain Range (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10072406,
          file_size_megabytes: 9.61,
          width: 3072,
          height: 5472,
          primary: "#e2dccd",
          secondary: "#333c21",
          tertiary: "#559ac5",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7ccbc3",
          hex_5: "#297092",
          hex_6: "#599989",
          hex_7: "#7d744f",
          hex_8: "#507345",
          hex_9: "#ac8c76"
        },
        {
          original_file_name: "Tropical Beach With Mountain Range (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10460380,
          file_size_megabytes: 9.98,
          width: 3072,
          height: 5472,
          primary: "#49919a",
          secondary: "#c8bcac",
          tertiary: "#212b12",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#495825",
          hex_5: "#92a899",
          hex_6: "#75c0d6",
          hex_7: "#285461",
          hex_8: "#8fd4dd",
          hex_9: "#ac846a"
        }
      ]
    },
    "Tropical Mountain Beach": {
      environment_title: "Tropical Mountain Beach",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Tropical Mountain Beach (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11017412,
          file_size_megabytes: 10.51,
          width: 3072,
          height: 5472,
          primary: "#d9d8ce",
          secondary: "#4b9c99",
          tertiary: "#1b2c0f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#465821",
          hex_5: "#8eb4a1",
          hex_6: "#2c584f",
          hex_7: "#497558",
          hex_8: "#88bbce",
          hex_9: "#8bdbc6"
        },
        {
          original_file_name: "Tropical Mountain Beach (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 11069332,
          file_size_megabytes: 10.56,
          width: 3072,
          height: 5472,
          primary: "#2a4a31",
          secondary: "#d6d0b9",
          tertiary: "#7dbbbf",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4e9679",
          hex_5: "#559fc5",
          hex_6: "#776924",
          hex_7: "#387372",
          hex_8: "#10150b",
          hex_9: "#a46408"
        },
        {
          original_file_name: "Tropical Mountain Beach (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 10571906,
          file_size_megabytes: 10.08,
          width: 3072,
          height: 5472,
          primary: "#3d8ca2",
          secondary: "#d1c8b4",
          tertiary: "#242a12",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4c5724",
          hex_5: "#8ea893",
          hex_6: "#5aa7d6",
          hex_7: "#28545e",
          hex_8: "#9dcdcd",
          hex_9: "#ad8c71"
        },
        {
          original_file_name: "Tropical Mountain Beach (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 9608059,
          file_size_megabytes: 9.16,
          width: 3072,
          height: 5472,
          primary: "#ccb99f",
          secondary: "#739385",
          tertiary: "#2a290d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4f5621",
          hex_5: "#47a5d5",
          hex_6: "#1c6a70",
          hex_7: "#3f5f5a",
          hex_8: "#9ad1dc",
          hex_9: "#c4843c"
        }
      ]
    },
    "Twilight Mountain Shore": {
      environment_title: "Twilight Mountain Shore",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Twilight Mountain Shore (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8507115,
          file_size_megabytes: 8.11,
          width: 3072,
          height: 5472,
          primary: "#2f2a41",
          secondary: "#d190b1",
          tertiary: "#8b6490",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#665081",
          hex_5: "#9e81ae",
          hex_6: "#62486c",
          hex_7: "#665c72",
          hex_8: "#9d8da2",
          hex_9: "#ac6e7c"
        },
        {
          original_file_name: "Twilight Mountain Shore (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8588720,
          file_size_megabytes: 8.19,
          width: 3072,
          height: 5472,
          primary: "#d28398",
          secondary: "#5e476d",
          tertiary: "#1b1926",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#252b43",
          hex_5: "#a36280",
          hex_6: "#937aa8",
          hex_7: "#a98eb5",
          hex_8: "#442c3e",
          hex_9: "#766e95"
        },
        {
          original_file_name: "Twilight Mountain Shore (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8298180,
          file_size_megabytes: 7.91,
          width: 3072,
          height: 5472,
          primary: "#343754",
          secondary: "#d78194",
          tertiary: "#935f7a",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8470a5",
          hex_5: "#0c0c15",
          hex_6: "#674d6d",
          hex_7: "#67668c",
          hex_8: "#a48493",
          hex_9: "#b66674"
        },
        {
          original_file_name: "Twilight Mountain Shore (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8142377,
          file_size_megabytes: 7.77,
          width: 3072,
          height: 5472,
          primary: "#d792a4",
          secondary: "#463458",
          tertiary: "#926a8a",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#977ea8",
          hex_5: "#70628a",
          hex_6: "#172341",
          hex_7: "#5c5385",
          hex_8: "#140b15",
          hex_9: "#a7849a"
        }
      ]
    }
  }
];
