export const database: unknown[] = [
  {
    "Adventurous Hiker In Nature": {
      environment_title: "Adventurous Hiker In Nature",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Adventurous Hiker In Nature (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7844517,
          file_size_megabytes: 7.48,
          width: 3072,
          height: 5472,
          primary: "#343534",
          secondary: "#cbc8c1",
          tertiary: "#93918b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a6b6b9",
          hex_5: "#587382",
          hex_6: "#708a94",
          hex_7: "#6e594b",
          hex_8: "#98abb4",
          hex_9: "#bd552a"
        },
        {
          original_file_name: "Adventurous Hiker In Nature (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8151058,
          file_size_megabytes: 7.77,
          width: 3072,
          height: 5472,
          primary: "#35302a",
          secondary: "#bdc0bd",
          tertiary: "#779ca8",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#65868f",
          hex_5: "#92b0b9",
          hex_6: "#4b6e7b",
          hex_7: "#4f6164",
          hex_8: "#7e6551",
          hex_9: "#a65822"
        },
        {
          original_file_name: "Adventurous Hiker In Nature (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8445419,
          file_size_megabytes: 8.05,
          width: 3072,
          height: 5472,
          primary: "#cabdb2",
          secondary: "#242d2c",
          tertiary: "#7d7567",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#94a7aa",
          hex_5: "#5c757a",
          hex_6: "#564a3a",
          hex_7: "#4c636c",
          hex_8: "#879ca4",
          hex_9: "#aa521f"
        },
        {
          original_file_name: "Adventurous Hiker In Nature (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8516261,
          file_size_megabytes: 8.12,
          width: 3072,
          height: 5472,
          primary: "#3c4547",
          secondary: "#ccc3b7",
          tertiary: "#867d6f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a0acad",
          hex_5: "#1a1310",
          hex_6: "#63818a",
          hex_7: "#90a2ad",
          hex_8: "#516f7f",
          hex_9: "#b4531e"
        }
      ]
    },
    "Adventurous Mountain Climber": {
      environment_title: "Adventurous Mountain Climber",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Adventurous Mountain Climber (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7503974,
          file_size_megabytes: 7.16,
          width: 3072,
          height: 5472,
          primary: "#cfcec9",
          secondary: "#314b5a",
          tertiary: "#97b3c1",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#271a13",
          hex_5: "#868076",
          hex_6: "#80a1b6",
          hex_7: "#5e8aa0",
          hex_8: "#477690",
          hex_9: "#b95d18"
        },
        {
          original_file_name: "Adventurous Mountain Climber (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7791978,
          file_size_megabytes: 7.43,
          width: 3072,
          height: 5472,
          primary: "#d2d2c7",
          secondary: "#2a3034",
          tertiary: "#99b3b6",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#88847e",
          hex_5: "#4a616a",
          hex_6: "#5d838f",
          hex_7: "#8ba3ac",
          hex_8: "#4a6f7e",
          hex_9: "#b15a38"
        },
        {
          original_file_name: "Adventurous Mountain Climber (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7642924,
          file_size_megabytes: 7.29,
          width: 3072,
          height: 5472,
          primary: "#c4c1bb",
          secondary: "#222020",
          tertiary: "#91aab8",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#657e8d",
          hex_5: "#3f5362",
          hex_6: "#80634c",
          hex_7: "#7c99ad",
          hex_8: "#566c73",
          hex_9: "#bf4627"
        },
        {
          original_file_name: "Adventurous Mountain Climber (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7755525,
          file_size_megabytes: 7.4,
          width: 3072,
          height: 5472,
          primary: "#e3e0d6",
          secondary: "#282c2e",
          tertiary: "#867c72",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7e9daf",
          hex_5: "#97b1ba",
          hex_6: "#5b8293",
          hex_7: "#466069",
          hex_8: "#466e80",
          hex_9: "#b46132"
        }
      ]
    },
    "Casual Skater In Urban Setting": {
      environment_title: "Casual Skater In Urban Setting",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Casual Skater In Urban Setting (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7921394,
          file_size_megabytes: 7.55,
          width: 3072,
          height: 5472,
          primary: "#b66567",
          secondary: "#201e1f",
          tertiary: "#84605f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7696aa",
          hex_5: "#447161",
          hex_6: "#135173",
          hex_7: "#bfc1c7",
          hex_8: "#563b3b",
          hex_9: "#919d73"
        },
        {
          original_file_name: "Casual Skater In Urban Setting (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8151394,
          file_size_megabytes: 7.77,
          width: 3072,
          height: 5472,
          primary: "#b7a99d",
          secondary: "#18151a",
          tertiary: "#7a4a4e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#459baa",
          hex_5: "#0e80a2",
          hex_6: "#ad2b53",
          hex_7: "#146d84",
          hex_8: "#502d34",
          hex_9: "#4c5851"
        },
        {
          original_file_name: "Casual Skater In Urban Setting (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7494674,
          file_size_megabytes: 7.15,
          width: 3072,
          height: 5472,
          primary: "#c4ac9e",
          secondary: "#241a1b",
          tertiary: "#5591af",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#966e62",
          hex_5: "#96b8ca",
          hex_6: "#367387",
          hex_7: "#6c3e3f",
          hex_8: "#205d7d",
          hex_9: "#be472a"
        },
        {
          original_file_name: "Casual Skater In Urban Setting (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7567393,
          file_size_megabytes: 7.22,
          width: 3072,
          height: 5472,
          primary: "#c3ab97",
          secondary: "#211b24",
          tertiary: "#8f7e71",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4b6f71",
          hex_5: "#97a6ae",
          hex_6: "#8b96a8",
          hex_7: "#0e537b",
          hex_8: "#5d2d40",
          hex_9: "#b04404"
        }
      ]
    },
    "Casual Urban Explorer": {
      environment_title: "Casual Urban Explorer",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Casual Urban Explorer (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6866993,
          file_size_megabytes: 6.55,
          width: 3072,
          height: 5472,
          primary: "#d3c9b8",
          secondary: "#232726",
          tertiary: "#807d76",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#93a5a2",
          hex_5: "#55504b",
          hex_6: "#819aa4",
          hex_7: "#5b716e",
          hex_8: "#52626c",
          hex_9: "#a65c4f"
        },
        {
          original_file_name: "Casual Urban Explorer (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7433499,
          file_size_megabytes: 7.09,
          width: 3072,
          height: 5472,
          primary: "#cdc7c2",
          secondary: "#1c292e",
          tertiary: "#7f776e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#97a8aa",
          hex_5: "#587075",
          hex_6: "#4d4f48",
          hex_7: "#8d9aa4",
          hex_8: "#4b636c",
          hex_9: "#a46446"
        },
        {
          original_file_name: "Casual Urban Explorer (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7268156,
          file_size_megabytes: 6.93,
          width: 3072,
          height: 5472,
          primary: "#c2aa93",
          secondary: "#1e2328",
          tertiary: "#776f66",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8ca1a2",
          hex_5: "#4b4847",
          hex_6: "#54696e",
          hex_7: "#475965",
          hex_8: "#82939c",
          hex_9: "#9c4c24"
        },
        {
          original_file_name: "Casual Urban Explorer (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7446539,
          file_size_megabytes: 7.1,
          width: 3072,
          height: 5472,
          primary: "#c1beb4",
          secondary: "#1f2930",
          tertiary: "#71878b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8aa7a6",
          hex_5: "#3d5963",
          hex_6: "#476976",
          hex_7: "#745447",
          hex_8: "#7e9ba4",
          hex_9: "#9d5b40"
        }
      ]
    },
    "Cheerful Baker In Bakery": {
      environment_title: "Cheerful Baker In Bakery",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Cheerful Baker In Bakery (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6951172,
          file_size_megabytes: 6.63,
          width: 3072,
          height: 5472,
          primary: "#d5b69f",
          secondary: "#2b190e",
          tertiary: "#916b53",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a6a29e",
          hex_5: "#694127",
          hex_6: "#98918e",
          hex_7: "#78685d",
          hex_8: "#6c584f",
          hex_9: "#b94f0d"
        },
        {
          original_file_name: "Cheerful Baker In Bakery (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7167167,
          file_size_megabytes: 6.84,
          width: 3072,
          height: 5472,
          primary: "#dba978",
          secondary: "#281811",
          tertiary: "#9a6c47",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#b09f85",
          hex_5: "#6a3f21",
          hex_6: "#74634d",
          hex_7: "#9d938c",
          hex_8: "#bd4b09",
          hex_9: "#4f4e57"
        },
        {
          original_file_name: "Cheerful Baker In Bakery (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7341888,
          file_size_megabytes: 7.0,
          width: 3072,
          height: 5472,
          primary: "#cea788",
          secondary: "#271711",
          tertiary: "#8a5c3e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#9e978d",
          hex_5: "#5e351e",
          hex_6: "#6c7f93",
          hex_7: "#3b4656",
          hex_8: "#58636e",
          hex_9: "#ac4b13"
        },
        {
          original_file_name: "Cheerful Baker In Bakery (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6975632,
          file_size_megabytes: 6.65,
          width: 3072,
          height: 5472,
          primary: "#dbb797",
          secondary: "#241309",
          tertiary: "#896145",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a1968c",
          hex_5: "#685749",
          hex_6: "#5f3b25",
          hex_7: "#b25009",
          hex_8: "#988c8c",
          hex_9: "#594c4c"
        }
      ]
    },
    "Confident Business Leader": {
      environment_title: "Confident Business Leader",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Confident Business Leader (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5599354,
          file_size_megabytes: 5.34,
          width: 3072,
          height: 5472,
          primary: "#af978e",
          secondary: "#191618",
          tertiary: "#6a534b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#82828d",
          hex_5: "#42312d",
          hex_6: "#848c91",
          hex_7: "#4a4b54",
          hex_8: "#4c5459",
          hex_9: "#8c4c3c"
        },
        {
          original_file_name: "Confident Business Leader (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5835148,
          file_size_megabytes: 5.56,
          width: 3072,
          height: 5472,
          primary: "#bfa394",
          secondary: "#101115",
          tertiary: "#684f45",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#828d98",
          hex_5: "#3e2c26",
          hex_6: "#7a818e",
          hex_7: "#4b545e",
          hex_8: "#454a56",
          hex_9: "#8c4c34"
        },
        {
          original_file_name: "Confident Business Leader (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6139523,
          file_size_megabytes: 5.86,
          width: 3072,
          height: 5472,
          primary: "#c1967c",
          secondary: "#131416",
          tertiary: "#684c3a",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3f2f26",
          hex_5: "#828c91",
          hex_6: "#4b5457",
          hex_7: "#7e838d",
          hex_8: "#464b54",
          hex_9: "#8c4c44"
        },
        {
          original_file_name: "Confident Business Leader (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6600921,
          file_size_megabytes: 6.3,
          width: 3072,
          height: 5472,
          primary: "#c6a48c",
          secondary: "#161416",
          tertiary: "#705444",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#413c3a",
          hex_5: "#4f585a",
          hex_6: "#898d8c",
          hex_7: "#474b54",
          hex_8: "#96542e",
          hex_9: "#82848e"
        }
      ]
    },
    "Confident Engineer With Blueprints": {
      environment_title: "Confident Engineer With Blueprints",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Confident Engineer With Blueprints (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7484702,
          file_size_megabytes: 7.14,
          width: 3072,
          height: 5472,
          primary: "#ccc9c6",
          secondary: "#1e2022",
          tertiary: "#9fa7a9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#837f7b",
          hex_5: "#8f97a0",
          hex_6: "#677175",
          hex_7: "#584941",
          hex_8: "#586068",
          hex_9: "#ac6438"
        },
        {
          original_file_name: "Confident Engineer With Blueprints (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7360667,
          file_size_megabytes: 7.02,
          width: 3072,
          height: 5472,
          primary: "#ddd3ca",
          secondary: "#181e27",
          tertiary: "#84756b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#9faeb9",
          hex_5: "#647275",
          hex_6: "#584e46",
          hex_7: "#8898a7",
          hex_8: "#465b72",
          hex_9: "#b76235"
        },
        {
          original_file_name: "Confident Engineer With Blueprints (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6896587,
          file_size_megabytes: 6.58,
          width: 3072,
          height: 5472,
          primary: "#24292d",
          secondary: "#cac4c0",
          tertiary: "#817974",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#657277",
          hex_5: "#99a6ad",
          hex_6: "#909aa5",
          hex_7: "#5c4b41",
          hex_8: "#56626d",
          hex_9: "#a46c4e"
        },
        {
          original_file_name: "Confident Engineer With Blueprints (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6632631,
          file_size_megabytes: 6.33,
          width: 3072,
          height: 5472,
          primary: "#c5c9ce",
          secondary: "#9ba9b3",
          tertiary: "#181e22",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7b756d",
          hex_5: "#546b71",
          hex_6: "#84909f",
          hex_7: "#4e453f",
          hex_8: "#485a65",
          hex_9: "#ac6444"
        }
      ]
    },
    "Elegant Sculptor With Marble Block": {
      environment_title: "Elegant Sculptor With Marble Block",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Elegant Sculptor With Marble Block (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6415617,
          file_size_megabytes: 6.12,
          width: 3072,
          height: 5472,
          primary: "#baa592",
          secondary: "#1a1a1a",
          tertiary: "#756151",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#503f34",
          hex_5: "#93948b",
          hex_6: "#8b8c94",
          hex_7: "#9c5c40",
          hex_8: "#595e5b",
          hex_9: "#34455c"
        },
        {
          original_file_name: "Elegant Sculptor With Marble Block (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6767417,
          file_size_megabytes: 6.45,
          width: 3072,
          height: 5472,
          primary: "#bbb0a8",
          secondary: "#1b1a18",
          tertiary: "#76716b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#575f5f",
          hex_5: "#4b4641",
          hex_6: "#8c9294",
          hex_7: "#929d9b",
          hex_8: "#4a535c",
          hex_9: "#9c5c44"
        },
        {
          original_file_name: "Elegant Sculptor With Marble Block (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6568396,
          file_size_megabytes: 6.26,
          width: 3072,
          height: 5472,
          primary: "#baa795",
          secondary: "#262320",
          tertiary: "#877f73",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#59524b",
          hex_5: "#596166",
          hex_6: "#9a9c94",
          hex_7: "#666e71",
          hex_8: "#474f52",
          hex_9: "#848f96"
        },
        {
          original_file_name: "Elegant Sculptor With Marble Block (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6579272,
          file_size_megabytes: 6.27,
          width: 3072,
          height: 5472,
          primary: "#beaf9e",
          secondary: "#1b1511",
          tertiary: "#989891",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#82786d",
          hex_5: "#5f6669",
          hex_6: "#728391",
          hex_7: "#464d54",
          hex_8: "#544031",
          hex_9: "#ac745e"
        }
      ]
    },
    "Energetic Musician In Action": {
      environment_title: "Energetic Musician In Action",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Energetic Musician In Action (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6135924,
          file_size_megabytes: 5.85,
          width: 3072,
          height: 5472,
          primary: "#ce6c26",
          secondary: "#0c0c15",
          tertiary: "#184f6d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#d6dfe1",
          hex_5: "#5ca1bf",
          hex_6: "#5a2816",
          hex_7: "#1b719c",
          hex_8: "#0a2d45",
          hex_9: "#574f48"
        },
        {
          original_file_name: "Energetic Musician In Action (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6035608,
          file_size_megabytes: 5.76,
          width: 3072,
          height: 5472,
          primary: "#ca6631",
          secondary: "#0f0b11",
          tertiary: "#64221d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3fa3ba",
          hex_5: "#0e7396",
          hex_6: "#e0dac4",
          hex_7: "#0e5870",
          hex_8: "#092b3e",
          hex_9: "#083f59"
        },
        {
          original_file_name: "Energetic Musician In Action (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6709090,
          file_size_megabytes: 6.4,
          width: 3072,
          height: 5472,
          primary: "#da772d",
          secondary: "#1a141d",
          tertiary: "#783a2d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#35a1b5",
          hex_5: "#0d546d",
          hex_6: "#4c1c1e",
          hex_7: "#f3daa7",
          hex_8: "#0e7b9a",
          hex_9: "#51564f"
        },
        {
          original_file_name: "Energetic Musician In Action (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5770289,
          file_size_megabytes: 5.5,
          width: 3072,
          height: 5472,
          primary: "#cf9877",
          secondary: "#0a1017",
          tertiary: "#1a596c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#52a2bf",
          hex_5: "#127b9a",
          hex_6: "#573627",
          hex_7: "#113644",
          hex_8: "#9f350c",
          hex_9: "#63584b"
        }
      ]
    },
    "Graceful Ballet Dancer": {
      environment_title: "Graceful Ballet Dancer",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Graceful Ballet Dancer (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6124398,
          file_size_megabytes: 5.84,
          width: 3072,
          height: 5472,
          primary: "#c6c0b8",
          secondary: "#1e1c1a",
          tertiary: "#8b9da3",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#706b67",
          hex_5: "#556165",
          hex_6: "#494543",
          hex_7: "#7a8b94",
          hex_8: "#4a535c",
          hex_9: "#9c6454"
        },
        {
          original_file_name: "Graceful Ballet Dancer (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6212695,
          file_size_megabytes: 5.92,
          width: 3072,
          height: 5472,
          primary: "#c7c6bd",
          secondary: "#1f1814",
          tertiary: "#949e99",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7c746c",
          hex_5: "#5f6161",
          hex_6: "#7e8998",
          hex_7: "#53453d",
          hex_8: "#515156",
          hex_9: "#a4644f"
        },
        {
          original_file_name: "Graceful Ballet Dancer (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6118579,
          file_size_megabytes: 5.84,
          width: 3072,
          height: 5472,
          primary: "#c3c2c3",
          secondary: "#1e1c1a",
          tertiary: "#8e999f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#747576",
          hex_5: "#828b94",
          hex_6: "#576165",
          hex_7: "#49413e",
          hex_8: "#4d535c",
          hex_9: "#9c6450"
        },
        {
          original_file_name: "Graceful Ballet Dancer (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5771094,
          file_size_megabytes: 5.5,
          width: 3072,
          height: 5472,
          primary: "#d5ceca",
          secondary: "#2f241d",
          tertiary: "#a6a9a8",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8e827a",
          hex_5: "#989a9d",
          hex_6: "#6f706d",
          hex_7: "#63615e",
          hex_8: "#624d41",
          hex_9: "#b47c64"
        }
      ]
    },
    "Graceful Violinist In Concert": {
      environment_title: "Graceful Violinist In Concert",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Graceful Violinist In Concert (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5808413,
          file_size_megabytes: 5.54,
          width: 3072,
          height: 5472,
          primary: "#d3a586",
          secondary: "#110a09",
          tertiary: "#6b493a",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3d2216",
          hex_5: "#9f3a0e",
          hex_6: "#717a87",
          hex_7: "#868d90",
          hex_8: "#48515a",
          hex_9: "#3a3e48"
        },
        {
          original_file_name: "Graceful Violinist In Concert (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6587282,
          file_size_megabytes: 6.28,
          width: 3072,
          height: 5472,
          primary: "#c9946e",
          secondary: "#160f10",
          tertiary: "#754b34",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#462a1e",
          hex_5: "#89959a",
          hex_6: "#a43f09",
          hex_7: "#75818d",
          hex_8: "#50585b",
          hex_9: "#404650"
        },
        {
          original_file_name: "Graceful Violinist In Concert (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5018529,
          file_size_megabytes: 4.79,
          width: 3072,
          height: 5472,
          primary: "#d7aa87",
          secondary: "#5d3a2b",
          tertiary: "#08060a",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#371d14",
          hex_5: "#96431e",
          hex_6: "#43444b",
          hex_7: "#81847a",
          hex_8: "#7c7c84",
          hex_9: "#3b3c4c"
        },
        {
          original_file_name: "Graceful Violinist In Concert (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5536444,
          file_size_megabytes: 5.28,
          width: 3072,
          height: 5472,
          primary: "#caae96",
          secondary: "#090a0d",
          tertiary: "#625144",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2f595e",
          hex_5: "#749597",
          hex_6: "#36281d",
          hex_7: "#a6491e",
          hex_8: "#18414f",
          hex_9: "#5c828d"
        }
      ]
    },
    "Joyful Family Gathering": {
      environment_title: "Joyful Family Gathering",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Joyful Family Gathering (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8106898,
          file_size_megabytes: 7.73,
          width: 3072,
          height: 5472,
          primary: "#d6ba92",
          secondary: "#483f27",
          tertiary: "#877b55",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8e929a",
          hex_5: "#71765d",
          hex_6: "#161511",
          hex_7: "#9ea6a9",
          hex_8: "#5f6168",
          hex_9: "#2b1107"
        },
        {
          original_file_name: "Joyful Family Gathering (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7360602,
          file_size_megabytes: 7.02,
          width: 3072,
          height: 5472,
          primary: "#2e281a",
          secondary: "#c5a690",
          tertiary: "#8b735e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#687778",
          hex_5: "#9aa8a9",
          hex_6: "#4c5d63",
          hex_7: "#88989f",
          hex_8: "#654c30",
          hex_9: "#b45c54"
        },
        {
          original_file_name: "Joyful Family Gathering (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7285171,
          file_size_megabytes: 6.95,
          width: 3072,
          height: 5472,
          primary: "#c8ad9a",
          secondary: "#211e16",
          tertiary: "#9ba2a6",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#896f58",
          hex_5: "#889098",
          hex_6: "#626d6e",
          hex_7: "#59422b",
          hex_8: "#48535c",
          hex_9: "#ac4c2c"
        },
        {
          original_file_name: "Joyful Family Gathering (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7546139,
          file_size_megabytes: 7.2,
          width: 3072,
          height: 5472,
          primary: "#34281d",
          secondary: "#d2b49a",
          tertiary: "#9f7756",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8b99a7",
          hex_5: "#a6b2bc",
          hex_6: "#775537",
          hex_7: "#717d85",
          hex_8: "#52606e",
          hex_9: "#bc6448"
        }
      ]
    },
    "Radiant Bride In Garden": {
      environment_title: "Radiant Bride In Garden",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Radiant Bride In Garden (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7385797,
          file_size_megabytes: 7.04,
          width: 3072,
          height: 5472,
          primary: "#d3c2a6",
          secondary: "#222613",
          tertiary: "#8d7b5a",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a8a690",
          hex_5: "#9f9996",
          hex_6: "#6d704f",
          hex_7: "#5f512a",
          hex_8: "#635f5a",
          hex_9: "#d23c1b"
        },
        {
          original_file_name: "Radiant Bride In Garden (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7732226,
          file_size_megabytes: 7.37,
          width: 3072,
          height: 5472,
          primary: "#d4b58a",
          secondary: "#2e2c15",
          tertiary: "#937d55",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#9a9c9c",
          hex_5: "#a8aea7",
          hex_6: "#69582b",
          hex_7: "#777756",
          hex_8: "#71665d",
          hex_9: "#c64814"
        },
        {
          original_file_name: "Radiant Bride In Garden (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7234738,
          file_size_megabytes: 6.9,
          width: 3072,
          height: 5472,
          primary: "#d9c19e",
          secondary: "#2b2914",
          tertiary: "#adada5",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#977950",
          hex_5: "#727246",
          hex_6: "#68522d",
          hex_7: "#9c9998",
          hex_8: "#685f58",
          hex_9: "#cc560a"
        },
        {
          original_file_name: "Radiant Bride In Garden (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7406186,
          file_size_megabytes: 7.06,
          width: 3072,
          height: 5472,
          primary: "#d2c3a7",
          secondary: "#222613",
          tertiary: "#8a7555",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#9ea293",
          hex_5: "#636a46",
          hex_6: "#564b26",
          hex_7: "#909395",
          hex_8: "#c33a4c",
          hex_9: "#555655"
        }
      ]
    },
    "Radiant Smiles In Golden Hour": {
      environment_title: "Radiant Smiles In Golden Hour",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Radiant Smiles In Golden Hour (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7013701,
          file_size_megabytes: 6.69,
          width: 3072,
          height: 5472,
          primary: "#73441f",
          secondary: "#f4d297",
          tertiary: "#281207",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#df954c",
          hex_5: "#a8a4a0",
          hex_6: "#b18e70",
          hex_7: "#ae6d35",
          hex_8: "#9c7968",
          hex_9: "#3c341a"
        },
        {
          original_file_name: "Radiant Smiles In Golden Hour (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7302360,
          file_size_megabytes: 6.96,
          width: 3072,
          height: 5472,
          primary: "#62391a",
          secondary: "#eaac67",
          tertiary: "#1d1108",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a1856e",
          hex_5: "#a8622d",
          hex_6: "#886e5a",
          hex_7: "#a5978d",
          hex_8: "#b7a58f",
          hex_9: "#c44b06"
        },
        {
          original_file_name: "Radiant Smiles In Golden Hour (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6995258,
          file_size_megabytes: 6.67,
          width: 3072,
          height: 5472,
          primary: "#e3c69d",
          secondary: "#3c1b0a",
          tertiary: "#9c6e4f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#c48553",
          hex_5: "#aa998e",
          hex_6: "#763f1e",
          hex_7: "#806a55",
          hex_8: "#f7a93f",
          hex_9: "#755b4c"
        },
        {
          original_file_name: "Radiant Smiles In Golden Hour (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7642741,
          file_size_megabytes: 7.29,
          width: 3072,
          height: 5472,
          primary: "#db9d5e",
          secondary: "#342016",
          tertiary: "#965d34",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a2a098",
          hex_5: "#6f706f",
          hex_6: "#515358",
          hex_7: "#703c19",
          hex_8: "#949394",
          hex_9: "#b44404"
        }
      ]
    },
    "Serene Meditation Practitioner": {
      environment_title: "Serene Meditation Practitioner",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Serene Meditation Practitioner (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7066151,
          file_size_megabytes: 6.74,
          width: 3072,
          height: 5472,
          primary: "#c5b79e",
          secondary: "#322a1d",
          tertiary: "#8e7d66",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#655340",
          hex_5: "#a2a6a1",
          hex_6: "#726d5b",
          hex_7: "#9a999f",
          hex_8: "#6a6364",
          hex_9: "#c53720"
        },
        {
          original_file_name: "Serene Meditation Practitioner (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7341394,
          file_size_megabytes: 7.0,
          width: 3072,
          height: 5472,
          primary: "#2b2a1e",
          secondary: "#c5bcb0",
          tertiary: "#827663",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#979e93",
          hex_5: "#5d503d",
          hex_6: "#8d9097",
          hex_7: "#676e55",
          hex_8: "#64605f",
          hex_9: "#a4643c"
        },
        {
          original_file_name: "Serene Meditation Practitioner (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7077138,
          file_size_megabytes: 6.75,
          width: 3072,
          height: 5472,
          primary: "#cfbbaa",
          secondary: "#4e4b32",
          tertiary: "#90826e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#777f4f",
          hex_5: "#0f0c08",
          hex_6: "#746e67",
          hex_7: "#2c170d",
          hex_8: "#9ea09e",
          hex_9: "#a1aca1"
        },
        {
          original_file_name: "Serene Meditation Practitioner (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7075275,
          file_size_megabytes: 6.75,
          width: 3072,
          height: 5472,
          primary: "#ccad84",
          secondary: "#282921",
          tertiary: "#7d614c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5b675e",
          hex_5: "#524934",
          hex_6: "#4d5561",
          hex_7: "#7d8b9a",
          hex_8: "#909ea7",
          hex_9: "#9c5438"
        }
      ]
    },
    "Stylish Fashion Designer": {
      environment_title: "Stylish Fashion Designer",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Stylish Fashion Designer (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7450144,
          file_size_megabytes: 7.11,
          width: 3072,
          height: 5472,
          primary: "#c9baa9",
          secondary: "#1c1a17",
          tertiary: "#8b6f57",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#9da29d",
          hex_5: "#584130",
          hex_6: "#656158",
          hex_7: "#8d9296",
          hex_8: "#324f5f",
          hex_9: "#af5c2a"
        },
        {
          original_file_name: "Stylish Fashion Designer (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7699089,
          file_size_megabytes: 7.34,
          width: 3072,
          height: 5472,
          primary: "#d3c4ba",
          secondary: "#aca49b",
          tertiary: "#191612",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#917a65",
          hex_5: "#6a6559",
          hex_6: "#5a422d",
          hex_7: "#9a9394",
          hex_8: "#4c5155",
          hex_9: "#bc7448"
        },
        {
          original_file_name: "Stylish Fashion Designer (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7314488,
          file_size_megabytes: 6.98,
          width: 3072,
          height: 5472,
          primary: "#d9c8b8",
          secondary: "#1f1612",
          tertiary: "#8e6d53",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a5a6a1",
          hex_5: "#61432c",
          hex_6: "#69645b",
          hex_7: "#8e9097",
          hex_8: "#515156",
          hex_9: "#b47450"
        },
        {
          original_file_name: "Stylish Fashion Designer (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7459377,
          file_size_megabytes: 7.11,
          width: 3072,
          height: 5472,
          primary: "#ccbcaa",
          secondary: "#251d19",
          tertiary: "#887765",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a19e93",
          hex_5: "#5d493a",
          hex_6: "#66665b",
          hex_7: "#5e5b5c",
          hex_8: "#98929c",
          hex_9: "#ac6434"
        }
      ]
    },
    "Thoughtful Artist In Studio": {
      environment_title: "Thoughtful Artist In Studio",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Thoughtful Artist In Studio (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6981924,
          file_size_megabytes: 6.66,
          width: 3072,
          height: 5472,
          primary: "#c5a793",
          secondary: "#1f1c1d",
          tertiary: "#7d5949",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#553b2c",
          hex_5: "#4c656f",
          hex_6: "#889a9b",
          hex_7: "#294a64",
          hex_8: "#547a97",
          hex_9: "#a14627"
        },
        {
          original_file_name: "Thoughtful Artist In Studio (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6945775,
          file_size_megabytes: 6.62,
          width: 3072,
          height: 5472,
          primary: "#d4b496",
          secondary: "#1e1712",
          tertiary: "#765e4f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#61ada8",
          hex_5: "#4d3727",
          hex_6: "#2872ae",
          hex_7: "#c1462f",
          hex_8: "#48655f",
          hex_9: "#34455e"
        },
        {
          original_file_name: "Thoughtful Artist In Studio (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6891919,
          file_size_megabytes: 6.57,
          width: 3072,
          height: 5472,
          primary: "#d5c9b2",
          secondary: "#1b1711",
          tertiary: "#77614b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#899f92",
          hex_5: "#4d3827",
          hex_6: "#738790",
          hex_7: "#4b645e",
          hex_8: "#354854",
          hex_9: "#d54333"
        },
        {
          original_file_name: "Thoughtful Artist In Studio (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6607675,
          file_size_megabytes: 6.3,
          width: 3072,
          height: 5472,
          primary: "#d2beac",
          secondary: "#191211",
          tertiary: "#80533d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#939e9e",
          hex_5: "#b04018",
          hex_6: "#513122",
          hex_7: "#4f5e5e",
          hex_8: "#7c8591",
          hex_9: "#364650"
        }
      ]
    },
    "Thoughtful Writer With Notebook": {
      environment_title: "Thoughtful Writer With Notebook",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Thoughtful Writer With Notebook (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6020097,
          file_size_megabytes: 5.74,
          width: 3072,
          height: 5472,
          primary: "#dcac79",
          secondary: "#110a05",
          tertiary: "#6d4729",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3d2312",
          hex_5: "#984920",
          hex_6: "#4b4432",
          hex_7: "#473b34",
          hex_8: "#8c8454",
          hex_9: "#8c7c74"
        },
        {
          original_file_name: "Thoughtful Writer With Notebook (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6111390,
          file_size_megabytes: 5.83,
          width: 3072,
          height: 5472,
          primary: "#e5c19e",
          secondary: "#100a09",
          tertiary: "#643d25",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#965029",
          hex_5: "#3c2316",
          hex_6: "#474746",
          hex_7: "#827c6e",
          hex_8: "#373b44",
          hex_9: "#5c6474"
        },
        {
          original_file_name: "Thoughtful Writer With Notebook (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6178663,
          file_size_megabytes: 5.89,
          width: 3072,
          height: 5472,
          primary: "#cda789",
          secondary: "#0f0c0c",
          tertiary: "#694630",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3f2516",
          hex_5: "#3f515a",
          hex_6: "#293c49",
          hex_7: "#8a8d86",
          hex_8: "#974417",
          hex_9: "#7d8384"
        },
        {
          original_file_name: "Thoughtful Writer With Notebook (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6401016,
          file_size_megabytes: 6.1,
          width: 3072,
          height: 5472,
          primary: "#d6b89f",
          secondary: "#150d0b",
          tertiary: "#6f4831",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#442b1d",
          hex_5: "#504d48",
          hex_6: "#964a23",
          hex_7: "#8c8e8c",
          hex_8: "#848285",
          hex_9: "#40444c"
        }
      ]
    },
    "Vintage Elegance": {
      environment_title: "Vintage Elegance",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Vintage Elegance (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6964415,
          file_size_megabytes: 6.64,
          width: 3072,
          height: 5472,
          primary: "#cfb58e",
          secondary: "#1d1d1c",
          tertiary: "#81664b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#467272",
          hex_5: "#573d2a",
          hex_6: "#88a090",
          hex_7: "#31595e",
          hex_8: "#5f9194",
          hex_9: "#b2353a"
        },
        {
          original_file_name: "Vintage Elegance (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6883015,
          file_size_megabytes: 6.56,
          width: 3072,
          height: 5472,
          primary: "#d1a471",
          secondary: "#1a1816",
          tertiary: "#87a392",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7c5b3c",
          hex_5: "#4f6e64",
          hex_6: "#51331d",
          hex_7: "#395354",
          hex_8: "#768c8c",
          hex_9: "#a43c2c"
        },
        {
          original_file_name: "Vintage Elegance (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6888299,
          file_size_megabytes: 6.57,
          width: 3072,
          height: 5472,
          primary: "#dac8a5",
          secondary: "#281910",
          tertiary: "#907653",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#a1a380",
          hex_5: "#687257",
          hex_6: "#60452d",
          hex_7: "#575a54",
          hex_8: "#9b948c",
          hex_9: "#b46c54"
        },
        {
          original_file_name: "Vintage Elegance (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6783536,
          file_size_megabytes: 6.47,
          width: 3072,
          height: 5472,
          primary: "#d2ab7d",
          secondary: "#1c1213",
          tertiary: "#844c35",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#989776",
          hex_5: "#a93f24",
          hex_6: "#562a1f",
          hex_7: "#5b5b4d",
          hex_8: "#424a54",
          hex_9: "#948c8c"
        }
      ]
    },
    "VintageInspired Photographer": {
      environment_title: "VintageInspired Photographer",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "VintageInspired Photographer (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7604951,
          file_size_megabytes: 7.25,
          width: 3072,
          height: 5472,
          primary: "#c9b397",
          secondary: "#2c1c16",
          tertiary: "#81614b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#9b9480",
          hex_5: "#593c2c",
          hex_6: "#615d51",
          hex_7: "#a46442",
          hex_8: "#575354",
          hex_9: "#9c8c8c"
        },
        {
          original_file_name: "VintageInspired Photographer (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6990643,
          file_size_megabytes: 6.67,
          width: 3072,
          height: 5472,
          primary: "#c6af93",
          secondary: "#2d1e17",
          tertiary: "#876d58",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5b4232",
          hex_5: "#69665a",
          hex_6: "#a46c52",
          hex_7: "#5e5955",
          hex_8: "#9a9e96",
          hex_9: "#93918d"
        },
        {
          original_file_name: "VintageInspired Photographer (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7786030,
          file_size_megabytes: 7.43,
          width: 3072,
          height: 5472,
          primary: "#b68b67",
          secondary: "#211411",
          tertiary: "#79624c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4d3a2d",
          hex_5: "#869593",
          hex_6: "#7c8b8d",
          hex_7: "#565d5a",
          hex_8: "#9c5c3c",
          hex_9: "#474c54"
        },
        {
          original_file_name: "VintageInspired Photographer (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7095474,
          file_size_megabytes: 6.77,
          width: 3072,
          height: 5472,
          primary: "#d3b391",
          secondary: "#261712",
          tertiary: "#7c664d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#543d2f",
          hex_5: "#615c4f",
          hex_6: "#949487",
          hex_7: "#585255",
          hex_8: "#9c5c44",
          hex_9: "#948c8c"
        }
      ]
    }
  }
];
