titles = [
    "Cinematic, Bokeh - Blurring the Boundaries",
    "Cinematic, Cinematic - Frame Your World",
    "Cinematic, Close-Up - Up Close and Personal",
    "Cinematic, Creative - Visual Storytelling Unleashed",
    "Cinematic, Fashion - Chic Through the Lens",
    "Cinematic, Film - Timeless Aesthetics",
    "Cinematic, Food - A Feast for the Eyes",
    "Cinematic, HDR - Dynamic Drama",
    "Cinematic, Long Exposure - Time in Motion",
    "Cinematic, Macro - The Tiny Universe",
    "Cinematic, Monochrome - Shades of Simplicity",
    "Cinematic, Moody - The Art of Atmosphere",
    "Cinematic, Neutral - Quiet Elegance",
    "Cinematic, Retro - Vintage Revival",
    "Cinematic, Portrait - Faces and Expressions",
    "Cinematic, Stock Photo - Versatile Visuals",
    "Cinematic, Unprocessed - Pure and Raw",
    "Cinematic, Vibrant - The Power of Color",
    "Anime, Background - Building Anime Worlds",
    "Anime, Flat Illustration - Flat Yet Impactful",
    "Anime, Monochrome - Minimalistic Anime Vibes",
    "Anime, Retro - Anime Nostalgia",
    "Anime, Screencap - Framing Anime Moments",
    "Anime, Semi-Realism - Anime Meets Realism",
    "Anime, Character Sheet - Blueprint of Personalities",
    "Anime, Character Sheet Painterly - Brushed Stories",
    "Anime, Manga - Panel Perfection",
    "Portrait Perfect, Bokeh - Focus on Faces",
    "Portrait Perfect, Cinematic - Dramatic Portraiture",
    "Portrait Perfect, Close-Up - Revealing Depth",
    "Portrait Perfect, Fashion - Styled to Perfection",
    "Portrait Perfect, Film - Portraits in Motion",
    "Portrait Perfect, Moody - Emotive Captures",
    "Portrait Perfect, Retro - Vintage Portraits",
    "DSLR Photography, Stock Photo - Picture Perfect Stock",
    "Graphic Design, 2D Design - Flat Creativity",
    "Graphic Design, 3D Design - Adding Dimensions",
    "Graphic Design, Art Deco Design - Golden Age Revival",
    "Graphic Design, Pop Art Design - Bold and Bright",
    "Graphic Design, Vector Design - Precision Meets Creativity",
    "Hyper Realism, 3D Render - Depth in Details",
    "Hyper Realism, Bokeh - Layered Realism",
    "Hyper Realism, Cinematic - Real-Life Drama",
    "Hyper Realism, Close-Up - Detailed Intimacy",
    "Hyper Realism, Creative - Reimagining Reality",
    "Hyper Realism, Fashion - Haute Realism",
    "Hyper Realism, Film - Hyper-Real Frames",
    "Hyper Realism, HDR - Bright and Bold Realism",
    "Hyper Realism, Illustration - Life-Like Strokes",
    "Hyper Realism, Long Exposure - Stretched Realities",
    "Hyper Realism, Macro - Hyper-Real Microcosms",
    "Hyper Realism, Minimalist - Focused Simplicity",
    "Hyper Realism, Monochrome - Realism in Black and White",
    "Hyper Realism, Moody - Darkly Detailed",
    "Hyper Realism, Ray Traced - Perfect Light, Perfect Shadows",
    "Hyper Realism, Retro - Hyper-Real Nostalgia",
    "Hyper Realism, Vibrant - Colorful Realities"
]