import os

def delete_unlisted_files(directory, allowed_files):
    for filename in os.listdir(directory):
        filepath = os.path.join(directory, filename)
        if os.path.isfile(filepath) and filename not in allowed_files:
            try:
                os.remove(filepath)
                print(f"Deleted: {filename} in {directory}")
            except Exception as e:
                print(f"Error deleting {filename} in {directory}: {e}")

parent_directory = "sources"
subdirectories = ["base", "highRes", "lowRes"]
file_list = []
for i in range(1, 5):
    file_list.append(f"The Ashen Veil Over Forgotten Ruins ({i}).jpg") 
    file_list.append(f"The Symphony Of Emerald Cascades ({i}).jpg") 
    file_list.append(f"The Echoes In Neon Shadows ({i}).jpg") 
    file_list.append(f"The Moonlight Upon Silent Dunes ({i}).jpg") 
    file_list.append(f"The Stories Etched In Painted Walls ({i}).jpg") 
    file_list.append(f"The Frozen Reverie Beneath Arctic Skies ({i}).jpg") 
    file_list.append(f"The Sunrise Over Pastel Shores ({i}).jpg") 
    file_list.append(f"The Ashfall Over Silent Plains ({i}).jpg") 
    file_list.append(f"The Serpentine Falls In Verdant Realm ({i}).jpg") 
    file_list.append(f"The Electric Horizon Beneath Crimson Rain ({i}).jpg") 
    file_list.append(f"The Dusk Glow Over Hidden Grove ({i}).jpg") 
    file_list.append(f"The Chaos Blazoned Across Stone Canvases ({i}).jpg") 
    file_list.append(f"The Silent Fjords Beneath Dusky Hues ({i}).jpg") 
    file_list.append(f"The Dreamscape Over Cotton Shores ({i}).jpg") 
    file_list.append(f"The Twilight Song Of Whispering Peaks ({i}).jpg") 
    file_list.append(f"The Ruins Beneath Crimson Storms ({i}).jpg") 
    file_list.append(f"The Haven Of Golden Horizons ({i}).jpg") 
    file_list.append(f"The Holographic Rain In Electric Alley ({i}).jpg") 
    file_list.append(f"The Crimson Sunset Over Quiet Sands ({i}).jpg") 
    file_list.append(f"The Layers Of Vivid Expression ({i}).jpg") 
    file_list.append(f"The Silent Tundra Under Frosted Skies ({i}).jpg") 
    file_list.append(f"The Pastel Glow Over Serene Lagoon ({i}).jpg") 
    file_list.append(f"The Ash And Glow In Forgotten Plains ({i}).jpg") 
    file_list.append(f"The Whispering Falls In Emerald Glade ({i}).jpg") 
    file_list.append(f"The Fluorescent Waves Beneath Sky Canals ({i}).jpg") 
    file_list.append(f"The Amber Glow Over Autumn Peaks ({i}).jpg") 
    file_list.append(f"The Glimmering Alley Of Painted Light ({i}).jpg") 
    file_list.append(f"he Frosted Horizon Beneath Nordic Lights ({i}).jpg") 
    file_list.append(f"The Opalescent Sky Over Still Lagoon ({i}).jpg") 
    file_list.append(f"The Twilight Song Beneath Luminous Peaks ({i}).jpg") 
    file_list.append(f"he Shattered Sky Over Steel Plains ({i}).jpg") 
    file_list.append(f"The Tranquility Under Emerald Canopy ({i}).jpg") 
    file_list.append(f"The Neon Twilight Over Broken Towers ({i}).jpg") 
    file_list.append(f"The Dusk Falls On Serene Cliffs ({i}).jpg") 
    file_list.append(f"The Vivid Chronicles On Hidden Walls ({i}).jpg") 
    file_list.append(f"The Glacial Majesty Under Arctic Sun ({i}).jpg") 
    file_list.append(f"The Soft Glow Of Pastel Skies ({i}).jpg") 
    file_list.append(f"The Cracked Earth Beneath Sulfuric Skies ({i}).jpg") 
    file_list.append(f"The Whispering Waters In Verdant Gorge ({i}).jpg") 
    file_list.append(f"The Electric Night Beneath Floating Bridges ({i}).jpg") 
    file_list.append(f"The Gilded Twilight Over Coastal Peaks ({i}).jpg") 
    file_list.append(f"The Urban Canvas Of Eternal Color ({i}).jpg") 
    file_list.append(f"The Frosted Plains Beneath Soft Aurora ({i}).jpg") 
    file_list.append(f"The Pastel Waves Upon Soft Shores ({i}).jpg") 
    file_list.append(f"The Moonlit Symphony Among Alpine Peaks ({i}).jpg") 
    file_list.append(f"The Rusted Spires Under Poisoned Skies ({i}).jpg") 
    file_list.append(f"The Serene Glade In Golden Light ({i}).jpg") 
    file_list.append(f"The Neon Abyss Beneath Floating Skylines ({i}).jpg") 
    file_list.append(f"The Evening Glow Across Quiet Fields ({i}).jpg") 
    file_list.append(f"The Vibrant Echoes In Hidden Alley ({i}).jpg") 
    file_list.append(f"The Silent Fjords Under Winter’S Embrace ({i}).jpg") 
    file_list.append(f"The Dreamscape Of Blush Meadows ({i}).jpg") 
    file_list.append(f"The Molten Plains Beneath A Crimson Sky ({i}).jpg") 
    file_list.append(f"The Hidden Cascades In Verdant Hollow ({i}).jpg") 
    file_list.append(f"The Cybernetic Glow Beneath Liquid Skies ({i}).jpg") 
    file_list.append(f"The Twilight Serenade On Tranquil Lake ({i}).jpg") 
    file_list.append(f"The Chaos Carved In Colorful Stone ({i}).jpg") 
    file_list.append(f"The Frostbound Shores Beneath Arctic Light ({i}).jpg") 
for subdir in subdirectories:
    directory_path = os.path.join(parent_directory, subdir)
    if os.path.exists(directory_path):
        delete_unlisted_files(directory_path, file_list)
    else:
        print(f"Directory {directory_path} does not exist.")
