// import "./globals.css";
// import Script from "next/script";
// import type { Metadata } from "next";
// import { Providers } from "./providers";
// import LocalFontLoader from "next/font/local";

// const Kurale = LocalFontLoader({ variable: "--font-Kurale", src: "../fonts/Kurale.ttf" });
// const Brittany = LocalFontLoader({ variable: "--font-Brittany", src: "../fonts/Brittany.otf" });
// export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app" };

// export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
// return (
// <html lang="en">
// <body className={`${Kurale.variable} ${Brittany.variable} antialiased`}>
// <Providers>
// <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9464475307933754" crossOrigin="anonymous" />
// {children}
// </Providers>
// </body>
// </html>
// );
// }

import "./globals.css";
import Script from "next/script";
import type { Metadata } from "next";
import { Kurale } from "next/font/google";
import SimpleBar from "simplebar-react";

const kurale = Kurale({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "picBook - Galaxy of Stories",
  description: "Explore a universe of short stories with moral lessons and downloadable images"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={kurale.className}>
        <SimpleBar style={{ maxHeight: "100vh" }}>
          <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9464475307933754" crossOrigin="anonymous" />
          <div className="flex flex-col min-h-screen bg-nordic-bg0">{children}</div>
        </SimpleBar>
      </body>
    </html>
  );
}
