export const database: unknown[] = [
  {
    Aurora_Vortex: {
      environment_title: "Aurora_Vortex",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Aurora_Vortex (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6768756,
          file_size_megabytes: 6.46,
          width: 3072,
          height: 5472,
          primary: "#df98a1",
          secondary: "#18d6c9",
          tertiary: "#1a2a56",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4967c3",
          hex_5: "#257584",
          hex_6: "#6f3465",
          hex_7: "#12101b",
          hex_8: "#b6326d",
          hex_9: "#294296"
        },
        {
          original_file_name: "Aurora_Vortex (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6043362,
          file_size_megabytes: 5.76,
          width: 3072,
          height: 5472,
          primary: "#d8afbf",
          secondary: "#0e254e",
          tertiary: "#26d1d7",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3761d5",
          hex_5: "#214895",
          hex_6: "#0c7368",
          hex_7: "#5e3758",
          hex_8: "#9d4266",
          hex_9: "#0d131a"
        },
        {
          original_file_name: "Aurora_Vortex (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6020458,
          file_size_megabytes: 5.74,
          width: 3072,
          height: 5472,
          primary: "#0a244f",
          secondary: "#c3bac4",
          tertiary: "#206bd7",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#184896",
          hex_5: "#27ccf5",
          hex_6: "#5c3c4e",
          hex_7: "#080718",
          hex_8: "#4d6865",
          hex_9: "#189ca4"
        },
        {
          original_file_name: "Aurora_Vortex (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5922041,
          file_size_megabytes: 5.65,
          width: 3072,
          height: 5472,
          primary: "#22e0a9",
          secondary: "#0f2c55",
          tertiary: "#c8b3a5",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2d7582",
          hex_5: "#05111d",
          hex_6: "#254b95",
          hex_7: "#5e4e81",
          hex_8: "#4571b9",
          hex_9: "#974669"
        }
      ]
    }
  },
  {
    Cosmic_Coliseum_Lights: {
      environment_title: "Cosmic_Coliseum_Lights",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Cosmic_Coliseum_Lights (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7061001,
          file_size_megabytes: 6.73,
          width: 3072,
          height: 5472,
          primary: "#e39ea1",
          secondary: "#201840",
          tertiary: "#4cc2f1",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3366ca",
          hex_5: "#363f84",
          hex_6: "#732342",
          hex_7: "#b72f49",
          hex_8: "#2a0811",
          hex_9: "#48546a"
        },
        {
          original_file_name: "Cosmic_Coliseum_Lights (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6704794,
          file_size_megabytes: 6.39,
          width: 3072,
          height: 5472,
          primary: "#df91bc",
          secondary: "#1d102b",
          tertiary: "#803e75",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4fc2e9",
          hex_5: "#5d64b7",
          hex_6: "#3b3e82",
          hex_7: "#38245e",
          hex_8: "#aa3882",
          hex_9: "#485861"
        },
        {
          original_file_name: "Cosmic_Coliseum_Lights (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7175057,
          file_size_megabytes: 6.84,
          width: 3072,
          height: 5472,
          primary: "#d65f62",
          secondary: "#29183e",
          tertiary: "#3460c7",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#812e45",
          hex_5: "#60bcf2",
          hex_6: "#f3e4e3",
          hex_7: "#2c3b84",
          hex_8: "#34070f",
          hex_9: "#415669"
        },
        {
          original_file_name: "Cosmic_Coliseum_Lights (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7430930,
          file_size_megabytes: 7.09,
          width: 3072,
          height: 5472,
          primary: "#ce6f7e",
          secondary: "#262046",
          tertiary: "#2465d1",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#56b8f1",
          hex_5: "#37488d",
          hex_6: "#78354c",
          hex_7: "#f4ded0",
          hex_8: "#0d0715",
          hex_9: "#495f6c"
        }
      ]
    }
  },
  {
    Cosmic_Hourglass: {
      environment_title: "Cosmic_Hourglass",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Cosmic_Hourglass (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6080763,
          file_size_megabytes: 5.8,
          width: 3072,
          height: 5472,
          primary: "#d2bdc4",
          secondary: "#131933",
          tertiary: "#4acaf0",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3271cc",
          hex_5: "#2a508d",
          hex_6: "#69403d",
          hex_7: "#173366",
          hex_8: "#a04c3d",
          hex_9: "#776864"
        },
        {
          original_file_name: "Cosmic_Hourglass (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6222252,
          file_size_megabytes: 5.93,
          width: 3072,
          height: 5472,
          primary: "#dbad83",
          secondary: "#236ebf",
          tertiary: "#151529",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2d4a81",
          hex_5: "#34bee1",
          hex_6: "#663931",
          hex_7: "#182b55",
          hex_8: "#a04427",
          hex_9: "#7a6352"
        },
        {
          original_file_name: "Cosmic_Hourglass (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6524258,
          file_size_megabytes: 6.22,
          width: 3072,
          height: 5472,
          primary: "#d8c5c4",
          secondary: "#1a1d35",
          tertiary: "#3fbeee",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4675c2",
          hex_5: "#3e578e",
          hex_6: "#704646",
          hex_7: "#1f3766",
          hex_8: "#a9515d",
          hex_9: "#396470"
        },
        {
          original_file_name: "Cosmic_Hourglass (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6315427,
          file_size_megabytes: 6.02,
          width: 3072,
          height: 5472,
          primary: "#d8b8ae",
          secondary: "#211928",
          tertiary: "#5468d3",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#51c8f3",
          hex_5: "#7f554a",
          hex_6: "#354283",
          hex_7: "#2c335d",
          hex_8: "#a8504c",
          hex_9: "#5d5d66"
        }
      ]
    }
  },
  {
    DragonS_Domain: {
      environment_title: "DragonS_Domain",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "DragonS_Domain (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6803644,
          file_size_megabytes: 6.49,
          width: 3072,
          height: 5472,
          primary: "#e8daaf",
          secondary: "#241a1f",
          tertiary: "#5ebbdc",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7d4c31",
          hex_5: "#3c7aa5",
          hex_6: "#562c1c",
          hex_7: "#ae5f2b",
          hex_8: "#264566",
          hex_9: "#3a6477"
        },
        {
          original_file_name: "DragonS_Domain (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7156572,
          file_size_megabytes: 6.83,
          width: 3072,
          height: 5472,
          primary: "#deb176",
          secondary: "#221b23",
          tertiary: "#814c2c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7ba8de",
          hex_5: "#647ab6",
          hex_6: "#562f1c",
          hex_7: "#303f66",
          hex_8: "#ab470e",
          hex_9: "#56606e"
        },
        {
          original_file_name: "DragonS_Domain (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6449365,
          file_size_megabytes: 6.15,
          width: 3072,
          height: 5472,
          primary: "#e6c691",
          secondary: "#261512",
          tertiary: "#805239",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#552f20",
          hex_5: "#585863",
          hex_6: "#ae5324",
          hex_7: "#4a4857",
          hex_8: "#7f8094",
          hex_9: "#959594"
        },
        {
          original_file_name: "DragonS_Domain (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6631072,
          file_size_megabytes: 6.32,
          width: 3072,
          height: 5472,
          primary: "#e5cb9f",
          secondary: "#271819",
          tertiary: "#815132",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6375a7",
          hex_5: "#81a5df",
          hex_6: "#ad5b27",
          hex_7: "#56301d",
          hex_8: "#556080",
          hex_9: "#434a6d"
        }
      ]
    }
  },
  {
    Energy_Grid: {
      environment_title: "Energy_Grid",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Energy_Grid (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 4979236,
          file_size_megabytes: 4.75,
          width: 3072,
          height: 5472,
          primary: "#c364a3",
          secondary: "#171d44",
          tertiary: "#3f4c82",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#692652",
          hex_5: "#ebe0f8",
          hex_6: "#66acd6",
          hex_7: "#586eb1",
          hex_8: "#090511",
          hex_9: "#1c5c6c"
        },
        {
          original_file_name: "Energy_Grid (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5584233,
          file_size_megabytes: 5.33,
          width: 3072,
          height: 5472,
          primary: "#d4666b",
          secondary: "#191227",
          tertiary: "#772c3a",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#f8e3cc",
          hex_5: "#5bbfd8",
          hex_6: "#2a4a75",
          hex_7: "#4e1a28",
          hex_8: "#5261bd",
          hex_9: "#485458"
        },
        {
          original_file_name: "Energy_Grid (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5686334,
          file_size_megabytes: 5.42,
          width: 3072,
          height: 5472,
          primary: "#d7a3ea",
          secondary: "#120e2a",
          tertiary: "#60aeea",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#475abf",
          hex_5: "#3c3685",
          hex_6: "#bc1e9b",
          hex_7: "#661150",
          hex_8: "#23205d",
          hex_9: "#2e4e68"
        },
        {
          original_file_name: "Energy_Grid (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6257148,
          file_size_megabytes: 5.97,
          width: 3072,
          height: 5472,
          primary: "#d9a3cf",
          secondary: "#1a0b29",
          tertiary: "#483980",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5f5ab9",
          hex_5: "#6f223e",
          hex_6: "#b0376c",
          hex_7: "#7f9edf",
          hex_8: "#2b1e55",
          hex_9: "#494c64"
        }
      ]
    }
  },
  {
    Fractal_Canyon: {
      environment_title: "Fractal_Canyon",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Fractal_Canyon (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6763534,
          file_size_megabytes: 6.45,
          width: 3072,
          height: 5472,
          primary: "#e3b79c",
          secondary: "#1da4a1",
          tertiary: "#2f1623",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#166578",
          hex_5: "#7c3938",
          hex_6: "#3672ad",
          hex_7: "#ab4339",
          hex_8: "#1a5a56",
          hex_9: "#5b2125"
        },
        {
          original_file_name: "Fractal_Canyon (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7006108,
          file_size_megabytes: 6.68,
          width: 3072,
          height: 5472,
          primary: "#dd9a71",
          secondary: "#2e1420",
          tertiary: "#823c2f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2d3480",
          hex_5: "#262760",
          hex_6: "#5353b0",
          hex_7: "#a93914",
          hex_8: "#9a9d8d",
          hex_9: "#5e6161"
        },
        {
          original_file_name: "Fractal_Canyon (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6429549,
          file_size_megabytes: 6.13,
          width: 3072,
          height: 5472,
          primary: "#dea07c",
          secondary: "#271422",
          tertiary: "#8c5448",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5557ae",
          hex_5: "#2f377a",
          hex_6: "#5e322a",
          hex_7: "#c43978",
          hex_8: "#a0a0bd",
          hex_9: "#676785"
        },
        {
          original_file_name: "Fractal_Canyon (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7087433,
          file_size_megabytes: 6.76,
          width: 3072,
          height: 5472,
          primary: "#e1b08a",
          secondary: "#26182d",
          tertiary: "#803e38",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7272ae",
          hex_5: "#b2431c",
          hex_6: "#3d4173",
          hex_7: "#552628",
          hex_8: "#84a7cb",
          hex_9: "#51604f"
        }
      ]
    }
  },
  {
    Fractal_Forest: {
      environment_title: "Fractal_Forest",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Fractal_Forest (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7273133,
          file_size_megabytes: 6.94,
          width: 3072,
          height: 5472,
          primary: "#c9c6c2",
          secondary: "#131f23",
          tertiary: "#72adc6",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5982b4",
          hex_5: "#557375",
          hex_6: "#2c506f",
          hex_7: "#664b38",
          hex_8: "#2d4b49",
          hex_9: "#9c5835"
        },
        {
          original_file_name: "Fractal_Forest (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8002420,
          file_size_megabytes: 7.63,
          width: 3072,
          height: 5472,
          primary: "#56c2b0",
          secondary: "#0c1d27",
          tertiary: "#afdff4",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3469b7",
          hex_5: "#183e78",
          hex_6: "#257760",
          hex_7: "#144c38",
          hex_8: "#8e65da",
          hex_9: "#534b4e"
        },
        {
          original_file_name: "Fractal_Forest (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8465913,
          file_size_megabytes: 8.07,
          width: 3072,
          height: 5472,
          primary: "#0d1c30",
          secondary: "#3cd0e9",
          tertiary: "#bad1d4",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2280c4",
          hex_5: "#17618d",
          hex_6: "#0e4267",
          hex_7: "#2a676d",
          hex_8: "#5b4441",
          hex_9: "#24ac8c"
        },
        {
          original_file_name: "Fractal_Forest (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7523339,
          file_size_megabytes: 7.17,
          width: 3072,
          height: 5472,
          primary: "#bcdad2",
          secondary: "#37d4d0",
          tertiary: "#0f1d2b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#0f4573",
          hex_5: "#1f78b0",
          hex_6: "#1b7671",
          hex_7: "#5e3a2c",
          hex_8: "#0f4b48",
          hex_9: "#0da35c"
        }
      ]
    }
  },
  {
    Glass_Cityscape: {
      environment_title: "Glass_Cityscape",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Glass_Cityscape (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6853660,
          file_size_megabytes: 6.54,
          width: 3072,
          height: 5472,
          primary: "#cfbbcc",
          secondary: "#131e3d",
          tertiary: "#5ebfe4",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3e6db9",
          hex_5: "#334d85",
          hex_6: "#664051",
          hex_7: "#a14a6b",
          hex_8: "#120b10",
          hex_9: "#3c634f"
        },
        {
          original_file_name: "Glass_Cityscape (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8504839,
          file_size_megabytes: 8.11,
          width: 3072,
          height: 5472,
          primary: "#c7b5b4",
          secondary: "#46cde9",
          tertiary: "#102046",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3275c7",
          hex_5: "#31598d",
          hex_6: "#5f4051",
          hex_7: "#52616b",
          hex_8: "#9b4b53",
          hex_9: "#080917"
        },
        {
          original_file_name: "Glass_Cityscape (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7116358,
          file_size_megabytes: 6.79,
          width: 3072,
          height: 5472,
          primary: "#d296b5",
          secondary: "#171f3e",
          tertiary: "#49d0ed",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3a4c83",
          hex_5: "#67374d",
          hex_6: "#4568ba",
          hex_7: "#ac3251",
          hex_8: "#0e0710",
          hex_9: "#355d67"
        },
        {
          original_file_name: "Glass_Cityscape (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7566575,
          file_size_megabytes: 7.22,
          width: 3072,
          height: 5472,
          primary: "#ddacdf",
          secondary: "#0f142c",
          tertiary: "#5f61c5",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#434286",
          hex_5: "#7da6dd",
          hex_6: "#6b2c44",
          hex_7: "#202c5d",
          hex_8: "#b04289",
          hex_9: "#405568"
        }
      ]
    }
  },
  {
    Icy_Reflections: {
      environment_title: "Icy_Reflections",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Icy_Reflections (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7335714,
          file_size_megabytes: 7.0,
          width: 3072,
          height: 5472,
          primary: "#dfc4c8",
          secondary: "#223e6e",
          tertiary: "#6bbce5",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4592cf",
          hex_5: "#4d85b1",
          hex_6: "#78557b",
          hex_7: "#191b36",
          hex_8: "#2368a7",
          hex_9: "#bd5472"
        },
        {
          original_file_name: "Icy_Reflections (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6685483,
          file_size_megabytes: 6.38,
          width: 3072,
          height: 5472,
          primary: "#e7c4ba",
          secondary: "#2c5a9a",
          tertiary: "#82bbe4",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#867ca4",
          hex_5: "#5499dc",
          hex_6: "#4a93c5",
          hex_7: "#0c2867",
          hex_8: "#222644",
          hex_9: "#bc566f"
        },
        {
          original_file_name: "Icy_Reflections (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6423330,
          file_size_megabytes: 6.13,
          width: 3072,
          height: 5472,
          primary: "#d9caca",
          secondary: "#1d3d68",
          tertiary: "#65c1e3",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3b90d0",
          hex_5: "#cc4d60",
          hex_6: "#7b5077",
          hex_7: "#5388ac",
          hex_8: "#231e36",
          hex_9: "#1a66ad"
        },
        {
          original_file_name: "Icy_Reflections (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6686737,
          file_size_megabytes: 6.38,
          width: 3072,
          height: 5472,
          primary: "#dbb8ca",
          secondary: "#1c5b97",
          tertiary: "#51c0e2",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#131a39",
          hex_5: "#746b9d",
          hex_6: "#3ba0dd",
          hex_7: "#10285b",
          hex_8: "#1a97c2",
          hex_9: "#c24c7b"
        }
      ]
    }
  },
  {
    Infinity_Pathway_Glow: {
      environment_title: "Infinity_Pathway_Glow",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Infinity_Pathway_Glow (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7311899,
          file_size_megabytes: 6.97,
          width: 3072,
          height: 5472,
          primary: "#d197a6",
          secondary: "#1b2a4e",
          tertiary: "#2976cb",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#47baeb",
          hex_5: "#265896",
          hex_6: "#703a55",
          hex_7: "#a53b59",
          hex_8: "#1e131a",
          hex_9: "#7d6674"
        },
        {
          original_file_name: "Infinity_Pathway_Glow (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7074841,
          file_size_megabytes: 6.75,
          width: 3072,
          height: 5472,
          primary: "#d6b2af",
          secondary: "#121d2c",
          tertiary: "#38517f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#1f385e",
          hex_5: "#4172bd",
          hex_6: "#674249",
          hex_7: "#5ab3f1",
          hex_8: "#9f4350",
          hex_9: "#7c6765"
        },
        {
          original_file_name: "Infinity_Pathway_Glow (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7080911,
          file_size_megabytes: 6.75,
          width: 3072,
          height: 5472,
          primary: "#dea27e",
          secondary: "#30293e",
          tertiary: "#814f53",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#377ab3",
          hex_5: "#245285",
          hex_6: "#75a5d0",
          hex_7: "#ac4127",
          hex_8: "#1f0c0e",
          hex_9: "#5e6467"
        },
        {
          original_file_name: "Infinity_Pathway_Glow (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7238606,
          file_size_megabytes: 6.9,
          width: 3072,
          height: 5472,
          primary: "#d8abaa",
          secondary: "#1b1d35",
          tertiary: "#3775c9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#324e8d",
          hex_5: "#57b1ef",
          hex_6: "#6f3e49",
          hex_7: "#203567",
          hex_8: "#a34249",
          hex_9: "#80676b"
        }
      ]
    }
  },
  {
    Lava_Rapids_Radiance: {
      environment_title: "Lava_Rapids_Radiance",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Lava_Rapids_Radiance (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7089071,
          file_size_megabytes: 6.76,
          width: 3072,
          height: 5472,
          primary: "#e9a17e",
          secondary: "#251727",
          tertiary: "#8a2e2d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#80baee",
          hex_5: "#c72e17",
          hex_6: "#274775",
          hex_7: "#5577b0",
          hex_8: "#5e1e24",
          hex_9: "#665559"
        },
        {
          original_file_name: "Lava_Rapids_Radiance (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6709603,
          file_size_megabytes: 6.4,
          width: 3072,
          height: 5472,
          primary: "#eba174",
          secondary: "#2e161f",
          tertiary: "#913934",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#cd3818",
          hex_5: "#80789a",
          hex_6: "#672325",
          hex_7: "#464a6a",
          hex_8: "#5b6182",
          hex_9: "#a39bb7"
        },
        {
          original_file_name: "Lava_Rapids_Radiance (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7004523,
          file_size_megabytes: 6.68,
          width: 3072,
          height: 5472,
          primary: "#de5e2c",
          secondary: "#32161e",
          tertiary: "#912e1e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#f8e999",
          hex_5: "#661f1b",
          hex_6: "#a09db9",
          hex_7: "#91829b",
          hex_8: "#624c63",
          hex_9: "#706274"
        },
        {
          original_file_name: "Lava_Rapids_Radiance (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7299500,
          file_size_megabytes: 6.96,
          width: 3072,
          height: 5472,
          primary: "#e39a6e",
          secondary: "#231a26",
          tertiary: "#823a36",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6abede",
          hex_5: "#bf2e11",
          hex_6: "#4f7caa",
          hex_7: "#3e5274",
          hex_8: "#56272b",
          hex_9: "#5b5d59"
        }
      ]
    }
  },
  {
    Liquid_Galaxy_Ocean: {
      environment_title: "Liquid_Galaxy_Ocean",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Liquid_Galaxy_Ocean (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7338160,
          file_size_megabytes: 7.0,
          width: 3072,
          height: 5472,
          primary: "#d3c6d5",
          secondary: "#1b3658",
          tertiary: "#5bbde7",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3b7dcb",
          hex_5: "#2e5a97",
          hex_6: "#507e9a",
          hex_7: "#625473",
          hex_8: "#0c1a2a",
          hex_9: "#a25486"
        },
        {
          original_file_name: "Liquid_Galaxy_Ocean (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7062484,
          file_size_megabytes: 6.74,
          width: 3072,
          height: 5472,
          primary: "#e1aec4",
          secondary: "#1b315a",
          tertiary: "#34d0ef",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4573d6",
          hex_5: "#3966a3",
          hex_6: "#6f456b",
          hex_7: "#c540a5",
          hex_8: "#0b0b26",
          hex_9: "#5e6f85"
        },
        {
          original_file_name: "Liquid_Galaxy_Ocean (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7462383,
          file_size_megabytes: 7.12,
          width: 3072,
          height: 5472,
          primary: "#d0c6dd",
          secondary: "#183461",
          tertiary: "#4ac0eb",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2f7bd2",
          hex_5: "#24569f",
          hex_6: "#437da8",
          hex_7: "#63517c",
          hex_8: "#a850bc",
          hex_9: "#06112f"
        },
        {
          original_file_name: "Liquid_Galaxy_Ocean (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7257905,
          file_size_megabytes: 6.92,
          width: 3072,
          height: 5472,
          primary: "#dfbebc",
          secondary: "#173759",
          tertiary: "#6fb7da",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3d84c1",
          hex_5: "#091925",
          hex_6: "#724c70",
          hex_7: "#c24161",
          hex_8: "#5d7d9a",
          hex_9: "#255997"
        }
      ]
    }
  },
  {
    Midnight_Bridge_Glow: {
      environment_title: "Midnight_Bridge_Glow",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Midnight_Bridge_Glow (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6125733,
          file_size_megabytes: 5.84,
          width: 3072,
          height: 5472,
          primary: "#d09eb5",
          secondary: "#122048",
          tertiary: "#3571c8",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#284a8e",
          hex_5: "#67aaf3",
          hex_6: "#68333f",
          hex_7: "#130c18",
          hex_8: "#a63524",
          hex_9: "#796561"
        },
        {
          original_file_name: "Midnight_Bridge_Glow (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6491805,
          file_size_megabytes: 6.19,
          width: 3072,
          height: 5472,
          primary: "#0c204b",
          secondary: "#caaca9",
          tertiary: "#3ebfed",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#1d6dc4",
          hex_5: "#17498e",
          hex_6: "#613c43",
          hex_7: "#95473b",
          hex_8: "#100d18",
          hex_9: "#726168"
        },
        {
          original_file_name: "Midnight_Bridge_Glow (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6230606,
          file_size_megabytes: 5.94,
          width: 3072,
          height: 5472,
          primary: "#122048",
          secondary: "#ccb4d5",
          tertiary: "#4371c9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2f498b",
          hex_5: "#6ba8f5",
          hex_6: "#634555",
          hex_7: "#765f6b",
          hex_8: "#0e0e1a",
          hex_9: "#9a4e42"
        },
        {
          original_file_name: "Midnight_Bridge_Glow (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6348677,
          file_size_megabytes: 6.05,
          width: 3072,
          height: 5472,
          primary: "#c397c1",
          secondary: "#102048",
          tertiary: "#3b6ecf",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2a468d",
          hex_5: "#60a5f8",
          hex_6: "#60343a",
          hex_7: "#110c18",
          hex_8: "#933f30",
          hex_9: "#715f66"
        }
      ]
    }
  },
  {
    Moonlit_Hilltop_Haven: {
      environment_title: "Moonlit_Hilltop_Haven",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Moonlit_Hilltop_Haven (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6952581,
          file_size_megabytes: 6.63,
          width: 3072,
          height: 5472,
          primary: "#b8d0cc",
          secondary: "#0a1a2d",
          tertiary: "#217ac6",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#18528c",
          hex_5: "#50ccf1",
          hex_6: "#0e3667",
          hex_7: "#5e474c",
          hex_8: "#656965",
          hex_9: "#4ea69c"
        },
        {
          original_file_name: "Moonlit_Hilltop_Haven (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7661582,
          file_size_megabytes: 7.31,
          width: 3072,
          height: 5472,
          primary: "#d09ca3",
          secondary: "#142d36",
          tertiary: "#32508d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#506fc0",
          hex_5: "#1c3765",
          hex_6: "#654659",
          hex_7: "#6ba7e0",
          hex_8: "#51695c",
          hex_9: "#9e3e64"
        },
        {
          original_file_name: "Moonlit_Hilltop_Haven (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7741328,
          file_size_megabytes: 7.38,
          width: 3072,
          height: 5472,
          primary: "#cd9ebc",
          secondary: "#112c48",
          tertiary: "#39508d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#486db5",
          hex_5: "#061613",
          hex_6: "#593c69",
          hex_7: "#6da5de",
          hex_8: "#9e3d9a",
          hex_9: "#24666d"
        },
        {
          original_file_name: "Moonlit_Hilltop_Haven (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6411362,
          file_size_megabytes: 6.11,
          width: 3072,
          height: 5472,
          primary: "#cdb1ca",
          secondary: "#0c1f29",
          tertiary: "#3d73ba",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#224f87",
          hex_5: "#0f345f",
          hex_6: "#6da3d4",
          hex_7: "#386b58",
          hex_8: "#564852",
          hex_9: "#964a83"
        }
      ]
    }
  },
  {
    Neon_Combat_Zone: {
      environment_title: "Neon_Combat_Zone",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Neon_Combat_Zone (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7038473,
          file_size_megabytes: 6.71,
          width: 3072,
          height: 5472,
          primary: "#d95e82",
          secondary: "#50cfe7",
          tertiary: "#1d1b32",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8a2644",
          hex_5: "#f2e4e9",
          hex_6: "#576ec3",
          hex_7: "#314d7e",
          hex_8: "#5b182f",
          hex_9: "#326560"
        },
        {
          original_file_name: "Neon_Combat_Zone (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6823767,
          file_size_megabytes: 6.51,
          width: 3072,
          height: 5472,
          primary: "#d8bee5",
          secondary: "#121732",
          tertiary: "#65cae9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6371c5",
          hex_5: "#47508d",
          hex_6: "#bb3b6c",
          hex_7: "#712d46",
          hex_8: "#263766",
          hex_9: "#36606f"
        },
        {
          original_file_name: "Neon_Combat_Zone (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7071356,
          file_size_megabytes: 6.74,
          width: 3072,
          height: 5472,
          primary: "#dbb3d7",
          secondary: "#161927",
          tertiary: "#53d8ec",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5f71b7",
          hex_5: "#485185",
          hex_6: "#6f2c4c",
          hex_7: "#b43a6d",
          hex_8: "#27355f",
          hex_9: "#326765"
        },
        {
          original_file_name: "Neon_Combat_Zone (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7205210,
          file_size_megabytes: 6.87,
          width: 3072,
          height: 5472,
          primary: "#dfa3d3",
          secondary: "#1c2047",
          tertiary: "#50bcdf",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#424f8e",
          hex_5: "#4e6ebe",
          hex_6: "#c92560",
          hex_7: "#73254a",
          hex_8: "#130711",
          hex_9: "#256865"
        }
      ]
    }
  },
  {
    Prism_Wave: {
      environment_title: "Prism_Wave",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Prism_Wave (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5164111,
          file_size_megabytes: 4.92,
          width: 3072,
          height: 5472,
          primary: "#e4a89d",
          secondary: "#13111f",
          tertiary: "#7b3b45",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#70d8ea",
          hex_5: "#394373",
          hex_6: "#5a6bc5",
          hex_7: "#c03839",
          hex_8: "#4b232f",
          hex_9: "#495655"
        },
        {
          original_file_name: "Prism_Wave (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5831005,
          file_size_megabytes: 5.56,
          width: 3072,
          height: 5472,
          primary: "#dfacbd",
          secondary: "#0f1721",
          tertiary: "#7d5069",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5acdea",
          hex_5: "#6373be",
          hex_6: "#3f4f72",
          hex_7: "#4a3041",
          hex_8: "#ca4584",
          hex_9: "#2a5e58"
        },
        {
          original_file_name: "Prism_Wave (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5270995,
          file_size_megabytes: 5.03,
          width: 3072,
          height: 5472,
          primary: "#d6c3d1",
          secondary: "#72c2dd",
          tertiary: "#0e0b14",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6a394d",
          hex_5: "#ab4653",
          hex_6: "#5b69b2",
          hex_7: "#354167",
          hex_8: "#3d1b29",
          hex_9: "#2c4d4b"
        },
        {
          original_file_name: "Prism_Wave (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6306212,
          file_size_megabytes: 6.01,
          width: 3072,
          height: 5472,
          primary: "#e3b8b1",
          secondary: "#80404f",
          tertiary: "#181522",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#56d3e0",
          hex_5: "#c03a57",
          hex_6: "#334675",
          hex_7: "#4f6aba",
          hex_8: "#512733",
          hex_9: "#4d5b4b"
        }
      ]
    }
  },
  {
    Rural_Harmony_Glow: {
      environment_title: "Rural_Harmony_Glow",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Rural_Harmony_Glow (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7959465,
          file_size_megabytes: 7.59,
          width: 3072,
          height: 5472,
          primary: "#ebc670",
          secondary: "#292d1d",
          tertiary: "#a0b13f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#94734e",
          hex_5: "#5f782b",
          hex_6: "#826f9a",
          hex_7: "#5f4e2c",
          hex_8: "#4a526a",
          hex_9: "#ca5962"
        },
        {
          original_file_name: "Rural_Harmony_Glow (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6649627,
          file_size_megabytes: 6.34,
          width: 3072,
          height: 5472,
          primary: "#eba57a",
          secondary: "#26221c",
          tertiary: "#9e6465",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8a7c9f",
          hex_5: "#645579",
          hex_6: "#666985",
          hex_7: "#68432a",
          hex_8: "#b5a08b",
          hex_9: "#c44c3a"
        },
        {
          original_file_name: "Rural_Harmony_Glow (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8415823,
          file_size_megabytes: 8.03,
          width: 3072,
          height: 5472,
          primary: "#e9ae6b",
          secondary: "#242522",
          tertiary: "#916350",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#71799b",
          hex_5: "#50754f",
          hex_6: "#384770",
          hex_7: "#624430",
          hex_8: "#9da26e",
          hex_9: "#bc4b46"
        },
        {
          original_file_name: "Rural_Harmony_Glow (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7390683,
          file_size_megabytes: 7.05,
          width: 3072,
          height: 5472,
          primary: "#e8a56a",
          secondary: "#965b4a",
          tertiary: "#201d15",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5d7ca8",
          hex_5: "#334572",
          hex_6: "#a5a9a9",
          hex_7: "#65412c",
          hex_8: "#627172",
          hex_9: "#c4483b"
        }
      ]
    }
  },
  {
    Skyborne_Chase: {
      environment_title: "Skyborne_Chase",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Skyborne_Chase (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6557179,
          file_size_megabytes: 6.25,
          width: 3072,
          height: 5472,
          primary: "#dbdddf",
          secondary: "#2c4d76",
          tertiary: "#4493dd",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#73c4f3",
          hex_5: "#211e2d",
          hex_6: "#6d8eb6",
          hex_7: "#cb512d",
          hex_8: "#286ab4",
          hex_9: "#7d687a"
        },
        {
          original_file_name: "Skyborne_Chase (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6191059,
          file_size_megabytes: 5.9,
          width: 3072,
          height: 5472,
          primary: "#e1dad8",
          secondary: "#145186",
          tertiary: "#191933",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8fbde5",
          hex_5: "#639cd2",
          hex_6: "#7d88a6",
          hex_7: "#082251",
          hex_8: "#d52836",
          hex_9: "#4189ba"
        },
        {
          original_file_name: "Skyborne_Chase (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7189659,
          file_size_megabytes: 6.86,
          width: 3072,
          height: 5472,
          primary: "#dbbfbf",
          secondary: "#334876",
          tertiary: "#171a27",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7bbde8",
          hex_5: "#5491cc",
          hex_6: "#836688",
          hex_7: "#3c6eab",
          hex_8: "#7789af",
          hex_9: "#b8514f"
        },
        {
          original_file_name: "Skyborne_Chase (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6404248,
          file_size_megabytes: 6.11,
          width: 3072,
          height: 5472,
          primary: "#ddd8dd",
          secondary: "#246198",
          tertiary: "#17152c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7fc8ed",
          hex_5: "#7b8aae",
          hex_6: "#4f9adc",
          hex_7: "#d2362e",
          hex_8: "#0e3651",
          hex_9: "#0e204c"
        }
      ]
    }
  },
  {
    Solar_Summit_Glow: {
      environment_title: "Solar_Summit_Glow",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Solar_Summit_Glow (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7307881,
          file_size_megabytes: 6.97,
          width: 3072,
          height: 5472,
          primary: "#5971b0",
          secondary: "#edd6b7",
          tertiary: "#38212e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#9e8ba1",
          hex_5: "#3b375c",
          hex_6: "#b0b5bf",
          hex_7: "#e98c42",
          hex_8: "#cb571f",
          hex_9: "#1c327f"
        },
        {
          original_file_name: "Solar_Summit_Glow (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7233949,
          file_size_megabytes: 6.9,
          width: 3072,
          height: 5472,
          primary: "#ebb78d",
          secondary: "#5169b0",
          tertiary: "#241923",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#323455",
          hex_5: "#9e7ba1",
          hex_6: "#e07030",
          hex_7: "#afb8b1",
          hex_8: "#122a78",
          hex_9: "#c44818"
        },
        {
          original_file_name: "Solar_Summit_Glow (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6404711,
          file_size_megabytes: 6.11,
          width: 3072,
          height: 5472,
          primary: "#e7bf96",
          secondary: "#4167a8",
          tertiary: "#1d1a22",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3c395b",
          hex_5: "#8c8cad",
          hex_6: "#598be1",
          hex_7: "#98adc8",
          hex_8: "#b25233",
          hex_9: "#0b2977"
        },
        {
          original_file_name: "Solar_Summit_Glow (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7440670,
          file_size_megabytes: 7.1,
          width: 3072,
          height: 5472,
          primary: "#eac39b",
          secondary: "#395c9d",
          tertiary: "#261b2d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#8a697e",
          hex_5: "#5286d9",
          hex_6: "#2e3556",
          hex_7: "#be5343",
          hex_8: "#121e4d",
          hex_9: "#97b2cd"
        }
      ]
    }
  },
  {
    Starlit_Pavilion_Glow: {
      environment_title: "Starlit_Pavilion_Glow",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Starlit_Pavilion_Glow (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6902999,
          file_size_megabytes: 6.58,
          width: 3072,
          height: 5472,
          primary: "#d8a6af",
          secondary: "#122545",
          tertiary: "#2c72cd",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#59b7f5",
          hex_5: "#2b4c8d",
          hex_6: "#6a414d",
          hex_7: "#a74763",
          hex_8: "#0e1219",
          hex_9: "#796a5e"
        },
        {
          original_file_name: "Starlit_Pavilion_Glow (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6539771,
          file_size_megabytes: 6.24,
          width: 3072,
          height: 5472,
          primary: "#c49a8d",
          secondary: "#12284b",
          tertiary: "#39c2f2",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#1f75c8",
          hex_5: "#1b5192",
          hex_6: "#5e3f4d",
          hex_7: "#264e74",
          hex_8: "#130f1a",
          hex_9: "#646673"
        },
        {
          original_file_name: "Starlit_Pavilion_Glow (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6402783,
          file_size_megabytes: 6.11,
          width: 3072,
          height: 5472,
          primary: "#cebac9",
          secondary: "#102550",
          tertiary: "#3fb9f5",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#1a72d3",
          hex_5: "#194c95",
          hex_6: "#613e4e",
          hex_7: "#9a4b46",
          hex_8: "#0d0d19",
          hex_9: "#78686b"
        },
        {
          original_file_name: "Starlit_Pavilion_Glow (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6376869,
          file_size_megabytes: 6.08,
          width: 3072,
          height: 5472,
          primary: "#cdadb6",
          secondary: "#172647",
          tertiary: "#48baf4",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2872cd",
          hex_5: "#244c8c",
          hex_6: "#664143",
          hex_7: "#1f1417",
          hex_8: "#9d4630",
          hex_9: "#7f6965"
        }
      ]
    }
  },
  {
    Stellar_Rescue_Mission: {
      environment_title: "Stellar_Rescue_Mission",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Stellar_Rescue_Mission (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6779098,
          file_size_megabytes: 6.47,
          width: 3072,
          height: 5472,
          primary: "#d5b1b8",
          secondary: "#171c37",
          tertiary: "#2c73d4",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#51b9f4",
          hex_5: "#2a4d8d",
          hex_6: "#653c47",
          hex_7: "#1e3566",
          hex_8: "#a6463d",
          hex_9: "#71676b"
        },
        {
          original_file_name: "Stellar_Rescue_Mission (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6760259,
          file_size_megabytes: 6.45,
          width: 3072,
          height: 5472,
          primary: "#d0c6b4",
          secondary: "#15182d",
          tertiary: "#76a8e0",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#384b7f",
          hex_5: "#4972be",
          hex_6: "#673e2a",
          hex_7: "#a25340",
          hex_8: "#1e2f5a",
          hex_9: "#446c64"
        },
        {
          original_file_name: "Stellar_Rescue_Mission (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6506846,
          file_size_megabytes: 6.21,
          width: 3072,
          height: 5472,
          primary: "#d1d6c9",
          secondary: "#0e1327",
          tertiary: "#54b4ec",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#306ec3",
          hex_5: "#a84c41",
          hex_6: "#33497b",
          hex_7: "#142953",
          hex_8: "#622f2a",
          hex_9: "#685f59"
        },
        {
          original_file_name: "Stellar_Rescue_Mission (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6566972,
          file_size_megabytes: 6.26,
          width: 3072,
          height: 5472,
          primary: "#c3dae7",
          secondary: "#171a2f",
          tertiary: "#6db4e8",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3c6fc3",
          hex_5: "#345184",
          hex_6: "#1c345e",
          hex_7: "#5e5059",
          hex_8: "#9e6049",
          hex_9: "#405d66"
        }
      ]
    }
  },
  {
    Time_Spiral: {
      environment_title: "Time_Spiral",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Time_Spiral (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6748674,
          file_size_megabytes: 6.44,
          width: 3072,
          height: 5472,
          primary: "#dcc595",
          secondary: "#181529",
          tertiary: "#79563e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4ec7e4",
          hex_5: "#3368be",
          hex_6: "#273c74",
          hex_7: "#4e3228",
          hex_8: "#a0592b",
          hex_9: "#575644"
        },
        {
          original_file_name: "Time_Spiral (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6323240,
          file_size_megabytes: 6.03,
          width: 3072,
          height: 5472,
          primary: "#deb78f",
          secondary: "#22181f",
          tertiary: "#805138",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#435cc1",
          hex_5: "#553120",
          hex_6: "#b3491b",
          hex_7: "#3c3c70",
          hex_8: "#88a1d5",
          hex_9: "#5c5e68"
        },
        {
          original_file_name: "Time_Spiral (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6506176,
          file_size_megabytes: 6.2,
          width: 3072,
          height: 5472,
          primary: "#cecfd6",
          secondary: "#17152c",
          tertiary: "#3b4682",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5268b9",
          hex_5: "#79a5dd",
          hex_6: "#67493a",
          hex_7: "#202a5a",
          hex_8: "#9c5a39",
          hex_9: "#49545b"
        },
        {
          original_file_name: "Time_Spiral (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6636700,
          file_size_megabytes: 6.33,
          width: 3072,
          height: 5472,
          primary: "#d4bb90",
          secondary: "#202541",
          tertiary: "#3a6bc0",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#344b83",
          hex_5: "#46caef",
          hex_6: "#6c483d",
          hex_7: "#23140e",
          hex_8: "#7b6d55",
          hex_9: "#9c5032"
        }
      ]
    }
  },
  {
    Twilight_Chapel_Glow: {
      environment_title: "Twilight_Chapel_Glow",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Twilight_Chapel_Glow (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7129179,
          file_size_megabytes: 6.8,
          width: 3072,
          height: 5472,
          primary: "#de988d",
          secondary: "#291f2d",
          tertiary: "#80444c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#7568b7",
          hex_5: "#552d35",
          hex_6: "#bb3834",
          hex_7: "#484377",
          hex_8: "#9397cd",
          hex_9: "#595e4a"
        },
        {
          original_file_name: "Twilight_Chapel_Glow (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7224420,
          file_size_megabytes: 6.89,
          width: 3072,
          height: 5472,
          primary: "#d9998a",
          secondary: "#261d2d",
          tertiary: "#435ec2",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#783f43",
          hex_5: "#74a3e2",
          hex_6: "#27367d",
          hex_7: "#b73a42",
          hex_8: "#2c2a53",
          hex_9: "#5c5c5c"
        },
        {
          original_file_name: "Twilight_Chapel_Glow (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8247286,
          file_size_megabytes: 7.87,
          width: 3072,
          height: 5472,
          primary: "#d9695a",
          secondary: "#221d33",
          tertiary: "#4ebf8c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#813841",
          hex_5: "#4e56c6",
          hex_6: "#f1d762",
          hex_7: "#562732",
          hex_8: "#2f417c",
          hex_9: "#247336"
        },
        {
          original_file_name: "Twilight_Chapel_Glow (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6721919,
          file_size_megabytes: 6.41,
          width: 3072,
          height: 5472,
          primary: "#c77b90",
          secondary: "#201f34",
          tertiary: "#4a63bd",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3e4584",
          hex_5: "#6f4048",
          hex_6: "#5ca9e7",
          hex_7: "#2c2f5c",
          hex_8: "#eed9d7",
          hex_9: "#2a5c56"
        }
      ]
    }
  }
];
