export const database: unknown[] = [
  {
    Cosmic_Horizon: {
      environment_title: "Cosmic_Horizon",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Cosmic_Horizon (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7007095,
          file_size_megabytes: 6.68,
          width: 3072,
          height: 5472,
          primary: "#cc7651",
          secondary: "#141723",
          tertiary: "#6a4241",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5dafb7",
          hex_5: "#ead999",
          hex_6: "#2e5f66",
          hex_7: "#2d3a48",
          hex_8: "#34819c",
          hex_9: "#1e4560"
        },
        {
          original_file_name: "Cosmic_Horizon (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6864205,
          file_size_megabytes: 6.55,
          width: 3072,
          height: 5472,
          primary: "#ca7854",
          secondary: "#181421",
          tertiary: "#6c3f44",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#452c38",
          hex_5: "#e1d5be",
          hex_6: "#484b63",
          hex_7: "#8795a4",
          hex_8: "#797799",
          hex_9: "#515451"
        },
        {
          original_file_name: "Cosmic_Horizon (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6997810,
          file_size_megabytes: 6.67,
          width: 3072,
          height: 5472,
          primary: "#ce907a",
          secondary: "#151624",
          tertiary: "#6e4556",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#64789a",
          hex_5: "#442738",
          hex_6: "#69a6b4",
          hex_7: "#3b4164",
          hex_8: "#375e76",
          hex_9: "#ac3228"
        },
        {
          original_file_name: "Cosmic_Horizon (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6956187,
          file_size_megabytes: 6.63,
          width: 3072,
          height: 5472,
          primary: "#c9725e",
          secondary: "#151321",
          tertiary: "#4b5376",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#683236",
          hex_5: "#5bb2d6",
          hex_6: "#dddfbd",
          hex_7: "#4579a8",
          hex_8: "#2e334d",
          hex_9: "#305a5a"
        }
      ]
    }
  },
  {
    Cyberpunk_Alley: {
      environment_title: "Cyberpunk_Alley",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Cyberpunk_Alley (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8092453,
          file_size_megabytes: 7.72,
          width: 3072,
          height: 5472,
          primary: "#c5698d",
          secondary: "#15101a",
          tertiary: "#3e536e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#662739",
          hex_5: "#5c739f",
          hex_6: "#243144",
          hex_7: "#6895ad",
          hex_8: "#ddccdc",
          hex_9: "#304c52"
        },
        {
          original_file_name: "Cyberpunk_Alley (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7736508,
          file_size_megabytes: 7.38,
          width: 3072,
          height: 5472,
          primary: "#c96468",
          secondary: "#100f18",
          tertiary: "#59abb5",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3f616f",
          hex_5: "#a5c8cc",
          hex_6: "#61232d",
          hex_7: "#203845",
          hex_8: "#598394",
          hex_9: "#294c53"
        },
        {
          original_file_name: "Cyberpunk_Alley (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7980186,
          file_size_megabytes: 7.61,
          width: 3072,
          height: 5472,
          primary: "#cc94b2",
          secondary: "#120f1a",
          tertiary: "#434f6c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#55adca",
          hex_5: "#233045",
          hex_6: "#612944",
          hex_7: "#3e759d",
          hex_8: "#913663",
          hex_9: "#314c54"
        },
        {
          original_file_name: "Cyberpunk_Alley (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7852921,
          file_size_megabytes: 7.49,
          width: 3072,
          height: 5472,
          primary: "#120f18",
          secondary: "#c45b52",
          tertiary: "#5db5c1",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#335f6f",
          hex_5: "#c6e3d4",
          hex_6: "#662626",
          hex_7: "#213544",
          hex_8: "#438196",
          hex_9: "#254c52"
        }
      ]
    }
  },
  {
    Cyber_Grid: {
      environment_title: "Cyber_Grid",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Cyber_Grid (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6913227,
          file_size_megabytes: 6.59,
          width: 3072,
          height: 5472,
          primary: "#b8606b",
          secondary: "#0d0f19",
          tertiary: "#603b4c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#342633",
          hex_5: "#fab2ac",
          hex_6: "#354757",
          hex_7: "#31394e",
          hex_8: "#70637d",
          hex_9: "#70898e"
        },
        {
          original_file_name: "Cyber_Grid (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8122231,
          file_size_megabytes: 7.75,
          width: 3072,
          height: 5472,
          primary: "#bc6126",
          secondary: "#160d13",
          tertiary: "#6f331f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#461c15",
          hex_5: "#f7ca43",
          hex_6: "#8c7c66",
          hex_7: "#534439",
          hex_8: "#8c7074",
          hex_9: "#513944"
        },
        {
          original_file_name: "Cyber_Grid (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7589796,
          file_size_megabytes: 7.24,
          width: 3072,
          height: 5472,
          primary: "#b55b36",
          secondary: "#18121a",
          tertiary: "#662d23",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3eadb3",
          hex_5: "#21606c",
          hex_6: "#153143",
          hex_7: "#f6c455",
          hex_8: "#2b8295",
          hex_9: "#1e5551"
        },
        {
          original_file_name: "Cyber_Grid (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6560859,
          file_size_megabytes: 6.26,
          width: 3072,
          height: 5472,
          primary: "#cb7058",
          secondary: "#0c1321",
          tertiary: "#3eabae",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#29586c",
          hex_5: "#643747",
          hex_6: "#ebd1ac",
          hex_7: "#22789b",
          hex_8: "#123649",
          hex_9: "#075a4c"
        }
      ]
    }
  },
  {
    Electric_Circuit_City: {
      environment_title: "Electric_Circuit_City",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Electric_Circuit_City (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8151430,
          file_size_megabytes: 7.77,
          width: 3072,
          height: 5472,
          primary: "#d39027",
          secondary: "#0e1428",
          tertiary: "#6c3823",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3e2120",
          hex_5: "#a2350b",
          hex_6: "#235883",
          hex_7: "#14355a",
          hex_8: "#38565d",
          hex_9: "#8a9854"
        },
        {
          original_file_name: "Electric_Circuit_City (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8042203,
          file_size_megabytes: 7.67,
          width: 3072,
          height: 5472,
          primary: "#d08b38",
          secondary: "#110e1b",
          tertiary: "#19426d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#633327",
          hex_5: "#1964a5",
          hex_6: "#38b1d3",
          hex_7: "#112746",
          hex_8: "#933619",
          hex_9: "#3b4f49"
        },
        {
          original_file_name: "Electric_Circuit_City (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8278613,
          file_size_megabytes: 7.9,
          width: 3072,
          height: 5472,
          primary: "#d89b3f",
          secondary: "#151523",
          tertiary: "#6c3723",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#29466c",
          hex_5: "#9d3e19",
          hex_6: "#142e52",
          hex_7: "#4974a4",
          hex_8: "#80a0c5",
          hex_9: "#485546"
        },
        {
          original_file_name: "Electric_Circuit_City (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7231773,
          file_size_megabytes: 6.9,
          width: 3072,
          height: 5472,
          primary: "#c68f3b",
          secondary: "#111524",
          tertiary: "#246ea8",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5f3920",
          hex_5: "#1d4468",
          hex_6: "#5b646a",
          hex_7: "#4ca6d3",
          hex_8: "#353f4a",
          hex_9: "#973507"
        }
      ]
    }
  },
  {
    Electric_Ocean: {
      environment_title: "Electric_Ocean",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Electric_Ocean (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7276914,
          file_size_megabytes: 6.94,
          width: 3072,
          height: 5472,
          primary: "#397fa7",
          secondary: "#071726",
          tertiary: "#73b5d3",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#235b7e",
          hex_5: "#103956",
          hex_6: "#6394a4",
          hex_7: "#3f4d5c",
          hex_8: "#748094",
          hex_9: "#405c64"
        },
        {
          original_file_name: "Electric_Ocean (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7064836,
          file_size_megabytes: 6.74,
          width: 3072,
          height: 5472,
          primary: "#16212b",
          secondary: "#bc9e8b",
          tertiary: "#4daec9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#487388",
          hex_5: "#3e88b1",
          hex_6: "#284a5c",
          hex_7: "#684d4c",
          hex_8: "#40444a",
          hex_9: "#586567"
        },
        {
          original_file_name: "Electric_Ocean (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7417784,
          file_size_megabytes: 7.07,
          width: 3072,
          height: 5472,
          primary: "#d39655",
          secondary: "#0c1621",
          tertiary: "#5ba0c4",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2a5c7e",
          hex_5: "#3f80a5",
          hex_6: "#093655",
          hex_7: "#623b32",
          hex_8: "#725d5c",
          hex_9: "#963807"
        },
        {
          original_file_name: "Electric_Ocean (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6699012,
          file_size_megabytes: 6.39,
          width: 3072,
          height: 5472,
          primary: "#0b1c27",
          secondary: "#abc3d0",
          tertiary: "#5989a7",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#75a2ba",
          hex_5: "#477184",
          hex_6: "#315970",
          hex_7: "#29495b",
          hex_8: "#8d94a1",
          hex_9: "#50575d"
        }
      ]
    }
  },
  {
    Energy_Dome: {
      environment_title: "Energy_Dome",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Energy_Dome (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6958168,
          file_size_megabytes: 6.64,
          width: 3072,
          height: 5472,
          primary: "#13121d",
          secondary: "#b49ba2",
          tertiary: "#5ab7d5",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#354e6e",
          hex_5: "#44789e",
          hex_6: "#653630",
          hex_7: "#1f2b43",
          hex_8: "#914139",
          hex_9: "#394c54"
        },
        {
          original_file_name: "Energy_Dome (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7274550,
          file_size_megabytes: 6.94,
          width: 3072,
          height: 5472,
          primary: "#bb7549",
          secondary: "#18131b",
          tertiary: "#704035",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#452829",
          hex_5: "#f2d778",
          hex_6: "#827398",
          hex_7: "#7f98ad",
          hex_8: "#444f67",
          hex_9: "#445454"
        },
        {
          original_file_name: "Energy_Dome (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6999185,
          file_size_megabytes: 6.67,
          width: 3072,
          height: 5472,
          primary: "#1f171d",
          secondary: "#c3ae9d",
          tertiary: "#60aabe",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#467b9f",
          hex_5: "#6c4b45",
          hex_6: "#2f4a6e",
          hex_7: "#366381",
          hex_8: "#4a2f30",
          hex_9: "#2b3e4a"
        },
        {
          original_file_name: "Energy_Dome (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6862628,
          file_size_megabytes: 6.54,
          width: 3072,
          height: 5472,
          primary: "#171a22",
          secondary: "#cd9a44",
          tertiary: "#3dbdd9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6c381b",
          hex_5: "#317cab",
          hex_6: "#45231a",
          hex_7: "#184861",
          hex_8: "#1b6375",
          hex_9: "#123f4e"
        }
      ]
    }
  },
  {
    Energy_Tree: {
      environment_title: "Energy_Tree",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Energy_Tree (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7661182,
          file_size_megabytes: 7.31,
          width: 3072,
          height: 5472,
          primary: "#292d3f",
          secondary: "#bba0bd",
          tertiary: "#736682",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#0e120b",
          hex_5: "#524961",
          hex_6: "#9084a5",
          hex_7: "#66516a",
          hex_8: "#929fb1",
          hex_9: "#5c646c"
        },
        {
          original_file_name: "Energy_Tree (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7080466,
          file_size_megabytes: 6.75,
          width: 3072,
          height: 5472,
          primary: "#141b24",
          secondary: "#adb4d4",
          tertiary: "#495a7b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6c80a6",
          hex_5: "#839abc",
          hex_6: "#303c56",
          hex_7: "#5d4561",
          hex_8: "#3d2940",
          hex_9: "#495c64"
        },
        {
          original_file_name: "Energy_Tree (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8039114,
          file_size_megabytes: 7.67,
          width: 3072,
          height: 5472,
          primary: "#b5a0c7",
          secondary: "#151b20",
          tertiary: "#7279a7",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#50547b",
          hex_5: "#303856",
          hex_6: "#395c29",
          hex_7: "#5e4b62",
          hex_8: "#3d2f41",
          hex_9: "#8c8494"
        },
        {
          original_file_name: "Energy_Tree (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7939926,
          file_size_megabytes: 7.57,
          width: 3072,
          height: 5472,
          primary: "#161727",
          secondary: "#66b5d3",
          tertiary: "#485d82",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#677eac",
          hex_5: "#323d5c",
          hex_6: "#583f66",
          hex_7: "#876696",
          hex_8: "#273c4b",
          hex_9: "#3a5e6a"
        }
      ]
    }
  },
  {
    Holographic_Display: {
      environment_title: "Holographic_Display",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Holographic_Display (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6610673,
          file_size_megabytes: 6.3,
          width: 3072,
          height: 5472,
          primary: "#cf625e",
          secondary: "#14131d",
          tertiary: "#4088b8",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#314b6c",
          hex_5: "#603045",
          hex_6: "#272f4a",
          hex_7: "#b67cd0",
          hex_8: "#4f8b80",
          hex_9: "#2b504c"
        },
        {
          original_file_name: "Holographic_Display (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6572722,
          file_size_megabytes: 6.27,
          width: 3072,
          height: 5472,
          primary: "#be5273",
          secondary: "#0d0b14",
          tertiary: "#2bafc7",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3b3d6e",
          hex_5: "#3855b5",
          hex_6: "#601d3a",
          hex_7: "#1c2645",
          hex_8: "#c4b5cf",
          hex_9: "#155f40"
        },
        {
          original_file_name: "Holographic_Display (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6857128,
          file_size_megabytes: 6.54,
          width: 3072,
          height: 5472,
          primary: "#b7698f",
          secondary: "#140b18",
          tertiary: "#3c89b9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#683055",
          hex_5: "#26466f",
          hex_6: "#212746",
          hex_7: "#56907c",
          hex_8: "#5f349d",
          hex_9: "#27504f"
        },
        {
          original_file_name: "Holographic_Display (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5299343,
          file_size_megabytes: 5.05,
          width: 3072,
          height: 5472,
          primary: "#b46c88",
          secondary: "#080a11",
          tertiary: "#2dbad9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#2f496b",
          hex_5: "#2d6daa",
          hex_6: "#1a293c",
          hex_7: "#c3cdb0",
          hex_8: "#572c2a",
          hex_9: "#56553d"
        }
      ]
    }
  },
  {
    Neon_Skyline: {
      environment_title: "Neon_Skyline",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Neon_Skyline (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7455967,
          file_size_megabytes: 7.11,
          width: 3072,
          height: 5472,
          primary: "#cf6fb4",
          secondary: "#1e2847",
          tertiary: "#4c558b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5675ba",
          hex_5: "#46c3ea",
          hex_6: "#f4d7e3",
          hex_7: "#69375e",
          hex_8: "#170c18",
          hex_9: "#465c74"
        },
        {
          original_file_name: "Neon_Skyline (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7678577,
          file_size_megabytes: 7.32,
          width: 3072,
          height: 5472,
          primary: "#d171a4",
          secondary: "#2e2849",
          tertiary: "#645689",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#53c6e3",
          hex_5: "#773862",
          hex_6: "#5777bf",
          hex_7: "#110d18",
          hex_8: "#eec8ba",
          hex_9: "#2c6c70"
        },
        {
          original_file_name: "Neon_Skyline (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 8196855,
          file_size_megabytes: 7.82,
          width: 3072,
          height: 5472,
          primary: "#d66799",
          secondary: "#2d2948",
          tertiary: "#5e5987",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4fbab5",
          hex_5: "#7b3b66",
          hex_6: "#5586b5",
          hex_7: "#160b17",
          hex_8: "#d8cbd0",
          hex_9: "#22706b"
        },
        {
          original_file_name: "Neon_Skyline (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7908081,
          file_size_megabytes: 7.54,
          width: 3072,
          height: 5472,
          primary: "#cf679c",
          secondary: "#292648",
          tertiary: "#68508b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#63b6d9",
          hex_5: "#773862",
          hex_6: "#7877b5",
          hex_7: "#181117",
          hex_8: "#e7c1d5",
          hex_9: "#3a6571"
        }
      ]
    }
  },
  {
    Neon_Storm: {
      environment_title: "Neon_Storm",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Neon_Storm (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7736531,
          file_size_megabytes: 7.38,
          width: 3072,
          height: 5472,
          primary: "#c0708f",
          secondary: "#211527",
          tertiary: "#78425f",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4d263e",
          hex_5: "#f3cfcc",
          hex_6: "#50436a",
          hex_7: "#886ea1",
          hex_8: "#79bcca",
          hex_9: "#515455"
        },
        {
          original_file_name: "Neon_Storm (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7181390,
          file_size_megabytes: 6.85,
          width: 3072,
          height: 5472,
          primary: "#221a30",
          secondary: "#c96e97",
          tertiary: "#774a6b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#efd2e3",
          hex_5: "#473858",
          hex_6: "#554b70",
          hex_7: "#8c9ba9",
          hex_8: "#877d9e",
          hex_9: "#565d60"
        },
        {
          original_file_name: "Neon_Storm (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7424040,
          file_size_megabytes: 7.08,
          width: 3072,
          height: 5472,
          primary: "#c97097",
          secondary: "#27182e",
          tertiary: "#7c3b5e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#562a49",
          hex_5: "#f8d0e2",
          hex_6: "#545375",
          hex_7: "#80a4b2",
          hex_8: "#8073a6",
          hex_9: "#4c5e62"
        },
        {
          original_file_name: "Neon_Storm (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7379672,
          file_size_megabytes: 7.04,
          width: 3072,
          height: 5472,
          primary: "#c86b8f",
          secondary: "#1c1529",
          tertiary: "#773d60",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#434570",
          hex_5: "#6666ac",
          hex_6: "#f3d1db",
          hex_7: "#4d2c46",
          hex_8: "#61abbc",
          hex_9: "#365f4f"
        }
      ]
    }
  },
  {
    SciFi_Spaceport: {
      environment_title: "SciFi_Spaceport",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "SciFi_Spaceport (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7237296,
          file_size_megabytes: 6.9,
          width: 3072,
          height: 5472,
          primary: "#d0967f",
          secondary: "#1c1d27",
          tertiary: "#764947",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4e3135",
          hex_5: "#52616b",
          hex_6: "#8c99a2",
          hex_7: "#9f4235",
          hex_8: "#525e59",
          hex_9: "#76899c"
        },
        {
          original_file_name: "SciFi_Spaceport (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6545438,
          file_size_megabytes: 6.24,
          width: 3072,
          height: 5472,
          primary: "#cd8462",
          secondary: "#1b1925",
          tertiary: "#6f4442",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#545f75",
          hex_5: "#363949",
          hex_6: "#6ba7bf",
          hex_7: "#5f83a3",
          hex_8: "#9e3819",
          hex_9: "#545c5c"
        },
        {
          original_file_name: "SciFi_Spaceport (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6692201,
          file_size_megabytes: 6.38,
          width: 3072,
          height: 5472,
          primary: "#cb997f",
          secondary: "#1a1924",
          tertiary: "#686470",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6d423f",
          hex_5: "#373c4b",
          hex_6: "#7d9caf",
          hex_7: "#9b3f27",
          hex_8: "#7187a0",
          hex_9: "#4e5c59"
        },
        {
          original_file_name: "SciFi_Spaceport (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7114179,
          file_size_megabytes: 6.78,
          width: 3072,
          height: 5472,
          primary: "#151a25",
          secondary: "#af7158",
          tertiary: "#72483e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#6eaac7",
          hex_5: "#d8dcdc",
          hex_6: "#442c2b",
          hex_7: "#4c7e9d",
          hex_8: "#334d61",
          hex_9: "#406172"
        }
      ]
    }
  },
  {
    Starship_Glow: {
      environment_title: "Starship_Glow",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Starship_Glow (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6039912,
          file_size_megabytes: 5.76,
          width: 3072,
          height: 5472,
          primary: "#151922",
          secondary: "#cda993",
          tertiary: "#626873",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#664039",
          hex_5: "#6a829a",
          hex_6: "#7e99af",
          hex_7: "#394d62",
          hex_8: "#3a3e4a",
          hex_9: "#8c4b3c"
        },
        {
          original_file_name: "Starship_Glow (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6453994,
          file_size_megabytes: 6.16,
          width: 3072,
          height: 5472,
          primary: "#0f1620",
          secondary: "#c7d2d0",
          tertiary: "#68aac9",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3f7ca0",
          hex_5: "#254967",
          hex_6: "#45647c",
          hex_7: "#5c3b36",
          hex_8: "#99573e",
          hex_9: "#2d3e4e"
        },
        {
          original_file_name: "Starship_Glow (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6676391,
          file_size_megabytes: 6.37,
          width: 3072,
          height: 5472,
          primary: "#bd744c",
          secondary: "#181722",
          tertiary: "#6e423e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#edddb0",
          hex_5: "#452d31",
          hex_6: "#7fa0b9",
          hex_7: "#68809a",
          hex_8: "#444c62",
          hex_9: "#4c6179"
        },
        {
          original_file_name: "Starship_Glow (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6702914,
          file_size_megabytes: 6.39,
          width: 3072,
          height: 5472,
          primary: "#0b1019",
          secondary: "#b89180",
          tertiary: "#2d556d",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4ca8c9",
          hex_5: "#61342a",
          hex_6: "#2f799c",
          hex_7: "#193345",
          hex_8: "#963620",
          hex_9: "#365452"
        }
      ]
    }
  },
  {
    Stormy_Mountain: {
      environment_title: "Stormy_Mountain",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Stormy_Mountain (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 5464852,
          file_size_megabytes: 5.21,
          width: 3072,
          height: 5472,
          primary: "#c4a7a8",
          secondary: "#101620",
          tertiary: "#665a68",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#51494f",
          hex_5: "#3c3b48",
          hex_6: "#7d934b",
          hex_7: "#8c6472",
          hex_8: "#41573b",
          hex_9: "#848494"
        },
        {
          original_file_name: "Stormy_Mountain (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7182967,
          file_size_megabytes: 6.85,
          width: 3072,
          height: 5472,
          primary: "#141d1e",
          secondary: "#beb2b5",
          tertiary: "#6c6b6c",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#829d40",
          hex_5: "#888195",
          hex_6: "#4b4d60",
          hex_7: "#3e4249",
          hex_8: "#4d622c",
          hex_9: "#947c93"
        },
        {
          original_file_name: "Stormy_Mountain (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6062674,
          file_size_megabytes: 5.78,
          width: 3072,
          height: 5472,
          primary: "#131920",
          secondary: "#beacb2",
          tertiary: "#6b606e",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#3c3c49",
          hex_5: "#947c89",
          hex_6: "#4b4d5c",
          hex_7: "#4a4c54",
          hex_8: "#8a8394",
          hex_9: "#8c8c94"
        },
        {
          original_file_name: "Stormy_Mountain (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6374121,
          file_size_megabytes: 6.08,
          width: 3072,
          height: 5472,
          primary: "#171f27",
          secondary: "#c1b4bd",
          tertiary: "#626172",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#5c5334",
          hex_5: "#3d4452",
          hex_6: "#8a94a4",
          hex_7: "#848b9d",
          hex_8: "#947c8e",
          hex_9: "#45545c"
        }
      ]
    }
  },
  {
    Thunderous_Skyline: {
      environment_title: "Thunderous_Skyline",
      environment_moral: "",
      environment_prompt: "",
      images: [
        {
          original_file_name: "Thunderous_Skyline (1).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6464962,
          file_size_megabytes: 6.17,
          width: 3072,
          height: 5472,
          primary: "#c9aaae",
          secondary: "#1f1c25",
          tertiary: "#785f6b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4e3f4a",
          hex_5: "#5a4e64",
          hex_6: "#8d9a9a",
          hex_7: "#91869d",
          hex_8: "#595c56",
          hex_9: "#9c4c04"
        },
        {
          original_file_name: "Thunderous_Skyline (2).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6543479,
          file_size_megabytes: 6.24,
          width: 3072,
          height: 5472,
          primary: "#bfa8ac",
          secondary: "#221f27",
          tertiary: "#76636b",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4b3f43",
          hex_5: "#574f67",
          hex_6: "#90829e",
          hex_7: "#8e9994",
          hex_8: "#575d52",
          hex_9: "#9c4908"
        },
        {
          original_file_name: "Thunderous_Skyline (3).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 7028350,
          file_size_megabytes: 6.7,
          width: 3072,
          height: 5472,
          primary: "#bca2aa",
          secondary: "#201d26",
          tertiary: "#786270",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#4b3f49",
          hex_5: "#555268",
          hex_6: "#8f849d",
          hex_7: "#8d9da0",
          hex_8: "#595c56",
          hex_9: "#9c4404"
        },
        {
          original_file_name: "Thunderous_Skyline (4).jpg",
          format: "JPEG",
          mode: "RGB",
          file_size_bytes: 6857719,
          file_size_megabytes: 6.54,
          width: 3072,
          height: 5472,
          primary: "#c3a3a5",
          secondary: "#231d24",
          tertiary: "#7f6268",
          downloadLink: "https://github.com/yt-dlx/picbook/blob/",
          previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
          hex_4: "#584247",
          hex_5: "#89a491",
          hex_6: "#7d88a3",
          hex_7: "#614f65",
          hex_8: "#56695d",
          hex_9: "#a44404"
        }
      ]
    }
  }
];
