import { EnvironmentEntry } from "@/types/database";
const CinematicDatabase: Record<string, EnvironmentEntry> = {
  Celestial_Portal: {
    environment_title: "Celestial_Portal",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Celestial_Portal (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7431706,
        file_size_megabytes: 7.09,
        width: 3072,
        height: 5472,
        primary: "#db934b",
        secondary: "#151118",
        tertiary: "#634436",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#424a64",
        hex_5: "#2b3346",
        hex_6: "#727f9f",
        hex_7: "#bdbed4",
        hex_8: "#3e4f4c",
        hex_9: "#71848a"
      },
      {
        original_file_name: "Celestial_Portal (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8125998,
        file_size_megabytes: 7.75,
        width: 3072,
        height: 5472,
        primary: "#cc834b",
        secondary: "#131820",
        tertiary: "#713d20",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#462418",
        hex_5: "#344f57",
        hex_6: "#22404e",
        hex_7: "#3e6978",
        hex_8: "#4d7d88",
        hex_9: "#963a06"
      },
      {
        original_file_name: "Celestial_Portal (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7781348,
        file_size_megabytes: 7.42,
        width: 3072,
        height: 5472,
        primary: "#151a24",
        secondary: "#b38678",
        tertiary: "#5573a7",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#6e493d",
        hex_5: "#1b456e",
        hex_6: "#7c9acc",
        hex_7: "#462d26",
        hex_8: "#415e7f",
        hex_9: "#953a08"
      },
      {
        original_file_name: "Celestial_Portal (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7026748,
        file_size_megabytes: 6.7,
        width: 3072,
        height: 5472,
        primary: "#c5af8d",
        secondary: "#111319",
        tertiary: "#3dabc2",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#5f321b",
        hex_5: "#17809d",
        hex_6: "#1e657c",
        hex_7: "#124b64",
        hex_8: "#092c40",
        hex_9: "#113d50"
      }
    ]
  },
  Cliffside_Journey: {
    environment_title: "Cliffside_Journey",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Cliffside_Journey (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8594270,
        file_size_megabytes: 8.2,
        width: 3072,
        height: 5472,
        primary: "#d2a37c",
        secondary: "#2e2824",
        tertiary: "#845a3a",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#5f4128",
        hex_5: "#555057",
        hex_6: "#a74b0f",
        hex_7: "#696562",
        hex_8: "#908a88",
        hex_9: "#9c9c94"
      },
      {
        original_file_name: "Cliffside_Journey (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8542712,
        file_size_megabytes: 8.15,
        width: 3072,
        height: 5472,
        primary: "#cd9b76",
        secondary: "#221f1b",
        tertiary: "#75503b",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#4f3a26",
        hex_5: "#7a7377",
        hex_6: "#918e8d",
        hex_7: "#4e4b4f",
        hex_8: "#575f67",
        hex_9: "#9c4c2c"
      },
      {
        original_file_name: "Cliffside_Journey (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8720512,
        file_size_megabytes: 8.32,
        width: 3072,
        height: 5472,
        primary: "#d3a88d",
        secondary: "#24211c",
        tertiary: "#80553e",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#93909d",
        hex_5: "#777c8a",
        hex_6: "#543a24",
        hex_7: "#4d4750",
        hex_8: "#ae432e",
        hex_9: "#635c50"
      },
      {
        original_file_name: "Cliffside_Journey (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8604219,
        file_size_megabytes: 8.21,
        width: 3072,
        height: 5472,
        primary: "#242424",
        secondary: "#c79066",
        tertiary: "#7c553c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#57697f",
        hex_5: "#445365",
        hex_6: "#553725",
        hex_7: "#848a97",
        hex_8: "#8ca3b4",
        hex_9: "#a0431d"
      }
    ]
  },
  Coastal_Serenity: {
    environment_title: "Coastal_Serenity",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Coastal_Serenity (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7887909,
        file_size_megabytes: 7.52,
        width: 3072,
        height: 5472,
        primary: "#34353c",
        secondary: "#d48156",
        tertiary: "#8b5b55",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#7c8a9a",
        hex_5: "#664446",
        hex_6: "#5c7180",
        hex_7: "#3e5d72",
        hex_8: "#969eab",
        hex_9: "#b43c3c"
      },
      {
        original_file_name: "Coastal_Serenity (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8281240,
        file_size_megabytes: 7.9,
        width: 3072,
        height: 5472,
        primary: "#d59359",
        secondary: "#1e2a32",
        tertiary: "#80655a",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#56413c",
        hex_5: "#2f5368",
        hex_6: "#6b7786",
        hex_7: "#516672",
        hex_8: "#978e8a",
        hex_9: "#a4440c"
      },
      {
        original_file_name: "Coastal_Serenity (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8148509,
        file_size_megabytes: 7.77,
        width: 3072,
        height: 5472,
        primary: "#d38b62",
        secondary: "#283038",
        tertiary: "#87584e",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#738ba1",
        hex_5: "#5f4347",
        hex_6: "#56788c",
        hex_7: "#45657b",
        hex_8: "#9da5b2",
        hex_9: "#b83a05"
      },
      {
        original_file_name: "Coastal_Serenity (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7943395,
        file_size_megabytes: 7.58,
        width: 3072,
        height: 5472,
        primary: "#da9058",
        secondary: "#333a40",
        tertiary: "#946451",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#6c8093",
        hex_5: "#62717b",
        hex_6: "#6d4b45",
        hex_7: "#395c73",
        hex_8: "#8f97a2",
        hex_9: "#110b0d"
      }
    ]
  },
  Cosmic_Ascent: {
    environment_title: "Cosmic_Ascent",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Cosmic_Ascent (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6772027,
        file_size_megabytes: 6.46,
        width: 3072,
        height: 5472,
        primary: "#cd5960",
        secondary: "#161c2a",
        tertiary: "#6b2d42",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#20b5be",
        hex_5: "#1c687b",
        hex_6: "#184154",
        hex_7: "#0e889e",
        hex_8: "#fbae8d",
        hex_9: "#1b5e62"
      },
      {
        original_file_name: "Cosmic_Ascent (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6642454,
        file_size_megabytes: 6.33,
        width: 3072,
        height: 5472,
        primary: "#bb504d",
        secondary: "#1c1722",
        tertiary: "#28b4aa",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#712c3a",
        hex_5: "#306271",
        hex_6: "#1f3a4c",
        hex_7: "#ecc299",
        hex_8: "#1f6054",
        hex_9: "#2a879e"
      },
      {
        original_file_name: "Cosmic_Ascent (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6739889,
        file_size_megabytes: 6.43,
        width: 3072,
        height: 5472,
        primary: "#c8605d",
        secondary: "#16131f",
        tertiary: "#2f5476",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#3d85ae",
        hex_5: "#6a2c45",
        hex_6: "#1e334c",
        hex_7: "#b591c4",
        hex_8: "#699586",
        hex_9: "#26545c"
      },
      {
        original_file_name: "Cosmic_Ascent (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6970595,
        file_size_megabytes: 6.65,
        width: 3072,
        height: 5472,
        primary: "#bf778e",
        secondary: "#3e8bab",
        tertiary: "#13101b",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#3b5471",
        hex_5: "#62283a",
        hex_6: "#243045",
        hex_7: "#3d1925",
        hex_8: "#78948c",
        hex_9: "#415454"
      }
    ]
  },
  Desert_Odyssey: {
    environment_title: "Desert_Odyssey",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Desert_Odyssey (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7891512,
        file_size_megabytes: 7.53,
        width: 3072,
        height: 5472,
        primary: "#dca267",
        secondary: "#402617",
        tertiary: "#a99a87",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#9e6232",
        hex_5: "#764524",
        hex_6: "#838383",
        hex_7: "#72685e",
        hex_8: "#575253",
        hex_9: "#c04c04"
      },
      {
        original_file_name: "Desert_Odyssey (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8606979,
        file_size_megabytes: 8.21,
        width: 3072,
        height: 5472,
        primary: "#dfa267",
        secondary: "#562d16",
        tertiary: "#767c80",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#ada292",
        hex_5: "#24100a",
        hex_6: "#a2612f",
        hex_7: "#b17b4e",
        hex_8: "#745946",
        hex_9: "#c45c0c"
      },
      {
        original_file_name: "Desert_Odyssey (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7948937,
        file_size_megabytes: 7.58,
        width: 3072,
        height: 5472,
        primary: "#cf874b",
        secondary: "#452a1e",
        tertiary: "#f4bd78",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#8e6143",
        hex_5: "#92877c",
        hex_6: "#525d63",
        hex_7: "#666f72",
        hex_8: "#c4a483",
        hex_9: "#190d0b"
      },
      {
        original_file_name: "Desert_Odyssey (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7534696,
        file_size_megabytes: 7.19,
        width: 3072,
        height: 5472,
        primary: "#dac6a7",
        secondary: "#5a3117",
        tertiary: "#839196",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#cd8441",
        hex_5: "#27150f",
        hex_6: "#a25a1e",
        hex_7: "#a47f60",
        hex_8: "#71605a",
        hex_9: "#9caca2"
      }
    ]
  },
  Distant_Citadel: {
    environment_title: "Distant_Citadel",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Distant_Citadel (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8213884,
        file_size_megabytes: 7.83,
        width: 3072,
        height: 5472,
        primary: "#d9ad7d",
        secondary: "#181d18",
        tertiary: "#806338",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#404951",
        hex_5: "#533c1f",
        hex_6: "#9a9485",
        hex_7: "#5e5f57",
        hex_8: "#908a84",
        hex_9: "#a75c11"
      },
      {
        original_file_name: "Distant_Citadel (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7986239,
        file_size_megabytes: 7.62,
        width: 3072,
        height: 5472,
        primary: "#d9a879",
        secondary: "#23231e",
        tertiary: "#896140",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#43535f",
        hex_5: "#5f4028",
        hex_6: "#a09f95",
        hex_7: "#606c6c",
        hex_8: "#94928d",
        hex_9: "#ae5428"
      },
      {
        original_file_name: "Distant_Citadel (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7303987,
        file_size_megabytes: 6.97,
        width: 3072,
        height: 5472,
        primary: "#d29962",
        secondary: "#24272a",
        tertiary: "#845d47",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#553f38",
        hex_5: "#a44c1d",
        hex_6: "#646462",
        hex_7: "#998e8c",
        hex_8: "#9c9c8c",
        hex_9: "#505866"
      },
      {
        original_file_name: "Distant_Citadel (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7744869,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#d28f52",
        secondary: "#232421",
        tertiary: "#7f573b",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#563b29",
        hex_5: "#615c52",
        hex_6: "#917a6e",
        hex_7: "#3d434c",
        hex_8: "#a64c0e",
        hex_9: "#948c74"
      }
    ]
  },
  Enchanted_Tower: {
    environment_title: "Enchanted_Tower",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Enchanted_Tower (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7448240,
        file_size_megabytes: 7.1,
        width: 3072,
        height: 5472,
        primary: "#151c1f",
        secondary: "#ce9450",
        tertiary: "#344e67",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#405d77",
        hex_5: "#794a1f",
        hex_6: "#493019",
        hex_7: "#456384",
        hex_8: "#948c34",
        hex_9: "#9c4404"
      },
      {
        original_file_name: "Enchanted_Tower (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7109254,
        file_size_megabytes: 6.78,
        width: 3072,
        height: 5472,
        primary: "#17181a",
        secondary: "#c3731d",
        tertiary: "#435e74",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#76a1ba",
        hex_5: "#22364c",
        hex_6: "#5f86a0",
        hex_7: "#703614",
        hex_8: "#c9d7c2",
        hex_9: "#4a545a"
      },
      {
        original_file_name: "Enchanted_Tower (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7283022,
        file_size_megabytes: 6.95,
        width: 3072,
        height: 5472,
        primary: "#547592",
        secondary: "#191e21",
        tertiary: "#c9811e",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#744619",
        hex_5: "#462f1e",
        hex_6: "#2a4055",
        hex_7: "#345574",
        hex_8: "#455c6c",
        hex_9: "#7c9cb4"
      },
      {
        original_file_name: "Enchanted_Tower (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6873382,
        file_size_megabytes: 6.55,
        width: 3072,
        height: 5472,
        primary: "#5b7895",
        secondary: "#857a76",
        tertiary: "#121917",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#324e68",
        hex_5: "#5c463b",
        hex_6: "#596472",
        hex_7: "#392f2c",
        hex_8: "#34547c",
        hex_9: "#414441"
      }
    ]
  },
  Ethereal_Plains: {
    environment_title: "Ethereal_Plains",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Ethereal_Plains (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7312669,
        file_size_megabytes: 6.97,
        width: 3072,
        height: 5472,
        primary: "#172324",
        secondary: "#beb29e",
        tertiary: "#7f9e9f",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#6c7875",
        hex_5: "#486567",
        hex_6: "#344f5e",
        hex_7: "#404c3b",
        hex_8: "#678a94",
        hex_9: "#9a745c"
      },
      {
        original_file_name: "Ethereal_Plains (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7578667,
        file_size_megabytes: 7.23,
        width: 3072,
        height: 5472,
        primary: "#111e1c",
        secondary: "#b6b1b2",
        tertiary: "#7d949e",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#31475e",
        hex_5: "#496363",
        hex_6: "#697b92",
        hex_7: "#617375",
        hex_8: "#374d38",
        hex_9: "#948478"
      },
      {
        original_file_name: "Ethereal_Plains (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7949806,
        file_size_megabytes: 7.58,
        width: 3072,
        height: 5472,
        primary: "#121f1c",
        secondary: "#baacb1",
        tertiary: "#5e6f7c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#395068",
        hex_5: "#778aa1",
        hex_6: "#8a9cae",
        hex_7: "#394b34",
        hex_8: "#94747d",
        hex_9: "#575a3c"
      },
      {
        original_file_name: "Ethereal_Plains (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7292344,
        file_size_megabytes: 6.95,
        width: 3072,
        height: 5472,
        primary: "#c1ac99",
        secondary: "#799495",
        tertiary: "#121c15",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#5a6f7b",
        hex_5: "#263a4f",
        hex_6: "#425860",
        hex_7: "#656669",
        hex_8: "#374533",
        hex_9: "#946c6a"
      }
    ]
  },
  Fiery_Summit: {
    environment_title: "Fiery_Summit",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Fiery_Summit (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6800687,
        file_size_megabytes: 6.49,
        width: 3072,
        height: 5472,
        primary: "#bf3e1b",
        secondary: "#11131b",
        tertiary: "#672c2d",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#5b5966",
        hex_5: "#3d1b23",
        hex_6: "#353441",
        hex_7: "#fac928",
        hex_8: "#748c8c",
        hex_9: "#485450"
      },
      {
        original_file_name: "Fiery_Summit (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5931729,
        file_size_megabytes: 5.66,
        width: 3072,
        height: 5472,
        primary: "#c7471d",
        secondary: "#0c121e",
        tertiary: "#602a2d",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#263548",
        hex_5: "#361d28",
        hex_6: "#606169",
        hex_7: "#f9b731",
        hex_8: "#3e4d57",
        hex_9: "#7c7c7c"
      },
      {
        original_file_name: "Fiery_Summit (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5805899,
        file_size_megabytes: 5.54,
        width: 3072,
        height: 5472,
        primary: "#c84923",
        secondary: "#0b1421",
        tertiary: "#586a7b",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#60222d",
        hex_5: "#243a53",
        hex_6: "#331e2b",
        hex_7: "#4c5c62",
        hex_8: "#849495",
        hex_9: "#2c3c43"
      },
      {
        original_file_name: "Fiery_Summit (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6037713,
        file_size_megabytes: 5.76,
        width: 3072,
        height: 5472,
        primary: "#10151f",
        secondary: "#cc3214",
        tertiary: "#662527",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#4b6a7d",
        hex_5: "#3b1d23",
        hex_6: "#f8b137",
        hex_7: "#254153",
        hex_8: "#3d5462",
        hex_9: "#538ca1"
      }
    ]
  },
  Forest_Mystique: {
    environment_title: "Forest_Mystique",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Forest_Mystique (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8816050,
        file_size_megabytes: 8.41,
        width: 3072,
        height: 5472,
        primary: "#beb694",
        secondary: "#172017",
        tertiary: "#6f7355",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#3c4c38",
        hex_5: "#62543a",
        hex_6: "#879d87",
        hex_7: "#41585e",
        hex_8: "#7b9099",
        hex_9: "#94644c"
      },
      {
        original_file_name: "Forest_Mystique (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8213696,
        file_size_megabytes: 7.83,
        width: 3072,
        height: 5472,
        primary: "#bbbea3",
        secondary: "#14221e",
        tertiary: "#6f7c67",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#86a08e",
        hex_5: "#3c523f",
        hex_6: "#455e68",
        hex_7: "#595d3f",
        hex_8: "#718fa0",
        hex_9: "#96844e"
      },
      {
        original_file_name: "Forest_Mystique (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7924849,
        file_size_megabytes: 7.56,
        width: 3072,
        height: 5472,
        primary: "#192520",
        secondary: "#c0c1a6",
        tertiary: "#6b7669",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#869e9f",
        hex_5: "#42514b",
        hex_6: "#728ea0",
        hex_7: "#3f5866",
        hex_8: "#5d5b50",
        hex_9: "#948474"
      },
      {
        original_file_name: "Forest_Mystique (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8417417,
        file_size_megabytes: 8.03,
        width: 3072,
        height: 5472,
        primary: "#b6b08c",
        secondary: "#182018",
        tertiary: "#6f7450",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#404c38",
        hex_5: "#5f5942",
        hex_6: "#8a9d67",
        hex_7: "#7c8f9a",
        hex_8: "#45585f",
        hex_9: "#946444"
      }
    ]
  },
  Galactic_Voyage: {
    environment_title: "Galactic_Voyage",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Galactic_Voyage (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6690391,
        file_size_megabytes: 6.38,
        width: 3072,
        height: 5472,
        primary: "#231f30",
        secondary: "#be929d",
        tertiary: "#3a5f84",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#3680b1",
        hex_5: "#4daccd",
        hex_6: "#723f55",
        hex_7: "#26405e",
        hex_8: "#a24057",
        hex_9: "#4c656b"
      },
      {
        original_file_name: "Galactic_Voyage (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6066318,
        file_size_megabytes: 5.79,
        width: 3072,
        height: 5472,
        primary: "#cfa99f",
        secondary: "#111d2e",
        tertiary: "#2f5a7c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#4aa2c0",
        hex_5: "#297ba7",
        hex_6: "#5e3744",
        hex_7: "#1d3e5b",
        hex_8: "#993e33",
        hex_9: "#715e60"
      },
      {
        original_file_name: "Galactic_Voyage (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6868456,
        file_size_megabytes: 6.55,
        width: 3072,
        height: 5472,
        primary: "#dba395",
        secondary: "#181a2a",
        tertiary: "#743e4c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#223a55",
        hex_5: "#71a3be",
        hex_6: "#295678",
        hex_7: "#b43931",
        hex_8: "#387da4",
        hex_9: "#4c5c5c"
      },
      {
        original_file_name: "Galactic_Voyage (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6690904,
        file_size_megabytes: 6.38,
        width: 3072,
        height: 5472,
        primary: "#c56167",
        secondary: "#221d2b",
        tertiary: "#79374f",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#59afc9",
        hex_5: "#d0e3e7",
        hex_6: "#2f5e7b",
        hex_7: "#3c82a5",
        hex_8: "#2e3c54",
        hex_9: "#495c63"
      }
    ]
  },
  Glacial_Haven: {
    environment_title: "Glacial_Haven",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Glacial_Haven (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7425326,
        file_size_megabytes: 7.08,
        width: 3072,
        height: 5472,
        primary: "#c6c3c7",
        secondary: "#11435f",
        tertiary: "#63a5cb",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#4b85a9",
        hex_5: "#216e99",
        hex_6: "#051928",
        hex_7: "#596e88",
        hex_8: "#82a4b4",
        hex_9: "#d4945c"
      },
      {
        original_file_name: "Glacial_Haven (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8151943,
        file_size_megabytes: 7.77,
        width: 3072,
        height: 5472,
        primary: "#0f435d",
        secondary: "#b9cedf",
        tertiary: "#559abb",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#041622",
        hex_5: "#4b84a1",
        hex_6: "#72b1cf",
        hex_7: "#216c91",
        hex_8: "#506e86",
        hex_9: "#8c94a4"
      },
      {
        original_file_name: "Glacial_Haven (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7566917,
        file_size_megabytes: 7.22,
        width: 3072,
        height: 5472,
        primary: "#0b3950",
        secondary: "#98cbe6",
        tertiary: "#4697bd",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#1a6a8f",
        hex_5: "#3e83a3",
        hex_6: "#1e5d78",
        hex_7: "#84a2bc",
        hex_8: "#39aed7",
        hex_9: "#456278"
      },
      {
        original_file_name: "Glacial_Haven (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8005800,
        file_size_megabytes: 7.63,
        width: 3072,
        height: 5472,
        primary: "#bbd5e7",
        secondary: "#103b53",
        tertiary: "#6fadca",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#337696",
        hex_5: "#5396b8",
        hex_6: "#04101b",
        hex_7: "#4e6177",
        hex_8: "#456c7b",
        hex_9: "#8c94a8"
      }
    ]
  },
  Lighthouse_Solitude: {
    environment_title: "Lighthouse_Solitude",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Lighthouse_Solitude (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6756970,
        file_size_megabytes: 6.44,
        width: 3072,
        height: 5472,
        primary: "#aebbbf",
        secondary: "#22323b",
        tertiary: "#70848b",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#90a6af",
        hex_5: "#869aa5",
        hex_6: "#475a62",
        hex_7: "#556975",
        hex_8: "#0d0f11",
        hex_9: "#6d615d"
      },
      {
        original_file_name: "Lighthouse_Solitude (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7197995,
        file_size_megabytes: 6.86,
        width: 3072,
        height: 5472,
        primary: "#1f2d33",
        secondary: "#afbabc",
        tertiary: "#8fa8b0",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#72868d",
        hex_5: "#859aa5",
        hex_6: "#425a63",
        hex_7: "#526975",
        hex_8: "#6c6059",
        hex_9: "#a24c25"
      },
      {
        original_file_name: "Lighthouse_Solitude (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6980753,
        file_size_megabytes: 6.66,
        width: 3072,
        height: 5472,
        primary: "#b4bfc8",
        secondary: "#1e272c",
        tertiary: "#758994",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#99aeb8",
        hex_5: "#8ea1ae",
        hex_6: "#50616a",
        hex_7: "#5e717e",
        hex_8: "#42515e",
        hex_9: "#766162"
      },
      {
        original_file_name: "Lighthouse_Solitude (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6599472,
        file_size_megabytes: 6.29,
        width: 3072,
        height: 5472,
        primary: "#a9bcc6",
        secondary: "#1a2932",
        tertiary: "#85a1ab",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#5d7983",
        hex_5: "#78919e",
        hex_6: "#37525b",
        hex_7: "#48616d",
        hex_8: "#6c3438",
        hex_9: "#9a4029"
      }
    ]
  },
  Mountain_Majesty: {
    environment_title: "Mountain_Majesty",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Mountain_Majesty (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7744844,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#d1a06f",
        secondary: "#2d3435",
        tertiary: "#885f3b",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#7d888a",
        hex_5: "#5d493b",
        hex_6: "#9b9f9a",
        hex_7: "#5f7176",
        hex_8: "#475b69",
        hex_9: "#ac5c14"
      },
      {
        original_file_name: "Mountain_Majesty (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7974931,
        file_size_megabytes: 7.61,
        width: 3072,
        height: 5472,
        primary: "#d9b187",
        secondary: "#232625",
        tertiary: "#7f6348",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#768488",
        hex_5: "#58696d",
        hex_6: "#415661",
        hex_7: "#56432e",
        hex_8: "#929f9a",
        hex_9: "#a85106"
      },
      {
        original_file_name: "Mountain_Majesty (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7348932,
        file_size_megabytes: 7.01,
        width: 3072,
        height: 5472,
        primary: "#dfa95f",
        secondary: "#312e2e",
        tertiary: "#8e6138",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#664a37",
        hex_5: "#667074",
        hex_6: "#555d63",
        hex_7: "#737f85",
        hex_8: "#ac6427",
        hex_9: "#a49c8c"
      },
      {
        original_file_name: "Mountain_Majesty (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7500742,
        file_size_megabytes: 7.15,
        width: 3072,
        height: 5472,
        primary: "#daa266",
        secondary: "#191e1f",
        tertiary: "#805a3c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#737676",
        hex_5: "#3c4955",
        hex_6: "#576065",
        hex_7: "#513722",
        hex_8: "#999588",
        hex_9: "#a84c08"
      }
    ]
  },
  Ruins_At_Twilight: {
    environment_title: "Ruins_At_Twilight",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Ruins_At_Twilight (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7932325,
        file_size_megabytes: 7.56,
        width: 3072,
        height: 5472,
        primary: "#d6885b",
        secondary: "#201f1d",
        tertiary: "#784c48",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#433d4c",
        hex_5: "#4c3434",
        hex_6: "#836674",
        hex_7: "#5b545d",
        hex_8: "#a53906",
        hex_9: "#947c64"
      },
      {
        original_file_name: "Ruins_At_Twilight (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8144712,
        file_size_megabytes: 7.77,
        width: 3072,
        height: 5472,
        primary: "#d3976f",
        secondary: "#889aae",
        tertiary: "#251714",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#68849c",
        hex_5: "#803f1c",
        hex_6: "#562612",
        hex_7: "#a63907",
        hex_8: "#544c52",
        hex_9: "#606066"
      },
      {
        original_file_name: "Ruins_At_Twilight (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7168317,
        file_size_megabytes: 6.84,
        width: 3072,
        height: 5472,
        primary: "#cd9975",
        secondary: "#232227",
        tertiary: "#835e57",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#454d61",
        hex_5: "#56362d",
        hex_6: "#98868c",
        hex_7: "#646771",
        hex_8: "#a43a08",
        hex_9: "#9c948c"
      },
      {
        original_file_name: "Ruins_At_Twilight (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8432045,
        file_size_megabytes: 8.04,
        width: 3072,
        height: 5472,
        primary: "#ce8966",
        secondary: "#231612",
        tertiary: "#6b5e74",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#834a2c",
        hex_5: "#553025",
        hex_6: "#313b56",
        hex_7: "#5a5560",
        hex_8: "#908494",
        hex_9: "#a44414"
      }
    ]
  },
  Sky_Kingdom: {
    environment_title: "Sky_Kingdom",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Sky_Kingdom (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7143497,
        file_size_megabytes: 6.81,
        width: 3072,
        height: 5472,
        primary: "#50413d",
        secondary: "#c9966c",
        tertiary: "#edc99c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#936548",
        hex_5: "#8c9a9a",
        hex_6: "#516674",
        hex_7: "#938a7c",
        hex_8: "#301a13",
        hex_9: "#9cb4ac"
      },
      {
        original_file_name: "Sky_Kingdom (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7217417,
        file_size_megabytes: 6.88,
        width: 3072,
        height: 5472,
        primary: "#dfb88f",
        secondary: "#3d3738",
        tertiary: "#9c765d",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#919797",
        hex_5: "#566874",
        hex_6: "#775543",
        hex_7: "#708085",
        hex_8: "#b1ad9d",
        hex_9: "#bc6c26"
      },
      {
        original_file_name: "Sky_Kingdom (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7369203,
        file_size_megabytes: 7.03,
        width: 3072,
        height: 5472,
        primary: "#e0af75",
        secondary: "#2c2a2e",
        tertiary: "#9b6d50",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#9db2aa",
        hex_5: "#6e8c93",
        hex_6: "#6b4839",
        hex_7: "#607177",
        hex_8: "#405a6c",
        hex_9: "#bc4c0c"
      },
      {
        original_file_name: "Sky_Kingdom (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7710237,
        file_size_megabytes: 7.35,
        width: 3072,
        height: 5472,
        primary: "#6c432d",
        secondary: "#f6cb91",
        tertiary: "#27292f",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#df9c61",
        hex_5: "#8d999a",
        hex_6: "#736b6a",
        hex_7: "#b36e3d",
        hex_8: "#b49274",
        hex_9: "#3c84a1"
      }
    ]
  },
  Starlit_Temple: {
    environment_title: "Starlit_Temple",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Starlit_Temple (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6856455,
        file_size_megabytes: 6.54,
        width: 3072,
        height: 5472,
        primary: "#c16b25",
        secondary: "#0d1625",
        tertiary: "#235d75",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#094262",
        hex_5: "#317592",
        hex_6: "#5598ab",
        hex_7: "#5a2d1c",
        hex_8: "#052e4a",
        hex_9: "#e0c26a"
      },
      {
        original_file_name: "Starlit_Temple (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7051131,
        file_size_megabytes: 6.72,
        width: 3072,
        height: 5472,
        primary: "#151d25",
        secondary: "#a3766c",
        tertiary: "#674f53",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#2a3749",
        hex_5: "#717392",
        hex_6: "#404963",
        hex_7: "#c5a6bb",
        hex_8: "#807c7c",
        hex_9: "#445454"
      },
      {
        original_file_name: "Starlit_Temple (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6798860,
        file_size_megabytes: 6.48,
        width: 3072,
        height: 5472,
        primary: "#161f2a",
        secondary: "#ab6c45",
        tertiary: "#72514c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#433536",
        hex_5: "#404a60",
        hex_6: "#7f7386",
        hex_7: "#4e4c53",
        hex_8: "#c4a1ae",
        hex_9: "#8a7475"
      },
      {
        original_file_name: "Starlit_Temple (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6388919,
        file_size_megabytes: 6.09,
        width: 3072,
        height: 5472,
        primary: "#0a141e",
        secondary: "#da9223",
        tertiary: "#395270",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#19314d",
        hex_5: "#62341b",
        hex_6: "#331f14",
        hex_7: "#983d0b",
        hex_8: "#3f4d5b",
        hex_9: "#637c90"
      }
    ]
  },
  Submerged_Wonder: {
    environment_title: "Submerged_Wonder",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Submerged_Wonder (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7257447,
        file_size_megabytes: 6.92,
        width: 3072,
        height: 5472,
        primary: "#0c252a",
        secondary: "#45aeb4",
        tertiary: "#b6d7c7",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#196e84",
        hex_5: "#118ca8",
        hex_6: "#09445d",
        hex_7: "#41705b",
        hex_8: "#544f30",
        hex_9: "#ac5942"
      },
      {
        original_file_name: "Submerged_Wonder (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7731354,
        file_size_megabytes: 7.37,
        width: 3072,
        height: 5472,
        primary: "#afd2ce",
        secondary: "#0c3a48",
        tertiary: "#63b3bf",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#1f7a8c",
        hex_5: "#457866",
        hex_6: "#081412",
        hex_7: "#2f97b1",
        hex_8: "#594d39",
        hex_9: "#915b3e"
      },
      {
        original_file_name: "Submerged_Wonder (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7375370,
        file_size_megabytes: 7.03,
        width: 3072,
        height: 5472,
        primary: "#0f2628",
        secondary: "#54bbc4",
        tertiary: "#b2d9cb",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#21787c",
        hex_5: "#178ea5",
        hex_6: "#0a5a70",
        hex_7: "#19524f",
        hex_8: "#514d39",
        hex_9: "#8c8462"
      },
      {
        original_file_name: "Submerged_Wonder (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7553797,
        file_size_megabytes: 7.2,
        width: 3072,
        height: 5472,
        primary: "#0e2829",
        secondary: "#50b7bb",
        tertiary: "#acd8dc",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#2d7c7e",
        hex_5: "#0c5970",
        hex_6: "#2691a3",
        hex_7: "#205350",
        hex_8: "#533f2c",
        hex_9: "#8c948c"
      }
    ]
  },
  Twilight_Canyon: {
    environment_title: "Twilight_Canyon",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Twilight_Canyon (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8700268,
        file_size_megabytes: 8.3,
        width: 3072,
        height: 5472,
        primary: "#d38c48",
        secondary: "#221d20",
        tertiary: "#778ca6",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#814c2c",
        hex_5: "#56382e",
        hex_6: "#44506c",
        hex_7: "#4d5f78",
        hex_8: "#acbacd",
        hex_9: "#9c8c7c"
      },
      {
        original_file_name: "Twilight_Canyon (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8073423,
        file_size_megabytes: 7.7,
        width: 3072,
        height: 5472,
        primary: "#d4ab84",
        secondary: "#272321",
        tertiary: "#745951",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#638a9d",
        hex_5: "#7ca7b9",
        hex_6: "#52332d",
        hex_7: "#3c6b7d",
        hex_8: "#2b5164",
        hex_9: "#a94609"
      },
      {
        original_file_name: "Twilight_Canyon (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8361143,
        file_size_megabytes: 7.97,
        width: 3072,
        height: 5472,
        primary: "#d3b78a",
        secondary: "#2b2324",
        tertiary: "#48829e",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#7e4f2d",
        hex_5: "#7aabc0",
        hex_6: "#46687e",
        hex_7: "#38516a",
        hex_8: "#593329",
        hex_9: "#ac570e"
      },
      {
        original_file_name: "Twilight_Canyon (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8456883,
        file_size_megabytes: 8.07,
        width: 3072,
        height: 5472,
        primary: "#da8c48",
        secondary: "#261f1f",
        tertiary: "#7b4d38",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#87a0b4",
        hex_5: "#563a34",
        hex_6: "#55606f",
        hex_7: "#6a8196",
        hex_8: "#484f61",
        hex_9: "#aa3707"
      }
    ]
  },
  Twilight_Shores: {
    environment_title: "Twilight_Shores",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt:
      "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Twilight_Shores (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7776793,
        file_size_megabytes: 7.42,
        width: 3072,
        height: 5472,
        primary: "#de8f6f",
        secondary: "#23313f",
        tertiary: "#7e4e59",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#5e6181",
        hex_5: "#564256",
        hex_6: "#181817",
        hex_7: "#4e5c6f",
        hex_8: "#a84c54",
        hex_9: "#9c8489"
      },
      {
        original_file_name: "Twilight_Shores (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8768456,
        file_size_megabytes: 8.36,
        width: 3072,
        height: 5472,
        primary: "#ce856a",
        secondary: "#273e4f",
        tertiary: "#8a5c67",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#0f1510",
        hex_5: "#5f4d62",
        hex_6: "#5c6e7f",
        hex_7: "#657795",
        hex_8: "#9c908d",
        hex_9: "#ae3c42"
      },
      {
        original_file_name: "Twilight_Shores (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8015341,
        file_size_megabytes: 7.64,
        width: 3072,
        height: 5472,
        primary: "#cd928a",
        secondary: "#2c3848",
        tertiary: "#806570",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#8295ab",
        hex_5: "#151411",
        hex_6: "#647d98",
        hex_7: "#505e78",
        hex_8: "#586e86",
        hex_9: "#594c5b"
      },
      {
        original_file_name: "Twilight_Shores (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8024387,
        file_size_megabytes: 7.65,
        width: 3072,
        height: 5472,
        primary: "#d38171",
        secondary: "#273142",
        tertiary: "#8a5156",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#6d718b",
        hex_5: "#5e4251",
        hex_6: "#151619",
        hex_7: "#596479",
        hex_8: "#a08c9f",
        hex_9: "#b14444"
      }
    ]
  }
};
export default CinematicDatabase;
