import { EnvironmentEntry } from "@/types/database";
const AnimeLandscapes: Record<string, EnvironmentEntry> = {
  "Autumn Misty Bridge": {
    environment_title: "Autumn Misty Bridge",
    images: [
      {
        original_file_name: "Autumn Misty Bridge (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7830454,
        file_size_megabytes: 7.47,
        width: 3072,
        height: 5472,
        primary: "#e6997b",
        secondary: "#302125",
        tertiary: "#92493c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#68352b",
        hex_5: "#c9381f",
        hex_6: "#51526b",
        hex_7: "#a0a1aa",
        hex_8: "#8d8ea1",
        hex_9: "#666675"
      },
      {
        original_file_name: "Autumn Misty Bridge (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7999997,
        file_size_megabytes: 7.63,
        width: 3072,
        height: 5472,
        primary: "#2f2835",
        secondary: "#703f3c",
        tertiary: "#f6cfb5",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e37950",
        hex_5: "#b25240",
        hex_6: "#b38472",
        hex_7: "#79667d",
        hex_8: "#e2a1a5",
        hex_9: "#f5bd3b"
      },
      {
        original_file_name: "Autumn Misty Bridge (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8568060,
        file_size_megabytes: 8.17,
        width: 3072,
        height: 5472,
        primary: "#2c242d",
        secondary: "#f0debd",
        tertiary: "#d96d4a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5d3736",
        hex_5: "#9e1d0d",
        hex_6: "#b8a8b8",
        hex_7: "#8c564c",
        hex_8: "#cc9991",
        hex_9: "#449cbc"
      },
      {
        original_file_name: "Autumn Misty Bridge (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7925445,
        file_size_megabytes: 7.56,
        width: 3072,
        height: 5472,
        primary: "#302731",
        secondary: "#6d352f",
        tertiary: "#edd3c0",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e67950",
        hex_5: "#b08073",
        hex_6: "#b1503f",
        hex_7: "#b39cac",
        hex_8: "#8e6371",
        hex_9: "#f8b03c"
      }
    ]
  },
  "Autumn Misty River": {
    environment_title: "Autumn Misty River",
    images: [
      {
        original_file_name: "Autumn Misty River (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8789602,
        file_size_megabytes: 8.38,
        width: 3072,
        height: 5472,
        primary: "#e0c282",
        secondary: "#243639",
        tertiary: "#87baaf",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#91522f",
        hex_5: "#4884c0",
        hex_6: "#538378",
        hex_7: "#cb4920",
        hex_8: "#633827",
        hex_9: "#38617c"
      },
      {
        original_file_name: "Autumn Misty River (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8643166,
        file_size_megabytes: 8.24,
        width: 3072,
        height: 5472,
        primary: "#e3af81",
        secondary: "#2a2f30",
        tertiary: "#92573f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5681ab",
        hex_5: "#8cb2c7",
        hex_6: "#674433",
        hex_7: "#be4527",
        hex_8: "#3a5477",
        hex_9: "#65726d"
      },
      {
        original_file_name: "Autumn Misty River (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9366198,
        file_size_megabytes: 8.93,
        width: 3072,
        height: 5472,
        primary: "#e8b491",
        secondary: "#242c30",
        tertiary: "#8eced0",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a26151",
        hex_5: "#5e92b1",
        hex_6: "#668181",
        hex_7: "#496076",
        hex_8: "#6e4438",
        hex_9: "#db3c15"
      },
      {
        original_file_name: "Autumn Misty River (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8885931,
        file_size_megabytes: 8.47,
        width: 3072,
        height: 5472,
        primary: "#e4ad8f",
        secondary: "#262c2d",
        tertiary: "#95bbd6",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#906253",
        hex_5: "#5d7675",
        hex_6: "#7a90af",
        hex_7: "#604638",
        hex_8: "#d74022",
        hex_9: "#475c74"
      }
    ]
  },
  "Crystal Ice Palace": {
    environment_title: "Crystal Ice Palace",
    images: [
      {
        original_file_name: "Crystal Ice Palace (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7638310,
        file_size_megabytes: 7.28,
        width: 3072,
        height: 5472,
        primary: "#d4e8f5",
        secondary: "#3b84ce",
        tertiary: "#6dd4f7",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#0e1a32",
        hex_5: "#304d6a",
        hex_6: "#0c2d61",
        hex_7: "#849fc9",
        hex_8: "#1b4c95",
        hex_9: "#a4744c"
      },
      {
        original_file_name: "Crystal Ice Palace (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7785216,
        file_size_megabytes: 7.42,
        width: 3072,
        height: 5472,
        primary: "#c9edf3",
        secondary: "#7bd3f2",
        tertiary: "#1f345a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3d87d5",
        hex_5: "#6984a0",
        hex_6: "#0a0f24",
        hex_7: "#2758a0",
        hex_8: "#696373",
        hex_9: "#a4848c"
      },
      {
        original_file_name: "Crystal Ice Palace (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7871860,
        file_size_megabytes: 7.51,
        width: 3072,
        height: 5472,
        primary: "#64d2f2",
        secondary: "#c9ecf1",
        tertiary: "#14304b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#378bd4",
        hex_5: "#3d6b95",
        hex_6: "#050a15",
        hex_7: "#417074",
        hex_8: "#5e565c",
        hex_9: "#a46964"
      },
      {
        original_file_name: "Crystal Ice Palace (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7974205,
        file_size_megabytes: 7.6,
        width: 3072,
        height: 5472,
        primary: "#5dcaf3",
        secondary: "#cadfea",
        tertiary: "#1a2d4e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#408fd6",
        hex_5: "#2c5f95",
        hex_6: "#070c16",
        hex_7: "#694b56",
        hex_8: "#72756e",
        hex_9: "#9e5d5b"
      }
    ]
  },
  "Crystal Lake At Dawn": {
    environment_title: "Crystal Lake At Dawn",
    images: [
      {
        original_file_name: "Crystal Lake At Dawn (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7826994,
        file_size_megabytes: 7.46,
        width: 3072,
        height: 5472,
        primary: "#d4cadb",
        secondary: "#192b3e",
        tertiary: "#78b9ee",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6c8bbe",
        hex_5: "#68758e",
        hex_6: "#43587f",
        hex_7: "#060611",
        hex_8: "#665562",
        hex_9: "#9e647c"
      },
      {
        original_file_name: "Crystal Lake At Dawn (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7507610,
        file_size_megabytes: 7.16,
        width: 3072,
        height: 5472,
        primary: "#dbced8",
        secondary: "#152535",
        tertiary: "#7eb8e8",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#516c8d",
        hex_5: "#678fb8",
        hex_6: "#2f4a65",
        hex_7: "#6c535d",
        hex_8: "#73706e",
        hex_9: "#a1615f"
      },
      {
        original_file_name: "Crystal Lake At Dawn (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7909220,
        file_size_megabytes: 7.54,
        width: 3072,
        height: 5472,
        primary: "#d2cbda",
        secondary: "#101a28",
        tertiary: "#6cc1e4",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#435d84",
        hex_5: "#4c80b5",
        hex_6: "#213e5e",
        hex_7: "#614a58",
        hex_8: "#6b6766",
        hex_9: "#975f76"
      },
      {
        original_file_name: "Crystal Lake At Dawn (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7885488,
        file_size_megabytes: 7.52,
        width: 3072,
        height: 5472,
        primary: "#dbccd2",
        secondary: "#12202e",
        tertiary: "#7cc5e6",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6a88c3",
        hex_5: "#55698f",
        hex_6: "#70545b",
        hex_7: "#324766",
        hex_8: "#b45955",
        hex_9: "#3a666e"
      }
    ]
  },
  "Desert Oasis Dream": {
    environment_title: "Desert Oasis Dream",
    images: [
      {
        original_file_name: "Desert Oasis Dream (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5617294,
        file_size_megabytes: 5.36,
        width: 3072,
        height: 5472,
        primary: "#f9ecb1",
        secondary: "#2a1510",
        tertiary: "#74443a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#dc7b46",
        hex_5: "#ae9069",
        hex_6: "#c3abac",
        hex_7: "#54180e",
        hex_8: "#8c7479",
        hex_9: "#efbf51"
      },
      {
        original_file_name: "Desert Oasis Dream (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7148533,
        file_size_megabytes: 6.82,
        width: 3072,
        height: 5472,
        primary: "#683e29",
        secondary: "#25221c",
        tertiary: "#e0ebcf",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#67b6c7",
        hex_5: "#887136",
        hex_6: "#bf8b65",
        hex_7: "#c89084",
        hex_8: "#ecd48b",
        hex_9: "#36b3bc"
      },
      {
        original_file_name: "Desert Oasis Dream (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7972878,
        file_size_megabytes: 7.6,
        width: 3072,
        height: 5472,
        primary: "#1e3d48",
        secondary: "#dfeacb",
        tertiary: "#783c21",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#b2a6bc",
        hex_5: "#d78f59",
        hex_6: "#625876",
        hex_7: "#9e9963",
        hex_8: "#97753a",
        hex_9: "#c4c750"
      },
      {
        original_file_name: "Desert Oasis Dream (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6842970,
        file_size_megabytes: 6.53,
        width: 3072,
        height: 5472,
        primary: "#373c45",
        secondary: "#74d6c8",
        tertiary: "#f4edc1",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#25a6e5",
        hex_5: "#9f6b53",
        hex_6: "#3aa08a",
        hex_7: "#e8b673",
        hex_8: "#e89b44",
        hex_9: "#cf6244"
      }
    ]
  },
  "Emerald Forest Glade": {
    environment_title: "Emerald Forest Glade",
    images: [
      {
        original_file_name: "Emerald Forest Glade (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8364147,
        file_size_megabytes: 7.98,
        width: 3072,
        height: 5472,
        primary: "#caeebc",
        secondary: "#69d1a9",
        tertiary: "#0f3227",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#429063",
        hex_5: "#419ea9",
        hex_6: "#22663b",
        hex_7: "#5e6540",
        hex_8: "#1f6570",
        hex_9: "#9c7444"
      },
      {
        original_file_name: "Emerald Forest Glade (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8735053,
        file_size_megabytes: 8.33,
        width: 3072,
        height: 5472,
        primary: "#c9e496",
        secondary: "#173127",
        tertiary: "#70c885",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4a8d57",
        hex_5: "#6e5f3a",
        hex_6: "#3e87aa",
        hex_7: "#216074",
        hex_8: "#28653c",
        hex_9: "#a26f39"
      },
      {
        original_file_name: "Emerald Forest Glade (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8398152,
        file_size_megabytes: 8.01,
        width: 3072,
        height: 5472,
        primary: "#c2ef98",
        secondary: "#68ca92",
        tertiary: "#0c3228",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3a8d60",
        hex_5: "#23696d",
        hex_6: "#3d99a2",
        hex_7: "#1b653e",
        hex_8: "#5c6846",
        hex_9: "#948c5e"
      },
      {
        original_file_name: "Emerald Forest Glade (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8814692,
        file_size_megabytes: 8.41,
        width: 3072,
        height: 5472,
        primary: "#c3edb7",
        secondary: "#0b3528",
        tertiary: "#6cc88c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#409567",
        hex_5: "#4ca3a2",
        hex_6: "#2a6a6d",
        hex_7: "#1c6d3f",
        hex_8: "#5d6b42",
        hex_9: "#947c6c"
      }
    ]
  },
  "Enchanted Garden Glade": {
    environment_title: "Enchanted Garden Glade",
    images: [
      {
        original_file_name: "Enchanted Garden Glade (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8458324,
        file_size_megabytes: 8.07,
        width: 3072,
        height: 5472,
        primary: "#d9c38d",
        secondary: "#1c2c29",
        tertiary: "#7c6945",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6dc1bc",
        hex_5: "#3c7cb3",
        hex_6: "#245473",
        hex_7: "#397d69",
        hex_8: "#385c3c",
        hex_9: "#b6503b"
      },
      {
        original_file_name: "Enchanted Garden Glade (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8214009,
        file_size_megabytes: 7.83,
        width: 3072,
        height: 5472,
        primary: "#cec5a7",
        secondary: "#15242e",
        tertiary: "#7ab69c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#607c61",
        hex_5: "#6681be",
        hex_6: "#3e547f",
        hex_7: "#305536",
        hex_8: "#6f4d38",
        hex_9: "#a65235"
      },
      {
        original_file_name: "Enchanted Garden Glade (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8607115,
        file_size_megabytes: 8.21,
        width: 3072,
        height: 5472,
        primary: "#dcaf6a",
        secondary: "#182729",
        tertiary: "#7c4b48",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5ac1b1",
        hex_5: "#3e76b4",
        hex_6: "#c13357",
        hex_7: "#234773",
        hex_8: "#2c7267",
        hex_9: "#4e332e"
      },
      {
        original_file_name: "Enchanted Garden Glade (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8494131,
        file_size_megabytes: 8.1,
        width: 3072,
        height: 5472,
        primary: "#d2db90",
        secondary: "#182b27",
        tertiary: "#60c198",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#40835f",
        hex_5: "#3b86ab",
        hex_6: "#285873",
        hex_7: "#aa5121",
        hex_8: "#255d41",
        hex_9: "#6d482b"
      }
    ]
  },
  "Enchanted Winter Forest": {
    environment_title: "Enchanted Winter Forest",
    images: [
      {
        original_file_name: "Enchanted Winter Forest (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8958816,
        file_size_megabytes: 8.54,
        width: 3072,
        height: 5472,
        primary: "#daccc4",
        secondary: "#77bdf1",
        tertiary: "#2f2433",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e8bd5",
        hex_5: "#546b97",
        hex_6: "#865c53",
        hex_7: "#3a496f",
        hex_8: "#b0603f",
        hex_9: "#626d78"
      },
      {
        original_file_name: "Enchanted Winter Forest (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8776718,
        file_size_megabytes: 8.37,
        width: 3072,
        height: 5472,
        primary: "#d9d0d7",
        secondary: "#79b8ec",
        tertiary: "#1a294c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4c82d3",
        hex_5: "#3a5f96",
        hex_6: "#735256",
        hex_7: "#120c15",
        hex_8: "#b95d42",
        hex_9: "#476678"
      },
      {
        original_file_name: "Enchanted Winter Forest (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8961772,
        file_size_megabytes: 8.55,
        width: 3072,
        height: 5472,
        primary: "#c7d0db",
        secondary: "#212034",
        tertiary: "#88bcea",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#395b9e",
        hex_5: "#557fcf",
        hex_6: "#7a5359",
        hex_7: "#284178",
        hex_8: "#b15a3e",
        hex_9: "#4a687c"
      },
      {
        original_file_name: "Enchanted Winter Forest (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9058290,
        file_size_megabytes: 8.64,
        width: 3072,
        height: 5472,
        primary: "#cccfdb",
        secondary: "#1a3563",
        tertiary: "#6bbff0",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4684d9",
        hex_5: "#150f1a",
        hex_6: "#5986ae",
        hex_7: "#2f60ab",
        hex_8: "#705e6f",
        hex_9: "#af5a4c"
      }
    ]
  },
  "Floating Islands At Dawn": {
    environment_title: "Floating Islands At Dawn",
    images: [
      {
        original_file_name: "Floating Islands At Dawn (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7517002,
        file_size_megabytes: 7.17,
        width: 3072,
        height: 5472,
        primary: "#dbe5d6",
        secondary: "#4894e6",
        tertiary: "#91d4c2",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#183548",
        hex_5: "#6c9c4c",
        hex_6: "#1e549c",
        hex_7: "#3d7244",
        hex_8: "#7f7545",
        hex_9: "#bc6c34"
      },
      {
        original_file_name: "Floating Islands At Dawn (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7037414,
        file_size_megabytes: 6.71,
        width: 3072,
        height: 5472,
        primary: "#e4d5c3",
        secondary: "#263b64",
        tertiary: "#80bbe0",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5895dc",
        hex_5: "#8d6a7f",
        hex_6: "#2d3120",
        hex_7: "#3f7ea3",
        hex_8: "#185fa8",
        hex_9: "#c05b7d"
      },
      {
        original_file_name: "Floating Islands At Dawn (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7445078,
        file_size_megabytes: 7.1,
        width: 3072,
        height: 5472,
        primary: "#e2d3c6",
        secondary: "#79dad0",
        tertiary: "#30432d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#2f69bf",
        hex_5: "#9687b8",
        hex_6: "#294966",
        hex_7: "#30a6ea",
        hex_8: "#112961",
        hex_9: "#c36080"
      },
      {
        original_file_name: "Floating Islands At Dawn (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7179200,
        file_size_megabytes: 6.85,
        width: 3072,
        height: 5472,
        primary: "#d6e7d0",
        secondary: "#53c7d8",
        tertiary: "#2c79d2",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#19304b",
        hex_5: "#628651",
        hex_6: "#225789",
        hex_7: "#695d52",
        hex_8: "#1c360f",
        hex_9: "#b1622a"
      }
    ]
  },
  "Floating Lantern Isles": {
    environment_title: "Floating Lantern Isles",
    images: [
      {
        original_file_name: "Floating Lantern Isles (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7831146,
        file_size_megabytes: 7.47,
        width: 3072,
        height: 5472,
        primary: "#3eced6",
        secondary: "#ceac7a",
        tertiary: "#15273f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#185784",
        hex_5: "#2c79b6",
        hex_6: "#693b39",
        hex_7: "#a94125",
        hex_8: "#487257",
        hex_9: "#110d0d"
      },
      {
        original_file_name: "Floating Lantern Isles (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7230642,
        file_size_megabytes: 6.9,
        width: 3072,
        height: 5472,
        primary: "#c3d5c8",
        secondary: "#152c4e",
        tertiary: "#62bbee",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#427ec8",
        hex_5: "#30588b",
        hex_6: "#ab583c",
        hex_7: "#120d12",
        hex_8: "#683e3d",
        hex_9: "#5a6b67"
      },
      {
        original_file_name: "Floating Lantern Isles (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7455734,
        file_size_megabytes: 7.11,
        width: 3072,
        height: 5472,
        primary: "#d5aea2",
        secondary: "#1c1b30",
        tertiary: "#54bcee",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#31578a",
        hex_5: "#347ec2",
        hex_6: "#734149",
        hex_7: "#1b3b68",
        hex_8: "#a54333",
        hex_9: "#1c6670"
      },
      {
        original_file_name: "Floating Lantern Isles (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6427611,
        file_size_megabytes: 6.13,
        width: 3072,
        height: 5472,
        primary: "#52c3ea",
        secondary: "#c0dab9",
        tertiary: "#0c2948",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1c5997",
        hex_5: "#2475cb",
        hex_6: "#3e6e69",
        hex_7: "#091919",
        hex_8: "#9a6341",
        hex_9: "#5e493b"
      }
    ]
  },
  "Floating Lotus Islands": {
    environment_title: "Floating Lotus Islands",
    images: [
      {
        original_file_name: "Floating Lotus Islands (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7058666,
        file_size_megabytes: 6.73,
        width: 3072,
        height: 5472,
        primary: "#cee5e9",
        secondary: "#2283dc",
        tertiary: "#173e4f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#73c6e2",
        hex_5: "#3b6ea0",
        hex_6: "#54905a",
        hex_7: "#0a2411",
        hex_8: "#65606a",
        hex_9: "#b26a94"
      },
      {
        original_file_name: "Floating Lotus Islands (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7381722,
        file_size_megabytes: 7.04,
        width: 3072,
        height: 5472,
        primary: "#d2eae4",
        secondary: "#152c3d",
        tertiary: "#427049",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3ea0ee",
        hex_5: "#93cbd7",
        hex_6: "#325884",
        hex_7: "#62e1f5",
        hex_8: "#578c90",
        hex_9: "#d54b80"
      },
      {
        original_file_name: "Floating Lotus Islands (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7446311,
        file_size_megabytes: 7.1,
        width: 3072,
        height: 5472,
        primary: "#d4e6ce",
        secondary: "#1b4254",
        tertiary: "#63d8c8",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3e9ddd",
        hex_5: "#316f9a",
        hex_6: "#499b8a",
        hex_7: "#307363",
        hex_8: "#786264",
        hex_9: "#c6608c"
      },
      {
        original_file_name: "Floating Lotus Islands (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6620901,
        file_size_megabytes: 6.31,
        width: 3072,
        height: 5472,
        primary: "#cfebe6",
        secondary: "#418040",
        tertiary: "#142b3a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1b7edd",
        hex_5: "#77d6f2",
        hex_6: "#7bb1de",
        hex_7: "#276284",
        hex_8: "#22b8f2",
        hex_9: "#d46d8e"
      }
    ]
  },
  "Hidden Fairy Springs": {
    environment_title: "Hidden Fairy Springs",
    images: [
      {
        original_file_name: "Hidden Fairy Springs (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8580839,
        file_size_megabytes: 8.18,
        width: 3072,
        height: 5472,
        primary: "#c5ddc9",
        secondary: "#49c9d1",
        tertiary: "#0c2730",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#21658d",
        hex_5: "#247bc2",
        hex_6: "#337a56",
        hex_7: "#164566",
        hex_8: "#aa5662",
        hex_9: "#5e4345"
      },
      {
        original_file_name: "Hidden Fairy Springs (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8654349,
        file_size_megabytes: 8.25,
        width: 3072,
        height: 5472,
        primary: "#c9cfb8",
        secondary: "#51c9c9",
        tertiary: "#10232b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3e7d71",
        hex_5: "#3583b6",
        hex_6: "#1e4c81",
        hex_7: "#183f5e",
        hex_8: "#b45249",
        hex_9: "#663f34"
      },
      {
        original_file_name: "Hidden Fairy Springs (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8268728,
        file_size_megabytes: 7.89,
        width: 3072,
        height: 5472,
        primary: "#c8daae",
        secondary: "#4ecdd0",
        tertiary: "#0b2328",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#397d73",
        hex_5: "#2a7cb9",
        hex_6: "#204d81",
        hex_7: "#143e5e",
        hex_8: "#a65593",
        hex_9: "#5c454d"
      },
      {
        original_file_name: "Hidden Fairy Springs (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8657933,
        file_size_megabytes: 8.26,
        width: 3072,
        height: 5472,
        primary: "#cdd2c4",
        secondary: "#4dc7d5",
        tertiary: "#0d222f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#24698e",
        hex_5: "#2e85c0",
        hex_6: "#447c51",
        hex_7: "#60454c",
        hex_8: "#164466",
        hex_9: "#b4516a"
      }
    ]
  },
  "Lush Tropical Beach": {
    environment_title: "Lush Tropical Beach",
    images: [
      {
        original_file_name: "Lush Tropical Beach  (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6335654,
        file_size_megabytes: 6.04,
        width: 3072,
        height: 5472,
        primary: "#e6f3e0",
        secondary: "#1f7995",
        tertiary: "#25593f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#89ede5",
        hex_5: "#48ecda",
        hex_6: "#084ea8",
        hex_7: "#1d9cea",
        hex_8: "#27bac0",
        hex_9: "#c29450"
      },
      {
        original_file_name: "Lush Tropical Beach  (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6264228,
        file_size_megabytes: 5.97,
        width: 3072,
        height: 5472,
        primary: "#14639a",
        secondary: "#6cccd9",
        tertiary: "#51647f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f4f3d7",
        hex_5: "#19d2e0",
        hex_6: "#769f44",
        hex_7: "#b1eae8",
        hex_8: "#dbc890",
        hex_9: "#a6adb5"
      },
      {
        original_file_name: "Lush Tropical Beach  (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6539510,
        file_size_megabytes: 6.24,
        width: 3072,
        height: 5472,
        primary: "#daeedf",
        secondary: "#406536",
        tertiary: "#13a7c7",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#50ebe9",
        hex_5: "#78adab",
        hex_6: "#0f6b7d",
        hex_7: "#095272",
        hex_8: "#166ccf",
        hex_9: "#c0dc4c"
      },
      {
        original_file_name: "Lush Tropical Beach  (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6722050,
        file_size_megabytes: 6.41,
        width: 3072,
        height: 5472,
        primary: "#e0eee4",
        secondary: "#266047",
        tertiary: "#1fa7df",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#39eae8",
        hex_5: "#73b0b7",
        hex_6: "#1a8381",
        hex_7: "#0c509f",
        hex_8: "#0966d0",
        hex_9: "#bcce53"
      }
    ]
  },
  "Moonlit Bamboo Grove": {
    environment_title: "Moonlit Bamboo Grove",
    images: [
      {
        original_file_name: "Moonlit Bamboo Grove (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9005585,
        file_size_megabytes: 8.59,
        width: 3072,
        height: 5472,
        primary: "#0a1e36",
        secondary: "#48c0c9",
        tertiary: "#23648b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#bbd5d0",
        hex_5: "#2a7abe",
        hex_6: "#143f66",
        hex_7: "#1c6c6b",
        hex_8: "#5e473e",
        hex_9: "#179d84"
      },
      {
        original_file_name: "Moonlit Bamboo Grove (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7623958,
        file_size_megabytes: 7.27,
        width: 3072,
        height: 5472,
        primary: "#c6d2d0",
        secondary: "#4477c6",
        tertiary: "#0a1a33",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#68b6ed",
        hex_5: "#2f558d",
        hex_6: "#193767",
        hex_7: "#5b665b",
        hex_8: "#5a473c",
        hex_9: "#254045"
      },
      {
        original_file_name: "Moonlit Bamboo Grove (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8092519,
        file_size_megabytes: 7.72,
        width: 3072,
        height: 5472,
        primary: "#c5cbbf",
        secondary: "#0c1e35",
        tertiary: "#3273c7",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#25528e",
        hex_5: "#53b5de",
        hex_6: "#153865",
        hex_7: "#5e4649",
        hex_8: "#50705b",
        hex_9: "#244a41"
      },
      {
        original_file_name: "Moonlit Bamboo Grove (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7857816,
        file_size_megabytes: 7.49,
        width: 3072,
        height: 5472,
        primary: "#0f2334",
        secondary: "#d6cba1",
        tertiary: "#3c74c6",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#284f8d",
        hex_5: "#57a7f0",
        hex_6: "#183866",
        hex_7: "#5d442e",
        hex_8: "#5f7047",
        hex_9: "#9b5d2f"
      }
    ]
  },
  "Mystical Moonlit Grove": {
    environment_title: "Mystical Moonlit Grove",
    images: [
      {
        original_file_name: "Mystical Moonlit Grove (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7761460,
        file_size_megabytes: 7.4,
        width: 3072,
        height: 5472,
        primary: "#54beef",
        secondary: "#0b2244",
        tertiary: "#2879ca",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#b0d3d4",
        hex_5: "#26558d",
        hex_6: "#050715",
        hex_7: "#254865",
        hex_8: "#544f55",
        hex_9: "#5c6f62"
      },
      {
        original_file_name: "Mystical Moonlit Grove (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7563867,
        file_size_megabytes: 7.21,
        width: 3072,
        height: 5472,
        primary: "#41c0d6",
        secondary: "#c3eaf0",
        tertiary: "#2477bf",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#06162b",
        hex_5: "#185485",
        hex_6: "#136b58",
        hex_7: "#0d375e",
        hex_8: "#0b4441",
        hex_9: "#494d57"
      },
      {
        original_file_name: "Mystical Moonlit Grove (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7572161,
        file_size_megabytes: 7.22,
        width: 3072,
        height: 5472,
        primary: "#08192f",
        secondary: "#bbebf0",
        tertiary: "#50bfe6",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#2e7ac4",
        hex_5: "#1c5384",
        hex_6: "#0f3660",
        hex_7: "#20695d",
        hex_8: "#2ca06f",
        hex_9: "#505162"
      },
      {
        original_file_name: "Mystical Moonlit Grove (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7066871,
        file_size_megabytes: 6.74,
        width: 3072,
        height: 5472,
        primary: "#071a2f",
        secondary: "#bdebf0",
        tertiary: "#3177c6",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4abaea",
        hex_5: "#255586",
        hex_6: "#11365f",
        hex_7: "#226561",
        hex_8: "#4f505d",
        hex_9: "#1ca471"
      }
    ]
  },
  "Neon Cyberpunk Garden": {
    environment_title: "Neon Cyberpunk Garden",
    images: [
      {
        original_file_name: "Neon Cyberpunk Garden (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7945345,
        file_size_megabytes: 7.58,
        width: 3072,
        height: 5472,
        primary: "#cda5df",
        secondary: "#0a1827",
        tertiary: "#4fb0cf",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3866bd",
        hex_5: "#2b4386",
        hex_6: "#142c5e",
        hex_7: "#1d6a45",
        hex_8: "#a92d66",
        hex_9: "#5e2c4e"
      },
      {
        original_file_name: "Neon Cyberpunk Garden (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8091269,
        file_size_megabytes: 7.72,
        width: 3072,
        height: 5472,
        primary: "#c89b90",
        secondary: "#151628",
        tertiary: "#41c5e2",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#2570b8",
        hex_5: "#1e497c",
        hex_6: "#663037",
        hex_7: "#152b55",
        hex_8: "#9c3046",
        hex_9: "#5b6347"
      },
      {
        original_file_name: "Neon Cyberpunk Garden (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7438520,
        file_size_megabytes: 7.09,
        width: 3072,
        height: 5472,
        primary: "#d2aa9f",
        secondary: "#11111f",
        tertiary: "#334277",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5abae7",
        hex_5: "#3c68ba",
        hex_6: "#693c35",
        hex_7: "#b6314f",
        hex_8: "#1b264f",
        hex_9: "#345b3d"
      },
      {
        original_file_name: "Neon Cyberpunk Garden (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8242200,
        file_size_megabytes: 7.86,
        width: 3072,
        height: 5472,
        primary: "#c6a2d6",
        secondary: "#0f1829",
        tertiary: "#314e85",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#57bac1",
        hex_5: "#3f61b7",
        hex_6: "#1b315e",
        hex_7: "#9b3bb2",
        hex_8: "#316a51",
        hex_9: "#58305b"
      }
    ]
  },
  "Serene Lotus Pond": {
    environment_title: "Serene Lotus Pond",
    images: [
      {
        original_file_name: "Serene Lotus Pond (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7547270,
        file_size_megabytes: 7.2,
        width: 3072,
        height: 5472,
        primary: "#c9e26b",
        secondary: "#16332d",
        tertiary: "#7abf76",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#578d53",
        hex_5: "#20597c",
        hex_6: "#3b87ae",
        hex_7: "#69582f",
        hex_8: "#2e6538",
        hex_9: "#bf5656"
      },
      {
        original_file_name: "Serene Lotus Pond (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7360459,
        file_size_megabytes: 7.02,
        width: 3072,
        height: 5472,
        primary: "#c9ed98",
        secondary: "#74cc93",
        tertiary: "#0e2e32",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4a8c5e",
        hex_5: "#2a88bd",
        hex_6: "#1c5d82",
        hex_7: "#206649",
        hex_8: "#5f5d4b",
        hex_9: "#bf4e44"
      },
      {
        original_file_name: "Serene Lotus Pond (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7834847,
        file_size_megabytes: 7.47,
        width: 3072,
        height: 5472,
        primary: "#d4ee94",
        secondary: "#73ccaf",
        tertiary: "#11312f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#568e5b",
        hex_5: "#3a8dbe",
        hex_6: "#19537b",
        hex_7: "#34653a",
        hex_8: "#686450",
        hex_9: "#ca5ca4"
      },
      {
        original_file_name: "Serene Lotus Pond (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7285818,
        file_size_megabytes: 6.95,
        width: 3072,
        height: 5472,
        primary: "#d1e697",
        secondary: "#74c78e",
        tertiary: "#11262b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#548e55",
        hex_5: "#4087c8",
        hex_6: "#2a613b",
        hex_7: "#23527d",
        hex_8: "#686126",
        hex_9: "#b85e6b"
      }
    ]
  },
  "Starflower Meadow": {
    environment_title: "Starflower Meadow",
    images: [
      {
        original_file_name: "Starflower Meadow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7092026,
        file_size_megabytes: 6.76,
        width: 3072,
        height: 5472,
        primary: "#d7a195",
        secondary: "#102557",
        tertiary: "#2a6cc9",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1a2116",
        hex_5: "#61466b",
        hex_6: "#41b2f5",
        hex_7: "#124499",
        hex_8: "#5c6e95",
        hex_9: "#9b4062"
      },
      {
        original_file_name: "Starflower Meadow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7450810,
        file_size_megabytes: 7.11,
        width: 3072,
        height: 5472,
        primary: "#0e304e",
        secondary: "#c99ca8",
        tertiary: "#215693",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#2b79d3",
        hex_5: "#42b8e0",
        hex_6: "#2a7566",
        hex_7: "#071b14",
        hex_8: "#5d3f5e",
        hex_9: "#9d3b66"
      },
      {
        original_file_name: "Starflower Meadow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7927027,
        file_size_megabytes: 7.56,
        width: 3072,
        height: 5472,
        primary: "#d89375",
        secondary: "#122020",
        tertiary: "#273a7e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3164c0",
        hex_5: "#172759",
        hex_6: "#6a3e39",
        hex_7: "#54bff4",
        hex_8: "#706d4b",
        hex_9: "#a1384a"
      },
      {
        original_file_name: "Starflower Meadow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8059726,
        file_size_megabytes: 7.69,
        width: 3072,
        height: 5472,
        primary: "#d5938e",
        secondary: "#102824",
        tertiary: "#3970d2",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#344887",
        hex_5: "#6dabdf",
        hex_6: "#6c4645",
        hex_7: "#142f60",
        hex_8: "#5c7645",
        hex_9: "#a1395a"
      }
    ]
  },
  "Sunlit Cherry Grove": {
    environment_title: "Sunlit Cherry Grove",
    images: [
      {
        original_file_name: "Sunlit Cherry Grove (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8384500,
        file_size_megabytes: 8.0,
        width: 3072,
        height: 5472,
        primary: "#90d5dd",
        secondary: "#e8d9cb",
        tertiary: "#314141",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5489ce",
        hex_5: "#9f7578",
        hex_6: "#425e94",
        hex_7: "#6d947b",
        hex_8: "#714b54",
        hex_9: "#d76074"
      },
      {
        original_file_name: "Sunlit Cherry Grove (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8593572,
        file_size_megabytes: 8.2,
        width: 3072,
        height: 5472,
        primary: "#e2cbbd",
        secondary: "#26474a",
        tertiary: "#7cd1cb",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#448dd0",
        hex_5: "#8e6f6a",
        hex_6: "#ce4a7b",
        hex_7: "#336496",
        hex_8: "#4d9180",
        hex_9: "#221325"
      },
      {
        original_file_name: "Sunlit Cherry Grove (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8601024,
        file_size_megabytes: 8.2,
        width: 3072,
        height: 5472,
        primary: "#283a52",
        secondary: "#e2d1cf",
        tertiary: "#697692",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#803649",
        hex_5: "#8c8232",
        hex_6: "#bf627d",
        hex_7: "#c3a371",
        hex_8: "#ce89a9",
        hex_9: "#41a4eb"
      },
      {
        original_file_name: "Sunlit Cherry Grove (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8372887,
        file_size_megabytes: 7.99,
        width: 3072,
        height: 5472,
        primary: "#214661",
        secondary: "#6399b5",
        tertiary: "#ebd5da",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#743555",
        hex_5: "#8b923a",
        hex_6: "#cb7095",
        hex_7: "#c7bc7b",
        hex_8: "#a0c3db",
        hex_9: "#39b0d8"
      }
    ]
  },
  "Sunrise Over Mystic Mountains": {
    environment_title: "Sunrise Over Mystic Mountains",
    images: [
      {
        original_file_name: "Sunrise Over Mystic Mountains (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7242629,
        file_size_megabytes: 6.91,
        width: 3072,
        height: 5472,
        primary: "#e2b7a9",
        secondary: "#2e3c5e",
        tertiary: "#598fd1",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#151823",
        hex_5: "#8bb2df",
        hex_6: "#886c87",
        hex_7: "#47659d",
        hex_8: "#5d7faa",
        hex_9: "#bf4d4b"
      },
      {
        original_file_name: "Sunrise Over Mystic Mountains (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7625308,
        file_size_megabytes: 7.27,
        width: 3072,
        height: 5472,
        primary: "#ddb8b5",
        secondary: "#202836",
        tertiary: "#628bc6",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5a6995",
        hex_5: "#8fb4e0",
        hex_6: "#815f5e",
        hex_7: "#3d4e6f",
        hex_8: "#5c6d71",
        hex_9: "#bd4c38"
      },
      {
        original_file_name: "Sunrise Over Mystic Mountains (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7554662,
        file_size_megabytes: 7.2,
        width: 3072,
        height: 5472,
        primary: "#e4b3a2",
        secondary: "#26354d",
        tertiary: "#5b6794",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6586c2",
        hex_5: "#825266",
        hex_6: "#85aedf",
        hex_7: "#0e1111",
        hex_8: "#b74f53",
        hex_9: "#496f67"
      },
      {
        original_file_name: "Sunrise Over Mystic Mountains (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7402980,
        file_size_megabytes: 7.06,
        width: 3072,
        height: 5472,
        primary: "#deb3a1",
        secondary: "#2f3e5e",
        tertiary: "#5488c9",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#15171d",
        hex_5: "#7f5e75",
        hex_6: "#3460a3",
        hex_7: "#8cb1d5",
        hex_8: "#7c84a2",
        hex_9: "#af4f58"
      }
    ]
  },
  "Sunset Over Cherry Blossom Lake": {
    environment_title: "Sunset Over Cherry Blossom Lake",
    images: [
      {
        original_file_name: "Sunset Over Cherry Blossom Lake (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7675148,
        file_size_megabytes: 7.32,
        width: 3072,
        height: 5472,
        primary: "#eab6ab",
        secondary: "#252038",
        tertiary: "#7774c4",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#965864",
        hex_5: "#92b2eb",
        hex_6: "#4a4e86",
        hex_7: "#61323b",
        hex_8: "#ca433f",
        hex_9: "#6a6855"
      },
      {
        original_file_name: "Sunset Over Cherry Blossom Lake (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8227087,
        file_size_megabytes: 7.85,
        width: 3072,
        height: 5472,
        primary: "#232446",
        secondary: "#da9f8f",
        tertiary: "#6e2944",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#626898",
        hex_5: "#ad5c71",
        hex_6: "#fbeda4",
        hex_7: "#aa5a39",
        hex_8: "#c5c6e7",
        hex_9: "#3996e6"
      },
      {
        original_file_name: "Sunset Over Cherry Blossom Lake (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8262989,
        file_size_megabytes: 7.88,
        width: 3072,
        height: 5472,
        primary: "#262843",
        secondary: "#f6dfc3",
        tertiary: "#794d6b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#ea897e",
        hex_5: "#9a97cd",
        hex_6: "#ba5f6e",
        hex_7: "#b69598",
        hex_8: "#7b2223",
        hex_9: "#448cdc"
      },
      {
        original_file_name: "Sunset Over Cherry Blossom Lake (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8527746,
        file_size_megabytes: 8.13,
        width: 3072,
        height: 5472,
        primary: "#302f58",
        secondary: "#f1dab8",
        tertiary: "#6d4769",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#ec876f",
        hex_5: "#8c98d3",
        hex_6: "#b75b66",
        hex_7: "#b19096",
        hex_8: "#742b20",
        hex_9: "#449cd4"
      }
    ]
  },
  "Twilight Blossom Bridge": {
    environment_title: "Twilight Blossom Bridge",
    images: [
      {
        original_file_name: "Twilight Blossom Bridge (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7542124,
        file_size_megabytes: 7.19,
        width: 3072,
        height: 5472,
        primary: "#d79b83",
        secondary: "#251e2f",
        tertiary: "#4f71c0",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#824441",
        hex_5: "#75abf0",
        hex_6: "#2f4485",
        hex_7: "#2a355e",
        hex_8: "#b13b29",
        hex_9: "#5c6953"
      },
      {
        original_file_name: "Twilight Blossom Bridge (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7721995,
        file_size_megabytes: 7.36,
        width: 3072,
        height: 5472,
        primary: "#dc9fa2",
        secondary: "#2b253f",
        tertiary: "#4e6fbf",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#814d59",
        hex_5: "#334a85",
        hex_6: "#8f9fde",
        hex_7: "#c23937",
        hex_8: "#39170e",
        hex_9: "#576566"
      },
      {
        original_file_name: "Twilight Blossom Bridge (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7127936,
        file_size_megabytes: 6.8,
        width: 3072,
        height: 5472,
        primary: "#d7958f",
        secondary: "#2a2a4d",
        tertiary: "#485093",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#646dc1",
        hex_5: "#7e4a56",
        hex_6: "#2c1316",
        hex_7: "#b33642",
        hex_8: "#979ed3",
        hex_9: "#5f6561"
      },
      {
        original_file_name: "Twilight Blossom Bridge (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7811606,
        file_size_megabytes: 7.45,
        width: 3072,
        height: 5472,
        primary: "#e0a49f",
        secondary: "#2d2a47",
        tertiary: "#635c8b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7e4857",
        hex_5: "#6676b5",
        hex_6: "#2c1716",
        hex_7: "#b23d41",
        hex_8: "#8e9fc0",
        hex_9: "#626568"
      }
    ]
  },
  "Twinkling Firefly Meadow": {
    environment_title: "Twinkling Firefly Meadow",
    images: [
      {
        original_file_name: "Twinkling Firefly Meadow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7879992,
        file_size_megabytes: 7.51,
        width: 3072,
        height: 5472,
        primary: "#d2a18a",
        secondary: "#132227",
        tertiary: "#5b65b3",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#324077",
        hex_5: "#664825",
        hex_6: "#726c58",
        hex_7: "#38483b",
        hex_8: "#869cd5",
        hex_9: "#944418"
      },
      {
        original_file_name: "Twinkling Firefly Meadow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8237904,
        file_size_megabytes: 7.86,
        width: 3072,
        height: 5472,
        primary: "#bcb475",
        secondary: "#2256bc",
        tertiary: "#0f2225",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#19337b",
        hex_5: "#5d723d",
        hex_6: "#2c4c2d",
        hex_7: "#594d2c",
        hex_8: "#70a4a2",
        hex_9: "#97497a"
      },
      {
        original_file_name: "Twinkling Firefly Meadow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7687441,
        file_size_megabytes: 7.33,
        width: 3072,
        height: 5472,
        primary: "#ce9887",
        secondary: "#0f2023",
        tertiary: "#245fbd",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#2b3a79",
        hex_5: "#4eb9f3",
        hex_6: "#61412b",
        hex_7: "#596d5e",
        hex_8: "#a43668",
        hex_9: "#254938"
      },
      {
        original_file_name: "Twinkling Firefly Meadow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7634030,
        file_size_megabytes: 7.28,
        width: 3072,
        height: 5472,
        primary: "#dda983",
        secondary: "#3764c7",
        tertiary: "#172223",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#724d50",
        hex_5: "#2d3a75",
        hex_6: "#b54469",
        hex_7: "#84a1cd",
        hex_8: "#374a30",
        hex_9: "#496863"
      }
    ]
  },
  "Winter Blossom Haven": {
    environment_title: "Winter Blossom Haven",
    images: [
      {
        original_file_name: "Winter Blossom Haven (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8964535,
        file_size_megabytes: 8.55,
        width: 3072,
        height: 5472,
        primary: "#5c87cd",
        secondary: "#282b24",
        tertiary: "#9fcde9",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e9d9e6",
        hex_5: "#3e455a",
        hex_6: "#a68ba9",
        hex_7: "#d45e91",
        hex_8: "#2f3486",
        hex_9: "#daad60"
      },
      {
        original_file_name: "Winter Blossom Haven (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9186562,
        file_size_megabytes: 8.76,
        width: 3072,
        height: 5472,
        primary: "#292a30",
        secondary: "#6c92da",
        tertiary: "#e7dce4",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a4caeb",
        hex_5: "#987675",
        hex_6: "#3c5c95",
        hex_7: "#608390",
        hex_8: "#dda44e",
        hex_9: "#d0524c"
      },
      {
        original_file_name: "Winter Blossom Haven (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8869364,
        file_size_megabytes: 8.46,
        width: 3072,
        height: 5472,
        primary: "#e4d2d6",
        secondary: "#4272de",
        tertiary: "#1d1b30",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4b5892",
        hex_5: "#94aee3",
        hex_6: "#7c5054",
        hex_7: "#273566",
        hex_8: "#b75572",
        hex_9: "#536866"
      },
      {
        original_file_name: "Winter Blossom Haven (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9333899,
        file_size_megabytes: 8.9,
        width: 3072,
        height: 5472,
        primary: "#1a2a37",
        secondary: "#648fc9",
        tertiary: "#95973d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e5d7e7",
        hex_5: "#663a61",
        hex_6: "#b670a9",
        hex_7: "#96b8e2",
        hex_8: "#c7b98c",
        hex_9: "#3b95ef"
      }
    ]
  },
  "Winter Night Sky": {
    environment_title: "Winter Night Sky",
    images: [
      {
        original_file_name: "Winter Night Sky (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7194480,
        file_size_megabytes: 6.86,
        width: 3072,
        height: 5472,
        primary: "#47c8dd",
        secondary: "#bdccda",
        tertiary: "#3070ce",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#071335",
        hex_5: "#1c4a96",
        hex_6: "#103170",
        hex_7: "#156f67",
        hex_8: "#5f4156",
        hex_9: "#955b61"
      },
      {
        original_file_name: "Winter Night Sky (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7825925,
        file_size_megabytes: 7.46,
        width: 3072,
        height: 5472,
        primary: "#d091b3",
        secondary: "#142c5b",
        tertiary: "#2cddc9",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3076c3",
        hex_5: "#0a0c1f",
        hex_6: "#235ca4",
        hex_7: "#34809e",
        hex_8: "#66547d",
        hex_9: "#c03774"
      },
      {
        original_file_name: "Winter Night Sky (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6948866,
        file_size_megabytes: 6.63,
        width: 3072,
        height: 5472,
        primary: "#0b2753",
        secondary: "#caa1a3",
        tertiary: "#17d1b7",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1462b8",
        hex_5: "#0a0a18",
        hex_6: "#13509d",
        hex_7: "#0e837b",
        hex_8: "#644d6a",
        hex_9: "#8c4c5a"
      },
      {
        original_file_name: "Winter Night Sky (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7450337,
        file_size_megabytes: 7.11,
        width: 3072,
        height: 5472,
        primary: "#d2c2ad",
        secondary: "#2373d4",
        tertiary: "#0c2449",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#38d8bd",
        hex_5: "#1d5497",
        hex_6: "#1c7364",
        hex_7: "#614551",
        hex_8: "#9e5549",
        hex_9: "#070917"
      }
    ]
  }
};
export default AnimeLandscapes;
