import { EnvironmentEntry } from "@/types/database";
const AntiqueLookObject: Record<string, EnvironmentEntry> = {
  "Ancient Book And Quill": {
    environment_title: "Ancient Book And Quill",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Ancient Book And Quill (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6762532,
        file_size_megabytes: 6.45,
        width: 3072,
        height: 5472,
        primary: "#cea071",
        secondary: "#82563d",
        tertiary: "#120604",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4b1f10",
        hex_5: "#9b8c6f",
        hex_6: "#998075",
        hex_7: "#5b4c3c",
        hex_8: "#a44227",
        hex_9: "#59433c"
      },
      {
        original_file_name: "Ancient Book And Quill (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7091454,
        file_size_megabytes: 6.76,
        width: 3072,
        height: 5472,
        primary: "#cb9b67",
        secondary: "#1a0b06",
        tertiary: "#7f5936",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e2c15",
        hex_5: "#a94106",
        hex_6: "#908470",
        hex_7: "#897a6c",
        hex_8: "#5b4d38",
        hex_9: "#54423c"
      },
      {
        original_file_name: "Ancient Book And Quill (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7647556,
        file_size_megabytes: 7.29,
        width: 3072,
        height: 5472,
        primary: "#d19e63",
        secondary: "#180a06",
        tertiary: "#81532c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e2811",
        hex_5: "#947c6c",
        hex_6: "#5b4c39",
        hex_7: "#a55404",
        hex_8: "#55423c",
        hex_9: "#9c8c74"
      },
      {
        original_file_name: "Ancient Book And Quill (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6663538,
        file_size_megabytes: 6.35,
        width: 3072,
        height: 5472,
        primary: "#c89e72",
        secondary: "#170805",
        tertiary: "#754b2d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#462110",
        hex_5: "#927c5c",
        hex_6: "#aa3c0b",
        hex_7: "#927364",
        hex_8: "#514530",
        hex_9: "#513b34"
      }
    ]
  },
  "Antique Lantern And Old Books": {
    environment_title: "Antique Lantern And Old Books",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Antique Lantern And Old Books (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7174781,
        file_size_megabytes: 6.84,
        width: 3072,
        height: 5472,
        primary: "#d89f66",
        secondary: "#1d0c07",
        tertiary: "#774021",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4d230f",
        hex_5: "#ac3708",
        hex_6: "#908e80",
        hex_7: "#545043",
        hex_8: "#8c837c",
        hex_9: "#3c4045"
      },
      {
        original_file_name: "Antique Lantern And Old Books (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6773075,
        file_size_megabytes: 6.46,
        width: 3072,
        height: 5472,
        primary: "#ca8d54",
        secondary: "#1b0c06",
        tertiary: "#764323",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e2812",
        hex_5: "#a43506",
        hex_6: "#5a4c37",
        hex_7: "#948c6e",
        hex_8: "#8c8484",
        hex_9: "#564444"
      },
      {
        original_file_name: "Antique Lantern And Old Books (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6885115,
        file_size_megabytes: 6.57,
        width: 3072,
        height: 5472,
        primary: "#dba163",
        secondary: "#200d07",
        tertiary: "#7e441e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#56280f",
        hex_5: "#5a503c",
        hex_6: "#988e76",
        hex_7: "#a74307",
        hex_8: "#908474",
        hex_9: "#44433c"
      },
      {
        original_file_name: "Antique Lantern And Old Books (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6986444,
        file_size_megabytes: 6.66,
        width: 3072,
        height: 5472,
        primary: "#c88f55",
        secondary: "#1b0b06",
        tertiary: "#79431f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e240e",
        hex_5: "#554e36",
        hex_6: "#9c3b10",
        hex_7: "#8c8c64",
        hex_8: "#94847c",
        hex_9: "#444444"
      }
    ]
  },
  "Antique Phonograph And Vinyl Records": {
    environment_title: "Antique Phonograph And Vinyl Records",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Antique Phonograph And Vinyl Records (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6998764,
        file_size_megabytes: 6.67,
        width: 3072,
        height: 5472,
        primary: "#ce9b66",
        secondary: "#1e0d08",
        tertiary: "#7a4b2b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4c2914",
        hex_5: "#a0410a",
        hex_6: "#928d76",
        hex_7: "#574d3d",
        hex_8: "#90847c",
        hex_9: "#4c4344"
      },
      {
        original_file_name: "Antique Phonograph And Vinyl Records (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7140090,
        file_size_megabytes: 6.81,
        width: 3072,
        height: 5472,
        primary: "#d5a05d",
        secondary: "#22120c",
        tertiary: "#7e4e2b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#553018",
        hex_5: "#595855",
        hex_6: "#49494f",
        hex_7: "#969482",
        hex_8: "#a54308",
        hex_9: "#818488"
      },
      {
        original_file_name: "Antique Phonograph And Vinyl Records (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7574558,
        file_size_megabytes: 7.22,
        width: 3072,
        height: 5472,
        primary: "#cf9253",
        secondary: "#200e0a",
        tertiary: "#794321",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e2711",
        hex_5: "#a53706",
        hex_6: "#574e3e",
        hex_7: "#948e74",
        hex_8: "#474145",
        hex_9: "#90847c"
      },
      {
        original_file_name: "Antique Phonograph And Vinyl Records (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7278386,
        file_size_megabytes: 6.94,
        width: 3072,
        height: 5472,
        primary: "#cb8e44",
        secondary: "#160b0a",
        tertiary: "#703e1b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#462613",
        hex_5: "#99380a",
        hex_6: "#4c4e3d",
        hex_7: "#7f7b70",
        hex_8: "#44413c",
        hex_9: "#8c8c68"
      }
    ]
  },
  "Antique Scarf And Perfume Bottles": {
    environment_title: "Antique Scarf And Perfume Bottles",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Antique Scarf And Perfume Bottles (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7500617,
        file_size_megabytes: 7.15,
        width: 3072,
        height: 5472,
        primary: "#bf9970",
        secondary: "#19100b",
        tertiary: "#795231",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e2e19",
        hex_5: "#5e9f97",
        hex_6: "#446056",
        hex_7: "#568582",
        hex_8: "#2e4647",
        hex_9: "#9c4c0e"
      },
      {
        original_file_name: "Antique Scarf And Perfume Bottles (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8173630,
        file_size_megabytes: 7.79,
        width: 3072,
        height: 5472,
        primary: "#b19173",
        secondary: "#58a6a4",
        tertiary: "#634330",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#0c0c0c",
        hex_5: "#115d62",
        hex_6: "#2e8186",
        hex_7: "#361a12",
        hex_8: "#093e49",
        hex_9: "#92380e"
      },
      {
        original_file_name: "Antique Scarf And Perfume Bottles (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7218655,
        file_size_megabytes: 6.88,
        width: 3072,
        height: 5472,
        primary: "#cea782",
        secondary: "#180c08",
        tertiary: "#825533",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#512d18",
        hex_5: "#5f4f40",
        hex_6: "#a9460c",
        hex_7: "#9a8d79",
        hex_8: "#8c848c",
        hex_9: "#4c444c"
      },
      {
        original_file_name: "Antique Scarf And Perfume Bottles (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7712437,
        file_size_megabytes: 7.36,
        width: 3072,
        height: 5472,
        primary: "#c19469",
        secondary: "#1a0f0d",
        tertiary: "#7a4c30",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4f2916",
        hex_5: "#62959c",
        hex_6: "#4c7f89",
        hex_7: "#346269",
        hex_8: "#1a4751",
        hex_9: "#9d3a12"
      }
    ]
  },
  "Antique Typewriter And Letters": {
    environment_title: "Antique Typewriter And Letters",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Antique Typewriter And Letters (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6979590,
        file_size_megabytes: 6.66,
        width: 3072,
        height: 5472,
        primary: "#eab47a",
        secondary: "#190b06",
        tertiary: "#7d4423",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#ad4b14",
        hex_5: "#4f2512",
        hex_6: "#978e7c",
        hex_7: "#594d3e",
        hex_8: "#8c807d",
        hex_9: "#4f4444"
      },
      {
        original_file_name: "Antique Typewriter And Letters (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8075112,
        file_size_megabytes: 7.7,
        width: 3072,
        height: 5472,
        primary: "#dcb888",
        secondary: "#20130b",
        tertiary: "#8c5e3d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#633a20",
        hex_5: "#6e6049",
        hex_6: "#b52e1b",
        hex_7: "#a29c7b",
        hex_8: "#62524c",
        hex_9: "#a2928c"
      },
      {
        original_file_name: "Antique Typewriter And Letters (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7151605,
        file_size_megabytes: 6.82,
        width: 3072,
        height: 5472,
        primary: "#ebc080",
        secondary: "#190a06",
        tertiary: "#7a4520",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4f250e",
        hex_5: "#a85520",
        hex_6: "#998c75",
        hex_7: "#584d37",
        hex_8: "#95847c",
        hex_9: "#4c4444"
      },
      {
        original_file_name: "Antique Typewriter And Letters (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7724534,
        file_size_megabytes: 7.37,
        width: 3072,
        height: 5472,
        primary: "#e0b077",
        secondary: "#1e0d08",
        tertiary: "#7f4521",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#b14510",
        hex_5: "#56260f",
        hex_6: "#5d4f3c",
        hex_7: "#9b8e77",
        hex_8: "#4f4444",
        hex_9: "#948484"
      }
    ]
  },
  "Candlelit Clock Tower": {
    environment_title: "Candlelit Clock Tower",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Candlelit Clock Tower (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7538330,
        file_size_megabytes: 7.19,
        width: 3072,
        height: 5472,
        primary: "#b66b33",
        secondary: "#120d15",
        tertiary: "#65371d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#bcbeba",
        hex_5: "#7b8993",
        hex_6: "#65768e",
        hex_7: "#3d4d60",
        hex_8: "#2d3241",
        hex_9: "#424c45"
      },
      {
        original_file_name: "Candlelit Clock Tower (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6597193,
        file_size_megabytes: 6.29,
        width: 3072,
        height: 5472,
        primary: "#ab5922",
        secondary: "#0a0e1c",
        tertiary: "#e5dfbf",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5a240d",
        hex_5: "#705135",
        hex_6: "#666c71",
        hex_7: "#7c8f98",
        hex_8: "#12213e",
        hex_9: "#728298"
      },
      {
        original_file_name: "Candlelit Clock Tower (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6329956,
        file_size_megabytes: 6.04,
        width: 3072,
        height: 5472,
        primary: "#ba6121",
        secondary: "#0c111b",
        tertiary: "#633222",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f1e2b3",
        hex_5: "#341d1a",
        hex_6: "#3c3444",
        hex_7: "#847c78",
        hex_8: "#84746c",
        hex_9: "#444443"
      },
      {
        original_file_name: "Candlelit Clock Tower (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6169905,
        file_size_megabytes: 5.88,
        width: 3072,
        height: 5472,
        primary: "#b47134",
        secondary: "#090d19",
        tertiary: "#5f2d10",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e4cd89",
        hex_5: "#6dadc8",
        hex_6: "#6f5236",
        hex_7: "#4e6771",
        hex_8: "#273241",
        hex_9: "#477d9b"
      }
    ]
  },
  "Classic Car Under Streetlights": {
    environment_title: "Classic Car Under Streetlights",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Classic Car Under Streetlights (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6768883,
        file_size_megabytes: 6.46,
        width: 3072,
        height: 5472,
        primary: "#b5a997",
        secondary: "#111010",
        tertiary: "#614b38",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#719daf",
        hex_5: "#345765",
        hex_6: "#20353d",
        hex_7: "#527d91",
        hex_8: "#214255",
        hex_9: "#8c5428"
      },
      {
        original_file_name: "Classic Car Under Streetlights (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6954520,
        file_size_megabytes: 6.63,
        width: 3072,
        height: 5472,
        primary: "#b16e2b",
        secondary: "#100c0d",
        tertiary: "#684424",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e9dcae",
        hex_5: "#3c2616",
        hex_6: "#659fb1",
        hex_7: "#2b596a",
        hex_8: "#417a93",
        hex_9: "#103c53"
      },
      {
        original_file_name: "Classic Car Under Streetlights (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7336777,
        file_size_megabytes: 7.0,
        width: 3072,
        height: 5472,
        primary: "#cf9751",
        secondary: "#120c0d",
        tertiary: "#6b3d17",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3d210f",
        hex_5: "#56a2b7",
        hex_6: "#16556b",
        hex_7: "#2d7896",
        hex_8: "#153c54",
        hex_9: "#974304"
      },
      {
        original_file_name: "Classic Car Under Streetlights (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6089845,
        file_size_megabytes: 5.81,
        width: 3072,
        height: 5472,
        primary: "#bc9c76",
        secondary: "#100d0e",
        tertiary: "#67462a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4ba2ae",
        hex_5: "#3d2616",
        hex_6: "#225e67",
        hex_7: "#337f8f",
        hex_8: "#17404f",
        hex_9: "#8d4c1e"
      }
    ]
  },
  "Classic Film Projector": {
    environment_title: "Classic Film Projector",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Classic Film Projector (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6100912,
        file_size_megabytes: 5.82,
        width: 3072,
        height: 5472,
        primary: "#c6b9a8",
        secondary: "#110a08",
        tertiary: "#6a5b4f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3c281c",
        hex_5: "#898f88",
        hex_6: "#7d8185",
        hex_7: "#4a4d48",
        hex_8: "#985328",
        hex_9: "#444245"
      },
      {
        original_file_name: "Classic Film Projector (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6104394,
        file_size_megabytes: 5.82,
        width: 3072,
        height: 5472,
        primary: "#c4a375",
        secondary: "#654125",
        tertiary: "#0c0809",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#352014",
        hex_5: "#4cadc3",
        hex_6: "#8f410a",
        hex_7: "#1b364e",
        hex_8: "#336f8e",
        hex_9: "#295365"
      },
      {
        original_file_name: "Classic Film Projector (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6159534,
        file_size_megabytes: 5.87,
        width: 3072,
        height: 5472,
        primary: "#bda585",
        secondary: "#100907",
        tertiary: "#695844",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3d2a1c",
        hex_5: "#1b3753",
        hex_6: "#3e4c53",
        hex_7: "#848c80",
        hex_8: "#7f8184",
        hex_9: "#8c4c20"
      },
      {
        original_file_name: "Classic Film Projector (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6161820,
        file_size_megabytes: 5.88,
        width: 3072,
        height: 5472,
        primary: "#c7a98b",
        secondary: "#120808",
        tertiary: "#7797a4",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#674937",
        hex_5: "#3b4f5d",
        hex_6: "#5a778a",
        hex_7: "#3d1f14",
        hex_8: "#9b4714",
        hex_9: "#2b3947"
      }
    ]
  },
  "Classic Motorcycle Helmet And Gloves": {
    environment_title: "Classic Motorcycle Helmet And Gloves",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Classic Motorcycle Helmet And Gloves (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6470943,
        file_size_megabytes: 6.17,
        width: 3072,
        height: 5472,
        primary: "#c19e81",
        secondary: "#150e0b",
        tertiary: "#755844",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7c98a5",
        hex_5: "#46565a",
        hex_6: "#453225",
        hex_7: "#607d91",
        hex_8: "#2c4050",
        hex_9: "#95421a"
      },
      {
        original_file_name: "Classic Motorcycle Helmet And Gloves (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6985475,
        file_size_megabytes: 6.66,
        width: 3072,
        height: 5472,
        primary: "#ca9f7b",
        secondary: "#170f0c",
        tertiary: "#805c44",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#85a6a4",
        hex_5: "#506462",
        hex_6: "#513525",
        hex_7: "#66898e",
        hex_8: "#3b494d",
        hex_9: "#a44c10"
      },
      {
        original_file_name: "Classic Motorcycle Helmet And Gloves (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6598230,
        file_size_megabytes: 6.29,
        width: 3072,
        height: 5472,
        primary: "#cb9665",
        secondary: "#190e0d",
        tertiary: "#764e33",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4d2b17",
        hex_5: "#859896",
        hex_6: "#50544f",
        hex_7: "#3c444c",
        hex_8: "#6c848c",
        hex_9: "#9c3c14"
      },
      {
        original_file_name: "Classic Motorcycle Helmet And Gloves (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7173185,
        file_size_megabytes: 6.84,
        width: 3072,
        height: 5472,
        primary: "#bd9f85",
        secondary: "#180e0b",
        tertiary: "#6f4933",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#472516",
        hex_5: "#819394",
        hex_6: "#4a5556",
        hex_7: "#72848c",
        hex_8: "#9a3e09",
        hex_9: "#3a434c"
      }
    ]
  },
  "Classic Sailboat Model And Nautical Charts": {
    environment_title: "Classic Sailboat Model And Nautical Charts",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Classic Sailboat Model And Nautical Charts (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8622651,
        file_size_megabytes: 8.22,
        width: 3072,
        height: 5472,
        primary: "#24140f",
        secondary: "#978268",
        tertiary: "#512e18",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e3decc",
        hex_5: "#dcc2a0",
        hex_6: "#595244",
        hex_7: "#724a26",
        hex_8: "#b7b3a3",
        hex_9: "#c7c4af"
      },
      {
        original_file_name: "Classic Sailboat Model And Nautical Charts (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7643221,
        file_size_megabytes: 7.29,
        width: 3072,
        height: 5472,
        primary: "#d2b691",
        secondary: "#283136",
        tertiary: "#877969",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5e4d3f",
        hex_5: "#a1a499",
        hex_6: "#58686e",
        hex_7: "#687676",
        hex_8: "#999b9c",
        hex_9: "#ad6c3f"
      },
      {
        original_file_name: "Classic Sailboat Model And Nautical Charts (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8161886,
        file_size_megabytes: 7.78,
        width: 3072,
        height: 5472,
        primary: "#dbc39b",
        secondary: "#2a2827",
        tertiary: "#927e63",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a1aa99",
        hex_5: "#607977",
        hex_6: "#654d37",
        hex_7: "#6c98a6",
        hex_8: "#3b5e6f",
        hex_9: "#b56440"
      },
      {
        original_file_name: "Classic Sailboat Model And Nautical Charts (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8279734,
        file_size_megabytes: 7.9,
        width: 3072,
        height: 5472,
        primary: "#d8af87",
        secondary: "#292d30",
        tertiary: "#97826e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#596973",
        hex_5: "#738183",
        hex_6: "#6a5648",
        hex_7: "#9ca19d",
        hex_8: "#a7aca2",
        hex_9: "#b46434"
      }
    ]
  },
  "Elegant Teapot And Saucers": {
    environment_title: "Elegant Teapot And Saucers",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Elegant Teapot And Saucers (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6009956,
        file_size_megabytes: 5.73,
        width: 3072,
        height: 5472,
        primary: "#ccc3b5",
        secondary: "#190d0b",
        tertiary: "#805a3e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#979a95",
        hex_5: "#51311d",
        hex_6: "#5a5853",
        hex_7: "#a85823",
        hex_8: "#414751",
        hex_9: "#8a8b8c"
      },
      {
        original_file_name: "Elegant Teapot And Saucers (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6472977,
        file_size_megabytes: 6.17,
        width: 3072,
        height: 5472,
        primary: "#ccc8bf",
        secondary: "#22140e",
        tertiary: "#7b6d61",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#969996",
        hex_5: "#5d5a56",
        hex_6: "#543d2e",
        hex_7: "#87898d",
        hex_8: "#4b494e",
        hex_9: "#a46c46"
      },
      {
        original_file_name: "Elegant Teapot And Saucers (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6333295,
        file_size_megabytes: 6.04,
        width: 3072,
        height: 5472,
        primary: "#d1bea9",
        secondary: "#817161",
        tertiary: "#170e09",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#9d9b92",
        hex_5: "#5e5950",
        hex_6: "#503a28",
        hex_7: "#7c878f",
        hex_8: "#48474f",
        hex_9: "#ac643c"
      },
      {
        original_file_name: "Elegant Teapot And Saucers (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5646294,
        file_size_megabytes: 5.38,
        width: 3072,
        height: 5472,
        primary: "#cac6bf",
        secondary: "#939b9f",
        tertiary: "#170f0c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#796d63",
        hex_5: "#818590",
        hex_6: "#5a5f5e",
        hex_7: "#4d2f20",
        hex_8: "#494a4d",
        hex_9: "#a45b2a"
      }
    ]
  },
  "Elegant Wine Glass And Bottle": {
    environment_title: "Elegant Wine Glass And Bottle",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Elegant Wine Glass And Bottle (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5516545,
        file_size_megabytes: 5.26,
        width: 3072,
        height: 5472,
        primary: "#d9ad88",
        secondary: "#140909",
        tertiary: "#6c3f36",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#461d18",
        hex_5: "#4e5153",
        hex_6: "#878e8b",
        hex_7: "#9d3d3f",
        hex_8: "#7d828c",
        hex_9: "#42434c"
      },
      {
        original_file_name: "Elegant Wine Glass And Bottle (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5392960,
        file_size_megabytes: 5.14,
        width: 3072,
        height: 5472,
        primary: "#d5c4b1",
        secondary: "#190e0b",
        tertiary: "#745d4f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#90908b",
        hex_5: "#54524d",
        hex_6: "#4c2618",
        hex_7: "#868384",
        hex_8: "#a43a3c",
        hex_9: "#474244"
      },
      {
        original_file_name: "Elegant Wine Glass And Bottle (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6151564,
        file_size_megabytes: 5.87,
        width: 3072,
        height: 5472,
        primary: "#dbc5a1",
        secondary: "#7b654f",
        tertiary: "#1a0b07",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#978f6a",
        hex_5: "#575147",
        hex_6: "#7d7f89",
        hex_7: "#4c3222",
        hex_8: "#4a4146",
        hex_9: "#b0101e"
      },
      {
        original_file_name: "Elegant Wine Glass And Bottle (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4933399,
        file_size_megabytes: 4.7,
        width: 3072,
        height: 5472,
        primary: "#cfc7ba",
        secondary: "#100807",
        tertiary: "#695c4e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8a8575",
        hex_5: "#3a2723",
        hex_6: "#484632",
        hex_7: "#ba1215",
        hex_8: "#847c84",
        hex_9: "#4c3c44"
      }
    ]
  },
  "Grand Piano In Concert Hall": {
    environment_title: "Grand Piano In Concert Hall",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Grand Piano In Concert Hall (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6898396,
        file_size_megabytes: 6.58,
        width: 3072,
        height: 5472,
        primary: "#ccb7a1",
        secondary: "#1c100d",
        tertiary: "#75553b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8d918d",
        hex_5: "#4f311d",
        hex_6: "#565a59",
        hex_7: "#44474e",
        hex_8: "#77838e",
        hex_9: "#9d511a"
      },
      {
        original_file_name: "Grand Piano In Concert Hall (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7291752,
        file_size_megabytes: 6.95,
        width: 3072,
        height: 5472,
        primary: "#d3af8e",
        secondary: "#20110b",
        tertiary: "#7a5539",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4d301e",
        hex_5: "#938c7f",
        hex_6: "#af4d17",
        hex_7: "#8e847c",
        hex_8: "#5a564c",
        hex_9: "#524a44"
      },
      {
        original_file_name: "Grand Piano In Concert Hall (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7533606,
        file_size_megabytes: 7.18,
        width: 3072,
        height: 5472,
        primary: "#d8cbbb",
        secondary: "#1d120e",
        tertiary: "#7a604d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#919ea5",
        hex_5: "#778692",
        hex_6: "#535d63",
        hex_7: "#4e3624",
        hex_8: "#414850",
        hex_9: "#be541c"
      },
      {
        original_file_name: "Grand Piano In Concert Hall (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7614789,
        file_size_megabytes: 7.26,
        width: 3072,
        height: 5472,
        primary: "#ddb895",
        secondary: "#22120e",
        tertiary: "#804d2c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8aa7b9",
        hex_5: "#562e17",
        hex_6: "#4f5f6c",
        hex_7: "#678095",
        hex_8: "#3c4651",
        hex_9: "#a85121"
      }
    ]
  },
  "Old Compass And Maps": {
    environment_title: "Old Compass And Maps",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Old Compass And Maps (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8314286,
        file_size_megabytes: 7.93,
        width: 3072,
        height: 5472,
        primary: "#d7aa7c",
        secondary: "#8f6c48",
        tertiary: "#1d0e07",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a59876",
        hex_5: "#593a20",
        hex_6: "#665a40",
        hex_7: "#9c8976",
        hex_8: "#40413c",
        hex_9: "#b45454"
      },
      {
        original_file_name: "Old Compass And Maps (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8291551,
        file_size_megabytes: 7.91,
        width: 3072,
        height: 5472,
        primary: "#d4ac7a",
        secondary: "#502d14",
        tertiary: "#966f46",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#0f0706",
        hex_5: "#706b52",
        hex_6: "#a59f83",
        hex_7: "#5e594d",
        hex_8: "#989384",
        hex_9: "#b47444"
      },
      {
        original_file_name: "Old Compass And Maps (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8230959,
        file_size_megabytes: 7.85,
        width: 3072,
        height: 5472,
        primary: "#dcaa6c",
        secondary: "#87592d",
        tertiary: "#170805",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#532b0f",
        hex_5: "#a28d6a",
        hex_6: "#624d32",
        hex_7: "#ac6429",
        hex_8: "#998074",
        hex_9: "#5c433c"
      },
      {
        original_file_name: "Old Compass And Maps (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8591017,
        file_size_megabytes: 8.19,
        width: 3072,
        height: 5472,
        primary: "#daa160",
        secondary: "#9b6a37",
        tertiary: "#221007",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6a3c18",
        hex_5: "#ac9868",
        hex_6: "#745c35",
        hex_7: "#bd6c30",
        hex_8: "#a0887c",
        hex_9: "#4d4846"
      }
    ]
  },
  "Old Map And Navigation Tools": {
    environment_title: "Old Map And Navigation Tools",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Old Map And Navigation Tools (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8005440,
        file_size_megabytes: 7.63,
        width: 3072,
        height: 5472,
        primary: "#d8b381",
        secondary: "#86613b",
        tertiary: "#140a06",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#523318",
        hex_5: "#a28d6a",
        hex_6: "#614d31",
        hex_7: "#ac6426",
        hex_8: "#59443c",
        hex_9: "#94847c"
      },
      {
        original_file_name: "Old Map And Navigation Tools (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8188645,
        file_size_megabytes: 7.81,
        width: 3072,
        height: 5472,
        primary: "#c29969",
        secondary: "#201209",
        tertiary: "#916b43",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#603f20",
        hex_5: "#705738",
        hex_6: "#a49470",
        hex_7: "#554c4c",
        hex_8: "#8c8c8c",
        hex_9: "#ac643c"
      },
      {
        original_file_name: "Old Map And Navigation Tools (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8862591,
        file_size_megabytes: 8.45,
        width: 3072,
        height: 5472,
        primary: "#d1995a",
        secondary: "#946332",
        tertiary: "#211007",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#623b19",
        hex_5: "#705531",
        hex_6: "#aa9671",
        hex_7: "#a0866d",
        hex_8: "#b4642c",
        hex_9: "#473f34"
      },
      {
        original_file_name: "Old Map And Navigation Tools (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8426304,
        file_size_megabytes: 8.04,
        width: 3072,
        height: 5472,
        primary: "#d09e63",
        secondary: "#886236",
        tertiary: "#1c0e07",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5a3a1a",
        hex_5: "#695531",
        hex_6: "#a29677",
        hex_7: "#ad4c16",
        hex_8: "#9c8c7c",
        hex_9: "#604c44"
      }
    ]
  },
  "Rustic Fishing Rod And Tackle Box": {
    environment_title: "Rustic Fishing Rod And Tackle Box",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Rustic Fishing Rod And Tackle Box (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8483003,
        file_size_megabytes: 8.09,
        width: 3072,
        height: 5472,
        primary: "#c9a57d",
        secondary: "#1b120d",
        tertiary: "#815e41",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#553622",
        hex_5: "#8f9f8d",
        hex_6: "#585b4e",
        hex_7: "#c92929",
        hex_8: "#6b8193",
        hex_9: "#454850"
      },
      {
        original_file_name: "Rustic Fishing Rod And Tackle Box (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8473687,
        file_size_megabytes: 8.08,
        width: 3072,
        height: 5472,
        primary: "#c69d71",
        secondary: "#1f120b",
        tertiary: "#7e5a3a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4c311d",
        hex_5: "#83a176",
        hex_6: "#515c49",
        hex_7: "#c3190c",
        hex_8: "#3e4451",
        hex_9: "#6b809b"
      },
      {
        original_file_name: "Rustic Fishing Rod And Tackle Box (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9005003,
        file_size_megabytes: 8.59,
        width: 3072,
        height: 5472,
        primary: "#c8986e",
        secondary: "#1f160e",
        tertiary: "#7f5b40",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#78ac98",
        hex_5: "#563925",
        hex_6: "#4b674f",
        hex_7: "#cb0e0c",
        hex_8: "#4e4f50",
        hex_9: "#77898d"
      },
      {
        original_file_name: "Rustic Fishing Rod And Tackle Box (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8488784,
        file_size_megabytes: 8.1,
        width: 3072,
        height: 5472,
        primary: "#caa579",
        secondary: "#2c2416",
        tertiary: "#866544",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#606a3d",
        hex_5: "#5b442a",
        hex_6: "#d52629",
        hex_7: "#8ba69b",
        hex_8: "#617da0",
        hex_9: "#3d4f5f"
      }
    ]
  },
  "Rustic Lantern In Fog": {
    environment_title: "Rustic Lantern In Fog",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Rustic Lantern In Fog (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6501595,
        file_size_megabytes: 6.2,
        width: 3072,
        height: 5472,
        primary: "#c28151",
        secondary: "#141413",
        tertiary: "#63676a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4c565f",
        hex_5: "#443a38",
        hex_6: "#2e383f",
        hex_7: "#7a8488",
        hex_8: "#747c8c",
        hex_9: "#4c5446"
      },
      {
        original_file_name: "Rustic Lantern In Fog (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6464455,
        file_size_megabytes: 6.16,
        width: 3072,
        height: 5472,
        primary: "#17191a",
        secondary: "#d39756",
        tertiary: "#384958",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#704027",
        hex_5: "#46271b",
        hex_6: "#896c56",
        hex_7: "#4a5d74",
        hex_8: "#4d443e",
        hex_9: "#943c0c"
      },
      {
        original_file_name: "Rustic Lantern In Fog (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6400731,
        file_size_megabytes: 6.1,
        width: 3072,
        height: 5472,
        primary: "#666b70",
        secondary: "#c68f5a",
        tertiary: "#111210",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4f5c65",
        hex_5: "#788794",
        hex_6: "#2f383c",
        hex_7: "#3f4a55",
        hex_8: "#413936",
        hex_9: "#84949c"
      },
      {
        original_file_name: "Rustic Lantern In Fog (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6807691,
        file_size_megabytes: 6.49,
        width: 3072,
        height: 5472,
        primary: "#171818",
        secondary: "#d19c67",
        tertiary: "#718392",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#675f5d",
        hex_5: "#425059",
        hex_6: "#4f5e67",
        hex_7: "#8396a3",
        hex_8: "#403c3c",
        hex_9: "#323e45"
      }
    ]
  },
  "Vintage Camera On Wooden Table": {
    environment_title: "Vintage Camera On Wooden Table",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Vintage Camera On Wooden Table (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7176056,
        file_size_megabytes: 6.84,
        width: 3072,
        height: 5472,
        primary: "#27160c",
        secondary: "#c6ad95",
        tertiary: "#846046",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#53331e",
        hex_5: "#989588",
        hex_6: "#615e53",
        hex_7: "#57524d",
        hex_8: "#a45c33",
        hex_9: "#928c8c"
      },
      {
        original_file_name: "Vintage Camera On Wooden Table (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7062758,
        file_size_megabytes: 6.74,
        width: 3072,
        height: 5472,
        primary: "#be9878",
        secondary: "#1d110f",
        tertiary: "#855f44",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5b3720",
        hex_5: "#969891",
        hex_6: "#5f5e59",
        hex_7: "#45494d",
        hex_8: "#8a8b8c",
        hex_9: "#a45c2e"
      },
      {
        original_file_name: "Vintage Camera On Wooden Table (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7227983,
        file_size_megabytes: 6.89,
        width: 3072,
        height: 5472,
        primary: "#29170d",
        secondary: "#bfa991",
        tertiary: "#7e5a3c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5d371b",
        hex_5: "#64635a",
        hex_6: "#98958b",
        hex_7: "#514f4e",
        hex_8: "#42403a",
        hex_9: "#908c8c"
      },
      {
        original_file_name: "Vintage Camera On Wooden Table (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7375154,
        file_size_megabytes: 7.03,
        width: 3072,
        height: 5472,
        primary: "#bc8f6e",
        secondary: "#23130c",
        tertiary: "#815334",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#929d9d",
        hex_5: "#586160",
        hex_6: "#56321b",
        hex_7: "#7f8a8d",
        hex_8: "#43494e",
        hex_9: "#a44c10"
      }
    ]
  },
  "Vintage Sewing Machine And Fabric Rolls": {
    environment_title: "Vintage Sewing Machine And Fabric Rolls",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Vintage Sewing Machine And Fabric Rolls (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7908873,
        file_size_megabytes: 7.54,
        width: 3072,
        height: 5472,
        primary: "#d19066",
        secondary: "#190f10",
        tertiary: "#54a5a1",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#78402d",
        hex_5: "#315f61",
        hex_6: "#c1252e",
        hex_7: "#4e2115",
        hex_8: "#27808f",
        hex_9: "#263f50"
      },
      {
        original_file_name: "Vintage Sewing Machine And Fabric Rolls (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8246982,
        file_size_megabytes: 7.86,
        width: 3072,
        height: 5472,
        primary: "#c76c44",
        secondary: "#1d1115",
        tertiary: "#5ba192",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#813325",
        hex_5: "#d4d4a6",
        hex_6: "#335c5a",
        hex_7: "#561d16",
        hex_8: "#247e8e",
        hex_9: "#213e57"
      },
      {
        original_file_name: "Vintage Sewing Machine And Fabric Rolls (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7922351,
        file_size_megabytes: 7.56,
        width: 3072,
        height: 5472,
        primary: "#dfaa7a",
        secondary: "#281915",
        tertiary: "#954933",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#78ada6",
        hex_5: "#4e726a",
        hex_6: "#6b3320",
        hex_7: "#3e8b9a",
        hex_8: "#cc3027",
        hex_9: "#1e4e61"
      },
      {
        original_file_name: "Vintage Sewing Machine And Fabric Rolls (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8545363,
        file_size_megabytes: 8.15,
        width: 3072,
        height: 5472,
        primary: "#c6562d",
        secondary: "#141218",
        tertiary: "#753021",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#64998d",
        hex_5: "#e0cfa9",
        hex_6: "#471b15",
        hex_7: "#1f6067",
        hex_8: "#0b445c",
        hex_9: "#227793"
      }
    ]
  },
  "Vintage Typewriter And Ink Bottles": {
    environment_title: "Vintage Typewriter And Ink Bottles",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Vintage Typewriter And Ink Bottles (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7415359,
        file_size_megabytes: 7.07,
        width: 3072,
        height: 5472,
        primary: "#e7c696",
        secondary: "#180e09",
        tertiary: "#85573a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#9c937c",
        hex_5: "#595341",
        hex_6: "#502b18",
        hex_7: "#ac592d",
        hex_8: "#4b4244",
        hex_9: "#948484"
      },
      {
        original_file_name: "Vintage Typewriter And Ink Bottles (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7026299,
        file_size_megabytes: 6.7,
        width: 3072,
        height: 5472,
        primary: "#e7c492",
        secondary: "#170c07",
        tertiary: "#7a4a2a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e2d17",
        hex_5: "#b64929",
        hex_6: "#998e75",
        hex_7: "#594e3b",
        hex_8: "#90827c",
        hex_9: "#4e4344"
      },
      {
        original_file_name: "Vintage Typewriter And Ink Bottles (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7255038,
        file_size_megabytes: 6.92,
        width: 3072,
        height: 5472,
        primary: "#b07344",
        secondary: "#160c0b",
        tertiary: "#724323",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f3ebcb",
        hex_5: "#472613",
        hex_6: "#524d40",
        hex_7: "#8c8c78",
        hex_8: "#8c848c",
        hex_9: "#4c444c"
      },
      {
        original_file_name: "Vintage Typewriter And Ink Bottles (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6359588,
        file_size_megabytes: 6.06,
        width: 3072,
        height: 5472,
        primary: "#e4cca1",
        secondary: "#1a100a",
        tertiary: "#845b3a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#503118",
        hex_5: "#999681",
        hex_6: "#5e5847",
        hex_7: "#a65a29",
        hex_8: "#8e8984",
        hex_9: "#504c4c"
      }
    ]
  }
};
export default AntiqueLookObject;
