import { EnvironmentEntry } from "@/types/database";
const CosmicAndLightning: Record<string, EnvironmentEntry> = {
  "Black Hole Lightning Vortex": {
    environment_title: "Black Hole Lightning Vortex",
    images: [
      {
        original_file_name: "Black Hole Lightning Vortex  (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5964748,
        file_size_megabytes: 5.69,
        width: 3072,
        height: 5472,
        primary: "#d89f5e",
        secondary: "#141315",
        tertiary: "#6e412c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#452d26",
        hex_5: "#9a400f",
        hex_6: "#6e8195",
        hex_7: "#495b6b",
        hex_8: "#3b4758",
        hex_9: "#829aad"
      },
      {
        original_file_name: "Black Hole Lightning Vortex  (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5572146,
        file_size_megabytes: 5.31,
        width: 3072,
        height: 5472,
        primary: "#deb46b",
        secondary: "#0e1015",
        tertiary: "#495a6d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5f301f",
        hex_5: "#7697b2",
        hex_6: "#a03f13",
        hex_7: "#2d3744",
        hex_8: "#617e99",
        hex_9: "#3e4c53"
      },
      {
        original_file_name: "Black Hole Lightning Vortex  (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5946564,
        file_size_megabytes: 5.67,
        width: 3072,
        height: 5472,
        primary: "#c3a99d",
        secondary: "#0f0f16",
        tertiary: "#5c5a6b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5b3a39",
        hex_5: "#2a3344",
        hex_6: "#9f3d09",
        hex_7: "#808fa2",
        hex_8: "#788095",
        hex_9: "#404c54"
      },
      {
        original_file_name: "Black Hole Lightning Vortex  (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6139435,
        file_size_megabytes: 5.86,
        width: 3072,
        height: 5472,
        primary: "#d5a569",
        secondary: "#14141c",
        tertiary: "#68433a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#647da1",
        hex_5: "#7ea0c7",
        hex_6: "#445974",
        hex_7: "#2c384a",
        hex_8: "#9d3d10",
        hex_9: "#364760"
      }
    ]
  },
  "Black Hole With Lightning Rings": {
    environment_title: "Black Hole With Lightning Rings",
    images: [
      {
        original_file_name: "Black Hole With Lightning Rings (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6188549,
        file_size_megabytes: 5.9,
        width: 3072,
        height: 5472,
        primary: "#d6b892",
        secondary: "#111115",
        tertiary: "#695451",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3c2f31",
        hex_5: "#424f5b",
        hex_6: "#849199",
        hex_7: "#95513d",
        hex_8: "#6f8194",
        hex_9: "#4c544c"
      },
      {
        original_file_name: "Black Hole With Lightning Rings (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6173222,
        file_size_megabytes: 5.89,
        width: 3072,
        height: 5472,
        primary: "#d5a362",
        secondary: "#101014",
        tertiary: "#6a4230",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3d2722",
        hex_5: "#9c3d0c",
        hex_6: "#8391a2",
        hex_7: "#6e7b92",
        hex_8: "#3b4658",
        hex_9: "#47576a"
      },
      {
        original_file_name: "Black Hole With Lightning Rings (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6892574,
        file_size_megabytes: 6.57,
        width: 3072,
        height: 5472,
        primary: "#dfb371",
        secondary: "#181215",
        tertiary: "#6f3d29",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7b9aa6",
        hex_5: "#9e4416",
        hex_6: "#45251b",
        hex_7: "#495d68",
        hex_8: "#658090",
        hex_9: "#3c4a56"
      },
      {
        original_file_name: "Black Hole With Lightning Rings (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6104795,
        file_size_megabytes: 5.82,
        width: 3072,
        height: 5472,
        primary: "#ca9f80",
        secondary: "#131219",
        tertiary: "#56596b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#663a31",
        hex_5: "#2f3544",
        hex_6: "#7e90ab",
        hex_7: "#944025",
        hex_8: "#6b799d",
        hex_9: "#445454"
      }
    ]
  },
  "Comet With Lightning Tail": {
    environment_title: "Comet With Lightning Tail",
    images: [
      {
        original_file_name: "Comet With Lightning Tail (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5557006,
        file_size_megabytes: 5.3,
        width: 3072,
        height: 5472,
        primary: "#bea187",
        secondary: "#080f20",
        tertiary: "#294a6c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#629ec7",
        hex_5: "#4172a2",
        hex_6: "#553428",
        hex_7: "#0d2c4a",
        hex_8: "#8d4013",
        hex_9: "#70574f"
      },
      {
        original_file_name: "Comet With Lightning Tail (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5765007,
        file_size_megabytes: 5.5,
        width: 3072,
        height: 5472,
        primary: "#c9b7aa",
        secondary: "#0b111e",
        tertiary: "#455a73",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7199ba",
        hex_5: "#5c4847",
        hex_6: "#1d364c",
        hex_7: "#507ba2",
        hex_8: "#90533d",
        hex_9: "#41545c"
      },
      {
        original_file_name: "Comet With Lightning Tail (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5912164,
        file_size_megabytes: 5.64,
        width: 3072,
        height: 5472,
        primary: "#c1aeb2",
        secondary: "#12141d",
        tertiary: "#6a6674",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#787e9d",
        hex_5: "#584344",
        hex_6: "#484e62",
        hex_7: "#373e4b",
        hex_8: "#8c5c4c",
        hex_9: "#8494a9"
      },
      {
        original_file_name: "Comet With Lightning Tail (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5859719,
        file_size_megabytes: 5.59,
        width: 3072,
        height: 5472,
        primary: "#c6aaa3",
        secondary: "#101521",
        tertiary: "#4e5974",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5c4142",
        hex_5: "#647fa7",
        hex_6: "#29364b",
        hex_7: "#7b9ac2",
        hex_8: "#7d5c56",
        hex_9: "#954521"
      }
    ]
  },
  "Electric Aurora In Space": {
    environment_title: "Electric Aurora In Space",
    images: [
      {
        original_file_name: "Electric Aurora In Space (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6996388,
        file_size_megabytes: 6.67,
        width: 3072,
        height: 5472,
        primary: "#c4a8cb",
        secondary: "#191b29",
        tertiary: "#42be82",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#56547b",
        hex_5: "#6471ac",
        hex_6: "#683e56",
        hex_7: "#333954",
        hex_8: "#266d48",
        hex_9: "#954b76"
      },
      {
        original_file_name: "Electric Aurora In Space (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6547798,
        file_size_megabytes: 6.24,
        width: 3072,
        height: 5472,
        primary: "#bda2b3",
        secondary: "#1b1e2a",
        tertiary: "#49b67f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5e5a7a",
        hex_5: "#653c53",
        hex_6: "#383d53",
        hex_7: "#1c6c54",
        hex_8: "#7b7aa2",
        hex_9: "#94446c"
      },
      {
        original_file_name: "Electric Aurora In Space (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6313850,
        file_size_megabytes: 6.02,
        width: 3072,
        height: 5472,
        primary: "#b6aba2",
        secondary: "#40c480",
        tertiary: "#141925",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#70445c",
        hex_5: "#266d5c",
        hex_6: "#432535",
        hex_7: "#11496f",
        hex_8: "#233a51",
        hex_9: "#657f94"
      },
      {
        original_file_name: "Electric Aurora In Space (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6937104,
        file_size_megabytes: 6.62,
        width: 3072,
        height: 5472,
        primary: "#ceaebb",
        secondary: "#4ac68f",
        tertiary: "#141823",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#525874",
        hex_5: "#673149",
        hex_6: "#a14164",
        hex_7: "#2a354b",
        hex_8: "#5f7da5",
        hex_9: "#236b46"
      }
    ]
  },
  "Electric Comet In Night Sky": {
    environment_title: "Electric Comet In Night Sky",
    images: [
      {
        original_file_name: "Electric Comet In Night Sky (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5807498,
        file_size_megabytes: 5.54,
        width: 3072,
        height: 5472,
        primary: "#c9b39c",
        secondary: "#0f151e",
        tertiary: "#3f5b74",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1b384c",
        hex_5: "#6e83a0",
        hex_6: "#5f4b41",
        hex_7: "#8095af",
        hex_8: "#6e6052",
        hex_9: "#8c5126"
      },
      {
        original_file_name: "Electric Comet In Night Sky (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6410009,
        file_size_megabytes: 6.11,
        width: 3072,
        height: 5472,
        primary: "#121a26",
        secondary: "#c1a193",
        tertiary: "#5aaada",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3d5c78",
        hex_5: "#5e382f",
        hex_6: "#327aae",
        hex_7: "#9a3809",
        hex_8: "#223e50",
        hex_9: "#785d58"
      },
      {
        original_file_name: "Electric Comet In Night Sky (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5529413,
        file_size_megabytes: 5.27,
        width: 3072,
        height: 5472,
        primary: "#b69a8f",
        secondary: "#071021",
        tertiary: "#535971",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#29364d",
        hex_5: "#504448",
        hex_6: "#6d574d",
        hex_7: "#737ea0",
        hex_8: "#7a8cad",
        hex_9: "#845c4c"
      },
      {
        original_file_name: "Electric Comet In Night Sky (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5863291,
        file_size_megabytes: 5.59,
        width: 3072,
        height: 5472,
        primary: "#b78b6b",
        secondary: "#0b1627",
        tertiary: "#5f4340",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#345c74",
        hex_5: "#72a4bb",
        hex_6: "#2a3e4e",
        hex_7: "#766151",
        hex_8: "#333c42",
        hex_9: "#56869f"
      }
    ]
  },
  "Electric Comet Tail A Dynamic Cosmic Pho": {
    environment_title: "Electric Comet Tail A Dynamic Cosmic Pho",
    images: [
      {
        original_file_name: "Electric Comet Tail A Dynamic Cosmic Pho (0).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6013549,
        file_size_megabytes: 5.73,
        width: 3072,
        height: 5472,
        primary: "#caa692",
        secondary: "#0d1321",
        tertiary: "#4c5b6a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5e4647",
        hex_5: "#25364d",
        hex_6: "#607ca0",
        hex_7: "#7c94ac",
        hex_8: "#445556",
        hex_9: "#8c441c"
      },
      {
        original_file_name: "Electric Comet Tail A Dynamic Cosmic Pho (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6111082,
        file_size_megabytes: 5.83,
        width: 3072,
        height: 5472,
        primary: "#c09d93",
        secondary: "#11111b",
        tertiary: "#635b76",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6a76a1",
        hex_5: "#424464",
        hex_6: "#292e45",
        hex_7: "#643b2c",
        hex_8: "#8294be",
        hex_9: "#8c440e"
      },
      {
        original_file_name: "Electric Comet Tail A Dynamic Cosmic Pho (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5796171,
        file_size_megabytes: 5.53,
        width: 3072,
        height: 5472,
        primary: "#bb9390",
        secondary: "#111624",
        tertiary: "#605e6f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5d3b3c",
        hex_5: "#2a3b52",
        hex_6: "#705f57",
        hex_7: "#923443",
        hex_8: "#7b729e",
        hex_9: "#7c94ac"
      },
      {
        original_file_name: "Electric Comet Tail A Dynamic Cosmic Pho (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5824324,
        file_size_megabytes: 5.55,
        width: 3072,
        height: 5472,
        primary: "#c2ab98",
        secondary: "#0e1520",
        tertiary: "#285075",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1c344d",
        hex_5: "#4076a7",
        hex_6: "#729dc0",
        hex_7: "#5a4137",
        hex_8: "#7c5f49",
        hex_9: "#3e3c3c"
      }
    ]
  },
  "Electric Nebula Burst An Abstract Cosmic": {
    environment_title: "Electric Nebula Burst An Abstract Cosmic",
    images: [
      {
        original_file_name: "Electric Nebula Burst An Abstract Cosmic (0).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7079225,
        file_size_megabytes: 6.75,
        width: 3072,
        height: 5472,
        primary: "#d78c83",
        secondary: "#202033",
        tertiary: "#81414e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6279aa",
        hex_5: "#6aaad8",
        hex_6: "#562a39",
        hex_7: "#3a5378",
        hex_8: "#aa393b",
        hex_9: "#225c63"
      },
      {
        original_file_name: "Electric Nebula Burst An Abstract Cosmic (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7056089,
        file_size_megabytes: 6.73,
        width: 3072,
        height: 5472,
        primary: "#d09eb8",
        secondary: "#201c2d",
        tertiary: "#7c5270",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#767cb1",
        hex_5: "#46567d",
        hex_6: "#8aa4d2",
        hex_7: "#553046",
        hex_8: "#a6433a",
        hex_9: "#4c5c64"
      },
      {
        original_file_name: "Electric Nebula Burst An Abstract Cosmic (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7262336,
        file_size_megabytes: 6.93,
        width: 3072,
        height: 5472,
        primary: "#d3949c",
        secondary: "#201b2e",
        tertiary: "#7f435f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6abcdd",
        hex_5: "#657db6",
        hex_6: "#41587f",
        hex_7: "#56293e",
        hex_8: "#ac3830",
        hex_9: "#455c63"
      },
      {
        original_file_name: "Electric Nebula Burst An Abstract Cosmic (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7088339,
        file_size_megabytes: 6.76,
        width: 3072,
        height: 5472,
        primary: "#d29ca5",
        secondary: "#201927",
        tertiary: "#4e5e7e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5485b3",
        hex_5: "#6baad7",
        hex_6: "#753c4a",
        hex_7: "#2f3d55",
        hex_8: "#a43f44",
        hex_9: "#485c5d"
      }
    ]
  },
  "Galactic Lightning Flash An Abstract Cos": {
    environment_title: "Galactic Lightning Flash An Abstract Cos",
    images: [
      {
        original_file_name: "Galactic Lightning Flash An Abstract Cos (0).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7130898,
        file_size_megabytes: 6.8,
        width: 3072,
        height: 5472,
        primary: "#d09da6",
        secondary: "#1d1723",
        tertiary: "#774650",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#69acc3",
        hex_5: "#7170b1",
        hex_6: "#445674",
        hex_7: "#4e2c38",
        hex_8: "#9f4133",
        hex_9: "#375c5b"
      },
      {
        original_file_name: "Galactic Lightning Flash An Abstract Cos (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7002269,
        file_size_megabytes: 6.68,
        width: 3072,
        height: 5472,
        primary: "#d0979a",
        secondary: "#181727",
        tertiary: "#72475b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#62b7d3",
        hex_5: "#637aa6",
        hex_6: "#345575",
        hex_7: "#2c3752",
        hex_8: "#a03a27",
        hex_9: "#44545c"
      },
      {
        original_file_name: "Galactic Lightning Flash An Abstract Cos (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7086850,
        file_size_megabytes: 6.76,
        width: 3072,
        height: 5472,
        primary: "#c7a0b3",
        secondary: "#191928",
        tertiary: "#754c5e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#72a8c7",
        hex_5: "#6775aa",
        hex_6: "#415476",
        hex_7: "#4d2e3a",
        hex_8: "#9e4144",
        hex_9: "#445c5c"
      },
      {
        original_file_name: "Galactic Lightning Flash An Abstract Cos (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7172083,
        file_size_megabytes: 6.84,
        width: 3072,
        height: 5472,
        primary: "#d0a6a8",
        secondary: "#1b1b29",
        tertiary: "#78515e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7ca2b0",
        hex_5: "#4d313d",
        hex_6: "#485b70",
        hex_7: "#7e80a2",
        hex_8: "#a34640",
        hex_9: "#3f5c5b"
      }
    ]
  },
  "Galactic Lightning Spiral An Artistic Po": {
    environment_title: "Galactic Lightning Spiral An Artistic Po",
    images: [
      {
        original_file_name: "Galactic Lightning Spiral An Artistic Po (0).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7253973,
        file_size_megabytes: 6.92,
        width: 3072,
        height: 5472,
        primary: "#cd9b74",
        secondary: "#121825",
        tertiary: "#775045",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#355574",
        hex_5: "#587aae",
        hex_6: "#69a3cb",
        hex_7: "#4c3131",
        hex_8: "#9e431a",
        hex_9: "#466055"
      },
      {
        original_file_name: "Galactic Lightning Spiral An Artistic Po (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7618966,
        file_size_megabytes: 7.27,
        width: 3072,
        height: 5472,
        primary: "#c99d9b",
        secondary: "#222029",
        tertiary: "#626883",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#764f51",
        hex_5: "#6c81b2",
        hex_6: "#3e475c",
        hex_7: "#82a3c1",
        hex_8: "#556469",
        hex_9: "#a44038"
      },
      {
        original_file_name: "Galactic Lightning Spiral An Artistic Po (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7696558,
        file_size_megabytes: 7.34,
        width: 3072,
        height: 5472,
        primary: "#cd9b90",
        secondary: "#1d1b26",
        tertiary: "#4d5d7f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5f7bb7",
        hex_5: "#76443b",
        hex_6: "#64b3d9",
        hex_7: "#303e56",
        hex_8: "#a14129",
        hex_9: "#446561"
      },
      {
        original_file_name: "Galactic Lightning Spiral An Artistic Po (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7670286,
        file_size_megabytes: 7.31,
        width: 3072,
        height: 5472,
        primary: "#cc9ea1",
        secondary: "#1a1d2a",
        tertiary: "#516384",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6f444d",
        hex_5: "#607db8",
        hex_6: "#6ab2d4",
        hex_7: "#2f445d",
        hex_8: "#3f6669",
        hex_9: "#a04130"
      }
    ]
  },
  "Lightning Filled Nebula": {
    environment_title: "Lightning Filled Nebula",
    images: [
      {
        original_file_name: "Lightning Filled Nebula (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7133377,
        file_size_megabytes: 6.8,
        width: 3072,
        height: 5472,
        primary: "#cc91a5",
        secondary: "#221a29",
        tertiary: "#784a63",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#413c53",
        hex_5: "#4a5c79",
        hex_6: "#797ca2",
        hex_7: "#789cbe",
        hex_8: "#a03943",
        hex_9: "#575c63"
      },
      {
        original_file_name: "Lightning Filled Nebula (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7075412,
        file_size_megabytes: 6.75,
        width: 3072,
        height: 5472,
        primary: "#ce93a9",
        secondary: "#1c1827",
        tertiary: "#77425a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#607aa9",
        hex_5: "#345377",
        hex_6: "#74a2ce",
        hex_7: "#4e2739",
        hex_8: "#a1393f",
        hex_9: "#4c5c5c"
      },
      {
        original_file_name: "Lightning Filled Nebula (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6937328,
        file_size_megabytes: 6.62,
        width: 3072,
        height: 5472,
        primary: "#c98ea2",
        secondary: "#191826",
        tertiary: "#764557",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5b78b1",
        hex_5: "#6ba8e2",
        hex_6: "#3d5175",
        hex_7: "#4e2d3d",
        hex_8: "#a23844",
        hex_9: "#3e545a"
      },
      {
        original_file_name: "Lightning Filled Nebula (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7269487,
        file_size_megabytes: 6.93,
        width: 3072,
        height: 5472,
        primary: "#ca9ead",
        secondary: "#241927",
        tertiary: "#5a5a7f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#757cae",
        hex_5: "#74394a",
        hex_6: "#323956",
        hex_7: "#7ea0c8",
        hex_8: "#a23e39",
        hex_9: "#475c61"
      }
    ]
  },
  "Lightning Fueled Nebula Burst": {
    environment_title: "Lightning Fueled Nebula Burst",
    images: [
      {
        original_file_name: "Lightning Fueled Nebula Burst (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7196306,
        file_size_megabytes: 6.86,
        width: 3072,
        height: 5472,
        primary: "#d0a1a1",
        secondary: "#1a1c2a",
        tertiary: "#774853",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#75abcc",
        hex_5: "#3d5974",
        hex_6: "#6382a4",
        hex_7: "#4d2e37",
        hex_8: "#a43f2d",
        hex_9: "#585c5c"
      },
      {
        original_file_name: "Lightning Fueled Nebula Burst (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7122037,
        file_size_megabytes: 6.79,
        width: 3072,
        height: 5472,
        primary: "#d19cab",
        secondary: "#1c1b29",
        tertiary: "#764b5d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3b5473",
        hex_5: "#6278a9",
        hex_6: "#4d2e3c",
        hex_7: "#75a2d6",
        hex_8: "#a53e37",
        hex_9: "#2f5e59"
      },
      {
        original_file_name: "Lightning Fueled Nebula Burst (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7007818,
        file_size_megabytes: 6.68,
        width: 3072,
        height: 5472,
        primary: "#d29fa7",
        secondary: "#1c1a27",
        tertiary: "#764755",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6878af",
        hex_5: "#435176",
        hex_6: "#80a1d8",
        hex_7: "#4e2e39",
        hex_8: "#a3402f",
        hex_9: "#575458"
      },
      {
        original_file_name: "Lightning Fueled Nebula Burst (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6907036,
        file_size_megabytes: 6.59,
        width: 3072,
        height: 5472,
        primary: "#d3a7a2",
        secondary: "#1c1c2a",
        tertiary: "#754f5b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4a5570",
        hex_5: "#4d2f39",
        hex_6: "#839eb1",
        hex_7: "#7d7ca3",
        hex_8: "#a6452c",
        hex_9: "#485c5c"
      }
    ]
  },
  "Lightning In The Andromeda Galaxy": {
    environment_title: "Lightning In The Andromeda Galaxy",
    images: [
      {
        original_file_name: "Lightning In The Andromeda Galaxy (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7274537,
        file_size_megabytes: 6.94,
        width: 3072,
        height: 5472,
        primary: "#c19ea7",
        secondary: "#1c1d28",
        tertiary: "#626e7e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#46546b",
        hex_5: "#6f83a4",
        hex_6: "#6a424c",
        hex_7: "#2a4755",
        hex_8: "#80a3c5",
        hex_9: "#964140"
      },
      {
        original_file_name: "Lightning In The Andromeda Galaxy (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7065440,
        file_size_megabytes: 6.74,
        width: 3072,
        height: 5472,
        primary: "#c3a6b0",
        secondary: "#1b1d29",
        tertiary: "#765f6d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4a5471",
        hex_5: "#7781a3",
        hex_6: "#849cbf",
        hex_7: "#4c3a45",
        hex_8: "#52545a",
        hex_9: "#9c4c48"
      },
      {
        original_file_name: "Lightning In The Andromeda Galaxy (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7096244,
        file_size_megabytes: 6.77,
        width: 3072,
        height: 5472,
        primary: "#c29b97",
        secondary: "#1d1920",
        tertiary: "#4f5875",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6e4437",
        hex_5: "#6c7ba8",
        hex_6: "#2e384c",
        hex_7: "#7e9bc3",
        hex_8: "#9b400d",
        hex_9: "#50545a"
      },
      {
        original_file_name: "Lightning In The Andromeda Galaxy (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6635310,
        file_size_megabytes: 6.33,
        width: 3072,
        height: 5472,
        primary: "#c2a7ae",
        secondary: "#11141d",
        tertiary: "#525d79",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6a7ea5",
        hex_5: "#664543",
        hex_6: "#8497bc",
        hex_7: "#2d3a4d",
        hex_8: "#964937",
        hex_9: "#47545b"
      }
    ]
  },
  "Lightning Over Alien Planet": {
    environment_title: "Lightning Over Alien Planet",
    images: [
      {
        original_file_name: "Lightning Over Alien Planet (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8074014,
        file_size_megabytes: 7.7,
        width: 3072,
        height: 5472,
        primary: "#d19a98",
        secondary: "#241623",
        tertiary: "#80484c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#562b2f",
        hex_5: "#504b6e",
        hex_6: "#8d83a3",
        hex_7: "#9995b2",
        hex_8: "#ad3f1c",
        hex_9: "#64545a"
      },
      {
        original_file_name: "Lightning Over Alien Planet (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7171610,
        file_size_megabytes: 6.84,
        width: 3072,
        height: 5472,
        primary: "#d29c99",
        secondary: "#1c1625",
        tertiary: "#794a56",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4d2e38",
        hex_5: "#4e4f68",
        hex_6: "#a1412a",
        hex_7: "#8e819d",
        hex_8: "#9494a4",
        hex_9: "#50545c"
      },
      {
        original_file_name: "Lightning Over Alien Planet (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7529124,
        file_size_megabytes: 7.18,
        width: 3072,
        height: 5472,
        primary: "#cdadba",
        secondary: "#1d1726",
        tertiary: "#745366",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#424f75",
        hex_5: "#757ca3",
        hex_6: "#7f9ec3",
        hex_7: "#4c2930",
        hex_8: "#a04835",
        hex_9: "#5a545a"
      },
      {
        original_file_name: "Lightning Over Alien Planet (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7507594,
        file_size_megabytes: 7.16,
        width: 3072,
        height: 5472,
        primary: "#d1a1a8",
        secondary: "#191220",
        tertiary: "#6e424f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#462834",
        hex_5: "#7b759d",
        hex_6: "#464968",
        hex_7: "#9c3e22",
        hex_8: "#888eae",
        hex_9: "#504c54"
      }
    ]
  },
  "Lightning Over Saturns Rings": {
    environment_title: "Lightning Over Saturns Rings",
    images: [
      {
        original_file_name: "Lightning Over Saturns Rings (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6036545,
        file_size_megabytes: 5.76,
        width: 3072,
        height: 5472,
        primary: "#bea277",
        secondary: "#13171e",
        tertiary: "#706657",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5e4a3c",
        hex_5: "#423f3a",
        hex_6: "#5678a4",
        hex_7: "#789bbd",
        hex_8: "#2f4867",
        hex_9: "#8c5436"
      },
      {
        original_file_name: "Lightning Over Saturns Rings (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5780019,
        file_size_megabytes: 5.51,
        width: 3072,
        height: 5472,
        primary: "#d0a15e",
        secondary: "#171f28",
        tertiary: "#746f5d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#30455b",
        hex_5: "#664f2f",
        hex_6: "#39526e",
        hex_7: "#4b4737",
        hex_8: "#828d9e",
        hex_9: "#8b9ca7"
      },
      {
        original_file_name: "Lightning Over Saturns Rings (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5445102,
        file_size_megabytes: 5.19,
        width: 3072,
        height: 5472,
        primary: "#161617",
        secondary: "#cca56c",
        tertiary: "#6e543c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#453528",
        hex_5: "#888b8d",
        hex_6: "#4c5154",
        hex_7: "#8c9490",
        hex_8: "#535c5b",
        hex_9: "#945434"
      },
      {
        original_file_name: "Lightning Over Saturns Rings (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6068588,
        file_size_megabytes: 5.79,
        width: 3072,
        height: 5472,
        primary: "#d0a767",
        secondary: "#1a1719",
        tertiary: "#78583b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4d3929",
        hex_5: "#8f808e",
        hex_6: "#574c56",
        hex_7: "#9494a0",
        hex_8: "#9c5404",
        hex_9: "#595e54"
      }
    ]
  },
  "Lightning Rings Around Star": {
    environment_title: "Lightning Rings Around Star",
    images: [
      {
        original_file_name: "Lightning Rings Around Star (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6966928,
        file_size_megabytes: 6.64,
        width: 3072,
        height: 5472,
        primary: "#ceb3a3",
        secondary: "#1b1920",
        tertiary: "#755f62",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4d3d40",
        hex_5: "#53556b",
        hex_6: "#8784a1",
        hex_7: "#8e97ab",
        hex_8: "#555c5b",
        hex_9: "#9c5434"
      },
      {
        original_file_name: "Lightning Rings Around Star (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6225396,
        file_size_megabytes: 5.94,
        width: 3072,
        height: 5472,
        primary: "#caa898",
        secondary: "#13131b",
        tertiary: "#6e524d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#463434",
        hex_5: "#857e99",
        hex_6: "#4f495e",
        hex_7: "#505562",
        hex_8: "#964c37",
        hex_9: "#8c94a4"
      },
      {
        original_file_name: "Lightning Rings Around Star (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6610825,
        file_size_megabytes: 6.3,
        width: 3072,
        height: 5472,
        primary: "#d1b7ca",
        secondary: "#1b1723",
        tertiary: "#745d6f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4c3946",
        hex_5: "#8680a3",
        hex_6: "#51506c",
        hex_7: "#9395ab",
        hex_8: "#5a5c5c",
        hex_9: "#9c5c54"
      },
      {
        original_file_name: "Lightning Rings Around Star (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6653027,
        file_size_megabytes: 6.34,
        width: 3072,
        height: 5472,
        primary: "#191a23",
        secondary: "#c9b9cd",
        tertiary: "#735c6b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7a7ea6",
        hex_5: "#4d5573",
        hex_6: "#8b9bc1",
        hex_7: "#4e3a40",
        hex_8: "#9c5c54",
        hex_9: "#5c5c5c"
      }
    ]
  },
  "Lightning Strike On A Distant Moon": {
    environment_title: "Lightning Strike On A Distant Moon",
    images: [
      {
        original_file_name: "Lightning Strike On A Distant Moon (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7450982,
        file_size_megabytes: 7.11,
        width: 3072,
        height: 5472,
        primary: "#d0a28c",
        secondary: "#151316",
        tertiary: "#704e45",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#452f2c",
        hex_5: "#51565a",
        hex_6: "#89979f",
        hex_7: "#848b94",
        hex_8: "#424c5c",
        hex_9: "#944424"
      },
      {
        original_file_name: "Lightning Strike On A Distant Moon (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6841286,
        file_size_megabytes: 6.52,
        width: 3072,
        height: 5472,
        primary: "#d5a17a",
        secondary: "#161316",
        tertiary: "#6e4635",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#44322c",
        hex_5: "#505554",
        hex_6: "#3e4b54",
        hex_7: "#944421",
        hex_8: "#8c8c8c",
        hex_9: "#8c948c"
      },
      {
        original_file_name: "Lightning Strike On A Distant Moon (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7533028,
        file_size_megabytes: 7.18,
        width: 3072,
        height: 5472,
        primary: "#17171d",
        secondary: "#cab3a7",
        tertiary: "#6b5f60",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#453b3b",
        hex_5: "#818699",
        hex_6: "#484d5f",
        hex_7: "#8b95a5",
        hex_8: "#535d6c",
        hex_9: "#945c44"
      },
      {
        original_file_name: "Lightning Strike On A Distant Moon (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6970183,
        file_size_megabytes: 6.65,
        width: 3072,
        height: 5472,
        primary: "#d6a387",
        secondary: "#17161a",
        tertiary: "#784b3c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e302a",
        hex_5: "#49574f",
        hex_6: "#4c5c60",
        hex_7: "#9d4c33",
        hex_8: "#8c8c8c",
        hex_9: "#948494"
      }
    ]
  },
  "LightningCracked Moon Surface": {
    environment_title: "LightningCracked Moon Surface",
    images: [
      {
        original_file_name: "LightningCracked Moon Surface (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7623336,
        file_size_megabytes: 7.27,
        width: 3072,
        height: 5472,
        primary: "#c2a69a",
        secondary: "#1a1920",
        tertiary: "#755c5a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#899eb0",
        hex_5: "#7d829b",
        hex_6: "#464d61",
        hex_7: "#536170",
        hex_8: "#4c3737",
        hex_9: "#a04510"
      },
      {
        original_file_name: "LightningCracked Moon Surface (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7679658,
        file_size_megabytes: 7.32,
        width: 3072,
        height: 5472,
        primary: "#bb795d",
        secondary: "#151922",
        tertiary: "#714c45",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f2dcbf",
        hex_5: "#463133",
        hex_6: "#6faabf",
        hex_7: "#466472",
        hex_8: "#628599",
        hex_9: "#364f60"
      },
      {
        original_file_name: "LightningCracked Moon Surface (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7196296,
        file_size_megabytes: 6.86,
        width: 3072,
        height: 5472,
        primary: "#c5c4be",
        secondary: "#13161f",
        tertiary: "#78a3c7",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#587da1",
        hex_5: "#6c514e",
        hex_6: "#45637d",
        hex_7: "#344c64",
        hex_8: "#a64e21",
        hex_9: "#443233"
      },
      {
        original_file_name: "LightningCracked Moon Surface (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7831626,
        file_size_megabytes: 7.47,
        width: 3072,
        height: 5472,
        primary: "#cd9d71",
        secondary: "#141821",
        tertiary: "#6f473a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#452c27",
        hex_5: "#486271",
        hex_6: "#8598a3",
        hex_7: "#3e4e5f",
        hex_8: "#748796",
        hex_9: "#99410d"
      }
    ]
  },
  "Neon Lightning Storm": {
    environment_title: "Neon Lightning Storm",
    images: [
      {
        original_file_name: "Neon Lightning Storm (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6636062,
        file_size_megabytes: 6.33,
        width: 3072,
        height: 5472,
        primary: "#cfa4bd",
        secondary: "#181329",
        tertiary: "#764f72",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3e3155",
        hex_5: "#8974a1",
        hex_6: "#524673",
        hex_7: "#a14157",
        hex_8: "#9296a8",
        hex_9: "#45563d"
      },
      {
        original_file_name: "Neon Lightning Storm (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6636062,
        file_size_megabytes: 6.33,
        width: 3072,
        height: 5472,
        primary: "#cfa4bd",
        secondary: "#181329",
        tertiary: "#764f72",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3e3155",
        hex_5: "#8974a1",
        hex_6: "#524673",
        hex_7: "#a14157",
        hex_8: "#9296a8",
        hex_9: "#45563d"
      },
      {
        original_file_name: "Neon Lightning Storm (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6941348,
        file_size_megabytes: 6.62,
        width: 3072,
        height: 5472,
        primary: "#d2a5b6",
        secondary: "#1a1529",
        tertiary: "#77526e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#847fa3",
        hex_5: "#3b3655",
        hex_6: "#4d5075",
        hex_7: "#9196b3",
        hex_8: "#a64962",
        hex_9: "#595d58"
      },
      {
        original_file_name: "Neon Lightning Storm (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6912599,
        file_size_megabytes: 6.59,
        width: 3072,
        height: 5472,
        primary: "#d2a0b6",
        secondary: "#150e23",
        tertiary: "#724869",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7d73a5",
        hex_5: "#3c4572",
        hex_6: "#332c4c",
        hex_7: "#8b91bb",
        hex_8: "#9e435d",
        hex_9: "#444c5c"
      }
    ]
  },
  "Planetary Lightning Storm": {
    environment_title: "Planetary Lightning Storm",
    images: [
      {
        original_file_name: "Planetary Lightning Storm (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7140313,
        file_size_megabytes: 6.81,
        width: 3072,
        height: 5472,
        primary: "#d7a49d",
        secondary: "#1b1521",
        tertiary: "#774b50",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e2e36",
        hex_5: "#564e69",
        hex_6: "#8d859f",
        hex_7: "#9f4c4d",
        hex_8: "#9194a1",
        hex_9: "#5c545c"
      },
      {
        original_file_name: "Planetary Lightning Storm (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6882877,
        file_size_megabytes: 6.56,
        width: 3072,
        height: 5472,
        primary: "#d2947b",
        secondary: "#1b1520",
        tertiary: "#794844",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e2e34",
        hex_5: "#9d3b10",
        hex_6: "#58485c",
        hex_7: "#5a5463",
        hex_8: "#908595",
        hex_9: "#94989c"
      },
      {
        original_file_name: "Planetary Lightning Storm (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7252201,
        file_size_megabytes: 6.92,
        width: 3072,
        height: 5472,
        primary: "#d1aeae",
        secondary: "#18131f",
        tertiary: "#78413b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5378a5",
        hex_5: "#66abd7",
        hex_6: "#3c5a80",
        hex_7: "#4f2522",
        hex_8: "#284266",
        hex_9: "#a34421"
      },
      {
        original_file_name: "Planetary Lightning Storm (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6983957,
        file_size_megabytes: 6.66,
        width: 3072,
        height: 5472,
        primary: "#d19791",
        secondary: "#181320",
        tertiary: "#784447",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e272c",
        hex_5: "#384c6b",
        hex_6: "#8299c6",
        hex_7: "#5f73a1",
        hex_8: "#9d433c",
        hex_9: "#4a4c4f"
      }
    ]
  },
  "Planetary Storm With Lightning": {
    environment_title: "Planetary Storm With Lightning",
    images: [
      {
        original_file_name: "Planetary Storm With Lightning (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7159354,
        file_size_megabytes: 6.83,
        width: 3072,
        height: 5472,
        primary: "#d19ca9",
        secondary: "#1b1729",
        tertiary: "#774b63",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#404870",
        hex_5: "#6e78a7",
        hex_6: "#4d2c42",
        hex_7: "#82a3ca",
        hex_8: "#a3424e",
        hex_9: "#534c5b"
      },
      {
        original_file_name: "Planetary Storm With Lightning (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6943113,
        file_size_megabytes: 6.62,
        width: 3072,
        height: 5472,
        primary: "#cc9aa5",
        secondary: "#161a27",
        tertiary: "#794955",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#345072",
        hex_5: "#4e2b35",
        hex_6: "#607aa5",
        hex_7: "#7ca1c4",
        hex_8: "#9c4431",
        hex_9: "#5c5c5c"
      },
      {
        original_file_name: "Planetary Storm With Lightning (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6874151,
        file_size_megabytes: 6.56,
        width: 3072,
        height: 5472,
        primary: "#d1a197",
        secondary: "#1a192a",
        tertiary: "#455776",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#64b6d6",
        hex_5: "#6f3436",
        hex_6: "#597ea5",
        hex_7: "#9f3f24",
        hex_8: "#293a52",
        hex_9: "#3e545c"
      },
      {
        original_file_name: "Planetary Storm With Lightning (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7038547,
        file_size_megabytes: 6.71,
        width: 3072,
        height: 5472,
        primary: "#d0a0b5",
        secondary: "#1b182a",
        tertiary: "#764e69",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#474f72",
        hex_5: "#757aa8",
        hex_6: "#899bc1",
        hex_7: "#4c3046",
        hex_8: "#a14244",
        hex_9: "#54545c"
      }
    ]
  },
  "Solar Eclipse With Lightning": {
    environment_title: "Solar Eclipse With Lightning",
    images: [
      {
        original_file_name: "Solar Eclipse With Lightning (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5598270,
        file_size_megabytes: 5.34,
        width: 3072,
        height: 5472,
        primary: "#ca9b84",
        secondary: "#1e1c22",
        tertiary: "#6f5048",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4a3736",
        hex_5: "#8a8480",
        hex_6: "#945440",
        hex_7: "#504c54",
        hex_8: "#535558",
        hex_9: "#847c84"
      },
      {
        original_file_name: "Solar Eclipse With Lightning (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5560671,
        file_size_megabytes: 5.3,
        width: 3072,
        height: 5472,
        primary: "#d2af9c",
        secondary: "#1e191e",
        tertiary: "#755750",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4c3632",
        hex_5: "#8f8197",
        hex_6: "#564c5f",
        hex_7: "#9c5c39",
        hex_8: "#5b5c62",
        hex_9: "#949496"
      },
      {
        original_file_name: "Solar Eclipse With Lightning (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5849104,
        file_size_megabytes: 5.58,
        width: 3072,
        height: 5472,
        primary: "#cc9f84",
        secondary: "#1e191d",
        tertiary: "#76554a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4d3835",
        hex_5: "#8f7c84",
        hex_6: "#595552",
        hex_7: "#918481",
        hex_8: "#574b54",
        hex_9: "#9c4c2c"
      },
      {
        original_file_name: "Solar Eclipse With Lightning (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5752032,
        file_size_megabytes: 5.49,
        width: 3072,
        height: 5472,
        primary: "#ca9c88",
        secondary: "#17151c",
        tertiary: "#6f4e49",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#463131",
        hex_5: "#8c7f8c",
        hex_6: "#9a4416",
        hex_7: "#524b5c",
        hex_8: "#54545a",
        hex_9: "#8c8c8c"
      }
    ]
  },
  "Solar Flare Lightning Display": {
    environment_title: "Solar Flare Lightning Display",
    images: [
      {
        original_file_name: "Solar Flare Lightning Display (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6009260,
        file_size_megabytes: 5.73,
        width: 3072,
        height: 5472,
        primary: "#c46935",
        secondary: "#131319",
        tertiary: "#703827",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#fae29f",
        hex_5: "#462621",
        hex_6: "#445062",
        hex_7: "#888c8d",
        hex_8: "#8a7894",
        hex_9: "#525450"
      },
      {
        original_file_name: "Solar Flare Lightning Display (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5457831,
        file_size_megabytes: 5.2,
        width: 3072,
        height: 5472,
        primary: "#ce6215",
        secondary: "#160806",
        tertiary: "#f9e484",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6f290f",
        hex_5: "#44180d",
        hex_6: "#8a7462",
        hex_7: "#533c34",
        hex_8: "#866c6c",
        hex_9: "#4c3434"
      },
      {
        original_file_name: "Solar Flare Lightning Display (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5558770,
        file_size_megabytes: 5.3,
        width: 3072,
        height: 5472,
        primary: "#cdab98",
        secondary: "#130e14",
        tertiary: "#6e4e54",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#442e33",
        hex_5: "#817491",
        hex_6: "#9e450b",
        hex_7: "#4a3f59",
        hex_8: "#524e64",
        hex_9: "#8c8c9a"
      },
      {
        original_file_name: "Solar Flare Lightning Display (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5944927,
        file_size_megabytes: 5.67,
        width: 3072,
        height: 5472,
        primary: "#d69f63",
        secondary: "#170c12",
        tertiary: "#78432f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e261f",
        hex_5: "#a73b0c",
        hex_6: "#574f55",
        hex_7: "#463c4e",
        hex_8: "#8c7f91",
        hex_9: "#908e98"
      }
    ]
  },
  "StarInfused Lightning Bolt": {
    environment_title: "StarInfused Lightning Bolt",
    images: [
      {
        original_file_name: "StarInfused Lightning Bolt (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6737529,
        file_size_megabytes: 6.43,
        width: 3072,
        height: 5472,
        primary: "#d3b0b1",
        secondary: "#151927",
        tertiary: "#745964",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6ea3c7",
        hex_5: "#537fa6",
        hex_6: "#325273",
        hex_7: "#2c3a52",
        hex_8: "#9d5454",
        hex_9: "#4e5c5a"
      },
      {
        original_file_name: "StarInfused Lightning Bolt (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6805596,
        file_size_megabytes: 6.49,
        width: 3072,
        height: 5472,
        primary: "#d2a9a4",
        secondary: "#171b27",
        tertiary: "#76575d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#849fc1",
        hex_5: "#475972",
        hex_6: "#4e363d",
        hex_7: "#6e82a5",
        hex_8: "#9c4c46",
        hex_9: "#575c5b"
      },
      {
        original_file_name: "StarInfused Lightning Bolt (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6762113,
        file_size_megabytes: 6.45,
        width: 3072,
        height: 5472,
        primary: "#cbacae",
        secondary: "#1c1c27",
        tertiary: "#77606b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4c3c45",
        hex_5: "#8486a3",
        hex_6: "#4f526a",
        hex_7: "#546878",
        hex_8: "#8f9fb3",
        hex_9: "#9c544c"
      },
      {
        original_file_name: "StarInfused Lightning Bolt (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6770195,
        file_size_megabytes: 6.46,
        width: 3072,
        height: 5472,
        primary: "#d4aba9",
        secondary: "#161926",
        tertiary: "#785966",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4c536e",
        hex_5: "#4d3642",
        hex_6: "#86839f",
        hex_7: "#8d99ac",
        hex_8: "#9d544e",
        hex_9: "#565c5c"
      }
    ]
  },
  "Stellar Lightning Pathways": {
    environment_title: "Stellar Lightning Pathways",
    images: [
      {
        original_file_name: "Stellar Lightning Pathways (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6906509,
        file_size_megabytes: 6.59,
        width: 3072,
        height: 5472,
        primary: "#17161e",
        secondary: "#b8b6cc",
        tertiary: "#5a6076",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#79a1c9",
        hex_5: "#6782a8",
        hex_6: "#373d4c",
        hex_7: "#684b4f",
        hex_8: "#955c59",
        hex_9: "#545c5c"
      },
      {
        original_file_name: "Stellar Lightning Pathways (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6890146,
        file_size_megabytes: 6.57,
        width: 3072,
        height: 5472,
        primary: "#c99e88",
        secondary: "#151521",
        tertiary: "#6f4e4c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#462f33",
        hex_5: "#79809c",
        hex_6: "#4b596d",
        hex_7: "#809fbb",
        hex_8: "#42485f",
        hex_9: "#94431a"
      },
      {
        original_file_name: "Stellar Lightning Pathways (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6986700,
        file_size_megabytes: 6.66,
        width: 3072,
        height: 5472,
        primary: "#c99e83",
        secondary: "#13141d",
        tertiary: "#6f514a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#74adba",
        hex_5: "#463032",
        hex_6: "#425f6b",
        hex_7: "#638698",
        hex_8: "#38495d",
        hex_9: "#974118"
      },
      {
        original_file_name: "Stellar Lightning Pathways (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7069784,
        file_size_megabytes: 6.74,
        width: 3072,
        height: 5472,
        primary: "#c3a69d",
        secondary: "#1b1820",
        tertiary: "#576176",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#809cbd",
        hex_5: "#6c453b",
        hex_6: "#6f83a4",
        hex_7: "#343d4c",
        hex_8: "#99461b",
        hex_9: "#515c5c"
      }
    ]
  },
  "Stormy Galaxy Spiral": {
    environment_title: "Stormy Galaxy Spiral",
    images: [
      {
        original_file_name: "Stormy Galaxy Spiral  (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7161516,
        file_size_megabytes: 6.83,
        width: 3072,
        height: 5472,
        primary: "#caa192",
        secondary: "#12151f",
        tertiary: "#71565b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#697cab",
        hex_5: "#3f5272",
        hex_6: "#829cc9",
        hex_7: "#2d394e",
        hex_8: "#a3400f",
        hex_9: "#505c5a"
      },
      {
        original_file_name: "Stormy Galaxy Spiral  (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7394504,
        file_size_megabytes: 7.05,
        width: 3072,
        height: 5472,
        primary: "#c89c8c",
        secondary: "#1d222b",
        tertiary: "#5b6983",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#765144",
        hex_5: "#6c84af",
        hex_6: "#36495d",
        hex_7: "#82a6c9",
        hex_8: "#a43d0f",
        hex_9: "#516568"
      },
      {
        original_file_name: "Stormy Galaxy Spiral  (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7489688,
        file_size_megabytes: 7.14,
        width: 3072,
        height: 5472,
        primary: "#c9a798",
        secondary: "#1b1f2a",
        tertiary: "#775f61",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7080aa",
        hex_5: "#3f506e",
        hex_6: "#4d3a40",
        hex_7: "#86a3c7",
        hex_8: "#516980",
        hex_9: "#a44920"
      },
      {
        original_file_name: "Stormy Galaxy Spiral  (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7080255,
        file_size_megabytes: 6.75,
        width: 3072,
        height: 5472,
        primary: "#c0a098",
        secondary: "#181d26",
        tertiary: "#6b7caa",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#686a7a",
        hex_5: "#495275",
        hex_6: "#684a45",
        hex_7: "#333f55",
        hex_8: "#80a2d3",
        hex_9: "#944408"
      }
    ]
  }
};
export default CosmicAndLightning;
