import { EnvironmentEntry } from "@/types/database";
const HyperCloseups: Record<string, EnvironmentEntry> = {
  "Ants Compound Eyes": {
    environment_title: "Ants Compound Eyes",
    images: [
      {
        original_file_name: "Ants Compound Eyes (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8027291,
        file_size_megabytes: 7.66,
        width: 3072,
        height: 5472,
        primary: "#d8a070",
        secondary: "#612f15",
        tertiary: "#170f11",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#98b7c6",
        hex_5: "#9f5421",
        hex_6: "#9f7554",
        hex_7: "#728799",
        hex_8: "#56595e",
        hex_9: "#bd4209"
      },
      {
        original_file_name: "Ants Compound Eyes (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8423452,
        file_size_megabytes: 8.03,
        width: 3072,
        height: 5472,
        primary: "#d49b72",
        secondary: "#602e17",
        tertiary: "#9eb7ca",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#24110b",
        hex_5: "#7e8699",
        hex_6: "#a14e1e",
        hex_7: "#997562",
        hex_8: "#645a60",
        hex_9: "#be3e09"
      },
      {
        original_file_name: "Ants Compound Eyes (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8790448,
        file_size_megabytes: 8.38,
        width: 3072,
        height: 5472,
        primary: "#dbbfa4",
        secondary: "#acb6bc",
        tertiary: "#512516",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#9b6a4a",
        hex_5: "#6d7071",
        hex_6: "#8b9299",
        hex_7: "#100807",
        hex_8: "#c45209",
        hex_9: "#605859"
      },
      {
        original_file_name: "Ants Compound Eyes (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8323964,
        file_size_megabytes: 7.94,
        width: 3072,
        height: 5472,
        primary: "#d4a176",
        secondary: "#65361a",
        tertiary: "#89bedc",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1b161b",
        hex_5: "#5d85b3",
        hex_6: "#a17c5c",
        hex_7: "#a05324",
        hex_8: "#5f5c6b",
        hex_9: "#be3d05"
      }
    ]
  },
  "Beetle Shell Texture": {
    environment_title: "Beetle Shell Texture",
    images: [
      {
        original_file_name: "Beetle Shell Texture (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8451121,
        file_size_megabytes: 8.06,
        width: 3072,
        height: 5472,
        primary: "#e9a442",
        secondary: "#352117",
        tertiary: "#9d5e31",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#77b0ad",
        hex_5: "#764123",
        hex_6: "#d82d06",
        hex_7: "#556d60",
        hex_8: "#618a94",
        hex_9: "#18485f"
      },
      {
        original_file_name: "Beetle Shell Texture (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8232330,
        file_size_megabytes: 7.85,
        width: 3072,
        height: 5472,
        primary: "#e0af7d",
        secondary: "#78b6be",
        tertiary: "#86311c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#181918",
        hex_5: "#468c9b",
        hex_6: "#3a6e74",
        hex_7: "#cc2b09",
        hex_8: "#521e14",
        hex_9: "#254e59"
      },
      {
        original_file_name: "Beetle Shell Texture (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7702997,
        file_size_megabytes: 7.35,
        width: 3072,
        height: 5472,
        primary: "#771d0f",
        secondary: "#ad6229",
        tertiary: "#e2ddd5",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#27150f",
        hex_5: "#7e6c63",
        hex_6: "#bd9a7b",
        hex_7: "#898780",
        hex_8: "#a69e99",
        hex_9: "#44544c"
      },
      {
        original_file_name: "Beetle Shell Texture (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8328062,
        file_size_megabytes: 7.94,
        width: 3072,
        height: 5472,
        primary: "#201f1c",
        secondary: "#b1643b",
        tertiary: "#e0dec3",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5f3924",
        hex_5: "#7da6b3",
        hex_6: "#d4a281",
        hex_7: "#eb9450",
        hex_8: "#3b95a6",
        hex_9: "#802a06"
      }
    ]
  },
  "Blooming Orchid Petal": {
    environment_title: "Blooming Orchid Petal",
    images: [
      {
        original_file_name: "Blooming Orchid Petal (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7585899,
        file_size_megabytes: 7.23,
        width: 3072,
        height: 5472,
        primary: "#eddade",
        secondary: "#7a3755",
        tertiary: "#310e19",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#d5a4c6",
        hex_5: "#b692a6",
        hex_6: "#dd7f6b",
        hex_7: "#ab6d96",
        hex_8: "#76130d",
        hex_9: "#444444"
      },
      {
        original_file_name: "Blooming Orchid Petal (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7451759,
        file_size_megabytes: 7.11,
        width: 3072,
        height: 5472,
        primary: "#f0d7c0",
        secondary: "#6e2035",
        tertiary: "#30050c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#d991b7",
        hex_5: "#b28789",
        hex_6: "#dd825d",
        hex_7: "#ab5981",
        hex_8: "#af3f26",
        hex_9: "#44443c"
      },
      {
        original_file_name: "Blooming Orchid Petal (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7349978,
        file_size_megabytes: 7.01,
        width: 3072,
        height: 5472,
        primary: "#914061",
        secondary: "#f5e8e4",
        tertiary: "#321111",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6d1b1d",
        hex_5: "#ea9dc4",
        hex_6: "#da84a5",
        hex_7: "#ba9299",
        hex_8: "#c36e98",
        hex_9: "#f2b862"
      },
      {
        original_file_name: "Blooming Orchid Petal (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7737645,
        file_size_megabytes: 7.38,
        width: 3072,
        height: 5472,
        primary: "#ead7df",
        secondary: "#2f0814",
        tertiary: "#753a53",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#d4a7c5",
        hex_5: "#b293a1",
        hex_6: "#e1855f",
        hex_7: "#aa6f94",
        hex_8: "#74130c",
        hex_9: "#ac5868"
      }
    ]
  },
  "Blooming Rose Petals": {
    environment_title: "Blooming Rose Petals",
    images: [
      {
        original_file_name: "Blooming Rose Petals (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6918460,
        file_size_megabytes: 6.6,
        width: 3072,
        height: 5472,
        primary: "#f5d0b3",
        secondary: "#8c3626",
        tertiary: "#e39d75",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#501809",
        hex_5: "#e6ada3",
        hex_6: "#e17050",
        hex_7: "#b0756f",
        hex_8: "#ad6c4c",
        hex_9: "#fcbc54"
      },
      {
        original_file_name: "Blooming Rose Petals (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6803498,
        file_size_megabytes: 6.49,
        width: 3072,
        height: 5472,
        primary: "#f5d3b8",
        secondary: "#d9987c",
        tertiary: "#5e1a0d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#902916",
        hex_5: "#a44a21",
        hex_6: "#915946",
        hex_7: "#dfb7ad",
        hex_8: "#be5344",
        hex_9: "#d17544"
      },
      {
        original_file_name: "Blooming Rose Petals (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7159578,
        file_size_megabytes: 6.83,
        width: 3072,
        height: 5472,
        primary: "#cd8768",
        secondary: "#f6d4b9",
        tertiary: "#761d0b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4f160b",
        hex_5: "#e4b0a8",
        hex_6: "#794331",
        hex_7: "#af4618",
        hex_8: "#9f4b36",
        hex_9: "#fcbc54"
      },
      {
        original_file_name: "Blooming Rose Petals (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7044239,
        file_size_megabytes: 6.72,
        width: 3072,
        height: 5472,
        primary: "#883c25",
        secondary: "#f1d3b7",
        tertiary: "#3d1208",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#d69c79",
        hex_5: "#da7147",
        hex_6: "#d8ada9",
        hex_7: "#aa7973",
        hex_8: "#ad7552",
        hex_9: "#f4bc54"
      }
    ]
  },
  "Closeup Of Moss On Stone": {
    environment_title: "Closeup Of Moss On Stone",
    images: [
      {
        original_file_name: "Closeup Of Moss On Stone (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8603187,
        file_size_megabytes: 8.2,
        width: 3072,
        height: 5472,
        primary: "#343413",
        secondary: "#c7c057",
        tertiary: "#a6b022",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#928b2c",
        hex_5: "#778120",
        hex_6: "#a09c92",
        hex_7: "#6c6855",
        hex_8: "#6b641d",
        hex_9: "#b4640c"
      },
      {
        original_file_name: "Closeup Of Moss On Stone (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10000076,
        file_size_megabytes: 9.54,
        width: 3072,
        height: 5472,
        primary: "#50511c",
        secondary: "#c1be48",
        tertiary: "#88853a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#9a9072",
        hex_5: "#0d0d05",
        hex_6: "#252208",
        hex_7: "#a2ad18",
        hex_8: "#707e0e",
        hex_9: "#ac8c64"
      },
      {
        original_file_name: "Closeup Of Moss On Stone (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9762307,
        file_size_megabytes: 9.31,
        width: 3072,
        height: 5472,
        primary: "#c8c456",
        secondary: "#36380e",
        tertiary: "#8c8a38",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a1ae11",
        hex_5: "#9e9790",
        hex_6: "#676155",
        hex_7: "#63631d",
        hex_8: "#707e0c",
        hex_9: "#ac8c78"
      },
      {
        original_file_name: "Closeup Of Moss On Stone (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8112143,
        file_size_megabytes: 7.74,
        width: 3072,
        height: 5472,
        primary: "#343512",
        secondary: "#cccf88",
        tertiary: "#8f9838",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a4b920",
        hex_5: "#9d9c94",
        hex_6: "#6b685a",
        hex_7: "#768911",
        hex_8: "#6a701a",
        hex_9: "#b4a48a"
      }
    ]
  },
  "Cracked Dried Mud Surface": {
    environment_title: "Cracked Dried Mud Surface",
    images: [
      {
        original_file_name: "Cracked Dried Mud Surface (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8741302,
        file_size_megabytes: 8.34,
        width: 3072,
        height: 5472,
        primary: "#d2a883",
        secondary: "#26140b",
        tertiary: "#946b4c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6d4529",
        hex_5: "#f9e4c2",
        hex_6: "#845a37",
        hex_7: "#fbddb2",
        hex_8: "#917e67",
        hex_9: "#5c5c54"
      },
      {
        original_file_name: "Cracked Dried Mud Surface (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8659199,
        file_size_megabytes: 8.26,
        width: 3072,
        height: 5472,
        primary: "#d5a37b",
        secondary: "#1e110b",
        tertiary: "#704423",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f9d9b6",
        hex_5: "#965c2f",
        hex_6: "#aa6f45",
        hex_7: "#83664e",
        hex_8: "#e9cab5",
        hex_9: "#5c5c56"
      },
      {
        original_file_name: "Cracked Dried Mud Surface (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9228084,
        file_size_megabytes: 8.8,
        width: 3072,
        height: 5472,
        primary: "#220f07",
        secondary: "#cfa17d",
        tertiary: "#663c1d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#80532f",
        hex_5: "#f4d7ba",
        hex_6: "#826045",
        hex_7: "#996846",
        hex_8: "#a87850",
        hex_9: "#fad5a9"
      },
      {
        original_file_name: "Cracked Dried Mud Surface (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8902576,
        file_size_megabytes: 8.49,
        width: 3072,
        height: 5472,
        primary: "#2a1108",
        secondary: "#d39e76",
        tertiary: "#6a3e1f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#80532f",
        hex_5: "#a77a56",
        hex_6: "#815f46",
        hex_7: "#9d6944",
        hex_8: "#edc8ae",
        hex_9: "#f8d6b4"
      }
    ]
  },
  "Detailed Leaf Veins": {
    environment_title: "Detailed Leaf Veins",
    images: [
      {
        original_file_name: "Detailed Leaf Veins (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9105820,
        file_size_megabytes: 8.68,
        width: 3072,
        height: 5472,
        primary: "#9aa751",
        secondary: "#263605",
        tertiary: "#cfd695",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#50620d",
        hex_5: "#6f7f14",
        hex_6: "#d5db74",
        hex_7: "#444b08",
        hex_8: "#c2d477",
        hex_9: "#3c6408"
      },
      {
        original_file_name: "Detailed Leaf Veins (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9841714,
        file_size_megabytes: 9.39,
        width: 3072,
        height: 5472,
        primary: "#cbda7f",
        secondary: "#465912",
        tertiary: "#889d31",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#101505",
        hex_5: "#9fb746",
        hex_6: "#718e1d",
        hex_7: "#1b2c05",
        hex_8: "#9faa7d",
        hex_9: "#6f7d4d"
      },
      {
        original_file_name: "Detailed Leaf Veins (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10204336,
        file_size_megabytes: 9.73,
        width: 3072,
        height: 5472,
        primary: "#778228",
        secondary: "#c6cd7a",
        tertiary: "#131a05",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3b460b",
        hex_5: "#293606",
        hex_6: "#49560f",
        hex_7: "#9fa75b",
        hex_8: "#abbc5c",
        hex_9: "#a7ae76"
      },
      {
        original_file_name: "Detailed Leaf Veins (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10133051,
        file_size_megabytes: 9.66,
        width: 3072,
        height: 5472,
        primary: "#222b0a",
        secondary: "#7a8d35",
        tertiary: "#c5d17f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#556621",
        hex_5: "#98ae46",
        hex_6: "#6c7338",
        hex_7: "#a4a461",
        hex_8: "#99a27d",
        hex_9: "#4c5246"
      }
    ]
  },
  "Frost Patterns On Window": {
    environment_title: "Frost Patterns On Window",
    images: [
      {
        original_file_name: "Frost Patterns On Window (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10935686,
        file_size_megabytes: 10.43,
        width: 3072,
        height: 5472,
        primary: "#9098a4",
        secondary: "#141c2a",
        tertiary: "#d8dbde",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#52657b",
        hex_5: "#c1cdd8",
        hex_6: "#b8c3d4",
        hex_7: "#44434b",
        hex_8: "#4c4c4b",
        hex_9: "#64636b"
      },
      {
        original_file_name: "Frost Patterns On Window (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8838533,
        file_size_megabytes: 8.43,
        width: 3072,
        height: 5472,
        primary: "#7f8b9b",
        secondary: "#152334",
        tertiary: "#e4dbca",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#b6b2af",
        hex_5: "#525e71",
        hex_6: "#48403c",
        hex_7: "#565048",
        hex_8: "#c1cdd6",
        hex_9: "#afbfd6"
      },
      {
        original_file_name: "Frost Patterns On Window (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11186888,
        file_size_megabytes: 10.67,
        width: 3072,
        height: 5472,
        primary: "#909ead",
        secondary: "#233c57",
        tertiary: "#d8d6d4",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#526d8a",
        hex_5: "#afc6de",
        hex_6: "#666a78",
        hex_7: "#c1d4e2",
        hex_8: "#494d53",
        hex_9: "#454351"
      },
      {
        original_file_name: "Frost Patterns On Window (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9913633,
        file_size_megabytes: 9.45,
        width: 3072,
        height: 5472,
        primary: "#98a3ae",
        secondary: "#28415a",
        tertiary: "#9dbfe4",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#c0d9f0",
        hex_5: "#5a6e82",
        hex_6: "#d9e0e7",
        hex_7: "#6d7380",
        hex_8: "#4c5465",
        hex_9: "#525c63"
      }
    ]
  },
  "Iridescent Beetle Shell": {
    environment_title: "Iridescent Beetle Shell",
    images: [
      {
        original_file_name: "Iridescent Beetle Shell (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10018808,
        file_size_megabytes: 9.55,
        width: 3072,
        height: 5472,
        primary: "#d06741",
        secondary: "#36bab6",
        tertiary: "#1b1517",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7e4937",
        hex_5: "#e5e88c",
        hex_6: "#326baf",
        hex_7: "#2c685d",
        hex_8: "#572a21",
        hex_9: "#1e3464"
      },
      {
        original_file_name: "Iridescent Beetle Shell (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8279201,
        file_size_megabytes: 7.9,
        width: 3072,
        height: 5472,
        primary: "#d5b1a8",
        secondary: "#4ec3d1",
        tertiary: "#5f79cc",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#191016",
        hex_5: "#83544e",
        hex_6: "#383c74",
        hex_7: "#376f5e",
        hex_8: "#4f2726",
        hex_9: "#c03b54"
      },
      {
        original_file_name: "Iridescent Beetle Shell (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8683342,
        file_size_megabytes: 8.28,
        width: 3072,
        height: 5472,
        primary: "#dba160",
        secondary: "#4bc6c8",
        tertiary: "#1a1516",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#874024",
        hex_5: "#486caa",
        hex_6: "#5d271a",
        hex_7: "#2b3b64",
        hex_8: "#386a59",
        hex_9: "#b03d20"
      },
      {
        original_file_name: "Iridescent Beetle Shell (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8828813,
        file_size_megabytes: 8.42,
        width: 3072,
        height: 5472,
        primary: "#ddb27d",
        secondary: "#1e1b1c",
        tertiary: "#44beb9",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#783e2a",
        hex_5: "#3a64ae",
        hex_6: "#b03a2f",
        hex_7: "#2b6c54",
        hex_8: "#4e2317",
        hex_9: "#1c3b6d"
      }
    ]
  },
  "Leaf Veins Macro": {
    environment_title: "Leaf Veins Macro",
    images: [
      {
        original_file_name: "Leaf Veins Macro (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9712600,
        file_size_megabytes: 9.26,
        width: 3072,
        height: 5472,
        primary: "#475e0d",
        secondary: "#ccdb6b",
        tertiary: "#879c39",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#9db84d",
        hex_5: "#6e8f19",
        hex_6: "#1b2704",
        hex_7: "#1b3404",
        hex_8: "#708046",
        hex_9: "#9daa7d"
      },
      {
        original_file_name: "Leaf Veins Macro (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9022724,
        file_size_megabytes: 8.6,
        width: 3072,
        height: 5472,
        primary: "#374b14",
        secondary: "#d2dc79",
        tertiary: "#778c3b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#98af56",
        hex_5: "#0e1704",
        hex_6: "#6c732a",
        hex_7: "#5e6f45",
        hex_8: "#94a177",
        hex_9: "#a4942c"
      },
      {
        original_file_name: "Leaf Veins Macro (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9070268,
        file_size_megabytes: 8.65,
        width: 3072,
        height: 5472,
        primary: "#3f580c",
        secondary: "#d1d46f",
        tertiary: "#839340",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#0c0e04",
        hex_5: "#9ab560",
        hex_6: "#6a8c2d",
        hex_7: "#667947",
        hex_8: "#99a87d",
        hex_9: "#132d04"
      },
      {
        original_file_name: "Leaf Veins Macro (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9610477,
        file_size_megabytes: 9.17,
        width: 3072,
        height: 5472,
        primary: "#d3da7e",
        secondary: "#4e5d11",
        tertiary: "#0a1404",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8f9b3d",
        hex_5: "#a2b554",
        hex_6: "#7a8d2e",
        hex_7: "#1a2d04",
        hex_8: "#707c3e",
        hex_9: "#99a86c"
      }
    ]
  },
  "Macro View Of Dragonfly Wings": {
    environment_title: "Macro View Of Dragonfly Wings",
    images: [
      {
        original_file_name: "Macro View Of Dragonfly Wings (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8369023,
        file_size_megabytes: 7.98,
        width: 3072,
        height: 5472,
        primary: "#96ad7b",
        secondary: "#29160f",
        tertiary: "#8c8624",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#693616",
        hex_5: "#e1bf91",
        hex_6: "#99ccc9",
        hex_7: "#78684f",
        hex_8: "#62977c",
        hex_9: "#c3dc90"
      },
      {
        original_file_name: "Macro View Of Dragonfly Wings (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9207209,
        file_size_megabytes: 8.78,
        width: 3072,
        height: 5472,
        primary: "#88956b",
        secondary: "#dab86f",
        tertiary: "#232414",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#502a12",
        hex_5: "#785d18",
        hex_6: "#b3c9b4",
        hex_7: "#7a89c9",
        hex_8: "#4c5b43",
        hex_9: "#705b43"
      },
      {
        original_file_name: "Macro View Of Dragonfly Wings (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8941472,
        file_size_megabytes: 8.53,
        width: 3072,
        height: 5472,
        primary: "#697537",
        secondary: "#d5c77d",
        tertiary: "#2e1e0e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#9bacba",
        hex_5: "#aec66e",
        hex_6: "#879681",
        hex_7: "#a3a64e",
        hex_8: "#324528",
        hex_9: "#8ea750"
      },
      {
        original_file_name: "Macro View Of Dragonfly Wings (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8401281,
        file_size_megabytes: 8.01,
        width: 3072,
        height: 5472,
        primary: "#939371",
        secondary: "#2f5573",
        tertiary: "#5f3310",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#deb263",
        hex_5: "#7e9fca",
        hex_6: "#8c6519",
        hex_7: "#567992",
        hex_8: "#93a0af",
        hex_9: "#aecdaf"
      }
    ]
  },
  "Morning Dew On Spiderweb": {
    environment_title: "Morning Dew On Spiderweb",
    images: [
      {
        original_file_name: "Morning Dew On Spiderweb (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8414390,
        file_size_megabytes: 8.02,
        width: 3072,
        height: 5472,
        primary: "#dbc598",
        secondary: "#2c2c12",
        tertiary: "#8f7f58",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a8a78e",
        hex_5: "#6f6f44",
        hex_6: "#655934",
        hex_7: "#979696",
        hex_8: "#56585c",
        hex_9: "#b47c46"
      },
      {
        original_file_name: "Morning Dew On Spiderweb (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8214419,
        file_size_megabytes: 7.83,
        width: 3072,
        height: 5472,
        primary: "#4b4a27",
        secondary: "#d5d3bb",
        tertiary: "#8c8a6d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#171b09",
        hex_5: "#6d7067",
        hex_6: "#9fa19d",
        hex_7: "#a1ac8c",
        hex_8: "#737d5f",
        hex_9: "#ac9c80"
      },
      {
        original_file_name: "Morning Dew On Spiderweb (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7492723,
        file_size_megabytes: 7.15,
        width: 3072,
        height: 5472,
        primary: "#d2c6a2",
        secondary: "#232411",
        tertiary: "#80795a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#9a9d8a",
        hex_5: "#545036",
        hex_6: "#62644b",
        hex_7: "#5a5a55",
        hex_8: "#949394",
        hex_9: "#a4845c"
      },
      {
        original_file_name: "Morning Dew On Spiderweb (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8554496,
        file_size_megabytes: 8.16,
        width: 3072,
        height: 5472,
        primary: "#cfcdc2",
        secondary: "#272213",
        tertiary: "#7f7e6e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#989f88",
        hex_5: "#626553",
        hex_6: "#524e3e",
        hex_7: "#5e5955",
        hex_8: "#989394",
        hex_9: "#a48c74"
      }
    ]
  },
  "Ocean Wave Foam": {
    environment_title: "Ocean Wave Foam",
    images: [
      {
        original_file_name: "Ocean Wave Foam (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8078416,
        file_size_megabytes: 7.7,
        width: 3072,
        height: 5472,
        primary: "#4d6d7d",
        secondary: "#cfc2ac",
        tertiary: "#07272c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#96a09c",
        hex_5: "#a8bdab",
        hex_6: "#154357",
        hex_7: "#0e314a",
        hex_8: "#93aec5",
        hex_9: "#b4947e"
      },
      {
        original_file_name: "Ocean Wave Foam (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9070078,
        file_size_megabytes: 8.65,
        width: 3072,
        height: 5472,
        primary: "#376582",
        secondary: "#cbd2ce",
        tertiary: "#072e38",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#90c2c8",
        hex_5: "#8d9da2",
        hex_6: "#6a9cd6",
        hex_7: "#5e9fa8",
        hex_8: "#06334c",
        hex_9: "#ac9c95"
      },
      {
        original_file_name: "Ocean Wave Foam (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7477240,
        file_size_megabytes: 7.13,
        width: 3072,
        height: 5472,
        primary: "#849196",
        secondary: "#17434e",
        tertiary: "#dcd1c6",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#9fcec8",
        hex_5: "#3f636e",
        hex_6: "#95aec4",
        hex_7: "#37414e",
        hex_8: "#3d4c4b",
        hex_9: "#c4aca5"
      },
      {
        original_file_name: "Ocean Wave Foam (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8894479,
        file_size_megabytes: 8.48,
        width: 3072,
        height: 5472,
        primary: "#3c5051",
        secondary: "#d5c3a0",
        tertiary: "#928971",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6591c0",
        hex_5: "#9dbac3",
        hex_6: "#376697",
        hex_7: "#051428",
        hex_8: "#638b89",
        hex_9: "#b47434"
      }
    ]
  },
  "Petal With Morning Dew": {
    environment_title: "Petal With Morning Dew",
    images: [
      {
        original_file_name: "Petal With Morning Dew (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7178076,
        file_size_megabytes: 6.85,
        width: 3072,
        height: 5472,
        primary: "#ca817d",
        secondary: "#f6d8d2",
        tertiary: "#940d18",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f3acb9",
        hex_5: "#bb600c",
        hex_6: "#5a1208",
        hex_7: "#af434a",
        hex_8: "#b96c43",
        hex_9: "#874642"
      },
      {
        original_file_name: "Petal With Morning Dew (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6944343,
        file_size_megabytes: 6.62,
        width: 3072,
        height: 5472,
        primary: "#7d271e",
        secondary: "#300c0c",
        tertiary: "#c29891",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#cb7416",
        hex_5: "#ecd4cf",
        hex_6: "#a15854",
        hex_7: "#7a5653",
        hex_8: "#d38b4c",
        hex_9: "#f7d2a7"
      },
      {
        original_file_name: "Petal With Morning Dew (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6957944,
        file_size_megabytes: 6.64,
        width: 3072,
        height: 5472,
        primary: "#250d0b",
        secondary: "#a96140",
        tertiary: "#f6d4a6",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#71211c",
        hex_5: "#dea057",
        hex_6: "#c7978f",
        hex_7: "#733f31",
        hex_8: "#d8adb0",
        hex_9: "#e18118"
      },
      {
        original_file_name: "Petal With Morning Dew (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6851448,
        file_size_megabytes: 6.53,
        width: 3072,
        height: 5472,
        primary: "#f3d1b8",
        secondary: "#a1552f",
        tertiary: "#140d0c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e6a8af",
        hex_5: "#d69a6b",
        hex_6: "#e16459",
        hex_7: "#bc7278",
        hex_8: "#981714",
        hex_9: "#6e4911"
      }
    ]
  },
  "Snowflake Structure": {
    environment_title: "Snowflake Structure",
    images: [
      {
        original_file_name: "Snowflake Structure (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6783621,
        file_size_megabytes: 6.47,
        width: 3072,
        height: 5472,
        primary: "#c6ced9",
        secondary: "#101218",
        tertiary: "#78808d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8f98a7",
        hex_5: "#99a5b2",
        hex_6: "#5e6977",
        hex_7: "#505867",
        hex_8: "#434854",
        hex_9: "#a4a4b1"
      },
      {
        original_file_name: "Snowflake Structure (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6634430,
        file_size_megabytes: 6.33,
        width: 3072,
        height: 5472,
        primary: "#c5c8cd",
        secondary: "#6f7379",
        tertiary: "#0b0e13",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#91969b",
        hex_5: "#4d5a68",
        hex_6: "#858a94",
        hex_7: "#3e4858",
        hex_8: "#3b3f44",
        hex_9: "#9c949e"
      },
      {
        original_file_name: "Snowflake Structure (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7419947,
        file_size_megabytes: 7.08,
        width: 3072,
        height: 5472,
        primary: "#c4c9d0",
        secondary: "#686f79",
        tertiary: "#9097a0",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#0a0d13",
        hex_5: "#828996",
        hex_6: "#9c9ca5",
        hex_7: "#485767",
        hex_8: "#3b4758",
        hex_9: "#333944"
      },
      {
        original_file_name: "Snowflake Structure (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7125684,
        file_size_megabytes: 6.8,
        width: 3072,
        height: 5472,
        primary: "#c8d0da",
        secondary: "#95a0ae",
        tertiary: "#757e8c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#0d1117",
        hex_5: "#505d6f",
        hex_6: "#8391a6",
        hex_7: "#3a4353",
        hex_8: "#a4a4b0",
        hex_9: "#4b545b"
      }
    ]
  },
  "Textured Seashell Surface": {
    environment_title: "Textured Seashell Surface",
    images: [
      {
        original_file_name: "Textured Seashell Surface (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7172394,
        file_size_megabytes: 6.84,
        width: 3072,
        height: 5472,
        primary: "#be916a",
        secondary: "#f0e4d3",
        tertiary: "#703614",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#efd2b0",
        hex_5: "#8e5226",
        hex_6: "#d5bda6",
        hex_7: "#825e45",
        hex_8: "#9c603a",
        hex_9: "#644c39"
      },
      {
        original_file_name: "Textured Seashell Surface (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7322017,
        file_size_megabytes: 6.98,
        width: 3072,
        height: 5472,
        primary: "#c4a181",
        secondary: "#512410",
        tertiary: "#985b2e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f6efdd",
        hex_5: "#f4ddb5",
        hex_6: "#816653",
        hex_7: "#615348",
        hex_8: "#9b684c",
        hex_9: "#544444"
      },
      {
        original_file_name: "Textured Seashell Surface (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8157681,
        file_size_megabytes: 7.78,
        width: 3072,
        height: 5472,
        primary: "#53250e",
        secondary: "#9d7250",
        tertiary: "#f5e7d2",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#d2b59a",
        hex_5: "#f0d1aa",
        hex_6: "#e2a56b",
        hex_7: "#c6a57e",
        hex_8: "#894a18",
        hex_9: "#5a4535"
      },
      {
        original_file_name: "Textured Seashell Surface (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7177846,
        file_size_megabytes: 6.85,
        width: 3072,
        height: 5472,
        primary: "#d8b490",
        secondary: "#a05a30",
        tertiary: "#662811",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f7eeda",
        hex_5: "#986b4e",
        hex_6: "#6c5d52",
        hex_7: "#9b856e",
        hex_8: "#fae6bc",
        hex_9: "#554444"
      }
    ]
  },
  "Textured Tree Bark": {
    environment_title: "Textured Tree Bark",
    images: [
      {
        original_file_name: "Textured Tree Bark (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11682433,
        file_size_megabytes: 11.14,
        width: 3072,
        height: 5472,
        primary: "#2e160e",
        secondary: "#af652e",
        tertiary: "#f0c89f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#70462a",
        hex_5: "#cd9d76",
        hex_6: "#e49b57",
        hex_7: "#6f2607",
        hex_8: "#cfaf97",
        hex_9: "#df853d"
      },
      {
        original_file_name: "Textured Tree Bark (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11092677,
        file_size_megabytes: 10.58,
        width: 3072,
        height: 5472,
        primary: "#bc6a2f",
        secondary: "#f3cda1",
        tertiary: "#291109",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#cca17b",
        hex_5: "#73492a",
        hex_6: "#7b2305",
        hex_7: "#f4a357",
        hex_8: "#d1b29d",
        hex_9: "#54544c"
      },
      {
        original_file_name: "Textured Tree Bark (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9899220,
        file_size_megabytes: 9.44,
        width: 3072,
        height: 5472,
        primary: "#be6c32",
        secondary: "#25140d",
        tertiary: "#f1c999",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6a4932",
        hex_5: "#c79c78",
        hex_6: "#702106",
        hex_7: "#f0a158",
        hex_8: "#c5aea0",
        hex_9: "#4c4c44"
      },
      {
        original_file_name: "Textured Tree Bark (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11016927,
        file_size_megabytes: 10.51,
        width: 3072,
        height: 5472,
        primary: "#270e07",
        secondary: "#b6642a",
        tertiary: "#f6c795",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e4a56f",
        hex_5: "#793e18",
        hex_6: "#702505",
        hex_7: "#e49855",
        hex_8: "#e58844",
        hex_9: "#d8b195"
      }
    ]
  },
  "Vibrant Butterfly Wings": {
    environment_title: "Vibrant Butterfly Wings",
    images: [
      {
        original_file_name: "Vibrant Butterfly Wings (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9058929,
        file_size_megabytes: 8.64,
        width: 3072,
        height: 5472,
        primary: "#eb9e47",
        secondary: "#4fadc4",
        tertiary: "#8f4830",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1c1011",
        hex_5: "#34739f",
        hex_6: "#df2a11",
        hex_7: "#213c5d",
        hex_8: "#375b6d",
        hex_9: "#59291a"
      },
      {
        original_file_name: "Vibrant Butterfly Wings (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9183953,
        file_size_megabytes: 8.76,
        width: 3072,
        height: 5472,
        primary: "#ebdabe",
        secondary: "#1d1e24",
        tertiary: "#922b0f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#cf7022",
        hex_5: "#b28856",
        hex_6: "#2a71a0",
        hex_7: "#74a6b6",
        hex_8: "#7e8283",
        hex_9: "#4198bc"
      },
      {
        original_file_name: "Vibrant Butterfly Wings (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7869195,
        file_size_megabytes: 7.5,
        width: 3072,
        height: 5472,
        primary: "#cfd6c7",
        secondary: "#b05470",
        tertiary: "#1a1813",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#57452f",
        hex_5: "#c3a2c4",
        hex_6: "#ce9c6a",
        hex_7: "#b64314",
        hex_8: "#276cb4",
        hex_9: "#3195ce"
      },
      {
        original_file_name: "Vibrant Butterfly Wings (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9360314,
        file_size_megabytes: 8.93,
        width: 3072,
        height: 5472,
        primary: "#e09032",
        secondary: "#2376aa",
        tertiary: "#3facd7",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#241110",
        hex_5: "#8b4418",
        hex_6: "#183f66",
        hex_7: "#c72d0a",
        hex_8: "#5f250d",
        hex_9: "#3b6375"
      }
    ]
  },
  "Water Droplet On Leaf": {
    environment_title: "Water Droplet On Leaf",
    images: [
      {
        original_file_name: "Water Droplet On Leaf (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6819884,
        file_size_megabytes: 6.5,
        width: 3072,
        height: 5472,
        primary: "#4c6722",
        secondary: "#090e05",
        tertiary: "#d3e2bc",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#748e62",
        hex_5: "#88a068",
        hex_6: "#9bb873",
        hex_7: "#779647",
        hex_8: "#99a49f",
        hex_9: "#1b3607"
      },
      {
        original_file_name: "Water Droplet On Leaf (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7359334,
        file_size_megabytes: 7.02,
        width: 3072,
        height: 5472,
        primary: "#cbdeb3",
        secondary: "#425c0d",
        tertiary: "#98ba71",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#152005",
        hex_5: "#8aa38e",
        hex_6: "#81a26b",
        hex_7: "#607c51",
        hex_8: "#6b9130",
        hex_9: "#1b3404"
      },
      {
        original_file_name: "Water Droplet On Leaf (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7330737,
        file_size_megabytes: 6.99,
        width: 3072,
        height: 5472,
        primary: "#c9d992",
        secondary: "#354d1a",
        tertiary: "#0a0f04",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#849c5e",
        hex_5: "#6e855f",
        hex_6: "#617a44",
        hex_7: "#95b94e",
        hex_8: "#708f42",
        hex_9: "#98a796"
      },
      {
        original_file_name: "Water Droplet On Leaf (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6712343,
        file_size_megabytes: 6.4,
        width: 3072,
        height: 5472,
        primary: "#3b5b18",
        secondary: "#cde2c6",
        tertiary: "#8fbb79",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#060804",
        hex_5: "#7aa162",
        hex_6: "#67914d",
        hex_7: "#90a294",
        hex_8: "#60775d",
        hex_9: "#132f04"
      }
    ]
  }
};
export default HyperCloseups;
