import { EnvironmentEntry } from "@/types/database";
const MinimalistAbstract: Record<string, EnvironmentEntry> = {
  "Abstract Skyline Silhouette": {
    environment_title: "Abstract Skyline Silhouette",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Abstract Skyline Silhouette (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5501368,
        file_size_megabytes: 5.25,
        width: 3072,
        height: 5472,
        primary: "#d9ddcf",
        secondary: "#86b6c2",
        tertiary: "#5f9caf",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#457f94",
        hex_5: "#091629",
        hex_6: "#275b75",
        hex_7: "#21495d",
        hex_8: "#a59c90",
        hex_9: "#5d5b56"
      },
      {
        original_file_name: "Abstract Skyline Silhouette (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5125693,
        file_size_megabytes: 4.89,
        width: 3072,
        height: 5472,
        primary: "#1e3449",
        secondary: "#e2ba9e",
        tertiary: "#faf9ec",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f67a3d",
        hex_5: "#4096a6",
        hex_6: "#944330",
        hex_7: "#90736d",
        hex_8: "#8d8a8b",
        hex_9: "#f39156"
      },
      {
        original_file_name: "Abstract Skyline Silhouette (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4818232,
        file_size_megabytes: 4.6,
        width: 3072,
        height: 5472,
        primary: "#1d283d",
        secondary: "#f7c192",
        tertiary: "#48718c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8e726d",
        hex_5: "#61a7b7",
        hex_6: "#4a99b5",
        hex_7: "#fafaef",
        hex_8: "#f88941",
        hex_9: "#c45c4c"
      },
      {
        original_file_name: "Abstract Skyline Silhouette (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5671108,
        file_size_megabytes: 5.41,
        width: 3072,
        height: 5472,
        primary: "#e2dacb",
        secondary: "#172c3c",
        tertiary: "#859da1",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#608593",
        hex_5: "#a5b6b6",
        hex_6: "#9babb4",
        hex_7: "#52707e",
        hex_8: "#43616d",
        hex_9: "#b4aca1"
      }
    ]
  },
  "Circular Flow": {
    environment_title: "Circular Flow",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Circular Flow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4801073,
        file_size_megabytes: 4.58,
        width: 3072,
        height: 5472,
        primary: "#1a152a",
        secondary: "#9e4832",
        tertiary: "#f7e6d3",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e9893d",
        hex_5: "#e3a174",
        hex_6: "#f5c19a",
        hex_7: "#ab9594",
        hex_8: "#aaa7b0",
        hex_9: "#6c7c9c"
      },
      {
        original_file_name: "Circular Flow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4875520,
        file_size_megabytes: 4.65,
        width: 3072,
        height: 5472,
        primary: "#1e3b4d",
        secondary: "#f2e5da",
        tertiary: "#f0a565",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4ba7b0",
        hex_5: "#d47c40",
        hex_6: "#8ab0af",
        hex_7: "#9b4b25",
        hex_8: "#998e8d",
        hex_9: "#dcb296"
      },
      {
        original_file_name: "Circular Flow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5443928,
        file_size_megabytes: 5.19,
        width: 3072,
        height: 5472,
        primary: "#193d4e",
        secondary: "#f27e46",
        tertiary: "#f2eadf",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#9c3418",
        hex_5: "#48b3c4",
        hex_6: "#c28b73",
        hex_7: "#87c1c9",
        hex_8: "#359cb2",
        hex_9: "#e6a67e"
      },
      {
        original_file_name: "Circular Flow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6023597,
        file_size_megabytes: 5.74,
        width: 3072,
        height: 5472,
        primary: "#e76658",
        secondary: "#1d243a",
        tertiary: "#1dbcdf",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#27608d",
        hex_5: "#118fba",
        hex_6: "#f8e7c6",
        hex_7: "#782f43",
        hex_8: "#5e6b65",
        hex_9: "#cea6af"
      }
    ]
  },
  "Circular Harmony": {
    environment_title: "Circular Harmony",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Circular Harmony (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4178870,
        file_size_megabytes: 3.99,
        width: 3072,
        height: 5472,
        primary: "#19535a",
        secondary: "#f3e4d8",
        tertiary: "#5fc5c3",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f41c54",
        hex_5: "#f5a44d",
        hex_6: "#8ecec5",
        hex_7: "#e29979",
        hex_8: "#e8c9ad",
        hex_9: "#a9a0a1"
      },
      {
        original_file_name: "Circular Harmony (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3671453,
        file_size_megabytes: 3.5,
        width: 3072,
        height: 5472,
        primary: "#1c2537",
        secondary: "#fbf2e5",
        tertiary: "#f49b1f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#c0611c",
        hex_5: "#aa9e90",
        hex_6: "#afaeb1",
        hex_7: "#d4c7b3",
        hex_8: "#747c7d",
        hex_9: "#bfacad"
      },
      {
        original_file_name: "Circular Harmony (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4958341,
        file_size_megabytes: 4.73,
        width: 3072,
        height: 5472,
        primary: "#18394e",
        secondary: "#82c8cf",
        tertiary: "#7f3644",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f7a184",
        hex_5: "#f98b31",
        hex_6: "#f5f6ed",
        hex_7: "#ea6676",
        hex_8: "#40a7af",
        hex_9: "#dcd5ac"
      },
      {
        original_file_name: "Circular Harmony (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5198422,
        file_size_megabytes: 4.96,
        width: 3072,
        height: 5472,
        primary: "#f8bf8f",
        secondary: "#4abcbc",
        tertiary: "#272c33",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f24f59",
        hex_5: "#36868b",
        hex_6: "#2c5e71",
        hex_7: "#3e96a4",
        hex_8: "#816558",
        hex_9: "#553e3a"
      }
    ]
  },
  "Color Block Gradient": {
    environment_title: "Color Block Gradient",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Color Block Gradient (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5493614,
        file_size_megabytes: 5.24,
        width: 3072,
        height: 5472,
        primary: "#222827",
        secondary: "#9ea49f",
        tertiary: "#e2c2b5",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6b7d7c",
        hex_5: "#4e5454",
        hex_6: "#b8746a",
        hex_7: "#c1c8c1",
        hex_8: "#53544c",
        hex_9: "#534c53"
      },
      {
        original_file_name: "Color Block Gradient (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5911051,
        file_size_megabytes: 5.64,
        width: 3072,
        height: 5472,
        primary: "#557171",
        secondary: "#8f5f5e",
        tertiary: "#d9ae9f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#82a09d",
        hex_5: "#b77572",
        hex_6: "#e5d9cf",
        hex_7: "#a7a6a0",
        hex_8: "#b26c64",
        hex_9: "#e2cbc4"
      },
      {
        original_file_name: "Color Block Gradient (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5400948,
        file_size_megabytes: 5.15,
        width: 3072,
        height: 5472,
        primary: "#23292f",
        secondary: "#e1c3b8",
        tertiary: "#6c9796",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a19c94",
        hex_5: "#aac7bf",
        hex_6: "#547b7c",
        hex_7: "#c46c55",
        hex_8: "#c47454",
        hex_9: "#b4bcc4"
      },
      {
        original_file_name: "Color Block Gradient (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5602999,
        file_size_megabytes: 5.34,
        width: 3072,
        height: 5472,
        primary: "#e1c4b7",
        secondary: "#914f44",
        tertiary: "#1e4f55",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#889692",
        hex_5: "#bd8171",
        hex_6: "#a7b9b6",
        hex_7: "#d4977f",
        hex_8: "#cd7058",
        hex_9: "#54847c"
      }
    ]
  },
  "Diagonal Light Streaks": {
    environment_title: "Diagonal Light Streaks",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Diagonal Light Streaks (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4549071,
        file_size_megabytes: 4.34,
        width: 3072,
        height: 5472,
        primary: "#e2c9c9",
        secondary: "#0a0910",
        tertiary: "#5f454f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5263b7",
        hex_5: "#24253d",
        hex_6: "#2e385f",
        hex_7: "#af598d",
        hex_8: "#324f7b",
        hex_9: "#7e8de5"
      },
      {
        original_file_name: "Diagonal Light Streaks (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4416010,
        file_size_megabytes: 4.21,
        width: 3072,
        height: 5472,
        primary: "#cfa192",
        secondary: "#0b0a0d",
        tertiary: "#5e3434",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#351d1c",
        hex_5: "#4eb7cf",
        hex_6: "#9a3c6b",
        hex_7: "#467499",
        hex_8: "#335567",
        hex_9: "#263a52"
      },
      {
        original_file_name: "Diagonal Light Streaks (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 2745086,
        file_size_megabytes: 2.62,
        width: 3072,
        height: 5472,
        primary: "#cca17c",
        secondary: "#060504",
        tertiary: "#593624",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#2d1a14",
        hex_5: "#874227",
        hex_6: "#747474",
        hex_7: "#7c6c74",
        hex_8: "#3c3c3c",
        hex_9: "#3c343c"
      },
      {
        original_file_name: "Diagonal Light Streaks (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3804199,
        file_size_megabytes: 3.63,
        width: 3072,
        height: 5472,
        primary: "#dbb3ba",
        secondary: "#06060e",
        tertiary: "#4b4565",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6b99c0",
        hex_5: "#a24489",
        hex_6: "#57629a",
        hex_7: "#161c31",
        hex_8: "#54302a",
        hex_9: "#3b443d"
      }
    ]
  },
  "Dot Matrix Simplicity": {
    environment_title: "Dot Matrix Simplicity",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Dot Matrix Simplicity (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6515523,
        file_size_megabytes: 6.21,
        width: 3072,
        height: 5472,
        primary: "#3b3b3c",
        secondary: "#141414",
        tertiary: "#2c2c2c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1e1e1e",
        hex_5: "#0c0b0c",
        hex_6: "#040404",
        hex_7: "#24242c",
        hex_8: "#0c0c14",
        hex_9: "#040c08"
      },
      {
        original_file_name: "Dot Matrix Simplicity (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 2348037,
        file_size_megabytes: 2.24,
        width: 3072,
        height: 5472,
        primary: "#f1f1f1",
        secondary: "#535353",
        tertiary: "#9d9d9d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7c7c7c",
        hex_5: "#747474",
        hex_6: "#848484",
        hex_7: "#b4b4b4",
        hex_8: "#c8c8c8",
        hex_9: "#bcbcbc"
      },
      {
        original_file_name: "Dot Matrix Simplicity (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3095420,
        file_size_megabytes: 2.95,
        width: 3072,
        height: 5472,
        primary: "#343434",
        secondary: "#f0f0f0",
        tertiary: "#999999",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#747473",
        hex_5: "#6c6c6b",
        hex_6: "#7c7c7c",
        hex_7: "#b4b4b3",
        hex_8: "#c4c4c4",
        hex_9: "#bcbcb4"
      },
      {
        original_file_name: "Dot Matrix Simplicity (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5014531,
        file_size_megabytes: 4.78,
        width: 3072,
        height: 5472,
        primary: "#f4f4f4",
        secondary: "#fcfcfc",
        tertiary: "#ececec",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e4e4e4",
        hex_5: "#dcdcdc",
        hex_6: "#d1d1d1",
        hex_7: "#f8f8f4",
        hex_8: "#f8fc100",
        hex_9: "#f8fc100"
      }
    ]
  },
  "Geometric Harmony": {
    environment_title: "Geometric Harmony",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Geometric Harmony (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6027885,
        file_size_megabytes: 5.75,
        width: 3072,
        height: 5472,
        primary: "#161514",
        secondary: "#d6d5d2",
        tertiary: "#888886",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a5a5a3",
        hex_5: "#9c9c94",
        hex_6: "#6c6c64",
        hex_7: "#9c9494",
        hex_8: "#b4acac",
        hex_9: "#6c6464"
      },
      {
        original_file_name: "Geometric Harmony (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6130979,
        file_size_megabytes: 5.85,
        width: 3072,
        height: 5472,
        primary: "#ababa8",
        secondary: "#282724",
        tertiary: "#6c6c68",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#efeeeb",
        hex_5: "#4c4b46",
        hex_6: "#7c7b78",
        hex_7: "#53544c",
        hex_8: "#83847c",
        hex_9: "#444c44"
      },
      {
        original_file_name: "Geometric Harmony (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5289670,
        file_size_megabytes: 5.04,
        width: 3072,
        height: 5472,
        primary: "#d4d2ce",
        secondary: "#787874",
        tertiary: "#1a1a18",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#56534f",
        hex_5: "#8c8b87",
        hex_6: "#5b5c53",
        hex_7: "#9e9d99",
        hex_8: "#93948c",
        hex_9: "#4c544c"
      },
      {
        original_file_name: "Geometric Harmony (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5177478,
        file_size_megabytes: 4.94,
        width: 3072,
        height: 5472,
        primary: "#c6c5c1",
        secondary: "#2b2b28",
        tertiary: "#5c5a56",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#706f6c",
        hex_5: "#63645c",
        hex_6: "#9a9a97",
        hex_7: "#8c8b88",
        hex_8: "#545c54",
        hex_9: "#93948c"
      }
    ]
  },
  "Linear Harmony": {
    environment_title: "Linear Harmony",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Linear Harmony (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3498322,
        file_size_megabytes: 3.34,
        width: 3072,
        height: 5472,
        primary: "#faf9ee",
        secondary: "#f16629",
        tertiary: "#28485a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#91c6c7",
        hex_5: "#b6a597",
        hex_6: "#73acad",
        hex_7: "#d1cabd",
        hex_8: "#847c7b",
        hex_9: "#bcb3ae"
      },
      {
        original_file_name: "Linear Harmony (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3829061,
        file_size_megabytes: 3.65,
        width: 3072,
        height: 5472,
        primary: "#163348",
        secondary: "#51bbd6",
        tertiary: "#3594b3",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f5f6f3",
        hex_5: "#c1ccd0",
        hex_6: "#aca4a4",
        hex_7: "#d5d4cb",
        hex_8: "#d4cbc9",
        hex_9: "#b4b0ac"
      },
      {
        original_file_name: "Linear Harmony (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3742599,
        file_size_megabytes: 3.57,
        width: 3072,
        height: 5472,
        primary: "#162333",
        secondary: "#93b5c1",
        tertiary: "#fafaf4",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#68727c",
        hex_5: "#b5cbd5",
        hex_6: "#b1b2ba",
        hex_7: "#7b7c74",
        hex_8: "#546c7c",
        hex_9: "#b3bcb4"
      },
      {
        original_file_name: "Linear Harmony (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4599228,
        file_size_megabytes: 4.39,
        width: 3072,
        height: 5472,
        primary: "#13263b",
        secondary: "#bfd8e7",
        tertiary: "#6e98ab",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#eca54c",
        hex_5: "#f2ca89",
        hex_6: "#f6f3e7",
        hex_7: "#626060",
        hex_8: "#93928e",
        hex_9: "#54949c"
      }
    ]
  },
  "Linear Symmetry": {
    environment_title: "Linear Symmetry",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Linear Symmetry (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 1964796,
        file_size_megabytes: 1.87,
        width: 3072,
        height: 5472,
        primary: "#3d3d3d",
        secondary: "#878787",
        tertiary: "#ededed",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#646464",
        hex_5: "#5c5c5c",
        hex_6: "#6c6c6c",
        hex_7: "#bcbcbc",
        hex_8: "#a4a4a4",
        hex_9: "#acacac"
      },
      {
        original_file_name: "Linear Symmetry (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3657667,
        file_size_megabytes: 3.49,
        width: 3072,
        height: 5472,
        primary: "#eee6e1",
        secondary: "#0b111b",
        tertiary: "#f46536",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a3a5a7",
        hex_5: "#7b6665",
        hex_6: "#463639",
        hex_7: "#575a5f",
        hex_8: "#515453",
        hex_9: "#8c849c"
      },
      {
        original_file_name: "Linear Symmetry (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3992685,
        file_size_megabytes: 3.81,
        width: 3072,
        height: 5472,
        primary: "#f9f4e8",
        secondary: "#5a5959",
        tertiary: "#959390",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#aaa9ae",
        hex_5: "#7c8484",
        hex_6: "#c1beb7",
        hex_7: "#b3b4b4",
        hex_8: "#857c68",
        hex_9: "#84746c"
      },
      {
        original_file_name: "Linear Symmetry (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 2935015,
        file_size_megabytes: 2.8,
        width: 3072,
        height: 5472,
        primary: "#434342",
        secondary: "#f3f3f1",
        tertiary: "#929291",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#747472",
        hex_5: "#b4b4b2",
        hex_6: "#c5c5c3",
        hex_7: "#7c7c74",
        hex_8: "#bbbcb4",
        hex_9: "#6c746c"
      }
    ]
  },
  "Minimalist Mountain Silhouette": {
    environment_title: "Minimalist Mountain Silhouette",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Minimalist Mountain Silhouette (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4666130,
        file_size_megabytes: 4.45,
        width: 3072,
        height: 5472,
        primary: "#243946",
        secondary: "#f3e6d3",
        tertiary: "#829695",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#845f5a",
        hex_5: "#e19a74",
        hex_6: "#eb8b58",
        hex_7: "#bca197",
        hex_8: "#c7b39e",
        hex_9: "#5c8c8c"
      },
      {
        original_file_name: "Minimalist Mountain Silhouette (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5127268,
        file_size_megabytes: 4.89,
        width: 3072,
        height: 5472,
        primary: "#ecceb6",
        secondary: "#3f535e",
        tertiary: "#a39890",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#778c8e",
        hex_5: "#050607",
        hex_6: "#6d767b",
        hex_7: "#a0b6ae",
        hex_8: "#d35944",
        hex_9: "#a4acb4"
      },
      {
        original_file_name: "Minimalist Mountain Silhouette (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4718008,
        file_size_megabytes: 4.5,
        width: 3072,
        height: 5472,
        primary: "#1e333f",
        secondary: "#e4e1d4",
        tertiary: "#92a5a9",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e47952",
        hex_5: "#e68d6c",
        hex_6: "#d0b6a4",
        hex_7: "#6e4f45",
        hex_8: "#547474",
        hex_9: "#a69c9a"
      },
      {
        original_file_name: "Minimalist Mountain Silhouette (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5713194,
        file_size_megabytes: 5.45,
        width: 3072,
        height: 5472,
        primary: "#182834",
        secondary: "#ac9d95",
        tertiary: "#f0ebda",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6e4241",
        hex_5: "#658486",
        hex_6: "#ecb399",
        hex_7: "#e5d7bf",
        hex_8: "#b25d40",
        hex_9: "#488c8c"
      }
    ]
  },
  "Minimalist Rainbow Spectrum": {
    environment_title: "Minimalist Rainbow Spectrum",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Minimalist Rainbow Spectrum (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5051212,
        file_size_megabytes: 4.82,
        width: 3072,
        height: 5472,
        primary: "#f2e1d7",
        secondary: "#7397ca",
        tertiary: "#fba172",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a1bcd2",
        hex_5: "#c67fb1",
        hex_6: "#d1a0bd",
        hex_7: "#bfd0d8",
        hex_8: "#f6e29d",
        hex_9: "#846ca4"
      },
      {
        original_file_name: "Minimalist Rainbow Spectrum (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4592389,
        file_size_megabytes: 4.38,
        width: 3072,
        height: 5472,
        primary: "#5a95bc",
        secondary: "#f2ebdc",
        tertiary: "#b07f9a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#97b8cb",
        hex_5: "#f2b981",
        hex_6: "#d7acb5",
        hex_7: "#f1dca2",
        hex_8: "#c2d4de",
        hex_9: "#74cce8"
      },
      {
        original_file_name: "Minimalist Rainbow Spectrum (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4856063,
        file_size_megabytes: 4.63,
        width: 3072,
        height: 5472,
        primary: "#e099b5",
        secondary: "#91abde",
        tertiary: "#efe1cc",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#bae0ce",
        hex_5: "#d6e5f4",
        hex_6: "#fbc594",
        hex_7: "#f2b5be",
        hex_8: "#9fddd4",
        hex_9: "#f1dca8"
      },
      {
        original_file_name: "Minimalist Rainbow Spectrum (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3105572,
        file_size_megabytes: 2.96,
        width: 3072,
        height: 5472,
        primary: "#f0a15f",
        secondary: "#5fbfc4",
        tertiary: "#f9f5ee",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f1ca99",
        hex_5: "#ca6f95",
        hex_6: "#a9d2d6",
        hex_7: "#86ca78",
        hex_8: "#f5e5bc",
        hex_9: "#e3b2c0"
      }
    ]
  },
  "Minimalist Star Constellation": {
    environment_title: "Minimalist Star Constellation",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Minimalist Star Constellation (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4212991,
        file_size_megabytes: 4.02,
        width: 3072,
        height: 5472,
        primary: "#10121a",
        secondary: "#435169",
        tertiary: "#b7c2d1",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#252f43",
        hex_5: "#5d789a",
        hex_6: "#7495b6",
        hex_7: "#494c51",
        hex_8: "#545154",
        hex_9: "#342f34"
      },
      {
        original_file_name: "Minimalist Star Constellation (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3389163,
        file_size_megabytes: 3.23,
        width: 3072,
        height: 5472,
        primary: "#14121b",
        secondary: "#b5b9c3",
        tertiary: "#5b5e69",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#393b45",
        hex_5: "#444856",
        hex_6: "#4b545f",
        hex_7: "#79808e",
        hex_8: "#838c9a",
        hex_9: "#2b343e"
      },
      {
        original_file_name: "Minimalist Star Constellation (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4068450,
        file_size_megabytes: 3.88,
        width: 3072,
        height: 5472,
        primary: "#0b0f1a",
        secondary: "#4a5669",
        tertiary: "#b4b7c0",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#273043",
        hex_5: "#5db1c8",
        hex_6: "#527c98",
        hex_7: "#4e4e50",
        hex_8: "#2d2d30",
        hex_9: "#414c54"
      },
      {
        original_file_name: "Minimalist Star Constellation (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3633382,
        file_size_megabytes: 3.47,
        width: 3072,
        height: 5472,
        primary: "#17171f",
        secondary: "#b7b9c1",
        tertiary: "#5c5d68",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#363743",
        hex_5: "#818d9c",
        hex_6: "#545254",
        hex_7: "#778094",
        hex_8: "#343134",
        hex_9: "#4c5454"
      }
    ]
  },
  "Monochrome Waves": {
    environment_title: "Monochrome Waves",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Monochrome Waves (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5133628,
        file_size_megabytes: 4.9,
        width: 3072,
        height: 5472,
        primary: "#343434",
        secondary: "#e0e0e0",
        tertiary: "#848484",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#acacac",
        hex_5: "#9c9c9b",
        hex_6: "#646463",
        hex_7: "#bcbcbb",
        hex_8: "#a3a49c",
        hex_9: "#6c6c64"
      },
      {
        original_file_name: "Monochrome Waves (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5097403,
        file_size_megabytes: 4.86,
        width: 3072,
        height: 5472,
        primary: "#d3d3d3",
        secondary: "#2a2a2a",
        tertiary: "#787878",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5c5b5c",
        hex_5: "#545454",
        hex_6: "#646464",
        hex_7: "#8c8c8b",
        hex_8: "#a0a0a0",
        hex_9: "#949493"
      },
      {
        original_file_name: "Monochrome Waves (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3918714,
        file_size_megabytes: 3.74,
        width: 3072,
        height: 5472,
        primary: "#d5d5d5",
        secondary: "#121212",
        tertiary: "#797979",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#575757",
        hex_5: "#4c4c4c",
        hex_6: "#646464",
        hex_7: "#a0a0a0",
        hex_8: "#8c8c8b",
        hex_9: "#949493"
      },
      {
        original_file_name: "Monochrome Waves (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4445372,
        file_size_megabytes: 4.24,
        width: 3072,
        height: 5472,
        primary: "#dadad9",
        secondary: "#1c1c1c",
        tertiary: "#7b7b7b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5c5c5c",
        hex_5: "#545454",
        hex_6: "#a4a4a4",
        hex_7: "#949493",
        hex_8: "#9c9c94",
        hex_9: "#64645c"
      }
    ]
  },
  "Muted Geometric Shapes": {
    environment_title: "Muted Geometric Shapes",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Muted Geometric Shapes (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4295767,
        file_size_megabytes: 4.1,
        width: 3072,
        height: 5472,
        primary: "#1f3d4a",
        secondary: "#faeddc",
        tertiary: "#ef8a5c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#d6694f",
        hex_5: "#e9a381",
        hex_6: "#a2bbb8",
        hex_7: "#e5c4ac",
        hex_8: "#93a2a7",
        hex_9: "#74948d"
      },
      {
        original_file_name: "Muted Geometric Shapes (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4117169,
        file_size_megabytes: 3.93,
        width: 3072,
        height: 5472,
        primary: "#233c49",
        secondary: "#f8e9d9",
        tertiary: "#e68a50",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#cfa486",
        hex_5: "#f8cdaf",
        hex_6: "#b2c2bb",
        hex_7: "#609493",
        hex_8: "#8a654f",
        hex_9: "#9fa2a4"
      },
      {
        original_file_name: "Muted Geometric Shapes (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4349628,
        file_size_megabytes: 4.15,
        width: 3072,
        height: 5472,
        primary: "#27424e",
        secondary: "#f3e5d5",
        tertiary: "#f69550",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#b59889",
        hex_5: "#97b5b4",
        hex_6: "#f0b08f",
        hex_7: "#6e949a",
        hex_8: "#865a4c",
        hex_9: "#e5b8a7"
      },
      {
        original_file_name: "Muted Geometric Shapes (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4095528,
        file_size_megabytes: 3.91,
        width: 3072,
        height: 5472,
        primary: "#1d363f",
        secondary: "#f2874f",
        tertiary: "#f9f3e3",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#b8967c",
        hex_5: "#8eadad",
        hex_6: "#8da2a6",
        hex_7: "#729d90",
        hex_8: "#f8c0a2",
        hex_9: "#d96845"
      }
    ]
  },
  "Negative Space Triangles": {
    environment_title: "Negative Space Triangles",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Negative Space Triangles (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4177591,
        file_size_megabytes: 3.98,
        width: 3072,
        height: 5472,
        primary: "#f35c2f",
        secondary: "#41b3c1",
        tertiary: "#2292ab",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f6ecd5",
        hex_5: "#101b27",
        hex_6: "#784c4b",
        hex_7: "#24455a",
        hex_8: "#377c85",
        hex_9: "#284c65"
      },
      {
        original_file_name: "Negative Space Triangles (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4175018,
        file_size_megabytes: 3.98,
        width: 3072,
        height: 5472,
        primary: "#1893a9",
        secondary: "#f1383c",
        tertiary: "#f78f35",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#71acb3",
        hex_5: "#111620",
        hex_6: "#fafbf3",
        hex_7: "#b0d5da",
        hex_8: "#d58a84",
        hex_9: "#f3c298"
      },
      {
        original_file_name: "Negative Space Triangles (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4409004,
        file_size_megabytes: 4.2,
        width: 3072,
        height: 5472,
        primary: "#cee7e7",
        secondary: "#070e22",
        tertiary: "#1c9eb4",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3699a5",
        hex_5: "#f4563a",
        hex_6: "#62b3bb",
        hex_7: "#195669",
        hex_8: "#376872",
        hex_9: "#54555d"
      },
      {
        original_file_name: "Negative Space Triangles (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4981450,
        file_size_megabytes: 4.75,
        width: 3072,
        height: 5472,
        primary: "#f4ac62",
        secondary: "#0e6778",
        tertiary: "#6ac9cb",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f13e45",
        hex_5: "#070611",
        hex_6: "#533d5c",
        hex_7: "#5b2a3d",
        hex_8: "#378897",
        hex_9: "#173a44"
      }
    ]
  },
  "Single Line Wave": {
    environment_title: "Single Line Wave",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Single Line Wave (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5184314,
        file_size_megabytes: 4.94,
        width: 3072,
        height: 5472,
        primary: "#faf2e7",
        secondary: "#a39a8c",
        tertiary: "#cec5b7",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#dcd4c6",
        hex_5: "#bcb4a7",
        hex_6: "#d8ccc4",
        hex_7: "#b8aca4",
        hex_8: "#e4d9cb",
        hex_9: "#e8dcd4"
      },
      {
        original_file_name: "Single Line Wave (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 2529268,
        file_size_megabytes: 2.41,
        width: 3072,
        height: 5472,
        primary: "#e3e3e3",
        secondary: "#565656",
        tertiary: "#929292",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#acacac",
        hex_5: "#747474",
        hex_6: "#a4a4a4",
        hex_7: "#7c7c7c",
        hex_8: "#bcbcbc",
        hex_9: "#b4b4b4"
      },
      {
        original_file_name: "Single Line Wave (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3944948,
        file_size_megabytes: 3.76,
        width: 3072,
        height: 5472,
        primary: "#f9f9f7",
        secondary: "#abaaa8",
        tertiary: "#585758",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#c9c8c6",
        hex_5: "#7c7c79",
        hex_6: "#bcbcb3",
        hex_7: "#84817c",
        hex_8: "#dcd4d3",
        hex_9: "#b4bcb4"
      },
      {
        original_file_name: "Single Line Wave (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4666389,
        file_size_megabytes: 4.45,
        width: 3072,
        height: 5472,
        primary: "#5e9393",
        secondary: "#9bc5c6",
        tertiary: "#faf7ef",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#233c3e",
        hex_5: "#c4dedd",
        hex_6: "#7e7a76",
        hex_7: "#bdb2aa",
        hex_8: "#86847b",
        hex_9: "#c2bdb2"
      }
    ]
  },
  "Sparse Color Blocks": {
    environment_title: "Sparse Color Blocks",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Sparse Color Blocks (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 2883482,
        file_size_megabytes: 2.75,
        width: 3072,
        height: 5472,
        primary: "#364448",
        secondary: "#f8eae2",
        tertiary: "#e69e41",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f7b083",
        hex_5: "#cd9b84",
        hex_6: "#c86b0e",
        hex_7: "#668c8b",
        hex_8: "#b1b5b2",
        hex_9: "#ccc0b7"
      },
      {
        original_file_name: "Sparse Color Blocks (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4005508,
        file_size_megabytes: 3.82,
        width: 3072,
        height: 5472,
        primary: "#ece0d7",
        secondary: "#0d0f1b",
        tertiary: "#f25834",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#f5b331",
        hex_5: "#37bfc2",
        hex_6: "#b89283",
        hex_7: "#c0b4a7",
        hex_8: "#bfb289",
        hex_9: "#8bbbb8"
      },
      {
        original_file_name: "Sparse Color Blocks (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3392293,
        file_size_megabytes: 3.24,
        width: 3072,
        height: 5472,
        primary: "#ece2d5",
        secondary: "#191d21",
        tertiary: "#f6a022",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#69b3b3",
        hex_5: "#80b1ae",
        hex_6: "#cc6a39",
        hex_7: "#b2a386",
        hex_8: "#ebcfa6",
        hex_9: "#aca4a4"
      },
      {
        original_file_name: "Sparse Color Blocks (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4001693,
        file_size_megabytes: 3.82,
        width: 3072,
        height: 5472,
        primary: "#2c4e55",
        secondary: "#eee5da",
        tertiary: "#de9c74",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#d85f32",
        hex_5: "#e86f3a",
        hex_6: "#c3b1a3",
        hex_7: "#a09996",
        hex_8: "#a6a79e",
        hex_9: "#6c948d"
      }
    ]
  },
  "Subdued Overlapping Circles": {
    environment_title: "Subdued Overlapping Circles",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Subdued Overlapping Circles (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4126918,
        file_size_megabytes: 3.94,
        width: 3072,
        height: 5472,
        primary: "#3d545c",
        secondary: "#f4d2b6",
        tertiary: "#abbec5",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#faf8f1",
        hex_5: "#e1b493",
        hex_6: "#948174",
        hex_7: "#849cac",
        hex_8: "#9c8c7c",
        hex_9: "#c0ac9c"
      },
      {
        original_file_name: "Subdued Overlapping Circles (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3840282,
        file_size_megabytes: 3.66,
        width: 3072,
        height: 5472,
        primary: "#426065",
        secondary: "#b77f61",
        tertiary: "#fbf8e8",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#da9167",
        hex_5: "#9daaa7",
        hex_6: "#f6c7a9",
        hex_7: "#c4d3d1",
        hex_8: "#e7b195",
        hex_9: "#7c9c9a"
      },
      {
        original_file_name: "Subdued Overlapping Circles (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4571022,
        file_size_megabytes: 4.36,
        width: 3072,
        height: 5472,
        primary: "#325964",
        secondary: "#f2905d",
        tertiary: "#f5dec8",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#93bebd",
        hex_5: "#dea985",
        hex_6: "#f9f9f2",
        hex_7: "#84847c",
        hex_8: "#7cb0b8",
        hex_9: "#d0aca0"
      },
      {
        original_file_name: "Subdued Overlapping Circles (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 3886869,
        file_size_megabytes: 3.71,
        width: 3072,
        height: 5472,
        primary: "#657e7f",
        secondary: "#a4b5ae",
        tertiary: "#ecd5bf",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e7a374",
        hex_5: "#fbfbf4",
        hex_6: "#f8c9a3",
        hex_7: "#9b9c96",
        hex_8: "#cdbbad",
        hex_9: "#8cacb4"
      }
    ]
  },
  "Subtle Gradient Lines": {
    environment_title: "Subtle Gradient Lines",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Subtle Gradient Lines (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4855641,
        file_size_megabytes: 4.63,
        width: 3072,
        height: 5472,
        primary: "#f29fa9",
        secondary: "#201a2d",
        tertiary: "#fbe2d2",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a86785",
        hex_5: "#863d5e",
        hex_6: "#e06983",
        hex_7: "#cb99d4",
        hex_8: "#9f514c",
        hex_9: "#745c7c"
      },
      {
        original_file_name: "Subtle Gradient Lines (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5056843,
        file_size_megabytes: 4.82,
        width: 3072,
        height: 5472,
        primary: "#493b7e",
        secondary: "#467da4",
        tertiary: "#fab7c2",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e06fc5",
        hex_5: "#98aecd",
        hex_6: "#fbe6d7",
        hex_7: "#405474",
        hex_8: "#f89b9c",
        hex_9: "#886478"
      },
      {
        original_file_name: "Subtle Gradient Lines (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5683723,
        file_size_megabytes: 5.42,
        width: 3072,
        height: 5472,
        primary: "#432743",
        secondary: "#f5cac8",
        tertiary: "#ab6984",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#db92af",
        hex_5: "#ab8cbd",
        hex_6: "#d8848b",
        hex_7: "#795673",
        hex_8: "#80545c",
        hex_9: "#5c4874"
      },
      {
        original_file_name: "Subtle Gradient Lines (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5918383,
        file_size_megabytes: 5.64,
        width: 3072,
        height: 5472,
        primary: "#582353",
        secondary: "#ecacbd",
        tertiary: "#676190",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a95c91",
        hex_5: "#ece9e3",
        hex_6: "#959ac1",
        hex_7: "#f28588",
        hex_8: "#7e465c",
        hex_9: "#8a3c84"
      }
    ]
  },
  "Subtle Textured Layers": {
    environment_title: "Subtle Textured Layers",
    environment_moral: "",
    environment_prompt: "",
    images: [
      {
        original_file_name: "Subtle Textured Layers (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5553520,
        file_size_megabytes: 5.3,
        width: 3072,
        height: 5472,
        primary: "#e1dbd1",
        secondary: "#45535a",
        tertiary: "#828f90",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#dbac92",
        hex_5: "#a4b9b8",
        hex_6: "#726662",
        hex_7: "#647c7d",
        hex_8: "#a49c9c",
        hex_9: "#847464"
      },
      {
        original_file_name: "Subtle Textured Layers (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5125073,
        file_size_megabytes: 4.89,
        width: 3072,
        height: 5472,
        primary: "#98a6a7",
        secondary: "#46555b",
        tertiary: "#e8cdc1",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#fbf8ef",
        hex_5: "#bac1c3",
        hex_6: "#84848b",
        hex_7: "#91897c",
        hex_8: "#b4aca6",
        hex_9: "#b4ac9c"
      },
      {
        original_file_name: "Subtle Textured Layers (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4596379,
        file_size_megabytes: 4.38,
        width: 3072,
        height: 5472,
        primary: "#486a6e",
        secondary: "#f6f0e3",
        tertiary: "#9a6649",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8ba7a7",
        hex_5: "#e3ae90",
        hex_6: "#c5906f",
        hex_7: "#c0c7c3",
        hex_8: "#6caca0",
        hex_9: "#b8b4b5"
      },
      {
        original_file_name: "Subtle Textured Layers (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5641529,
        file_size_megabytes: 5.38,
        width: 3072,
        height: 5472,
        primary: "#394951",
        secondary: "#e5d3c5",
        tertiary: "#889999",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#adbfc2",
        hex_5: "#b69d8c",
        hex_6: "#fbf5ed",
        hex_7: "#716960",
        hex_8: "#959c9d",
        hex_9: "#6e6c6c"
      }
    ]
  }
};
export default MinimalistAbstract;
