import { EnvironmentEntry } from "@/types/database";
const NatureWonders: Record<string, EnvironmentEntry> = {
  "Ancient Redwood Grove": {
    environment_title: "Ancient Redwood Grove",
    images: [
      {
        original_file_name: "Ancient Redwood Grove (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9618614,
        file_size_megabytes: 9.17,
        width: 3072,
        height: 5472,
        primary: "#c6ba88",
        secondary: "#252316",
        tertiary: "#756e44",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#909e96",
        hex_5: "#808c91",
        hex_6: "#56674f",
        hex_7: "#514d2a",
        hex_8: "#4a5659",
        hex_9: "#a45414"
      },
      {
        original_file_name: "Ancient Redwood Grove (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9206863,
        file_size_megabytes: 8.78,
        width: 3072,
        height: 5472,
        primary: "#c8be91",
        secondary: "#221e11",
        tertiary: "#76734c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4c4b27",
        hex_5: "#7f8c93",
        hex_6: "#8f9f94",
        hex_7: "#586739",
        hex_8: "#4e5258",
        hex_9: "#9c7439"
      },
      {
        original_file_name: "Ancient Redwood Grove (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9463997,
        file_size_megabytes: 9.03,
        width: 3072,
        height: 5472,
        primary: "#c8ba80",
        secondary: "#272516",
        tertiary: "#787148",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#524e2f",
        hex_5: "#58654c",
        hex_6: "#4c5657",
        hex_7: "#939d8f",
        hex_8: "#899097",
        hex_9: "#9c6c3a"
      },
      {
        original_file_name: "Ancient Redwood Grove (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9063478,
        file_size_megabytes: 8.64,
        width: 3072,
        height: 5472,
        primary: "#cbc298",
        secondary: "#222111",
        tertiary: "#76744d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4c4e2c",
        hex_5: "#566732",
        hex_6: "#929d59",
        hex_7: "#8e8f90",
        hex_8: "#555856",
        hex_9: "#9c6424"
      }
    ]
  },
  "Autumn Mist Over Lavender Fields": {
    environment_title: "Autumn Mist Over Lavender Fields",
    images: [
      {
        original_file_name: "Autumn Mist Over Lavender Fields (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8908812,
        file_size_megabytes: 8.5,
        width: 3072,
        height: 5472,
        primary: "#e3c2b5",
        secondary: "#342930",
        tertiary: "#9a787f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a4a9b0",
        hex_5: "#a292a6",
        hex_6: "#705454",
        hex_7: "#7e7476",
        hex_8: "#755a7b",
        hex_9: "#bc6c2c"
      },
      {
        original_file_name: "Autumn Mist Over Lavender Fields (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9110267,
        file_size_megabytes: 8.69,
        width: 3072,
        height: 5472,
        primary: "#33272e",
        secondary: "#dec3ba",
        tertiary: "#997578",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a48ca6",
        hex_5: "#715051",
        hex_6: "#ada697",
        hex_7: "#797b7d",
        hex_8: "#7c5b6f",
        hex_9: "#bc7c7f"
      },
      {
        original_file_name: "Autumn Mist Over Lavender Fields (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9712383,
        file_size_megabytes: 9.26,
        width: 3072,
        height: 5472,
        primary: "#d3b7ae",
        secondary: "#30232a",
        tertiary: "#9f7368",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#b0a7ad",
        hex_5: "#9e92af",
        hex_6: "#724e49",
        hex_7: "#685575",
        hex_8: "#7a716c",
        hex_9: "#bc6c74"
      },
      {
        original_file_name: "Autumn Mist Over Lavender Fields (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8655821,
        file_size_megabytes: 8.25,
        width: 3072,
        height: 5472,
        primary: "#dcbdb9",
        secondary: "#2c222e",
        tertiary: "#966c7a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a288a5",
        hex_5: "#684f56",
        hex_6: "#6f5674",
        hex_7: "#766c75",
        hex_8: "#b3a4a1",
        hex_9: "#bc6c88"
      }
    ]
  },
  "Bioluminescent Bay": {
    environment_title: "Bioluminescent Bay",
    images: [
      {
        original_file_name: "Bioluminescent Bay (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6480301,
        file_size_megabytes: 6.18,
        width: 3072,
        height: 5472,
        primary: "#10aded",
        secondary: "#061626",
        tertiary: "#125b85",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#0a76ba",
        hex_5: "#b49840",
        hex_6: "#0b3b5f",
        hex_7: "#563e11",
        hex_8: "#4c5e46",
        hex_9: "#123c47"
      },
      {
        original_file_name: "Bioluminescent Bay (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6295979,
        file_size_megabytes: 6.0,
        width: 3072,
        height: 5472,
        primary: "#b29495",
        secondary: "#06273e",
        tertiary: "#2c5e84",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e7dac",
        hex_5: "#23bcc3",
        hex_6: "#104861",
        hex_7: "#0d0e0a",
        hex_8: "#55485c",
        hex_9: "#086867"
      },
      {
        original_file_name: "Bioluminescent Bay (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6342163,
        file_size_megabytes: 6.05,
        width: 3072,
        height: 5472,
        primary: "#071d2e",
        secondary: "#3790c1",
        tertiary: "#15658d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#094465",
        hex_5: "#1d8da1",
        hex_6: "#0a5f70",
        hex_7: "#0564ac",
        hex_8: "#5e7d93",
        hex_9: "#36444c"
      },
      {
        original_file_name: "Bioluminescent Bay (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6273812,
        file_size_megabytes: 5.98,
        width: 3072,
        height: 5472,
        primary: "#05182a",
        secondary: "#1a5e82",
        tertiary: "#ab9a8d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1f7bae",
        hex_5: "#093f5e",
        hex_6: "#3ea1d5",
        hex_7: "#3f5e69",
        hex_8: "#163c4b",
        hex_9: "#494c51"
      }
    ]
  },
  "Blooming Desert Cactus": {
    environment_title: "Blooming Desert Cactus",
    images: [
      {
        original_file_name: "Blooming Desert Cactus (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9315132,
        file_size_megabytes: 8.88,
        width: 3072,
        height: 5472,
        primary: "#836642",
        secondary: "#211911",
        tertiary: "#da9a72",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e5cea1",
        hex_5: "#83b4d0",
        hex_6: "#7b1727",
        hex_7: "#95888a",
        hex_8: "#bba363",
        hex_9: "#3c5c74"
      },
      {
        original_file_name: "Blooming Desert Cactus (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8866905,
        file_size_megabytes: 8.46,
        width: 3072,
        height: 5472,
        primary: "#e2bb93",
        secondary: "#8db9cb",
        tertiary: "#312617",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#98734b",
        hex_5: "#e3275a",
        hex_6: "#6e512b",
        hex_7: "#776f4f",
        hex_8: "#6598ae",
        hex_9: "#605b5f"
      },
      {
        original_file_name: "Blooming Desert Cactus (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7992902,
        file_size_megabytes: 7.62,
        width: 3072,
        height: 5472,
        primary: "#dec5a7",
        secondary: "#2c251b",
        tertiary: "#a1afa8",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#976855",
        hex_5: "#7d9497",
        hex_6: "#3f5666",
        hex_7: "#5e757c",
        hex_8: "#e32847",
        hex_9: "#6b4730"
      },
      {
        original_file_name: "Blooming Desert Cactus (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9142278,
        file_size_megabytes: 8.72,
        width: 3072,
        height: 5472,
        primary: "#63492e",
        secondary: "#ddb282",
        tertiary: "#1a1713",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a68b5d",
        hex_5: "#95bdcd",
        hex_6: "#9d5e44",
        hex_7: "#d72261",
        hex_8: "#8f726f",
        hex_9: "#8398ab"
      }
    ]
  },
  "Coral Reef Wonderland": {
    environment_title: "Coral Reef Wonderland",
    images: [
      {
        original_file_name: "Coral Reef Wonderland (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8451144,
        file_size_megabytes: 8.06,
        width: 3072,
        height: 5472,
        primary: "#c3b48f",
        secondary: "#2f2620",
        tertiary: "#79b7c8",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#0a5f89",
        hex_5: "#558b87",
        hex_6: "#1b8db3",
        hex_7: "#825c38",
        hex_8: "#505c4f",
        hex_9: "#af4921"
      },
      {
        original_file_name: "Coral Reef Wonderland (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8197903,
        file_size_megabytes: 7.82,
        width: 3072,
        height: 5472,
        primary: "#c2b186",
        secondary: "#2f2720",
        tertiary: "#13648d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4791b5",
        hex_5: "#7eb9d2",
        hex_6: "#618b89",
        hex_7: "#83653e",
        hex_8: "#506652",
        hex_9: "#a44c2c"
      },
      {
        original_file_name: "Coral Reef Wonderland (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8462800,
        file_size_megabytes: 8.07,
        width: 3072,
        height: 5472,
        primary: "#c2af7f",
        secondary: "#358baf",
        tertiary: "#27221d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#80b5c1",
        hex_5: "#778265",
        hex_6: "#7c5830",
        hex_7: "#515440",
        hex_8: "#1c5b78",
        hex_9: "#a44c08"
      },
      {
        original_file_name: "Coral Reef Wonderland (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9105171,
        file_size_megabytes: 8.68,
        width: 3072,
        height: 5472,
        primary: "#c7b48b",
        secondary: "#29221d",
        tertiary: "#0e7dae",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#658874",
        hex_5: "#71c0bb",
        hex_6: "#7c5e3c",
        hex_7: "#156381",
        hex_8: "#4a5d45",
        hex_9: "#aa5038"
      }
    ]
  },
  "Crystal Caves With Stalactites": {
    environment_title: "Crystal Caves With Stalactites",
    images: [
      {
        original_file_name: "Crystal Caves With Stalactites (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8678723,
        file_size_megabytes: 8.28,
        width: 3072,
        height: 5472,
        primary: "#112835",
        secondary: "#b8d3e2",
        tertiary: "#7dacc5",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#557d93",
        hex_5: "#6596b1",
        hex_6: "#29576d",
        hex_7: "#556e79",
        hex_8: "#55626d",
        hex_9: "#949ca8"
      },
      {
        original_file_name: "Crystal Caves With Stalactites (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8464937,
        file_size_megabytes: 8.07,
        width: 3072,
        height: 5472,
        primary: "#12252b",
        secondary: "#50798c",
        tertiary: "#b2cfe2",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7fabc3",
        hex_5: "#6896b1",
        hex_6: "#2e5667",
        hex_7: "#566d72",
        hex_8: "#585e5e",
        hex_9: "#94948c"
      },
      {
        original_file_name: "Crystal Caves With Stalactites (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8284610,
        file_size_megabytes: 7.9,
        width: 3072,
        height: 5472,
        primary: "#11222d",
        secondary: "#b1cbdb",
        tertiary: "#53798f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#81aac2",
        hex_5: "#6b96b1",
        hex_6: "#2f5367",
        hex_7: "#566c72",
        hex_8: "#566168",
        hex_9: "#949494"
      },
      {
        original_file_name: "Crystal Caves With Stalactites (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7930775,
        file_size_megabytes: 7.56,
        width: 3072,
        height: 5472,
        primary: "#0d202a",
        secondary: "#aec9d9",
        tertiary: "#7faabe",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4f7a90",
        hex_5: "#7098af",
        hex_6: "#275266",
        hex_7: "#356472",
        hex_8: "#545c66",
        hex_9: "#9494a4"
      }
    ]
  },
  "Frozen Glacier Under Northern Lights": {
    environment_title: "Frozen Glacier Under Northern Lights",
    images: [
      {
        original_file_name: "Frozen Glacier Under Northern Lights (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6657146,
        file_size_megabytes: 6.35,
        width: 3072,
        height: 5472,
        primary: "#234a5a",
        secondary: "#76cba8",
        tertiary: "#040d18",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6f9bb9",
        hex_5: "#488e88",
        hex_6: "#437591",
        hex_7: "#5d6473",
        hex_8: "#0e1a2f",
        hex_9: "#8a9590"
      },
      {
        original_file_name: "Frozen Glacier Under Northern Lights (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6719837,
        file_size_megabytes: 6.41,
        width: 3072,
        height: 5472,
        primary: "#aac8a3",
        secondary: "#122e3f",
        tertiary: "#48bca8",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#348a87",
        hex_5: "#6697b5",
        hex_6: "#62516d",
        hex_7: "#416c89",
        hex_8: "#19636a",
        hex_9: "#204d68"
      },
      {
        original_file_name: "Frozen Glacier Under Northern Lights (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7113991,
        file_size_megabytes: 6.78,
        width: 3072,
        height: 5472,
        primary: "#1d3c52",
        secondary: "#af8d96",
        tertiary: "#52b6a6",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3c838e",
        hex_5: "#07111f",
        hex_6: "#6e4e73",
        hex_7: "#5e97b7",
        hex_8: "#2a6787",
        hex_9: "#0d132e"
      },
      {
        original_file_name: "Frozen Glacier Under Northern Lights (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6814203,
        file_size_megabytes: 6.5,
        width: 3072,
        height: 5472,
        primary: "#6bc2b2",
        secondary: "#1b3347",
        tertiary: "#38728b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3c92b2",
        hex_5: "#267c65",
        hex_6: "#5d4e67",
        hex_7: "#040c14",
        hex_8: "#9f766a",
        hex_9: "#7da845"
      }
    ]
  },
  "Glacial Ice Fields": {
    environment_title: "Glacial Ice Fields",
    images: [
      {
        original_file_name: "Glacial Ice Fields (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7626035,
        file_size_megabytes: 7.27,
        width: 3072,
        height: 5472,
        primary: "#326a95",
        secondary: "#c9d4dc",
        tertiary: "#87a4b5",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#08334f",
        hex_5: "#97bfd1",
        hex_6: "#6097b7",
        hex_7: "#6399cc",
        hex_8: "#063b67",
        hex_9: "#a49494"
      },
      {
        original_file_name: "Glacial Ice Fields (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8065986,
        file_size_megabytes: 7.69,
        width: 3072,
        height: 5472,
        primary: "#2e6992",
        secondary: "#c8d7e1",
        tertiary: "#0f2b45",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#85a2b4",
        hex_5: "#93c0d6",
        hex_6: "#71a7d5",
        hex_7: "#5e97b9",
        hex_8: "#0a335c",
        hex_9: "#a49c9e"
      },
      {
        original_file_name: "Glacial Ice Fields (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7522054,
        file_size_megabytes: 7.17,
        width: 3072,
        height: 5472,
        primary: "#5383a6",
        secondary: "#d3dbe2",
        tertiary: "#0b344e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#96aec0",
        hex_5: "#0a5782",
        hex_6: "#a4c8dd",
        hex_7: "#073a67",
        hex_8: "#70afd8",
        hex_9: "#b4acb2"
      },
      {
        original_file_name: "Glacial Ice Fields (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7003241,
        file_size_megabytes: 6.68,
        width: 3072,
        height: 5472,
        primary: "#195b88",
        secondary: "#c0cfd9",
        tertiary: "#89a7ba",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#9fbfce",
        hex_5: "#062e4d",
        hex_6: "#043162",
        hex_7: "#5392b2",
        hex_8: "#55a5d0",
        hex_9: "#aca4b0"
      }
    ]
  },
  "Glowing Bioluminescent Fungi": {
    environment_title: "Glowing Bioluminescent Fungi",
    images: [
      {
        original_file_name: "Glowing Bioluminescent Fungi (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6871906,
        file_size_megabytes: 6.55,
        width: 3072,
        height: 5472,
        primary: "#c48041",
        secondary: "#27b2d8",
        tertiary: "#081216",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#27626c",
        hex_5: "#1279a8",
        hex_6: "#0c4466",
        hex_7: "#0d3245",
        hex_8: "#543c29",
        hex_9: "#1b391e"
      },
      {
        original_file_name: "Glowing Bioluminescent Fungi (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6758220,
        file_size_megabytes: 6.45,
        width: 3072,
        height: 5472,
        primary: "#b36b34",
        secondary: "#091619",
        tertiary: "#36bbe7",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1372ad",
        hex_5: "#5c3e32",
        hex_6: "#10486b",
        hex_7: "#396371",
        hex_8: "#abf5f4",
        hex_9: "#0e4044"
      },
      {
        original_file_name: "Glowing Bioluminescent Fungi (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7055156,
        file_size_megabytes: 6.73,
        width: 3072,
        height: 5472,
        primary: "#b56e30",
        secondary: "#0a1416",
        tertiary: "#26b2cd",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#2d6862",
        hex_5: "#177ea3",
        hex_6: "#134a5f",
        hex_7: "#5a3e26",
        hex_8: "#0f413a",
        hex_9: "#cdc85b"
      },
      {
        original_file_name: "Glowing Bioluminescent Fungi (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7095155,
        file_size_megabytes: 6.77,
        width: 3072,
        height: 5472,
        primary: "#b66360",
        secondary: "#08151b",
        tertiary: "#40afcd",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#2b7ba3",
        hex_5: "#2b6677",
        hex_6: "#1e4e64",
        hex_7: "#c6dbc8",
        hex_8: "#5a322c",
        hex_9: "#11414b"
      }
    ]
  },
  "Grand Canyon Sunset": {
    environment_title: "Grand Canyon Sunset",
    images: [
      {
        original_file_name: "Grand Canyon Sunset (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9831438,
        file_size_megabytes: 9.38,
        width: 3072,
        height: 5472,
        primary: "#d07749",
        secondary: "#251a1e",
        tertiary: "#7f4632",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#56332b",
        hex_5: "#3c5a82",
        hex_6: "#353f5d",
        hex_7: "#515567",
        hex_8: "#958a92",
        hex_9: "#aa3319"
      },
      {
        original_file_name: "Grand Canyon Sunset (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9121487,
        file_size_megabytes: 8.7,
        width: 3072,
        height: 5472,
        primary: "#cc7d63",
        secondary: "#242129",
        tertiary: "#763d2d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#605f7c",
        hex_5: "#522e26",
        hex_6: "#ae3516",
        hex_7: "#273b5b",
        hex_8: "#8c7583",
        hex_9: "#4f5060"
      },
      {
        original_file_name: "Grand Canyon Sunset (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9193124,
        file_size_megabytes: 8.77,
        width: 3072,
        height: 5472,
        primary: "#3d2927",
        secondary: "#d4774f",
        tertiary: "#835448",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#444052",
        hex_5: "#10131f",
        hex_6: "#475872",
        hex_7: "#605558",
        hex_8: "#907d7c",
        hex_9: "#a43424"
      },
      {
        original_file_name: "Grand Canyon Sunset (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8391958,
        file_size_megabytes: 8.0,
        width: 3072,
        height: 5472,
        primary: "#2d201f",
        secondary: "#db8431",
        tertiary: "#835e4a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5a3c37",
        hex_5: "#78726d",
        hex_6: "#5f5f5f",
        hex_7: "#3d4452",
        hex_8: "#b6391b",
        hex_9: "#9c8c74"
      }
    ]
  },
  "Luminous Jellyfish In Deep Sea": {
    environment_title: "Luminous Jellyfish In Deep Sea",
    images: [
      {
        original_file_name: "Luminous Jellyfish In Deep Sea (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6678721,
        file_size_megabytes: 6.37,
        width: 3072,
        height: 5472,
        primary: "#c6926e",
        secondary: "#0b1f39",
        tertiary: "#5a6c81",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#64423d",
        hex_5: "#799ea5",
        hex_6: "#6b6360",
        hex_7: "#914022",
        hex_8: "#6a84a9",
        hex_9: "#0c0813"
      },
      {
        original_file_name: "Luminous Jellyfish In Deep Sea (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6452698,
        file_size_megabytes: 6.15,
        width: 3072,
        height: 5472,
        primary: "#c99771",
        secondary: "#071226",
        tertiary: "#2a5e78",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#49aaaa",
        hex_5: "#2670a3",
        hex_6: "#5b3c34",
        hex_7: "#4c5853",
        hex_8: "#103251",
        hex_9: "#953e12"
      },
      {
        original_file_name: "Luminous Jellyfish In Deep Sea (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6088603,
        file_size_megabytes: 5.81,
        width: 3072,
        height: 5472,
        primary: "#c29e7d",
        secondary: "#06172e",
        tertiary: "#50aec7",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#36647c",
        hex_5: "#327eaa",
        hex_6: "#0b3359",
        hex_7: "#5e423a",
        hex_8: "#923f0e",
        hex_9: "#53625c"
      },
      {
        original_file_name: "Luminous Jellyfish In Deep Sea (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6679652,
        file_size_megabytes: 6.37,
        width: 3072,
        height: 5472,
        primary: "#bc8c6f",
        secondary: "#09172c",
        tertiary: "#33aecf",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#2e6182",
        hex_5: "#574149",
        hex_6: "#237fae",
        hex_7: "#103d5e",
        hex_8: "#655f65",
        hex_9: "#873a11"
      }
    ]
  },
  "Majestic Waterfall Cascade": {
    environment_title: "Majestic Waterfall Cascade",
    images: [
      {
        original_file_name: "Majestic Waterfall Cascade (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10010227,
        file_size_megabytes: 9.55,
        width: 3072,
        height: 5472,
        primary: "#18271d",
        secondary: "#bbc2c3",
        tertiary: "#757461",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#87a490",
        hex_5: "#718a9c",
        hex_6: "#4b6d58",
        hex_7: "#4d4737",
        hex_8: "#375563",
        hex_9: "#9c7c6e"
      },
      {
        original_file_name: "Majestic Waterfall Cascade (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11690098,
        file_size_megabytes: 11.15,
        width: 3072,
        height: 5472,
        primary: "#16241e",
        secondary: "#d1d4cc",
        tertiary: "#737b50",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8aa1a0",
        hex_5: "#708a9e",
        hex_6: "#526859",
        hex_7: "#474f2b",
        hex_8: "#3c5661",
        hex_9: "#9c9485"
      },
      {
        original_file_name: "Majestic Waterfall Cascade (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9666170,
        file_size_megabytes: 9.22,
        width: 3072,
        height: 5472,
        primary: "#1c2921",
        secondary: "#c0cfd0",
        tertiary: "#89a298",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#707d6e",
        hex_5: "#536a59",
        hex_6: "#7b909e",
        hex_7: "#4a4f42",
        hex_8: "#4a5a66",
        hex_9: "#9c7c6c"
      },
      {
        original_file_name: "Majestic Waterfall Cascade (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11332367,
        file_size_megabytes: 10.81,
        width: 3072,
        height: 5472,
        primary: "#b4b9b0",
        secondary: "#15201a",
        tertiary: "#677550",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7ea19a",
        hex_5: "#608aa8",
        hex_6: "#5f523f",
        hex_7: "#2d4c36",
        hex_8: "#355562",
        hex_9: "#945c44"
      }
    ]
  },
  "Majestic Waterfall In Tropical Jungle": {
    environment_title: "Majestic Waterfall In Tropical Jungle",
    images: [
      {
        original_file_name: "Majestic Waterfall In Tropical Jungle (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8634657,
        file_size_megabytes: 8.23,
        width: 3072,
        height: 5472,
        primary: "#1b251b",
        secondary: "#bbced2",
        tertiary: "#5c745d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#85a18b",
        hex_5: "#778d9a",
        hex_6: "#3c513a",
        hex_7: "#465760",
        hex_8: "#94947d",
        hex_9: "#5c5949"
      },
      {
        original_file_name: "Majestic Waterfall In Tropical Jungle (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8787253,
        file_size_megabytes: 8.38,
        width: 3072,
        height: 5472,
        primary: "#18251d",
        secondary: "#bccfc8",
        tertiary: "#82a397",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5e785a",
        hex_5: "#6f8a9e",
        hex_6: "#3d5335",
        hex_7: "#415965",
        hex_8: "#5f604d",
        hex_9: "#94946c"
      },
      {
        original_file_name: "Majestic Waterfall In Tropical Jungle (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9125554,
        file_size_megabytes: 8.7,
        width: 3072,
        height: 5472,
        primary: "#18251b",
        secondary: "#bbcecf",
        tertiary: "#597263",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#85a2a2",
        hex_5: "#728d9a",
        hex_6: "#39513a",
        hex_7: "#3f5761",
        hex_8: "#5f5847",
        hex_9: "#948c44"
      },
      {
        original_file_name: "Majestic Waterfall In Tropical Jungle (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8894676,
        file_size_megabytes: 8.48,
        width: 3072,
        height: 5472,
        primary: "#c3d1c7",
        secondary: "#131e13",
        tertiary: "#6b7c65",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8ba396",
        hex_5: "#768d9b",
        hex_6: "#394c33",
        hex_7: "#4e6851",
        hex_8: "#40535b",
        hex_9: "#9c8c65"
      }
    ]
  },
  "Northern Forest In Autumn": {
    environment_title: "Northern Forest In Autumn",
    images: [
      {
        original_file_name: "Northern Forest In Autumn (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 12217549,
        file_size_megabytes: 11.65,
        width: 3072,
        height: 5472,
        primary: "#4b2f17",
        secondary: "#ce7823",
        tertiary: "#934f1d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#161912",
        hex_5: "#9c907f",
        hex_6: "#6d623f",
        hex_7: "#807778",
        hex_8: "#584d4a",
        hex_9: "#c52c28"
      },
      {
        original_file_name: "Northern Forest In Autumn (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11182272,
        file_size_megabytes: 10.66,
        width: 3072,
        height: 5472,
        primary: "#d67519",
        secondary: "#2e291b",
        tertiary: "#924816",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#673114",
        hex_5: "#988235",
        hex_6: "#bb2d19",
        hex_7: "#2f4245",
        hex_8: "#686969",
        hex_9: "#4f5542"
      },
      {
        original_file_name: "Northern Forest In Autumn (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11457629,
        file_size_megabytes: 10.93,
        width: 3072,
        height: 5472,
        primary: "#965224",
        secondary: "#d77d24",
        tertiary: "#17201c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3f3421",
        hex_5: "#5b3e21",
        hex_6: "#6d1608",
        hex_7: "#b69042",
        hex_8: "#8e7062",
        hex_9: "#ca3410"
      },
      {
        original_file_name: "Northern Forest In Autumn (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11323913,
        file_size_megabytes: 10.8,
        width: 3072,
        height: 5472,
        primary: "#9cbacc",
        secondary: "#623614",
        tertiary: "#7c95a6",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#d5a982",
        hex_5: "#1e1912",
        hex_6: "#a25a1f",
        hex_7: "#53616e",
        hex_8: "#91856a",
        hex_9: "#bcac64"
      }
    ]
  },
  "Rainforest Waterfall": {
    environment_title: "Rainforest Waterfall",
    images: [
      {
        original_file_name: "Rainforest Waterfall (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9304293,
        file_size_megabytes: 8.87,
        width: 3072,
        height: 5472,
        primary: "#151f15",
        secondary: "#baccbe",
        tertiary: "#5a7749",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#80a471",
        hex_5: "#738b9c",
        hex_6: "#374c2b",
        hex_7: "#40525c",
        hex_8: "#949465",
        hex_9: "#5c5b44"
      },
      {
        original_file_name: "Rainforest Waterfall (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9167262,
        file_size_megabytes: 8.74,
        width: 3072,
        height: 5472,
        primary: "#bacbb6",
        secondary: "#121c10",
        tertiary: "#567645",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7ea563",
        hex_5: "#758a95",
        hex_6: "#324d21",
        hex_7: "#3c5156",
        hex_8: "#58573a",
        hex_9: "#94744c"
      },
      {
        original_file_name: "Rainforest Waterfall (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9402709,
        file_size_megabytes: 8.97,
        width: 3072,
        height: 5472,
        primary: "#bdcebf",
        secondary: "#151e12",
        tertiary: "#5b734f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#82a472",
        hex_5: "#738896",
        hex_6: "#3a4d2a",
        hex_7: "#42545c",
        hex_8: "#5d594d",
        hex_9: "#94847c"
      },
      {
        original_file_name: "Rainforest Waterfall (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8588299,
        file_size_megabytes: 8.19,
        width: 3072,
        height: 5472,
        primary: "#171e13",
        secondary: "#b4c4b7",
        tertiary: "#617556",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#85a080",
        hex_5: "#7b8e9a",
        hex_6: "#3b4c2f",
        hex_7: "#47555a",
        hex_8: "#948c64",
        hex_9: "#5c5c4f"
      }
    ]
  },
  "Savannah Sunrise": {
    environment_title: "Savannah Sunrise",
    images: [
      {
        original_file_name: "Savannah Sunrise (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8818795,
        file_size_megabytes: 8.41,
        width: 3072,
        height: 5472,
        primary: "#d3913b",
        secondary: "#626871",
        tertiary: "#452a10",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8d633a",
        hex_5: "#4c525d",
        hex_6: "#160b05",
        hex_7: "#6c6860",
        hex_8: "#a49c8c",
        hex_9: "#ac4404"
      },
      {
        original_file_name: "Savannah Sunrise (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9982137,
        file_size_megabytes: 9.52,
        width: 3072,
        height: 5472,
        primary: "#d69648",
        secondary: "#2c1c0c",
        tertiary: "#8d6a4a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#65696e",
        hex_5: "#663b13",
        hex_6: "#525053",
        hex_7: "#a3947f",
        hex_8: "#ac4c04",
        hex_9: "#84848c"
      },
      {
        original_file_name: "Savannah Sunrise (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8856727,
        file_size_megabytes: 8.45,
        width: 3072,
        height: 5472,
        primary: "#dd9a43",
        secondary: "#5c3818",
        tertiary: "#1e1208",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#887864",
        hex_5: "#6d6762",
        hex_6: "#9f5d1c",
        hex_7: "#97847c",
        hex_8: "#b49c7c",
        hex_9: "#c0540c"
      },
      {
        original_file_name: "Savannah Sunrise (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9636274,
        file_size_megabytes: 9.19,
        width: 3072,
        height: 5472,
        primary: "#e3a63d",
        secondary: "#4f3116",
        tertiary: "#915b26",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#150c06",
        hex_5: "#786549",
        hex_6: "#70564d",
        hex_7: "#ac9c80",
        hex_8: "#a49484",
        hex_9: "#b45404"
      }
    ]
  },
  "Serene Alpine Meadow": {
    environment_title: "Serene Alpine Meadow",
    images: [
      {
        original_file_name: "Serene Alpine Meadow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9480592,
        file_size_megabytes: 9.04,
        width: 3072,
        height: 5472,
        primary: "#4d80b1",
        secondary: "#53501d",
        tertiary: "#dedcd0",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e6175",
        hex_5: "#918855",
        hex_6: "#111509",
        hex_7: "#a3b8ca",
        hex_8: "#788464",
        hex_9: "#bc4634"
      },
      {
        original_file_name: "Serene Alpine Meadow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9719798,
        file_size_megabytes: 9.27,
        width: 3072,
        height: 5472,
        primary: "#514d20",
        secondary: "#d7d2c4",
        tertiary: "#5382b7",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#908457",
        hex_5: "#575e6f",
        hex_6: "#9a97ab",
        hex_7: "#131406",
        hex_8: "#a7b5bf",
        hex_9: "#7a8475"
      },
      {
        original_file_name: "Serene Alpine Meadow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9953959,
        file_size_megabytes: 9.49,
        width: 3072,
        height: 5472,
        primary: "#4b7fae",
        secondary: "#d3cfbe",
        tertiary: "#4e4c1c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#455e77",
        hex_5: "#918e63",
        hex_6: "#83713c",
        hex_7: "#131204",
        hex_8: "#9eb8ce",
        hex_9: "#b06207"
      },
      {
        original_file_name: "Serene Alpine Meadow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9812258,
        file_size_megabytes: 9.36,
        width: 3072,
        height: 5472,
        primary: "#4780b3",
        secondary: "#565424",
        tertiary: "#cdcbc2",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5e6e7e",
        hex_5: "#1c1a06",
        hex_6: "#1c5575",
        hex_7: "#897944",
        hex_8: "#95914a",
        hex_9: "#9eb5cc"
      }
    ]
  },
  "SnowCapped Volcano": {
    environment_title: "SnowCapped Volcano",
    images: [
      {
        original_file_name: "SnowCapped Volcano (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7730900,
        file_size_megabytes: 7.37,
        width: 3072,
        height: 5472,
        primary: "#cdd2d8",
        secondary: "#245c8f",
        tertiary: "#1c1c1e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3d7bb1",
        hex_5: "#8fa7b9",
        hex_6: "#294260",
        hex_7: "#60676f",
        hex_8: "#5c5b5e",
        hex_9: "#9c9498"
      },
      {
        original_file_name: "SnowCapped Volcano (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7503044,
        file_size_megabytes: 7.16,
        width: 3072,
        height: 5472,
        primary: "#ced1d2",
        secondary: "#19649e",
        tertiary: "#1a1a22",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7b93aa",
        hex_5: "#2d3a51",
        hex_6: "#142a49",
        hex_7: "#90b6ce",
        hex_8: "#82acd4",
        hex_9: "#9c8c8c"
      },
      {
        original_file_name: "SnowCapped Volcano (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7836918,
        file_size_megabytes: 7.47,
        width: 3072,
        height: 5472,
        primary: "#d4d5d6",
        secondary: "#154774",
        tertiary: "#1c1a1d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#89b4cf",
        hex_5: "#7e92a7",
        hex_6: "#5796c8",
        hex_7: "#67707d",
        hex_8: "#1f6eac",
        hex_9: "#a49492"
      },
      {
        original_file_name: "SnowCapped Volcano (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7672424,
        file_size_megabytes: 7.32,
        width: 3072,
        height: 5472,
        primary: "#284d78",
        secondary: "#d4d7db",
        tertiary: "#201c1e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8b98a9",
        hex_5: "#97b0c4",
        hex_6: "#2f70ac",
        hex_7: "#5d9cce",
        hex_8: "#5488b5",
        hex_9: "#aca4a5"
      }
    ]
  },
  "Sunlit Coral Reef": {
    environment_title: "Sunlit Coral Reef",
    images: [
      {
        original_file_name: "Sunlit Coral Reef (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8668002,
        file_size_megabytes: 8.27,
        width: 3072,
        height: 5472,
        primary: "#c09951",
        secondary: "#29211a",
        tertiary: "#1d89bc",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#08618f",
        hex_5: "#61bce9",
        hex_6: "#7d5424",
        hex_7: "#63857a",
        hex_8: "#4f5c4a",
        hex_9: "#a24130"
      },
      {
        original_file_name: "Sunlit Coral Reef (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8326334,
        file_size_megabytes: 7.94,
        width: 3072,
        height: 5472,
        primary: "#c0a682",
        secondary: "#0d8fb5",
        tertiary: "#281a14",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#53bed3",
        hex_5: "#0c5682",
        hex_6: "#568076",
        hex_7: "#7b4a2c",
        hex_8: "#525641",
        hex_9: "#b23620"
      },
      {
        original_file_name: "Sunlit Coral Reef (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8440580,
        file_size_megabytes: 8.05,
        width: 3072,
        height: 5472,
        primary: "#c5bb95",
        secondary: "#72acb3",
        tertiary: "#3293a9",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1e1916",
        hex_5: "#806641",
        hex_6: "#2d7885",
        hex_7: "#185575",
        hex_8: "#563924",
        hex_9: "#d04b19"
      },
      {
        original_file_name: "Sunlit Coral Reef (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8826217,
        file_size_megabytes: 8.42,
        width: 3072,
        height: 5472,
        primary: "#c29f6e",
        secondary: "#272929",
        tertiary: "#64b5ca",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#816345",
        hex_5: "#09517f",
        hex_6: "#1b8cb2",
        hex_7: "#327d84",
        hex_8: "#485c4b",
        hex_9: "#b82b3e"
      }
    ]
  },
  "Verdant Mangrove Forest": {
    environment_title: "Verdant Mangrove Forest",
    images: [
      {
        original_file_name: "Verdant Mangrove Forest (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10933185,
        file_size_megabytes: 10.43,
        width: 3072,
        height: 5472,
        primary: "#263b24",
        secondary: "#b4c18e",
        tertiary: "#6c8146",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8da98a",
        hex_5: "#686545",
        hex_6: "#51582c",
        hex_7: "#7b94a5",
        hex_8: "#0e0d08",
        hex_9: "#476462"
      },
      {
        original_file_name: "Verdant Mangrove Forest (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11802675,
        file_size_megabytes: 11.26,
        width: 3072,
        height: 5472,
        primary: "#233c25",
        secondary: "#b0bc75",
        tertiary: "#658241",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#89a854",
        hex_5: "#0c0d09",
        hex_6: "#525d2d",
        hex_7: "#65693d",
        hex_8: "#6c929d",
        hex_9: "#396165"
      },
      {
        original_file_name: "Verdant Mangrove Forest (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11044295,
        file_size_megabytes: 10.53,
        width: 3072,
        height: 5472,
        primary: "#1b2b1c",
        secondary: "#b2c594",
        tertiary: "#677a3d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#85a153",
        hex_5: "#414327",
        hex_6: "#45592c",
        hex_7: "#5e5f3f",
        hex_8: "#748d99",
        hex_9: "#425e61"
      },
      {
        original_file_name: "Verdant Mangrove Forest (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10466614,
        file_size_megabytes: 9.98,
        width: 3072,
        height: 5472,
        primary: "#aeb97a",
        secondary: "#1d2d21",
        tertiary: "#738339",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#60643f",
        hex_5: "#4a5a23",
        hex_6: "#414429",
        hex_7: "#8aa542",
        hex_8: "#76929c",
        hex_9: "#466263"
      }
    ]
  }
};
export default NatureWonders;
