import { EnvironmentEntry } from "@/types/database";
const NaturalLandscapes: Record<string, EnvironmentEntry> = {
  "Autumn Lakeside Reflection": {
    environment_title: "Autumn Lakeside Reflection",
    images: [
      {
        original_file_name: "Autumn Lakeside Reflection (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10843420,
        file_size_megabytes: 10.34,
        width: 3072,
        height: 5472,
        primary: "#c5cccb",
        secondary: "#91b4cb",
        tertiary: "#241e17",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#885a36",
        hex_5: "#bc4e14",
        hex_6: "#728c9e",
        hex_7: "#5b6d75",
        hex_8: "#5f4024",
        hex_9: "#42515c"
      },
      {
        original_file_name: "Autumn Lakeside Reflection (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10337386,
        file_size_megabytes: 9.86,
        width: 3072,
        height: 5472,
        primary: "#ca945b",
        secondary: "#2c2114",
        tertiary: "#88b4d3",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#895723",
        hex_5: "#5482a7",
        hex_6: "#234e6e",
        hex_7: "#5f3d1a",
        hex_8: "#b93416",
        hex_9: "#537073"
      },
      {
        original_file_name: "Autumn Lakeside Reflection (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 12011918,
        file_size_megabytes: 11.46,
        width: 3072,
        height: 5472,
        primary: "#bd742e",
        secondary: "#2b2415",
        tertiary: "#865528",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5b83a3",
        hex_5: "#bacfdc",
        hex_6: "#5e3d1e",
        hex_7: "#4e686c",
        hex_8: "#375673",
        hex_9: "#88977c"
      },
      {
        original_file_name: "Autumn Lakeside Reflection (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9110347,
        file_size_megabytes: 8.69,
        width: 3072,
        height: 5472,
        primary: "#2e2a25",
        secondary: "#84b2ca",
        tertiary: "#6294b1",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#cc7d42",
        hex_5: "#8f5129",
        hex_6: "#5a7885",
        hex_7: "#38596c",
        hex_8: "#67391b",
        hex_9: "#aca484"
      }
    ]
  },
  "Craggy Cliffside At Twilight": {
    environment_title: "Craggy Cliffside At Twilight",
    images: [
      {
        original_file_name: "Craggy Cliffside At Twilight (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7922408,
        file_size_megabytes: 7.56,
        width: 3072,
        height: 5472,
        primary: "#c69e92",
        secondary: "#77859c",
        tertiary: "#16161a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3d5068",
        hex_5: "#696774",
        hex_6: "#8b7d81",
        hex_7: "#442f2d",
        hex_8: "#534c4b",
        hex_9: "#b46843"
      },
      {
        original_file_name: "Craggy Cliffside At Twilight (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7870453,
        file_size_megabytes: 7.51,
        width: 3072,
        height: 5472,
        primary: "#222731",
        secondary: "#cd9884",
        tertiary: "#7d666d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7a7d92",
        hex_5: "#938e9b",
        hex_6: "#54434e",
        hex_7: "#5c6778",
        hex_8: "#4b586f",
        hex_9: "#a45c5b"
      },
      {
        original_file_name: "Craggy Cliffside At Twilight (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8044588,
        file_size_megabytes: 7.67,
        width: 3072,
        height: 5472,
        primary: "#c4948b",
        secondary: "#20222a",
        tertiary: "#785663",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7b96b1",
        hex_5: "#6a7895",
        hex_6: "#4c3d4d",
        hex_7: "#4b6279",
        hex_8: "#465065",
        hex_9: "#9e4c5e"
      },
      {
        original_file_name: "Craggy Cliffside At Twilight (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8339315,
        file_size_megabytes: 7.95,
        width: 3072,
        height: 5472,
        primary: "#c7958e",
        secondary: "#687086",
        tertiary: "#181215",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#82899e",
        hex_5: "#7e504f",
        hex_6: "#434359",
        hex_7: "#53586c",
        hex_8: "#512718",
        hex_9: "#a44c22"
      }
    ]
  },
  "Desolate Desert Dunes": {
    environment_title: "Desolate Desert Dunes",
    images: [
      {
        original_file_name: "Desolate Desert Dunes (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8732489,
        file_size_megabytes: 8.33,
        width: 3072,
        height: 5472,
        primary: "#cd8d4e",
        secondary: "#281711",
        tertiary: "#facb83",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#663c1d",
        hex_5: "#56260c",
        hex_6: "#84461a",
        hex_7: "#8d5a30",
        hex_8: "#dfb489",
        hex_9: "#444440"
      },
      {
        original_file_name: "Desolate Desert Dunes (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7959856,
        file_size_megabytes: 7.59,
        width: 3072,
        height: 5472,
        primary: "#d38a47",
        secondary: "#261e1d",
        tertiary: "#653b1f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#fbc974",
        hex_5: "#915627",
        hex_6: "#a65a20",
        hex_7: "#853b08",
        hex_8: "#d5a881",
        hex_9: "#444c48"
      },
      {
        original_file_name: "Desolate Desert Dunes (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8546127,
        file_size_megabytes: 8.15,
        width: 3072,
        height: 5472,
        primary: "#e8a961",
        secondary: "#3b2315",
        tertiary: "#a36532",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#72411e",
        hex_5: "#ad9b8a",
        hex_6: "#8d827b",
        hex_7: "#786352",
        hex_8: "#c46c32",
        hex_9: "#5a4b45"
      },
      {
        original_file_name: "Desolate Desert Dunes (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8933548,
        file_size_megabytes: 8.52,
        width: 3072,
        height: 5472,
        primary: "#e2a058",
        secondary: "#4a2d1c",
        tertiary: "#975d2a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#120a08",
        hex_5: "#8a989f",
        hex_6: "#707984",
        hex_7: "#735e50",
        hex_8: "#544b52",
        hex_9: "#b55c19"
      }
    ]
  },
  "Emerald Lake At Dusk": {
    environment_title: "Emerald Lake At Dusk",
    images: [
      {
        original_file_name: "Emerald Lake At Dusk (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8829793,
        file_size_megabytes: 8.42,
        width: 3072,
        height: 5472,
        primary: "#c5808f",
        secondary: "#6b6c91",
        tertiary: "#152b21",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#3e5e63",
        hex_5: "#6e5b63",
        hex_6: "#225644",
        hex_7: "#433c3c",
        hex_8: "#4b7f78",
        hex_9: "#a0543c"
      },
      {
        original_file_name: "Emerald Lake At Dusk (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8920446,
        file_size_megabytes: 8.51,
        width: 3072,
        height: 5472,
        primary: "#c27371",
        secondary: "#17352d",
        tertiary: "#6a574a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#286252",
        hex_5: "#827a94",
        hex_6: "#0c100a",
        hex_7: "#738772",
        hex_8: "#3d4b55",
        hex_9: "#9c4458"
      },
      {
        original_file_name: "Emerald Lake At Dusk (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8570705,
        file_size_megabytes: 8.17,
        width: 3072,
        height: 5472,
        primary: "#16322a",
        secondary: "#bc7f8c",
        tertiary: "#795a6d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7b70a0",
        hex_5: "#347069",
        hex_6: "#4c4240",
        hex_7: "#6a9796",
        hex_8: "#4e567f",
        hex_9: "#a43206"
      },
      {
        original_file_name: "Emerald Lake At Dusk (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8935551,
        file_size_megabytes: 8.52,
        width: 3072,
        height: 5472,
        primary: "#c9705c",
        secondary: "#1c312a",
        tertiary: "#794e57",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4d3e44",
        hex_5: "#4f4c6a",
        hex_6: "#7d8f93",
        hex_7: "#2c6a5e",
        hex_8: "#c6a4a5",
        hex_9: "#748f7c"
      }
    ]
  },
  "Foggy Coastal Cliffs": {
    environment_title: "Foggy Coastal Cliffs",
    images: [
      {
        original_file_name: "Foggy Coastal Cliffs (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7643363,
        file_size_megabytes: 7.29,
        width: 3072,
        height: 5472,
        primary: "#a6bac4",
        secondary: "#222c31",
        tertiary: "#869fab",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#67848e",
        hex_5: "#4b6671",
        hex_6: "#3f575f",
        hex_7: "#8bacac",
        hex_8: "#625a52",
        hex_9: "#8d9495"
      },
      {
        original_file_name: "Foggy Coastal Cliffs (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7693617,
        file_size_megabytes: 7.34,
        width: 3072,
        height: 5472,
        primary: "#a6beca",
        secondary: "#91a8b6",
        tertiary: "#1f282f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6a8591",
        hex_5: "#4f6a76",
        hex_6: "#3f5963",
        hex_7: "#949fa4",
        hex_8: "#5c686b",
        hex_9: "#749eac"
      },
      {
        original_file_name: "Foggy Coastal Cliffs (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8285848,
        file_size_megabytes: 7.9,
        width: 3072,
        height: 5472,
        primary: "#a4bac4",
        secondary: "#202627",
        tertiary: "#bfd1da",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#8ea7b1",
        hex_5: "#7b9198",
        hex_6: "#64838b",
        hex_7: "#546f79",
        hex_8: "#425b61",
        hex_9: "#b4bcc4"
      },
      {
        original_file_name: "Foggy Coastal Cliffs (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7830030,
        file_size_megabytes: 7.47,
        width: 3072,
        height: 5472,
        primary: "#99acb6",
        secondary: "#1e2627",
        tertiary: "#b8c9d3",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#778e97",
        hex_5: "#516973",
        hex_6: "#405860",
        hex_7: "#949ea2",
        hex_8: "#aabcbc",
        hex_9: "#5e5b4e"
      }
    ]
  },
  "Frozen River With Icebergs": {
    environment_title: "Frozen River With Icebergs",
    images: [
      {
        original_file_name: "Frozen River With Icebergs (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8860494,
        file_size_megabytes: 8.45,
        width: 3072,
        height: 5472,
        primary: "#44637c",
        secondary: "#ccdae5",
        tertiary: "#a1c1d8",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7ea9cc",
        hex_5: "#0a2437",
        hex_6: "#92a1ab",
        hex_7: "#6a96b1",
        hex_8: "#b4b4b9",
        hex_9: "#1e343b"
      },
      {
        original_file_name: "Frozen River With Icebergs (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9678195,
        file_size_megabytes: 9.23,
        width: 3072,
        height: 5472,
        primary: "#2a4b5f",
        secondary: "#c5d3e1",
        tertiary: "#91b8d2",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6a8ea6",
        hex_5: "#7ca4c1",
        hex_6: "#071723",
        hex_7: "#477897",
        hex_8: "#6f7884",
        hex_9: "#a5947d"
      },
      {
        original_file_name: "Frozen River With Icebergs (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9547706,
        file_size_megabytes: 9.11,
        width: 3072,
        height: 5472,
        primary: "#304e62",
        secondary: "#c5daeb",
        tertiary: "#90b5d1",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#081521",
        hex_5: "#729cbb",
        hex_6: "#718ca0",
        hex_7: "#727680",
        hex_8: "#041b34",
        hex_9: "#a48c8c"
      },
      {
        original_file_name: "Frozen River With Icebergs (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10201581,
        file_size_megabytes: 9.73,
        width: 3072,
        height: 5472,
        primary: "#3f5f77",
        secondary: "#c6d8e7",
        tertiary: "#7aa9cc",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#081725",
        hex_5: "#9cbfda",
        hex_6: "#8799a9",
        hex_7: "#0b293f",
        hex_8: "#6796b5",
        hex_9: "#ac9c9c"
      }
    ]
  },
  "Frozen Tundra Under Northern Lights": {
    environment_title: "Frozen Tundra Under Northern Lights",
    images: [
      {
        original_file_name: "Frozen Tundra Under Northern Lights (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6517522,
        file_size_megabytes: 6.22,
        width: 3072,
        height: 5472,
        primary: "#1a2d43",
        secondary: "#6bc6a8",
        tertiary: "#4e898b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a76b94",
        hex_5: "#536b89",
        hex_6: "#376271",
        hex_7: "#cee7d5",
        hex_8: "#6e3e6c",
        hex_9: "#769bb8"
      },
      {
        original_file_name: "Frozen Tundra Under Northern Lights (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6710724,
        file_size_megabytes: 6.4,
        width: 3072,
        height: 5472,
        primary: "#1a4454",
        secondary: "#62caa2",
        tertiary: "#2a8b79",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#061220",
        hex_5: "#6e94aa",
        hex_6: "#0d1a2e",
        hex_7: "#486b88",
        hex_8: "#777769",
        hex_9: "#585a61"
      },
      {
        original_file_name: "Frozen Tundra Under Northern Lights (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6444284,
        file_size_megabytes: 6.15,
        width: 3072,
        height: 5472,
        primary: "#274357",
        secondary: "#83ca93",
        tertiary: "#4c8d78",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#101122",
        hex_5: "#191930",
        hex_6: "#46657f",
        hex_7: "#72506e",
        hex_8: "#969099",
        hex_9: "#73949f"
      },
      {
        original_file_name: "Frozen Tundra Under Northern Lights (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6365202,
        file_size_megabytes: 6.07,
        width: 3072,
        height: 5472,
        primary: "#aaae94",
        secondary: "#1d3c50",
        tertiary: "#578083",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5bbb8b",
        hex_5: "#07131f",
        hex_6: "#466680",
        hex_7: "#6e4d6a",
        hex_8: "#7d92a6",
        hex_9: "#13142c"
      }
    ]
  },
  "Golden Wheat Field At Noon": {
    environment_title: "Golden Wheat Field At Noon",
    images: [
      {
        original_file_name: "Golden Wheat Field At Noon (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9017188,
        file_size_megabytes: 8.6,
        width: 3072,
        height: 5472,
        primary: "#d8d0b1",
        secondary: "#7a4613",
        tertiary: "#2f1507",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e4a03c",
        hex_5: "#7caac0",
        hex_6: "#b87520",
        hex_7: "#c49043",
        hex_8: "#917858",
        hex_9: "#444c34"
      },
      {
        original_file_name: "Golden Wheat Field At Noon (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8424639,
        file_size_megabytes: 8.03,
        width: 3072,
        height: 5472,
        primary: "#d9ad67",
        secondary: "#598396",
        tertiary: "#8d5415",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#243c4c",
        hex_5: "#4e1f07",
        hex_6: "#b0bfbe",
        hex_7: "#a6a396",
        hex_8: "#8cafbc",
        hex_9: "#c46c14"
      },
      {
        original_file_name: "Golden Wheat Field At Noon (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8710357,
        file_size_megabytes: 8.31,
        width: 3072,
        height: 5472,
        primary: "#7e4a14",
        secondary: "#291207",
        tertiary: "#ebd498",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#e2a147",
        hex_5: "#c68f40",
        hex_6: "#bc7a26",
        hex_7: "#93795c",
        hex_8: "#90a7aa",
        hex_9: "#446454"
      },
      {
        original_file_name: "Golden Wheat Field At Noon (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8347714,
        file_size_megabytes: 7.96,
        width: 3072,
        height: 5472,
        primary: "#e1d0a3",
        secondary: "#704415",
        tertiary: "#251308",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#78aab8",
        hex_5: "#dda142",
        hex_6: "#b07627",
        hex_7: "#bc9044",
        hex_8: "#3698ba",
        hex_9: "#8f7759"
      }
    ]
  },
  "Lush Rainforest Waterfall": {
    environment_title: "Lush Rainforest Waterfall",
    images: [
      {
        original_file_name: "Lush Rainforest Waterfall (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9197574,
        file_size_megabytes: 8.77,
        width: 3072,
        height: 5472,
        primary: "#bfd1c5",
        secondary: "#142314",
        tertiary: "#81a57d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5d7a59",
        hex_5: "#779098",
        hex_6: "#405b5d",
        hex_7: "#385331",
        hex_8: "#5e603d",
        hex_9: "#96843c"
      },
      {
        original_file_name: "Lush Rainforest Waterfall (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9530207,
        file_size_megabytes: 9.09,
        width: 3072,
        height: 5472,
        primary: "#162315",
        secondary: "#b6cfae",
        tertiary: "#7ea765",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5c794f",
        hex_5: "#768c9b",
        hex_6: "#38542a",
        hex_7: "#43575f",
        hex_8: "#5f5e42",
        hex_9: "#949494"
      },
      {
        original_file_name: "Lush Rainforest Waterfall (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9088106,
        file_size_megabytes: 8.67,
        width: 3072,
        height: 5472,
        primary: "#162314",
        secondary: "#bfcfbc",
        tertiary: "#85ad68",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#62834c",
        hex_5: "#7a919d",
        hex_6: "#455b60",
        hex_7: "#3e5d27",
        hex_8: "#5f6750",
        hex_9: "#9c8c4c"
      },
      {
        original_file_name: "Lush Rainforest Waterfall (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9403300,
        file_size_megabytes: 8.97,
        width: 3072,
        height: 5472,
        primary: "#182518",
        secondary: "#bdcfb7",
        tertiary: "#87a68e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#6f7d53",
        hex_5: "#425532",
        hex_6: "#6c899f",
        hex_7: "#547253",
        hex_8: "#425966",
        hex_9: "#9c945f"
      }
    ]
  },
  "Lush Valley With Flowing River": {
    environment_title: "Lush Valley With Flowing River",
    images: [
      {
        original_file_name: "Lush Valley With Flowing River (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 13214999,
        file_size_megabytes: 12.6,
        width: 3072,
        height: 5472,
        primary: "#b3bd97",
        secondary: "#172c1b",
        tertiary: "#558b9f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#668a4c",
        hex_5: "#265b70",
        hex_6: "#81af9a",
        hex_7: "#626e2d",
        hex_8: "#4c6226",
        hex_9: "#414e1c"
      },
      {
        original_file_name: "Lush Valley With Flowing River (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11317061,
        file_size_megabytes: 10.79,
        width: 3072,
        height: 5472,
        primary: "#c3c098",
        secondary: "#304c47",
        tertiary: "#3c8eb9",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#84933b",
        hex_5: "#416b7c",
        hex_6: "#747342",
        hex_7: "#92b674",
        hex_8: "#384509",
        hex_9: "#0b130a"
      },
      {
        original_file_name: "Lush Valley With Flowing River (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11294470,
        file_size_megabytes: 10.77,
        width: 3072,
        height: 5472,
        primary: "#152d22",
        secondary: "#b2a96b",
        tertiary: "#5994b0",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1a6873",
        hex_5: "#688e42",
        hex_6: "#626c26",
        hex_7: "#78b9cc",
        hex_8: "#2f623f",
        hex_9: "#946c4b"
      },
      {
        original_file_name: "Lush Valley With Flowing River (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10800553,
        file_size_megabytes: 10.3,
        width: 3072,
        height: 5472,
        primary: "#285851",
        secondary: "#c7ced8",
        tertiary: "#5c98c4",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#366f89",
        hex_5: "#75822d",
        hex_6: "#475d0c",
        hex_7: "#8fb5d2",
        hex_8: "#0a190c",
        hex_9: "#638c22"
      }
    ]
  },
  "Misty Morning In Lavender Fields": {
    environment_title: "Misty Morning In Lavender Fields",
    images: [
      {
        original_file_name: "Misty Morning In Lavender Fields  (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8568272,
        file_size_megabytes: 8.17,
        width: 3072,
        height: 5472,
        primary: "#ddc5c1",
        secondary: "#2d262f",
        tertiary: "#8a7182",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a4aaae",
        hex_5: "#9c94a8",
        hex_6: "#66515a",
        hex_7: "#715976",
        hex_8: "#6f7271",
        hex_9: "#b48c9b"
      },
      {
        original_file_name: "Misty Morning In Lavender Fields  (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8740561,
        file_size_megabytes: 8.34,
        width: 3072,
        height: 5472,
        primary: "#312935",
        secondary: "#e2c8cb",
        tertiary: "#8f727f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#aca1b9",
        hex_5: "#8e87af",
        hex_6: "#73617d",
        hex_7: "#6d565c",
        hex_8: "#796d56",
        hex_9: "#bc9495"
      },
      {
        original_file_name: "Misty Morning In Lavender Fields  (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8999576,
        file_size_megabytes: 8.58,
        width: 3072,
        height: 5472,
        primary: "#2f2c36",
        secondary: "#ddc5c8",
        tertiary: "#9a7d8d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a2aab3",
        hex_5: "#757389",
        hex_6: "#a395ae",
        hex_7: "#6f595f",
        hex_8: "#796f63",
        hex_9: "#bc8496"
      },
      {
        original_file_name: "Misty Morning In Lavender Fields  (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8026113,
        file_size_megabytes: 7.65,
        width: 3072,
        height: 5472,
        primary: "#e3c8c7",
        secondary: "#312d38",
        tertiary: "#8c7a92",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a4a7b7",
        hex_5: "#9490b1",
        hex_6: "#635467",
        hex_7: "#6e6083",
        hex_8: "#706c6c",
        hex_9: "#b47c84"
      }
    ]
  },
  "Moonrise Over Snowy Peaks": {
    environment_title: "Moonrise Over Snowy Peaks",
    images: [
      {
        original_file_name: "Moonrise Over Snowy Peaks (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7268638,
        file_size_megabytes: 6.93,
        width: 3072,
        height: 5472,
        primary: "#bcaba8",
        secondary: "#526f96",
        tertiary: "#0b2139",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#294564",
        hex_5: "#6b84ad",
        hex_6: "#756a6c",
        hex_7: "#634b48",
        hex_8: "#879cb5",
        hex_9: "#3c454f"
      },
      {
        original_file_name: "Moonrise Over Snowy Peaks (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6965067,
        file_size_megabytes: 6.64,
        width: 3072,
        height: 5472,
        primary: "#18304a",
        secondary: "#5d748f",
        tertiary: "#be967a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#0a0d12",
        hex_5: "#5c7ca4",
        hex_6: "#685f62",
        hex_7: "#48596a",
        hex_8: "#4c637f",
        hex_9: "#8c9c94"
      },
      {
        original_file_name: "Moonrise Over Snowy Peaks (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7043468,
        file_size_megabytes: 6.72,
        width: 3072,
        height: 5472,
        primary: "#d0a991",
        secondary: "#0a1e32",
        tertiary: "#5880b1",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5a6e8a",
        hex_5: "#7ea1c7",
        hex_6: "#2e445b",
        hex_7: "#5b6066",
        hex_8: "#584b4c",
        hex_9: "#8c4c24"
      },
      {
        original_file_name: "Moonrise Over Snowy Peaks (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7709801,
        file_size_megabytes: 7.35,
        width: 3072,
        height: 5472,
        primary: "#476488",
        secondary: "#0a0e1d",
        tertiary: "#08213f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#19314d",
        hex_5: "#cec2b7",
        hex_6: "#818798",
        hex_7: "#8299bd",
        hex_8: "#698cb0",
        hex_9: "#9cacc4"
      }
    ]
  },
  "Rolling Hills And Flower Fields": {
    environment_title: "Rolling Hills And Flower Fields",
    images: [
      {
        original_file_name: "Rolling Hills And Flower Fields  (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10595835,
        file_size_megabytes: 10.1,
        width: 3072,
        height: 5472,
        primary: "#4a4919",
        secondary: "#dbab77",
        tertiary: "#8d847d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#897532",
        hex_5: "#151e08",
        hex_6: "#727434",
        hex_7: "#2a1808",
        hex_8: "#9ea44c",
        hex_9: "#ae5404"
      },
      {
        original_file_name: "Rolling Hills And Flower Fields  (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 12008451,
        file_size_megabytes: 11.45,
        width: 3072,
        height: 5472,
        primary: "#3c471e",
        secondary: "#ba9f34",
        tertiary: "#918125",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5f7077",
        hex_5: "#6d6522",
        hex_6: "#747f25",
        hex_7: "#9fa63c",
        hex_8: "#112714",
        hex_9: "#0e1a0c"
      },
      {
        original_file_name: "Rolling Hills And Flower Fields  (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11787769,
        file_size_megabytes: 11.24,
        width: 3072,
        height: 5472,
        primary: "#2b3417",
        secondary: "#c49a58",
        tertiary: "#8a771d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7b8ca7",
        hex_5: "#6c7824",
        hex_6: "#655c15",
        hex_7: "#4c5a1a",
        hex_8: "#525d5c",
        hex_9: "#9aa84d"
      },
      {
        original_file_name: "Rolling Hills And Flower Fields  (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10483813,
        file_size_megabytes: 10.0,
        width: 3072,
        height: 5472,
        primary: "#caa25e",
        secondary: "#303a17",
        tertiary: "#837320",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#757371",
        hex_5: "#5d5921",
        hex_6: "#676e27",
        hex_7: "#454a49",
        hex_8: "#131106",
        hex_9: "#989c4f"
      }
    ]
  },
  "Snowy Mountain Range": {
    environment_title: "Snowy Mountain Range",
    images: [
      {
        original_file_name: "Snowy Mountain Range (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8819143,
        file_size_megabytes: 8.41,
        width: 3072,
        height: 5472,
        primary: "#cfd4d9",
        secondary: "#84919e",
        tertiary: "#0f1826",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#2b3948",
        hex_5: "#43515e",
        hex_6: "#4f616f",
        hex_7: "#334553",
        hex_8: "#b4c4cb",
        hex_9: "#b3bccc"
      },
      {
        original_file_name: "Snowy Mountain Range (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9331009,
        file_size_megabytes: 8.9,
        width: 3072,
        height: 5472,
        primary: "#253541",
        secondary: "#dad5ce",
        tertiary: "#818b93",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#697e8c",
        hex_5: "#54636c",
        hex_6: "#5f707f",
        hex_7: "#a2adb0",
        hex_8: "#95a1ac",
        hex_9: "#ac9c9a"
      },
      {
        original_file_name: "Snowy Mountain Range (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8029195,
        file_size_megabytes: 7.66,
        width: 3072,
        height: 5472,
        primary: "#cdd0d2",
        secondary: "#1b303e",
        tertiary: "#5a6f7d",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#86949f",
        hex_5: "#475058",
        hex_6: "#76828d",
        hex_7: "#858c8b",
        hex_8: "#386c86",
        hex_9: "#5c5c54"
      },
      {
        original_file_name: "Snowy Mountain Range (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7551756,
        file_size_megabytes: 7.2,
        width: 3072,
        height: 5472,
        primary: "#2e4960",
        secondary: "#d6d6d4",
        tertiary: "#889199",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a0aeb5",
        hex_5: "#608097",
        hex_6: "#456f8f",
        hex_7: "#859eb5",
        hex_8: "#081423",
        hex_9: "#aca4a5"
      }
    ]
  },
  "Starry Night Over Desert Dunes": {
    environment_title: "Starry Night Over Desert Dunes",
    images: [
      {
        original_file_name: "Starry Night Over Desert Dunes (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7293740,
        file_size_megabytes: 6.96,
        width: 3072,
        height: 5472,
        primary: "#c59056",
        secondary: "#1e212d",
        tertiary: "#7b532c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e3524",
        hex_5: "#4f5366",
        hex_6: "#d7c7be",
        hex_7: "#948c8a",
        hex_8: "#818eac",
        hex_9: "#5c5c5a"
      },
      {
        original_file_name: "Starry Night Over Desert Dunes (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7669097,
        file_size_megabytes: 7.31,
        width: 3072,
        height: 5472,
        primary: "#c78c58",
        secondary: "#191b24",
        tertiary: "#795239",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4f3424",
        hex_5: "#434c65",
        hex_6: "#787d9a",
        hex_7: "#868eaa",
        hex_8: "#5b544c",
        hex_9: "#9c4c14"
      },
      {
        original_file_name: "Starry Night Over Desert Dunes (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7390930,
        file_size_megabytes: 7.05,
        width: 3072,
        height: 5472,
        primary: "#c18344",
        secondary: "#1d1d24",
        tertiary: "#7a522f",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#374253",
        hex_5: "#4e301a",
        hex_6: "#505562",
        hex_7: "#686677",
        hex_8: "#8e8084",
        hex_9: "#9c4404"
      },
      {
        original_file_name: "Starry Night Over Desert Dunes (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7261346,
        file_size_megabytes: 6.92,
        width: 3072,
        height: 5472,
        primary: "#cb884c",
        secondary: "#1f1f27",
        tertiary: "#794e2e",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4e3323",
        hex_5: "#424556",
        hex_6: "#796d7b",
        hex_7: "#535563",
        hex_8: "#9c5420",
        hex_9: "#948484"
      }
    ]
  },
  "Starry Night Over Serene Lake": {
    environment_title: "Starry Night Over Serene Lake",
    images: [
      {
        original_file_name: "Starry Night Over Serene Lake (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6579490,
        file_size_megabytes: 6.27,
        width: 3072,
        height: 5472,
        primary: "#375266",
        secondary: "#0a1a22",
        tertiary: "#857978",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#15364b",
        hex_5: "#516e85",
        hex_6: "#627d8d",
        hex_7: "#494f51",
        hex_8: "#0f343a",
        hex_9: "#474246"
      },
      {
        original_file_name: "Starry Night Over Serene Lake (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6655314,
        file_size_megabytes: 6.35,
        width: 3072,
        height: 5472,
        primary: "#131d26",
        secondary: "#a18a58",
        tertiary: "#595d4b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#303f3e",
        hex_5: "#35464e",
        hex_6: "#3f5550",
        hex_7: "#606467",
        hex_8: "#797c53",
        hex_9: "#343336"
      },
      {
        original_file_name: "Starry Night Over Serene Lake (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6539558,
        file_size_megabytes: 6.24,
        width: 3072,
        height: 5472,
        primary: "#0b1b27",
        secondary: "#9a7f50",
        tertiary: "#5c5e51",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#203949",
        hex_5: "#2a4963",
        hex_6: "#727f7e",
        hex_7: "#3f544e",
        hex_8: "#283e3b",
        hex_9: "#4e6b88"
      },
      {
        original_file_name: "Starry Night Over Serene Lake (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6198680,
        file_size_megabytes: 5.91,
        width: 3072,
        height: 5472,
        primary: "#0b1c29",
        secondary: "#ad8d73",
        tertiary: "#5b686c",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#2a4450",
        hex_5: "#5b6057",
        hex_6: "#514d51",
        hex_7: "#253e43",
        hex_8: "#84849c",
        hex_9: "#849490"
      }
    ]
  },
  "Sunlit Orchard In Spring": {
    environment_title: "Sunlit Orchard In Spring",
    images: [
      {
        original_file_name: "Sunlit Orchard In Spring (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9103708,
        file_size_megabytes: 8.68,
        width: 3072,
        height: 5472,
        primary: "#b3c4cc",
        secondary: "#98792c",
        tertiary: "#312909",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#58330c",
        hex_5: "#dead62",
        hex_6: "#a39982",
        hex_7: "#eecb70",
        hex_8: "#595514",
        hex_9: "#406c72"
      },
      {
        original_file_name: "Sunlit Orchard In Spring (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9353039,
        file_size_megabytes: 8.92,
        width: 3072,
        height: 5472,
        primary: "#92752c",
        secondary: "#cfd2ce",
        tertiary: "#261e08",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#50320e",
        hex_5: "#deb56c",
        hex_6: "#a2987f",
        hex_7: "#524e15",
        hex_8: "#bfbd4d",
        hex_9: "#3c543c"
      },
      {
        original_file_name: "Sunlit Orchard In Spring (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9528029,
        file_size_megabytes: 9.09,
        width: 3072,
        height: 5472,
        primary: "#987e31",
        secondary: "#bbcdd4",
        tertiary: "#272509",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#50320e",
        hex_5: "#e1bc6e",
        hex_6: "#575315",
        hex_7: "#a99f86",
        hex_8: "#c7c632",
        hex_9: "#3c5c6e"
      },
      {
        original_file_name: "Sunlit Orchard In Spring (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10221646,
        file_size_megabytes: 9.75,
        width: 3072,
        height: 5472,
        primary: "#846b27",
        secondary: "#ddbb75",
        tertiary: "#221b08",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#a4b98d",
        hex_5: "#83a1a9",
        hex_6: "#3f230a",
        hex_7: "#40430c",
        hex_8: "#a18767",
        hex_9: "#c47c4a"
      }
    ]
  },
  "Sunrise In The Redwood Forest": {
    environment_title: "Sunrise In The Redwood Forest",
    images: [
      {
        original_file_name: "Sunrise In The Redwood Forest (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8691888,
        file_size_megabytes: 8.29,
        width: 3072,
        height: 5472,
        primary: "#d4b07b",
        secondary: "#231d0f",
        tertiary: "#766038",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#4c4123",
        hex_5: "#556024",
        hex_6: "#8f9670",
        hex_7: "#80868f",
        hex_8: "#4b4e51",
        hex_9: "#9c5c3c"
      },
      {
        original_file_name: "Sunrise In The Redwood Forest (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9159753,
        file_size_megabytes: 8.74,
        width: 3072,
        height: 5472,
        primary: "#cc9f62",
        secondary: "#2a2415",
        tertiary: "#7d5d39",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#543f28",
        hex_5: "#4c525b",
        hex_6: "#536857",
        hex_7: "#7d8899",
        hex_8: "#8f9fb2",
        hex_9: "#9c5424"
      },
      {
        original_file_name: "Sunrise In The Redwood Forest (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9190270,
        file_size_megabytes: 8.76,
        width: 3072,
        height: 5472,
        primary: "#caa463",
        secondary: "#272316",
        tertiary: "#795d35",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#7f8794",
        hex_5: "#523f1e",
        hex_6: "#49515c",
        hex_7: "#909fae",
        hex_8: "#54664c",
        hex_9: "#9c4c1c"
      },
      {
        original_file_name: "Sunrise In The Redwood Forest (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9390516,
        file_size_megabytes: 8.96,
        width: 3072,
        height: 5472,
        primary: "#cda25e",
        secondary: "#262215",
        tertiary: "#785b33",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#534023",
        hex_5: "#828994",
        hex_6: "#4d535b",
        hex_7: "#919ea7",
        hex_8: "#5a6561",
        hex_9: "#9d4404"
      }
    ]
  },
  "Sunrise Through Tall Grass Plains": {
    environment_title: "Sunrise Through Tall Grass Plains",
    images: [
      {
        original_file_name: "Sunrise Through Tall Grass Plains (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10153330,
        file_size_megabytes: 9.68,
        width: 3072,
        height: 5472,
        primary: "#dfa351",
        secondary: "#2e2109",
        tertiary: "#895a1a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5e4113",
        hex_5: "#675944",
        hex_6: "#a0927c",
        hex_7: "#6c6446",
        hex_8: "#a49c84",
        hex_9: "#ac4c1c"
      },
      {
        original_file_name: "Sunrise Through Tall Grass Plains (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10043387,
        file_size_megabytes: 9.58,
        width: 3072,
        height: 5472,
        primary: "#ecb867",
        secondary: "#2b210a",
        tertiary: "#885819",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#5e3f13",
        hex_5: "#695d3f",
        hex_6: "#ad5b0f",
        hex_7: "#9f9474",
        hex_8: "#9c8474",
        hex_9: "#4c4a3c"
      },
      {
        original_file_name: "Sunrise Through Tall Grass Plains (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10361078,
        file_size_megabytes: 9.88,
        width: 3072,
        height: 5472,
        primary: "#d59e57",
        secondary: "#271e09",
        tertiary: "#825823",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#573b11",
        hex_5: "#5f5e3d",
        hex_6: "#94826c",
        hex_7: "#9c8c64",
        hex_8: "#a44c04",
        hex_9: "#443c3c"
      },
      {
        original_file_name: "Sunrise Through Tall Grass Plains (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10168870,
        file_size_megabytes: 9.7,
        width: 3072,
        height: 5472,
        primary: "#e3a042",
        secondary: "#2e220b",
        tertiary: "#9d682b",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#734a1e",
        hex_5: "#7b6c55",
        hex_6: "#b49c6d",
        hex_7: "#5b5545",
        hex_8: "#ac947c",
        hex_9: "#bc540c"
      }
    ]
  },
  "Twilight Over The Savannah": {
    environment_title: "Twilight Over The Savannah",
    images: [
      {
        original_file_name: "Twilight Over The Savannah (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7937694,
        file_size_megabytes: 7.57,
        width: 3072,
        height: 5472,
        primary: "#de7b22",
        secondary: "#703b17",
        tertiary: "#aa5921",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#1b0c08",
        hex_5: "#3c1f0c",
        hex_6: "#fbe95e",
        hex_7: "#8f664f",
        hex_8: "#b48444",
        hex_9: "#a47c6c"
      },
      {
        original_file_name: "Twilight Over The Savannah (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8418812,
        file_size_megabytes: 8.03,
        width: 3072,
        height: 5472,
        primary: "#d17b24",
        secondary: "#3a2113",
        tertiary: "#905226",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#693717",
        hex_5: "#0e0705",
        hex_6: "#715543",
        hex_7: "#735c54",
        hex_8: "#a48460",
        hex_9: "#ac2c04"
      },
      {
        original_file_name: "Twilight Over The Savannah (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9018574,
        file_size_megabytes: 8.6,
        width: 3072,
        height: 5472,
        primary: "#da7320",
        secondary: "#583121",
        tertiary: "#974f27",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#140a07",
        hex_5: "#2b130b",
        hex_6: "#a77e64",
        hex_7: "#755b54",
        hex_8: "#7a5c46",
        hex_9: "#b83404"
      },
      {
        original_file_name: "Twilight Over The Savannah (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9007894,
        file_size_megabytes: 8.59,
        width: 3072,
        height: 5472,
        primary: "#da761a",
        secondary: "#9d5326",
        tertiary: "#24120a",
        downloadLink: "https://github.com/yt-dlx/picWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picWall/",
        hex_4: "#773e26",
        hex_5: "#572e1d",
        hex_6: "#fbb908",
        hex_7: "#b18450",
        hex_8: "#614f40",
        hex_9: "#544444"
      }
    ]
  }
};
export default NaturalLandscapes;
