import { EnvironmentEntry } from "@/types/database";
const PhotographyDatabase: Record<string, EnvironmentEntry> = {
  Busy_Crosswalk: {
    environment_title: "Busy_Crosswalk",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Busy_Crosswalk (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8871232,
        file_size_megabytes: 8.46,
        width: 3072,
        height: 5472,
        primary: "#d6bb8f",
        secondary: "#92a9b9",
        tertiary: "#1f1b1f",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#83716c",
        hex_5: "#4b83a9",
        hex_6: "#5b6d7a",
        hex_7: "#57413c",
        hex_8: "#49566a",
        hex_9: "#c74616"
      },
      {
        original_file_name: "Busy_Crosswalk (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8159444,
        file_size_megabytes: 7.78,
        width: 3072,
        height: 5472,
        primary: "#cbb688",
        secondary: "#6fa6c2",
        tertiary: "#17181f",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#746662",
        hex_5: "#4583a8",
        hex_6: "#363f4c",
        hex_7: "#3f5c71",
        hex_8: "#c52a20",
        hex_9: "#505e55"
      },
      {
        original_file_name: "Busy_Crosswalk (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9970043,
        file_size_megabytes: 9.51,
        width: 3072,
        height: 5472,
        primary: "#cdc7c1",
        secondary: "#2f2e30",
        tertiary: "#99b6c4",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8d7468",
        hex_5: "#739baf",
        hex_6: "#c7101b",
        hex_7: "#6e7779",
        hex_8: "#645048",
        hex_9: "#62656f"
      },
      {
        original_file_name: "Busy_Crosswalk (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9889647,
        file_size_megabytes: 9.43,
        width: 3072,
        height: 5472,
        primary: "#c9a78e",
        secondary: "#202027",
        tertiary: "#73abc5",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#81655f",
        hex_5: "#5f8ca9",
        hex_6: "#c72527",
        hex_7: "#56413d",
        hex_8: "#526977",
        hex_9: "#3c526b"
      }
    ]
  },
  Crystal_Clear: {
    environment_title: "Crystal_Clear",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Crystal_Clear (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10100844,
        file_size_megabytes: 9.63,
        width: 3072,
        height: 5472,
        primary: "#4c402c",
        secondary: "#77abd3",
        tertiary: "#c18c54",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#94642e",
        hex_5: "#4b7188",
        hex_6: "#152a34",
        hex_7: "#969f93",
        hex_8: "#6f6e5a",
        hex_9: "#5984af"
      },
      {
        original_file_name: "Crystal_Clear (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 12334991,
        file_size_megabytes: 11.76,
        width: 3072,
        height: 5472,
        primary: "#4b3d20",
        secondary: "#c79355",
        tertiary: "#5098c2",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8c6329",
        hex_5: "#3b5e70",
        hex_6: "#0f1314",
        hex_7: "#5e777b",
        hex_8: "#055c94",
        hex_9: "#a2a579"
      },
      {
        original_file_name: "Crystal_Clear (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8902604,
        file_size_megabytes: 8.49,
        width: 3072,
        height: 5472,
        primary: "#caa882",
        secondary: "#172e32",
        tertiary: "#895f37",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8caec1",
        hex_5: "#5a90ae",
        hex_6: "#5b4329",
        hex_7: "#305e78",
        hex_8: "#4b7b8f",
        hex_9: "#b54729"
      },
      {
        original_file_name: "Crystal_Clear (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10440007,
        file_size_megabytes: 9.96,
        width: 3072,
        height: 5472,
        primary: "#72acd9",
        secondary: "#30392d",
        tertiary: "#c77523",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#4e778a",
        hex_5: "#965422",
        hex_6: "#6f4520",
        hex_7: "#5f705b",
        hex_8: "#8a9f8f",
        hex_9: "#5274ac"
      }
    ]
  },
  Desert_Serenity: {
    environment_title: "Desert_Serenity",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Desert_Serenity (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7829348,
        file_size_megabytes: 7.47,
        width: 3072,
        height: 5472,
        primary: "#502c17",
        secondary: "#f5b76f",
        tertiary: "#da823e",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#97592f",
        hex_5: "#fcf9db",
        hex_6: "#745a54",
        hex_7: "#ca987c",
        hex_8: "#23160b",
        hex_9: "#7c6c68"
      },
      {
        original_file_name: "Desert_Serenity (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7750987,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#e7a261",
        secondary: "#6c3c1c",
        tertiary: "#937d73",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#b27b50",
        hex_5: "#ae622a",
        hex_6: "#765c51",
        hex_7: "#361d0f",
        hex_8: "#c29c7f",
        hex_9: "#481304"
      },
      {
        original_file_name: "Desert_Serenity (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8072899,
        file_size_megabytes: 7.7,
        width: 3072,
        height: 5472,
        primary: "#9e5925",
        secondary: "#e78e40",
        tertiary: "#3c291e",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#f7b062",
        hex_5: "#553725",
        hex_6: "#aa8468",
        hex_7: "#572107",
        hex_8: "#c98548",
        hex_9: "#434444"
      },
      {
        original_file_name: "Desert_Serenity (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8040250,
        file_size_megabytes: 7.67,
        width: 3072,
        height: 5472,
        primary: "#56321e",
        secondary: "#de8138",
        tertiary: "#f6c282",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#9e5b2f",
        hex_5: "#997c7a",
        hex_6: "#6a5659",
        hex_7: "#21140e",
        hex_8: "#806c64",
        hex_9: "#ca9986"
      }
    ]
  },
  Forest_Pathway: {
    environment_title: "Forest_Pathway",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Forest_Pathway (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10028681,
        file_size_megabytes: 9.56,
        width: 3072,
        height: 5472,
        primary: "#c7c179",
        secondary: "#22280e",
        tertiary: "#767937",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8ea038",
        hex_5: "#4a4d24",
        hex_6: "#57681e",
        hex_7: "#544e4e",
        hex_8: "#8d928d",
        hex_9: "#9c6c4e"
      },
      {
        original_file_name: "Forest_Pathway (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9898834,
        file_size_megabytes: 9.44,
        width: 3072,
        height: 5472,
        primary: "#ccbd7a",
        secondary: "#232911",
        tertiary: "#7f7d3e",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#99a547",
        hex_5: "#545525",
        hex_6: "#5f6f28",
        hex_7: "#5f5d56",
        hex_8: "#9c9a8e",
        hex_9: "#a4643c"
      },
      {
        original_file_name: "Forest_Pathway (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9599918,
        file_size_megabytes: 9.16,
        width: 3072,
        height: 5472,
        primary: "#c8bf78",
        secondary: "#22270f",
        tertiary: "#777139",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8ea03a",
        hex_5: "#546c25",
        hex_6: "#4c4924",
        hex_7: "#4d554f",
        hex_8: "#9c6c56",
        hex_9: "#91948e"
      },
      {
        original_file_name: "Forest_Pathway (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9824036,
        file_size_megabytes: 9.37,
        width: 3072,
        height: 5472,
        primary: "#ccbe73",
        secondary: "#1e220f",
        tertiary: "#777530",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8da14a",
        hex_5: "#566920",
        hex_6: "#4c4b1c",
        hex_7: "#859196",
        hex_8: "#48534d",
        hex_9: "#9c5c24"
      }
    ]
  },
  Frozen_Lake_Beauty: {
    environment_title: "Frozen_Lake_Beauty",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Frozen_Lake_Beauty (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8378271,
        file_size_megabytes: 7.99,
        width: 3072,
        height: 5472,
        primary: "#626c86",
        secondary: "#dcb4b1",
        tertiary: "#23435d",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#18222f",
        hex_5: "#a7b4c8",
        hex_6: "#ab93a2",
        hex_7: "#91a7c5",
        hex_8: "#373345",
        hex_9: "#c47484"
      },
      {
        original_file_name: "Frozen_Lake_Beauty (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7931139,
        file_size_megabytes: 7.56,
        width: 3072,
        height: 5472,
        primary: "#b2adba",
        secondary: "#2c4055",
        tertiary: "#5e6b80",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#f0cec5",
        hex_5: "#8d798d",
        hex_6: "#9b7475",
        hex_7: "#4e4b60",
        hex_8: "#436284",
        hex_9: "#6c4c4a"
      },
      {
        original_file_name: "Frozen_Lake_Beauty (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7664695,
        file_size_megabytes: 7.31,
        width: 3072,
        height: 5472,
        primary: "#73788e",
        secondary: "#293e52",
        tertiary: "#e7c3bf",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#b594a2",
        hex_5: "#98aabd",
        hex_6: "#bcc5d0",
        hex_7: "#acb9cc",
        hex_8: "#474354",
        hex_9: "#605149"
      },
      {
        original_file_name: "Frozen_Lake_Beauty (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8412620,
        file_size_megabytes: 8.02,
        width: 3072,
        height: 5472,
        primary: "#5f6c86",
        secondary: "#d1b2be",
        tertiary: "#1d2732",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#a9c1d8",
        hex_5: "#273345",
        hex_6: "#a393aa",
        hex_7: "#284054",
        hex_8: "#a1b4c3",
        hex_9: "#bc8084"
      }
    ]
  },
  Golden_Beach_Sunrise: {
    environment_title: "Golden_Beach_Sunrise",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Golden_Beach_Sunrise (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7837594,
        file_size_megabytes: 7.47,
        width: 3072,
        height: 5472,
        primary: "#e0b278",
        secondary: "#5b3e2a",
        tertiary: "#8b8e8f",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#a1856d",
        hex_5: "#6a6266",
        hex_6: "#aaaea7",
        hex_7: "#221d22",
        hex_8: "#936e55",
        hex_9: "#bc743c"
      },
      {
        original_file_name: "Golden_Beach_Sunrise (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7365946,
        file_size_megabytes: 7.02,
        width: 3072,
        height: 5472,
        primary: "#302d32",
        secondary: "#775a49",
        tertiary: "#e49f56",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#fad472",
        hex_5: "#b67e4f",
        hex_6: "#bc9773",
        hex_7: "#6f401b",
        hex_8: "#4f2b1d",
        hex_9: "#e0b494"
      },
      {
        original_file_name: "Golden_Beach_Sunrise (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7397250,
        file_size_megabytes: 7.05,
        width: 3072,
        height: 5472,
        primary: "#654d3f",
        secondary: "#daa25e",
        tertiary: "#f8d17a",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#29292d",
        hex_5: "#a87649",
        hex_6: "#b29574",
        hex_7: "#8f7e75",
        hex_8: "#3f1a0c",
        hex_9: "#bca19c"
      },
      {
        original_file_name: "Golden_Beach_Sunrise (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7680676,
        file_size_megabytes: 7.32,
        width: 3072,
        height: 5472,
        primary: "#77655b",
        secondary: "#2a2c32",
        tertiary: "#e29e57",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#facc6b",
        hex_5: "#b68660",
        hex_6: "#4a3024",
        hex_7: "#9aa4ac",
        hex_8: "#949b9c",
        hex_9: "#814a21"
      }
    ]
  },
  Misty_Mountain_Morning: {
    environment_title: "Misty_Mountain_Morning",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Misty_Mountain_Morning (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7239300,
        file_size_megabytes: 6.9,
        width: 3072,
        height: 5472,
        primary: "#cbc6c6",
        secondary: "#223632",
        tertiary: "#869390",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#9eafb3",
        hex_5: "#3d647d",
        hex_6: "#55675d",
        hex_7: "#677e80",
        hex_8: "#879eb0",
        hex_9: "#ae8c86"
      },
      {
        original_file_name: "Misty_Mountain_Morning (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6795727,
        file_size_megabytes: 6.48,
        width: 3072,
        height: 5472,
        primary: "#2c3832",
        secondary: "#e3ccac",
        tertiary: "#b4b7b2",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#9da4ab",
        hex_5: "#9f9681",
        hex_6: "#63707f",
        hex_7: "#7b8a8a",
        hex_8: "#706d58",
        hex_9: "#c59c7a"
      },
      {
        original_file_name: "Misty_Mountain_Morning (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6932214,
        file_size_megabytes: 6.61,
        width: 3072,
        height: 5472,
        primary: "#d6bca3",
        secondary: "#3a515f",
        tertiary: "#9cb1b6",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#83959b",
        hex_5: "#121f14",
        hex_6: "#65889c",
        hex_7: "#567995",
        hex_8: "#81a3bc",
        hex_9: "#ac7c60"
      },
      {
        original_file_name: "Misty_Mountain_Morning (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7531837,
        file_size_megabytes: 7.18,
        width: 3072,
        height: 5472,
        primary: "#d0cbc9",
        secondary: "#283328",
        tertiary: "#84897a",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#a1afaa",
        hex_5: "#4d6174",
        hex_6: "#54634c",
        hex_7: "#979ea8",
        hex_8: "#6a7c70",
        hex_9: "#ae5b29"
      }
    ]
  },
  Modern_Cityscape: {
    environment_title: "Modern_Cityscape",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Modern_Cityscape (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8849426,
        file_size_megabytes: 8.44,
        width: 3072,
        height: 5472,
        primary: "#d4d4cb",
        secondary: "#1a2724",
        tertiary: "#777c72",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8badb5",
        hex_5: "#6e92a4",
        hex_6: "#52736f",
        hex_7: "#41533f",
        hex_8: "#465b6b",
        hex_9: "#a48466"
      },
      {
        original_file_name: "Modern_Cityscape (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9329726,
        file_size_megabytes: 8.9,
        width: 3072,
        height: 5472,
        primary: "#22342c",
        secondary: "#ccd7d9",
        tertiary: "#97bdd1",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#729db6",
        hex_5: "#7a9085",
        hex_6: "#3e6c89",
        hex_7: "#70775f",
        hex_8: "#556947",
        hex_9: "#ac8c80"
      },
      {
        original_file_name: "Modern_Cityscape (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8215562,
        file_size_megabytes: 7.83,
        width: 3072,
        height: 5472,
        primary: "#cddee6",
        secondary: "#193132",
        tertiary: "#a0bdcf",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#779ebb",
        hex_5: "#808e66",
        hex_6: "#44697d",
        hex_7: "#598093",
        hex_8: "#4a614e",
        hex_9: "#b69c2a"
      },
      {
        original_file_name: "Modern_Cityscape (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9365021,
        file_size_megabytes: 8.93,
        width: 3072,
        height: 5472,
        primary: "#d0d9d8",
        secondary: "#94b7c5",
        tertiary: "#6791ad",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#1e2921",
        hex_5: "#7d8567",
        hex_6: "#485f71",
        hex_7: "#5b7874",
        hex_8: "#505c3b",
        hex_9: "#ac947c"
      }
    ]
  },
  Northern_Lights_Magic: {
    environment_title: "Northern_Lights_Magic",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Northern_Lights_Magic (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7443700,
        file_size_megabytes: 7.1,
        width: 3072,
        height: 5472,
        primary: "#293349",
        secondary: "#79c098",
        tertiary: "#6d738d",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#947898",
        hex_5: "#3a7c69",
        hex_6: "#9d8dae",
        hex_7: "#674a6f",
        hex_8: "#0b0b15",
        hex_9: "#a0c72e"
      },
      {
        original_file_name: "Northern_Lights_Magic (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7315005,
        file_size_megabytes: 6.98,
        width: 3072,
        height: 5472,
        primary: "#bbacaa",
        secondary: "#1e2b44",
        tertiary: "#5ac484",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#4e7c76",
        hex_5: "#8986a9",
        hex_6: "#635382",
        hex_7: "#060d14",
        hex_8: "#66346a",
        hex_9: "#34595f"
      },
      {
        original_file_name: "Northern_Lights_Magic (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7180984,
        file_size_megabytes: 6.85,
        width: 3072,
        height: 5472,
        primary: "#85c5a0",
        secondary: "#192535",
        tertiary: "#58897b",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#5d6584",
        hex_5: "#808da9",
        hex_6: "#989aa8",
        hex_7: "#37635d",
        hex_8: "#3b4764",
        hex_9: "#64566b"
      },
      {
        original_file_name: "Northern_Lights_Magic (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6797025,
        file_size_megabytes: 6.48,
        width: 3072,
        height: 5472,
        primary: "#82c789",
        secondary: "#142137",
        tertiary: "#327d67",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8e6d99",
        hex_5: "#454977",
        hex_6: "#5c799d",
        hex_7: "#1b544c",
        hex_8: "#12b65b",
        hex_9: "#4e2d61"
      }
    ]
  },
  Quiet_Alleyway: {
    environment_title: "Quiet_Alleyway",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Quiet_Alleyway (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9074439,
        file_size_megabytes: 8.65,
        width: 3072,
        height: 5472,
        primary: "#30261b",
        secondary: "#c6a58d",
        tertiary: "#8d7361",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#6b7369",
        hex_5: "#654a37",
        hex_6: "#5f5f60",
        hex_7: "#9da681",
        hex_8: "#8c969e",
        hex_9: "#ac5418"
      },
      {
        original_file_name: "Quiet_Alleyway (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9532683,
        file_size_megabytes: 9.09,
        width: 3072,
        height: 5472,
        primary: "#30261a",
        secondary: "#cebaa0",
        tertiary: "#8d7c63",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#64523c",
        hex_5: "#6f6e42",
        hex_6: "#6c625d",
        hex_7: "#a29a94",
        hex_8: "#a1a56e",
        hex_9: "#ae641c"
      },
      {
        original_file_name: "Quiet_Alleyway (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8717920,
        file_size_megabytes: 8.31,
        width: 3072,
        height: 5472,
        primary: "#c8aa85",
        secondary: "#2c261c",
        tertiary: "#846e58",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#636a55",
        hex_5: "#5c4536",
        hex_6: "#94a17e",
        hex_7: "#5c5b5d",
        hex_8: "#909194",
        hex_9: "#a64a07"
      },
      {
        original_file_name: "Quiet_Alleyway (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9797186,
        file_size_megabytes: 9.34,
        width: 3072,
        height: 5472,
        primary: "#cfc2ae",
        secondary: "#2e241a",
        tertiary: "#8c7256",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#6d695d",
        hex_5: "#654d38",
        hex_6: "#a09e91",
        hex_7: "#949295",
        hex_8: "#5f5b5d",
        hex_9: "#b34c25"
      }
    ]
  },
  Quiet_Park_Bench: {
    environment_title: "Quiet_Park_Bench",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Quiet_Park_Bench (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8854508,
        file_size_megabytes: 8.44,
        width: 3072,
        height: 5472,
        primary: "#cec774",
        secondary: "#2b3110",
        tertiary: "#8d8e37",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#a2ad38",
        hex_5: "#6f7827",
        hex_6: "#626421",
        hex_7: "#959792",
        hex_8: "#625e55",
        hex_9: "#ac846c"
      },
      {
        original_file_name: "Quiet_Park_Bench (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8524499,
        file_size_megabytes: 8.13,
        width: 3072,
        height: 5472,
        primary: "#c9bd73",
        secondary: "#2a2f14",
        tertiary: "#8a8436",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#a1a63f",
        hex_5: "#676f2a",
        hex_6: "#5b5a23",
        hex_7: "#5e5b5a",
        hex_8: "#9b9595",
        hex_9: "#ac7c64"
      },
      {
        original_file_name: "Quiet_Park_Bench (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8955391,
        file_size_megabytes: 8.54,
        width: 3072,
        height: 5472,
        primary: "#cfc783",
        secondary: "#26350f",
        tertiary: "#868348",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#9db22c",
        hex_5: "#617a26",
        hex_6: "#848d93",
        hex_7: "#5d5b54",
        hex_8: "#5a5b23",
        hex_9: "#ac7450"
      },
      {
        original_file_name: "Quiet_Park_Bench (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8141704,
        file_size_megabytes: 7.76,
        width: 3072,
        height: 5472,
        primary: "#343213",
        secondary: "#dfc78e",
        tertiary: "#94884e",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#725f58",
        hex_5: "#a7af4e",
        hex_6: "#6c632f",
        hex_7: "#777f30",
        hex_8: "#aa9995",
        hex_9: "#b47c54"
      }
    ]
  },
  Rolling_Hills: {
    environment_title: "Rolling_Hills",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Rolling_Hills (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11443194,
        file_size_megabytes: 10.91,
        width: 3072,
        height: 5472,
        primary: "#81add4",
        secondary: "#5b6218",
        tertiary: "#c0ad5f",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#0e2a1e",
        hex_5: "#9c9723",
        hex_6: "#323011",
        hex_7: "#868f11",
        hex_8: "#a8ac28",
        hex_9: "#5b665d"
      },
      {
        original_file_name: "Rolling_Hills (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8761044,
        file_size_megabytes: 8.36,
        width: 3072,
        height: 5472,
        primary: "#6d95ba",
        secondary: "#cfd6d3",
        tertiary: "#5b5e16",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#a7c0d0",
        hex_5: "#245c8a",
        hex_6: "#958e2a",
        hex_7: "#18220c",
        hex_8: "#1e659d",
        hex_9: "#828c28"
      },
      {
        original_file_name: "Rolling_Hills (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 12174484,
        file_size_megabytes: 11.61,
        width: 3072,
        height: 5472,
        primary: "#696d1a",
        secondary: "#132510",
        tertiary: "#73a3d7",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#c6ba5c",
        hex_5: "#99c1e5",
        hex_6: "#a5a035",
        hex_7: "#868c66",
        hex_8: "#35330a",
        hex_9: "#929c26"
      },
      {
        original_file_name: "Rolling_Hills (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 11393274,
        file_size_megabytes: 10.87,
        width: 3072,
        height: 5472,
        primary: "#b7a539",
        secondary: "#7cacd6",
        tertiary: "#142f1f",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#7b802e",
        hex_5: "#94a134",
        hex_6: "#586f2f",
        hex_7: "#495b2b",
        hex_8: "#3b5561",
        hex_9: "#c0d6e5"
      }
    ]
  },
  Rooftop_Sunset: {
    environment_title: "Rooftop_Sunset",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Rooftop_Sunset (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7665674,
        file_size_megabytes: 7.31,
        width: 3072,
        height: 5472,
        primary: "#e2a675",
        secondary: "#36241e",
        tertiary: "#a06b51",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#958988",
        hex_5: "#765348",
        hex_6: "#696e74",
        hex_7: "#595960",
        hex_8: "#b2a598",
        hex_9: "#be4a20"
      },
      {
        original_file_name: "Rooftop_Sunset (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8165338,
        file_size_megabytes: 7.79,
        width: 3072,
        height: 5472,
        primary: "#d99c67",
        secondary: "#4e372f",
        tertiary: "#936650",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#9a9189",
        hex_5: "#140d0b",
        hex_6: "#626365",
        hex_7: "#737574",
        hex_8: "#aaa498",
        hex_9: "#b45408"
      },
      {
        original_file_name: "Rooftop_Sunset (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7616292,
        file_size_megabytes: 7.26,
        width: 3072,
        height: 5472,
        primary: "#dda373",
        secondary: "#382e32",
        tertiary: "#8e5946",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#66423d",
        hex_5: "#767b89",
        hex_6: "#6a6872",
        hex_7: "#b84713",
        hex_8: "#5b5966",
        hex_9: "#a39487"
      },
      {
        original_file_name: "Rooftop_Sunset (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8504204,
        file_size_megabytes: 8.11,
        width: 3072,
        height: 5472,
        primary: "#de8552",
        secondary: "#322220",
        tertiary: "#94553e",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#5f6269",
        hex_5: "#5c4e58",
        hex_6: "#9d9998",
        hex_7: "#683c2b",
        hex_8: "#8c878d",
        hex_9: "#b43c16"
      }
    ]
  },
  Skyline_Reflections: {
    environment_title: "Skyline_Reflections",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Skyline_Reflections (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8010409,
        file_size_megabytes: 7.64,
        width: 3072,
        height: 5472,
        primary: "#e1a16a",
        secondary: "#2f2f32",
        tertiary: "#a5775a",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#725542",
        hex_5: "#7d6e62",
        hex_6: "#716165",
        hex_7: "#c77431",
        hex_8: "#b1a688",
        hex_9: "#a49494"
      },
      {
        original_file_name: "Skyline_Reflections (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8079080,
        file_size_megabytes: 7.7,
        width: 3072,
        height: 5472,
        primary: "#242e35",
        secondary: "#dd9f63",
        tertiary: "#635e60",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#967968",
        hex_5: "#543828",
        hex_6: "#784f25",
        hex_7: "#8b6047",
        hex_8: "#c4ae99",
        hex_9: "#447498"
      },
      {
        original_file_name: "Skyline_Reflections (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7620101,
        file_size_megabytes: 7.27,
        width: 3072,
        height: 5472,
        primary: "#dbb080",
        secondary: "#7994ac",
        tertiary: "#a3a8a7",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#232a2c",
        hex_5: "#947353",
        hex_6: "#61777f",
        hex_7: "#3b576a",
        hex_8: "#60422d",
        hex_9: "#c05207"
      },
      {
        original_file_name: "Skyline_Reflections (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7978391,
        file_size_megabytes: 7.61,
        width: 3072,
        height: 5472,
        primary: "#e4a66d",
        secondary: "#2a2e30",
        tertiary: "#9a796b",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#69564b",
        hex_5: "#6a7387",
        hex_6: "#3c5060",
        hex_7: "#756d68",
        hex_8: "#b19c90",
        hex_9: "#bc641c"
      }
    ]
  },
  Street_Market_Glow: {
    environment_title: "Street_Market_Glow",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Street_Market_Glow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8575521,
        file_size_megabytes: 8.18,
        width: 3072,
        height: 5472,
        primary: "#cd905d",
        secondary: "#23171a",
        tertiary: "#77a2bc",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#814d31",
        hex_5: "#2f80ab",
        hex_6: "#552f23",
        hex_7: "#556370",
        hex_8: "#ae310e",
        hex_9: "#4c4d5f"
      },
      {
        original_file_name: "Street_Market_Glow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7906677,
        file_size_megabytes: 7.54,
        width: 3072,
        height: 5472,
        primary: "#d6945e",
        secondary: "#1d1212",
        tertiary: "#1c6697",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#78422b",
        hex_5: "#4e2c23",
        hex_6: "#b22c0b",
        hex_7: "#2e5b6b",
        hex_8: "#094775",
        hex_9: "#30b0c2"
      },
      {
        original_file_name: "Street_Market_Glow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8231806,
        file_size_megabytes: 7.85,
        width: 3072,
        height: 5472,
        primary: "#d08e54",
        secondary: "#211314",
        tertiary: "#79492d",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#06447a",
        hex_5: "#4e2c1d",
        hex_6: "#054f96",
        hex_7: "#b8310c",
        hex_8: "#86966e",
        hex_9: "#3d5e5d"
      },
      {
        original_file_name: "Street_Market_Glow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8246463,
        file_size_megabytes: 7.86,
        width: 3072,
        height: 5472,
        primary: "#d99c5e",
        secondary: "#4d85aa",
        tertiary: "#20181c",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#86a0b3",
        hex_5: "#895637",
        hex_6: "#415267",
        hex_7: "#5a3325",
        hex_8: "#4c6c7a",
        hex_9: "#c72d0e"
      }
    ]
  },
  Subway_Station_Glow: {
    environment_title: "Subway_Station_Glow",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Subway_Station_Glow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7396122,
        file_size_megabytes: 7.05,
        width: 3072,
        height: 5472,
        primary: "#d0ccca",
        secondary: "#6ea6b2",
        tertiary: "#744c49",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#0b141d",
        hex_5: "#c53a2f",
        hex_6: "#3a8499",
        hex_7: "#246475",
        hex_8: "#422225",
        hex_9: "#114761"
      },
      {
        original_file_name: "Subway_Station_Glow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6689123,
        file_size_megabytes: 6.38,
        width: 3072,
        height: 5472,
        primary: "#caccc5",
        secondary: "#1b2022",
        tertiary: "#787d78",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8ca198",
        hex_5: "#4b5150",
        hex_6: "#596662",
        hex_7: "#b95182",
        hex_8: "#585b64",
        hex_9: "#91919d"
      },
      {
        original_file_name: "Subway_Station_Glow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7417764,
        file_size_megabytes: 7.07,
        width: 3072,
        height: 5472,
        primary: "#cfc19d",
        secondary: "#1c2027",
        tertiary: "#767c7d",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#909c9c",
        hex_5: "#596669",
        hex_6: "#494f51",
        hex_7: "#8c939c",
        hex_8: "#515b64",
        hex_9: "#ad1173"
      },
      {
        original_file_name: "Subway_Station_Glow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6999909,
        file_size_megabytes: 6.68,
        width: 3072,
        height: 5472,
        primary: "#d2c5b6",
        secondary: "#202326",
        tertiary: "#75736f",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#4c4946",
        hex_5: "#919d9c",
        hex_6: "#586667",
        hex_7: "#b63d43",
        hex_8: "#88939c",
        hex_9: "#4f5b64"
      }
    ]
  },
  Towering_Skyscrapers: {
    environment_title: "Towering_Skyscrapers",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Towering_Skyscrapers (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9283517,
        file_size_megabytes: 8.85,
        width: 3072,
        height: 5472,
        primary: "#cfc4b6",
        secondary: "#252622",
        tertiary: "#89a1b4",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8e8d88",
        hex_5: "#a3b8c2",
        hex_6: "#667e8d",
        hex_7: "#5f574b",
        hex_8: "#566877",
        hex_9: "#b46444"
      },
      {
        original_file_name: "Towering_Skyscrapers (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9101674,
        file_size_megabytes: 8.68,
        width: 3072,
        height: 5472,
        primary: "#cfcac5",
        secondary: "#1d2527",
        tertiary: "#909291",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#90a5b8",
        hex_5: "#658294",
        hex_6: "#a5b5c0",
        hex_7: "#4d6e82",
        hex_8: "#5b5a55",
        hex_9: "#b49481"
      },
      {
        original_file_name: "Towering_Skyscrapers (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 10007387,
        file_size_megabytes: 9.54,
        width: 3072,
        height: 5472,
        primary: "#272a2a",
        secondary: "#d6d3ce",
        tertiary: "#86a0b7",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#958a7e",
        hex_5: "#acb9c2",
        hex_6: "#695f54",
        hex_7: "#6f838f",
        hex_8: "#3d647f",
        hex_9: "#bc7c40"
      },
      {
        original_file_name: "Towering_Skyscrapers (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 9091778,
        file_size_megabytes: 8.67,
        width: 3072,
        height: 5472,
        primary: "#293035",
        secondary: "#c8baa5",
        tertiary: "#5284b7",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#4c7599",
        hex_5: "#857c6e",
        hex_6: "#736556",
        hex_7: "#3a566d",
        hex_8: "#98aeba",
        hex_9: "#a47c5c"
      }
    ]
  },
  Tranquil_Waterfall: {
    environment_title: "Tranquil_Waterfall",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Tranquil_Waterfall (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8532436,
        file_size_megabytes: 8.14,
        width: 3072,
        height: 5472,
        primary: "#c4c5ae",
        secondary: "#1b2318",
        tertiary: "#74775a",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8ea097",
        hex_5: "#7a8b9c",
        hex_6: "#55694e",
        hex_7: "#4c4e31",
        hex_8: "#475663",
        hex_9: "#9c744a"
      },
      {
        original_file_name: "Tranquil_Waterfall (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8939964,
        file_size_megabytes: 8.53,
        width: 3072,
        height: 5472,
        primary: "#c7c38b",
        secondary: "#1a261a",
        tertiary: "#747643",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#89a27d",
        hex_5: "#4c6d4f",
        hex_6: "#6d8a9f",
        hex_7: "#4c4f2d",
        hex_8: "#3a5563",
        hex_9: "#9c6c24"
      },
      {
        original_file_name: "Tranquil_Waterfall (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8568942,
        file_size_megabytes: 8.17,
        width: 3072,
        height: 5472,
        primary: "#c7c296",
        secondary: "#21261c",
        tertiary: "#76764f",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#8da190",
        hex_5: "#72879e",
        hex_6: "#56685c",
        hex_7: "#4c4d2e",
        hex_8: "#465564",
        hex_9: "#9c643c"
      },
      {
        original_file_name: "Tranquil_Waterfall (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8596112,
        file_size_megabytes: 8.2,
        width: 3072,
        height: 5472,
        primary: "#c2c9b0",
        secondary: "#1b2215",
        tertiary: "#6d7c5a",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#7b8f9f",
        hex_5: "#8fa79a",
        hex_6: "#475861",
        hex_7: "#45532a",
        hex_8: "#695b3a",
        hex_9: "#9c744a"
      }
    ]
  },
  Vibrant_City_Nights: {
    environment_title: "Vibrant_City_Nights",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Vibrant_City_Nights (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8598262,
        file_size_megabytes: 8.2,
        width: 3072,
        height: 5472,
        primary: "#cb6c6a",
        secondary: "#100e19",
        tertiary: "#35afd2",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#2d5071",
        hex_5: "#61252c",
        hex_6: "#3075a2",
        hex_7: "#e4dec6",
        hex_8: "#1a2e45",
        hex_9: "#324d4f"
      },
      {
        original_file_name: "Vibrant_City_Nights (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7663709,
        file_size_megabytes: 7.31,
        width: 3072,
        height: 5472,
        primary: "#c7695a",
        secondary: "#0d0f18",
        tertiary: "#4aaeca",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#29556f",
        hex_5: "#602c23",
        hex_6: "#3271a7",
        hex_7: "#d3e1ca",
        hex_8: "#143145",
        hex_9: "#214f49"
      },
      {
        original_file_name: "Vibrant_City_Nights (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8291376,
        file_size_megabytes: 7.91,
        width: 3072,
        height: 5472,
        primary: "#c96458",
        secondary: "#14121d",
        tertiary: "#6b383e",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#61a7ba",
        hex_5: "#ded5ce",
        hex_6: "#1e586c",
        hex_7: "#1c3245",
        hex_8: "#4d7a99",
        hex_9: "#385850"
      },
      {
        original_file_name: "Vibrant_City_Nights (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8556645,
        file_size_megabytes: 8.16,
        width: 3072,
        height: 5472,
        primary: "#d09a99",
        secondary: "#36adb7",
        tertiary: "#0f0f1a",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#2a4b6f",
        hex_5: "#296da2",
        hex_6: "#62252d",
        hex_7: "#ab285b",
        hex_8: "#162845",
        hex_9: "#0a6348"
      }
    ]
  },
  Vibrant_Wildflowers: {
    environment_title: "Vibrant_Wildflowers",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Vibrant_Wildflowers (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7734914,
        file_size_megabytes: 7.38,
        width: 3072,
        height: 5472,
        primary: "#3c3b1c",
        secondary: "#d6ab6e",
        tertiary: "#9f8353",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#b0ae55",
        hex_5: "#664f6c",
        hex_6: "#9a76a9",
        hex_7: "#746033",
        hex_8: "#7e7f39",
        hex_9: "#da330f"
      },
      {
        original_file_name: "Vibrant_Wildflowers (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7934466,
        file_size_megabytes: 7.57,
        width: 3072,
        height: 5472,
        primary: "#d6913a",
        secondary: "#655e2d",
        tertiary: "#1e2610",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#a5863d",
        hex_5: "#8c6f70",
        hex_6: "#9c6ba0",
        hex_7: "#661f22",
        hex_8: "#8d8f35",
        hex_9: "#b0b54b"
      },
      {
        original_file_name: "Vibrant_Wildflowers (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7687032,
        file_size_megabytes: 7.33,
        width: 3072,
        height: 5472,
        primary: "#5f5628",
        secondary: "#e0a86a",
        tertiary: "#212812",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#aa813f",
        hex_5: "#9e7971",
        hex_6: "#db2d2f",
        hex_7: "#b3af48",
        hex_8: "#811521",
        hex_9: "#935ea9"
      },
      {
        original_file_name: "Vibrant_Wildflowers (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7817339,
        file_size_megabytes: 7.46,
        width: 3072,
        height: 5472,
        primary: "#877d35",
        secondary: "#df9b42",
        tertiary: "#212711",
        downloadLink: "https://github.com/yt-dlx/pikWall/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/pikWall/",
        hex_4: "#40431f",
        hex_5: "#b3b73e",
        hex_6: "#a288a3",
        hex_7: "#5d2421",
        hex_8: "#957b76",
        hex_9: "#6e422e"
      }
    ]
  }
};
export default PhotographyDatabase;
