import { EnvironmentEntry } from "@/types/database";
const PortraitDatabase: Record<string, EnvironmentEntry> = {
  Artistic_Flair: {
    environment_title: "Artistic_Flair",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Artistic_Flair (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5305855,
        file_size_megabytes: 5.06,
        width: 3072,
        height: 5472,
        primary: "#d16022",
        secondary: "#1367ac",
        tertiary: "#0a0a0f",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#652b1e",
        hex_5: "#15375e",
        hex_6: "#227f66",
        hex_7: "#351520",
        hex_8: "#204329",
        hex_9: "#8c3ae6"
      },
      {
        original_file_name: "Artistic_Flair (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6489622,
        file_size_megabytes: 6.19,
        width: 3072,
        height: 5472,
        primary: "#c56246",
        secondary: "#100d13",
        tertiary: "#6b2424",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#4ea7b5",
        hex_5: "#25728e",
        hex_6: "#ebc981",
        hex_7: "#18596b",
        hex_8: "#3e1416",
        hex_9: "#1b3857"
      },
      {
        original_file_name: "Artistic_Flair (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6947500,
        file_size_megabytes: 6.63,
        width: 3072,
        height: 5472,
        primary: "#cd7942",
        secondary: "#1d0f10",
        tertiary: "#7a3f28",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#f4d79a",
        hex_5: "#4e261b",
        hex_6: "#4caebd",
        hex_7: "#1a6aa2",
        hex_8: "#2a575b",
        hex_9: "#24335b"
      },
      {
        original_file_name: "Artistic_Flair (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6697817,
        file_size_megabytes: 6.39,
        width: 3072,
        height: 5472,
        primary: "#cd9872",
        secondary: "#1a1112",
        tertiary: "#2a9cad",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#704337",
        hex_5: "#355a9a",
        hex_6: "#422c27",
        hex_7: "#316268",
        hex_8: "#2c3261",
        hex_9: "#a03027"
      }
    ]
  },
  Bold_Contrast: {
    environment_title: "Bold_Contrast",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Bold_Contrast (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5242938,
        file_size_megabytes: 5.0,
        width: 3072,
        height: 5472,
        primary: "#bb7f55",
        secondary: "#0c0b0b",
        tertiary: "#623b27",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#3e6479",
        hex_5: "#3b859e",
        hex_6: "#344a55",
        hex_7: "#341d12",
        hex_8: "#283642",
        hex_9: "#8e320e"
      },
      {
        original_file_name: "Bold_Contrast (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6291539,
        file_size_megabytes: 6.0,
        width: 3072,
        height: 5472,
        primary: "#c88f6e",
        secondary: "#160b09",
        tertiary: "#713d28",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#452114",
        hex_5: "#aa2117",
        hex_6: "#8c745e",
        hex_7: "#846c5c",
        hex_8: "#544432",
        hex_9: "#2e2e2c"
      },
      {
        original_file_name: "Bold_Contrast (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6184200,
        file_size_megabytes: 5.9,
        width: 3072,
        height: 5472,
        primary: "#988f89",
        secondary: "#150f0f",
        tertiary: "#64868a",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#5b3f3a",
        hex_5: "#365055",
        hex_6: "#3a221e",
        hex_7: "#8c141b",
        hex_8: "#4c6a75",
        hex_9: "#2a3b44"
      },
      {
        original_file_name: "Bold_Contrast (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5903603,
        file_size_megabytes: 5.63,
        width: 3072,
        height: 5472,
        primary: "#beaba0",
        secondary: "#140f0f",
        tertiary: "#765749",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#90999d",
        hex_5: "#82898e",
        hex_6: "#4b2b1e",
        hex_7: "#535c62",
        hex_8: "#40474f",
        hex_9: "#9d4d3a"
      }
    ]
  },
  Candid_Smile: {
    environment_title: "Candid_Smile",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Candid_Smile (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6902730,
        file_size_megabytes: 6.58,
        width: 3072,
        height: 5472,
        primary: "#d4ba9c",
        secondary: "#30251d",
        tertiary: "#977652",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#a3a7aa",
        hex_5: "#8c96a1",
        hex_6: "#707470",
        hex_7: "#4a5765",
        hex_8: "#6e4e2e",
        hex_9: "#bf470f"
      },
      {
        original_file_name: "Candid_Smile (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6885215,
        file_size_megabytes: 6.57,
        width: 3072,
        height: 5472,
        primary: "#513626",
        secondary: "#d1ba9c",
        tertiary: "#956b48",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#16110a",
        hex_5: "#545864",
        hex_6: "#a9a696",
        hex_7: "#766d58",
        hex_8: "#9a9597",
        hex_9: "#b46c3c"
      },
      {
        original_file_name: "Candid_Smile (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7220230,
        file_size_megabytes: 6.89,
        width: 3072,
        height: 5472,
        primary: "#302825",
        secondary: "#d4b391",
        tertiary: "#937159",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#714d37",
        hex_5: "#786e63",
        hex_6: "#515b66",
        hex_7: "#a9a49b",
        hex_8: "#a39b9c",
        hex_9: "#b45c2c"
      },
      {
        original_file_name: "Candid_Smile (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6537161,
        file_size_megabytes: 6.23,
        width: 3072,
        height: 5472,
        primary: "#5d3c27",
        secondary: "#e0ba93",
        tertiary: "#20160b",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#9e8777",
        hex_5: "#b0a6a0",
        hex_6: "#816f68",
        hex_7: "#9c683c",
        hex_8: "#a49a9d",
        hex_9: "#bc5c14"
      }
    ]
  },
  Cultural_Elegance: {
    environment_title: "Cultural_Elegance",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Cultural_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 8243856,
        file_size_megabytes: 7.86,
        width: 3072,
        height: 5472,
        primary: "#c49c7c",
        secondary: "#2e1d18",
        tertiary: "#8d513c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#96a391",
        hex_5: "#5d7266",
        hex_6: "#bc3722",
        hex_7: "#663122",
        hex_8: "#6e8d90",
        hex_9: "#3a4d58"
      },
      {
        original_file_name: "Cultural_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7673998,
        file_size_megabytes: 7.32,
        width: 3072,
        height: 5472,
        primary: "#d08d62",
        secondary: "#2e1710",
        tertiary: "#8d482c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#66311c",
        hex_5: "#be130c",
        hex_6: "#1c7e85",
        hex_7: "#436657",
        hex_8: "#559e8f",
        hex_9: "#184b4f"
      },
      {
        original_file_name: "Cultural_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7754015,
        file_size_megabytes: 7.39,
        width: 3072,
        height: 5472,
        primary: "#c88760",
        secondary: "#2c1810",
        tertiary: "#8f5231",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#663921",
        hex_5: "#939885",
        hex_6: "#656453",
        hex_7: "#b0370b",
        hex_8: "#314c4f",
        hex_9: "#9d8c8d"
      },
      {
        original_file_name: "Cultural_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7689795,
        file_size_megabytes: 7.33,
        width: 3072,
        height: 5472,
        primary: "#c7956e",
        secondary: "#221412",
        tertiary: "#804f3c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#8d9d86",
        hex_5: "#3d6259",
        hex_6: "#562c22",
        hex_7: "#1f808f",
        hex_8: "#ab3025",
        hex_9: "#164a57"
      }
    ]
  },
  Delicate_Balance_Generate: {
    environment_title: "Delicate_Balance_Generate",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Delicate_Balance_Generate (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7196811,
        file_size_megabytes: 6.86,
        width: 3072,
        height: 5472,
        primary: "#765851",
        secondary: "#90acb0",
        tertiary: "#c19c8e",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#190e0d",
        hex_5: "#848482",
        hex_6: "#3e1f17",
        hex_7: "#474544",
        hex_8: "#573120",
        hex_9: "#969c93"
      },
      {
        original_file_name: "Delicate_Balance_Generate (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6778528,
        file_size_megabytes: 6.46,
        width: 3072,
        height: 5472,
        primary: "#d5b9a4",
        secondary: "#6d584d",
        tertiary: "#1b130e",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#a8afae",
        hex_5: "#56351f",
        hex_6: "#a78473",
        hex_7: "#402119",
        hex_8: "#a79fa7",
        hex_9: "#828d86"
      },
      {
        original_file_name: "Delicate_Balance_Generate (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6574047,
        file_size_megabytes: 6.27,
        width: 3072,
        height: 5472,
        primary: "#b4947f",
        secondary: "#3f322c",
        tertiary: "#826355",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#8e8a82",
        hex_5: "#485354",
        hex_6: "#636059",
        hex_7: "#110a07",
        hex_8: "#877c7c",
        hex_9: "#9c444c"
      },
      {
        original_file_name: "Delicate_Balance_Generate (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6978220,
        file_size_megabytes: 6.65,
        width: 3072,
        height: 5472,
        primary: "#624941",
        secondary: "#bbb9af",
        tertiary: "#c2aa92",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#b58e75",
        hex_5: "#956f60",
        hex_6: "#918583",
        hex_7: "#3b211b",
        hex_8: "#25130f",
        hex_9: "#7d7c72"
      }
    ]
  },
  Elegant_Simplicity: {
    environment_title: "Elegant_Simplicity",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Elegant_Simplicity (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6738085,
        file_size_megabytes: 6.43,
        width: 3072,
        height: 5472,
        primary: "#aa8c75",
        secondary: "#301b10",
        tertiary: "#583524",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#d1ccc2",
        hex_5: "#d7b29a",
        hex_6: "#664936",
        hex_7: "#805642",
        hex_8: "#764a33",
        hex_9: "#dec4ab"
      },
      {
        original_file_name: "Elegant_Simplicity (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6413849,
        file_size_megabytes: 6.12,
        width: 3072,
        height: 5472,
        primary: "#957c66",
        secondary: "#241610",
        tertiary: "#d7cfc4",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#d4a789",
        hex_5: "#542e1d",
        hex_6: "#5d4b3e",
        hex_7: "#613f29",
        hex_8: "#78503b",
        hex_9: "#c1bca4"
      },
      {
        original_file_name: "Elegant_Simplicity (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6320959,
        file_size_megabytes: 6.03,
        width: 3072,
        height: 5472,
        primary: "#997e66",
        secondary: "#351f11",
        tertiary: "#cdc9c1",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#573321",
        hex_5: "#b5aca2",
        hex_6: "#654c3b",
        hex_7: "#d6b096",
        hex_8: "#c2bcab",
        hex_9: "#6a442b"
      },
      {
        original_file_name: "Elegant_Simplicity (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6321500,
        file_size_megabytes: 6.03,
        width: 3072,
        height: 5472,
        primary: "#a0876f",
        secondary: "#23130c",
        tertiary: "#ccc8c2",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#603825",
        hex_5: "#6f4730",
        hex_6: "#6c5849",
        hex_7: "#cda48e",
        hex_8: "#855640",
        hex_9: "#c9b4a1"
      }
    ]
  },
  Ethereal_Beauty: {
    environment_title: "Ethereal_Beauty",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Ethereal_Beauty (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7267326,
        file_size_megabytes: 6.93,
        width: 3072,
        height: 5472,
        primary: "#e1c4a4",
        secondary: "#5c453b",
        tertiary: "#1a1513",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#818487",
        hex_5: "#6a7078",
        hex_6: "#8f9ca7",
        hex_7: "#321911",
        hex_8: "#956949",
        hex_9: "#a8acaf"
      },
      {
        original_file_name: "Ethereal_Beauty (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6869160,
        file_size_megabytes: 6.55,
        width: 3072,
        height: 5472,
        primary: "#4d3831",
        secondary: "#dbc7ac",
        tertiary: "#917a69",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#a6a6a1",
        hex_5: "#727271",
        hex_6: "#91989f",
        hex_7: "#140b0a",
        hex_8: "#626267",
        hex_9: "#b66431"
      },
      {
        original_file_name: "Ethereal_Beauty (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6542913,
        file_size_megabytes: 6.24,
        width: 3072,
        height: 5472,
        primary: "#dfc9b3",
        secondary: "#342621",
        tertiary: "#956d56",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#a2aaae",
        hex_5: "#8794a0",
        hex_6: "#6e7781",
        hex_7: "#6e4735",
        hex_8: "#565d69",
        hex_9: "#b46442"
      },
      {
        original_file_name: "Ethereal_Beauty (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5873121,
        file_size_megabytes: 5.6,
        width: 3072,
        height: 5472,
        primary: "#d1ccc8",
        secondary: "#28211e",
        tertiary: "#887063",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#a0a09b",
        hex_5: "#5c4439",
        hex_6: "#686764",
        hex_7: "#959394",
        hex_8: "#5d5b5c",
        hex_9: "#ac7460"
      }
    ]
  },
  Golden_Elegance: {
    environment_title: "Golden_Elegance",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Golden_Elegance (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6976604,
        file_size_megabytes: 6.65,
        width: 3072,
        height: 5472,
        primary: "#ca9767",
        secondary: "#26140a",
        tertiary: "#8b5833",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#5f361a",
        hex_5: "#ac643c",
        hex_6: "#a09484",
        hex_7: "#685f52",
        hex_8: "#94847c",
        hex_9: "#5e4e44"
      },
      {
        original_file_name: "Golden_Elegance (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7039170,
        file_size_megabytes: 6.71,
        width: 3072,
        height: 5472,
        primary: "#c78955",
        secondary: "#221109",
        tertiary: "#844d28",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#562c14",
        hex_5: "#634c37",
        hex_6: "#987a64",
        hex_7: "#94846c",
        hex_8: "#a44c24",
        hex_9: "#443434"
      },
      {
        original_file_name: "Golden_Elegance (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6833825,
        file_size_megabytes: 6.52,
        width: 3072,
        height: 5472,
        primary: "#cc9866",
        secondary: "#20100b",
        tertiary: "#835332",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#57311a",
        hex_5: "#a5541f",
        hex_6: "#948074",
        hex_7: "#9c8c64",
        hex_8: "#544744",
        hex_9: "#64543c"
      },
      {
        original_file_name: "Golden_Elegance (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7361339,
        file_size_megabytes: 7.02,
        width: 3072,
        height: 5472,
        primary: "#c79160",
        secondary: "#2d170b",
        tertiary: "#8f5730",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#67381c",
        hex_5: "#ae5429",
        hex_6: "#715e45",
        hex_7: "#a08674",
        hex_8: "#4d3e34",
        hex_9: "#a4947c"
      }
    ]
  },
  Monochrome_Grace: {
    environment_title: "Monochrome_Grace",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Monochrome_Grace (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 4311167,
        file_size_megabytes: 4.11,
        width: 3072,
        height: 5472,
        primary: "#babab9",
        secondary: "#656562",
        tertiary: "#0d0d0d",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#373835",
        hex_5: "#848c84",
        hex_6: "#444c44",
        hex_7: "#84848c",
        hex_8: "#8c848c",
        hex_9: "#44444c"
      },
      {
        original_file_name: "Monochrome_Grace (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5193818,
        file_size_megabytes: 4.95,
        width: 3072,
        height: 5472,
        primary: "#bbbbb9",
        secondary: "#111110",
        tertiary: "#656562",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#3b3b37",
        hex_5: "#848384",
        hex_6: "#4c4c4c",
        hex_7: "#8c8486",
        hex_8: "#848c84",
        hex_9: "#4c544c"
      },
      {
        original_file_name: "Monochrome_Grace (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5717551,
        file_size_megabytes: 5.45,
        width: 3072,
        height: 5472,
        primary: "#171716",
        secondary: "#aaaaa9",
        tertiary: "#70706d",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#8b8c89",
        hex_5: "#535450",
        hex_6: "#444441",
        hex_7: "#948c8c",
        hex_8: "#84848c",
        hex_9: "#4c4c54"
      },
      {
        original_file_name: "Monochrome_Grace (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5830686,
        file_size_megabytes: 5.56,
        width: 3072,
        height: 5472,
        primary: "#b7b7b5",
        secondary: "#111110",
        tertiary: "#666663",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#8b8c89",
        hex_5: "#848484",
        hex_6: "#3b3b39",
        hex_7: "#4c4c4c",
        hex_8: "#4c544c",
        hex_9: "#948c8c"
      }
    ]
  },
  Mystic_Vibes: {
    environment_title: "Mystic_Vibes",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Mystic_Vibes (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5552727,
        file_size_megabytes: 5.3,
        width: 3072,
        height: 5472,
        primary: "#0f1013",
        secondary: "#908782",
        tertiary: "#534540",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#7a635d",
        hex_5: "#314e5a",
        hex_6: "#322926",
        hex_7: "#253946",
        hex_8: "#5f6874",
        hex_9: "#867464"
      },
      {
        original_file_name: "Mystic_Vibes (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5000288,
        file_size_megabytes: 4.77,
        width: 3072,
        height: 5472,
        primary: "#0c0c0f",
        secondary: "#968178",
        tertiary: "#523e34",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#4b5e68",
        hex_5: "#5b6e77",
        hex_6: "#34444d",
        hex_7: "#32231c",
        hex_8: "#22323d",
        hex_9: "#744446"
      },
      {
        original_file_name: "Mystic_Vibes (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5861796,
        file_size_megabytes: 5.59,
        width: 3072,
        height: 5472,
        primary: "#a1836f",
        secondary: "#0e1014",
        tertiary: "#645043",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#5c8590",
        hex_5: "#345864",
        hex_6: "#352a26",
        hex_7: "#2a404f",
        hex_8: "#b9c4c0",
        hex_9: "#6d8479"
      },
      {
        original_file_name: "Mystic_Vibes (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6057597,
        file_size_megabytes: 5.78,
        width: 3072,
        height: 5472,
        primary: "#141414",
        secondary: "#aca092",
        tertiary: "#686157",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#8d776d",
        hex_5: "#53423c",
        hex_6: "#353734",
        hex_7: "#372925",
        hex_8: "#2c434e",
        hex_9: "#918384"
      }
    ]
  },
  Natural_Serenity: {
    environment_title: "Natural_Serenity",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Natural_Serenity (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7128779,
        file_size_megabytes: 6.8,
        width: 3072,
        height: 5472,
        primary: "#cab99b",
        secondary: "#252713",
        tertiary: "#7f7153",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#534b2f",
        hex_5: "#9b9d7b",
        hex_6: "#606646",
        hex_7: "#5c5b54",
        hex_8: "#979494",
        hex_9: "#a45c50"
      },
      {
        original_file_name: "Natural_Serenity (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7146384,
        file_size_megabytes: 6.82,
        width: 3072,
        height: 5472,
        primary: "#bdad83",
        secondary: "#212515",
        tertiary: "#786541",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#90a1a3",
        hex_5: "#7f8c92",
        hex_6: "#4c4323",
        hex_7: "#566862",
        hex_8: "#4b5758",
        hex_9: "#9c5c36"
      },
      {
        original_file_name: "Natural_Serenity (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7219247,
        file_size_megabytes: 6.88,
        width: 3072,
        height: 5472,
        primary: "#c29972",
        secondary: "#1e2311",
        tertiary: "#785d3d",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#6d7a7e",
        hex_5: "#4c4124",
        hex_6: "#3f4d4e",
        hex_7: "#55673c",
        hex_8: "#909d7c",
        hex_9: "#9c4c3a"
      },
      {
        original_file_name: "Natural_Serenity (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7140714,
        file_size_megabytes: 6.81,
        width: 3072,
        height: 5472,
        primary: "#cdbb8a",
        secondary: "#24261a",
        tertiary: "#806f43",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#554929",
        hex_5: "#999d69",
        hex_6: "#606539",
        hex_7: "#465660",
        hex_8: "#8c9494",
        hex_9: "#a46438"
      }
    ]
  },
  Poised_Perfection: {
    environment_title: "Poised_Perfection",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Poised_Perfection (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5592711,
        file_size_megabytes: 5.33,
        width: 3072,
        height: 5472,
        primary: "#232325",
        secondary: "#ba9582",
        tertiary: "#6f5448",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#483f3d",
        hex_5: "#888f95",
        hex_6: "#7e838c",
        hex_7: "#3b4445",
        hex_8: "#4d525d",
        hex_9: "#535c64"
      },
      {
        original_file_name: "Poised_Perfection (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6536663,
        file_size_megabytes: 6.23,
        width: 3072,
        height: 5472,
        primary: "#404142",
        secondary: "#ccab9c",
        tertiary: "#0d0d0f",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#1e1a1b",
        hex_5: "#85675c",
        hex_6: "#686b74",
        hex_7: "#6b7476",
        hex_8: "#989aa5",
        hex_9: "#99a5a7"
      },
      {
        original_file_name: "Poised_Perfection (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6909817,
        file_size_megabytes: 6.59,
        width: 3072,
        height: 5472,
        primary: "#b79b8f",
        secondary: "#252324",
        tertiary: "#76574a",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#52372d",
        hex_5: "#8a8b94",
        hex_6: "#8c9498",
        hex_7: "#5a5e63",
        hex_8: "#53535c",
        hex_9: "#94543f"
      },
      {
        original_file_name: "Poised_Perfection (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6273317,
        file_size_megabytes: 5.98,
        width: 3072,
        height: 5472,
        primary: "#cab2a7",
        secondary: "#403e3e",
        tertiary: "#866150",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#0c0c0d",
        hex_5: "#201919",
        hex_6: "#95999f",
        hex_7: "#9aa5a5",
        hex_8: "#6a6e72",
        hex_9: "#62626c"
      }
    ]
  },
  Radiant_Glow: {
    environment_title: "Radiant_Glow",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Radiant_Glow (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7351611,
        file_size_megabytes: 7.01,
        width: 3072,
        height: 5472,
        primary: "#ebc594",
        secondary: "#6c4221",
        tertiary: "#d68f49",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#24170a",
        hex_5: "#aa886c",
        hex_6: "#b0a196",
        hex_7: "#a76630",
        hex_8: "#8e705f",
        hex_9: "#431907"
      },
      {
        original_file_name: "Radiant_Glow (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6983533,
        file_size_megabytes: 6.66,
        width: 3072,
        height: 5472,
        primary: "#e2b57e",
        secondary: "#805232",
        tertiary: "#221509",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#b1ab9d",
        hex_5: "#401e0a",
        hex_6: "#9f8a79",
        hex_7: "#483018",
        hex_8: "#9f9a94",
        hex_9: "#aa7f56"
      },
      {
        original_file_name: "Radiant_Glow (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7179049,
        file_size_megabytes: 6.85,
        width: 3072,
        height: 5472,
        primary: "#683c1f",
        secondary: "#ecc592",
        tertiary: "#251309",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#d18c4e",
        hex_5: "#af9e9a",
        hex_6: "#a58670",
        hex_7: "#a56535",
        hex_8: "#8b6f62",
        hex_9: "#fcac44"
      },
      {
        original_file_name: "Radiant_Glow (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7098784,
        file_size_megabytes: 6.77,
        width: 3072,
        height: 5472,
        primary: "#3a1f0e",
        secondary: "#d28643",
        tertiary: "#9d6d4b",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#e7be8d",
        hex_5: "#9c928b",
        hex_6: "#764624",
        hex_7: "#7e6c5e",
        hex_8: "#61554e",
        hex_9: "#94a4a8"
      }
    ]
  },
  Rustic_Charm: {
    environment_title: "Rustic_Charm",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Rustic_Charm (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7436338,
        file_size_megabytes: 7.09,
        width: 3072,
        height: 5472,
        primary: "#c59c7a",
        secondary: "#301e14",
        tertiary: "#8c6347",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#66412b",
        hex_5: "#65635b",
        hex_6: "#7a8589",
        hex_7: "#9e9889",
        hex_8: "#474c52",
        hex_9: "#ac442c"
      },
      {
        original_file_name: "Rustic_Charm (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7338223,
        file_size_megabytes: 7.0,
        width: 3072,
        height: 5472,
        primary: "#d29d6c",
        secondary: "#352112",
        tertiary: "#96663c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#6f4929",
        hex_5: "#796534",
        hex_6: "#b4643a",
        hex_7: "#ac9c69",
        hex_8: "#947c7c",
        hex_9: "#5c4c44"
      },
      {
        original_file_name: "Rustic_Charm (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7545783,
        file_size_megabytes: 7.2,
        width: 3072,
        height: 5472,
        primary: "#bd9364",
        secondary: "#27180d",
        tertiary: "#86653c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#626442",
        hex_5: "#5e3f22",
        hex_6: "#989553",
        hex_7: "#3c4b53",
        hex_8: "#75868e",
        hex_9: "#a5350f"
      },
      {
        original_file_name: "Rustic_Charm (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7267323,
        file_size_megabytes: 6.93,
        width: 3072,
        height: 5472,
        primary: "#c49b77",
        secondary: "#2e1b0f",
        tertiary: "#86603e",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#5f3d24",
        hex_5: "#9b8a74",
        hex_6: "#6a5e36",
        hex_7: "#9c9472",
        hex_8: "#4c3d34",
        hex_9: "#a44c41"
      }
    ]
  },
  Subtle_Emotions: {
    environment_title: "Subtle_Emotions",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Subtle_Emotions (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6583628,
        file_size_megabytes: 6.28,
        width: 3072,
        height: 5472,
        primary: "#bd9f87",
        secondary: "#312219",
        tertiary: "#835f4d",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#918272",
        hex_5: "#5e3e31",
        hex_6: "#635a4f",
        hex_7: "#424644",
        hex_8: "#a45c54",
        hex_9: "#647474"
      },
      {
        original_file_name: "Subtle_Emotions (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6729323,
        file_size_megabytes: 6.42,
        width: 3072,
        height: 5472,
        primary: "#967966",
        secondary: "#2b1a11",
        tertiary: "#e3e3db",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#552e22",
        hex_5: "#5d554e",
        hex_6: "#633e2a",
        hex_7: "#b7bab4",
        hex_8: "#adaa9e",
        hex_9: "#cdbcab"
      },
      {
        original_file_name: "Subtle_Emotions (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7158432,
        file_size_megabytes: 6.83,
        width: 3072,
        height: 5472,
        primary: "#231510",
        secondary: "#8d6954",
        tertiary: "#b59b8c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#4c281e",
        hex_5: "#ad8871",
        hex_6: "#543a2c",
        hex_7: "#b1947b",
        hex_8: "#6a4032",
        hex_9: "#51341c"
      },
      {
        original_file_name: "Subtle_Emotions (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6759967,
        file_size_megabytes: 6.45,
        width: 3072,
        height: 5472,
        primary: "#523325",
        secondary: "#b7947c",
        tertiary: "#160c08",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#8c664f",
        hex_5: "#997d68",
        hex_6: "#795c48",
        hex_7: "#7d706d",
        hex_8: "#6b534c",
        hex_9: "#a45454"
      }
    ]
  },
  The_Thinker: {
    environment_title: "The_Thinker",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "The_Thinker (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6264783,
        file_size_megabytes: 5.97,
        width: 3072,
        height: 5472,
        primary: "#ca8f65",
        secondary: "#141a21",
        tertiary: "#6a5c50",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#54809e",
        hex_5: "#33434a",
        hex_6: "#446273",
        hex_7: "#6a97b6",
        hex_8: "#344e62",
        hex_9: "#944404"
      },
      {
        original_file_name: "The_Thinker (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6302270,
        file_size_megabytes: 6.01,
        width: 3072,
        height: 5472,
        primary: "#c7a890",
        secondary: "#1b1b1e",
        tertiary: "#6b5043",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#463630",
        hex_5: "#8a8b8c",
        hex_6: "#333c3e",
        hex_7: "#535c5b",
        hex_8: "#8c948e",
        hex_9: "#4e545c"
      },
      {
        original_file_name: "The_Thinker (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5762886,
        file_size_megabytes: 5.5,
        width: 3072,
        height: 5472,
        primary: "#161111",
        secondary: "#c99f7e",
        tertiary: "#6a564c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#45352f",
        hex_5: "#878681",
        hex_6: "#4f4f4e",
        hex_7: "#44444c",
        hex_8: "#7c7c84",
        hex_9: "#945430"
      },
      {
        original_file_name: "The_Thinker (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6869804,
        file_size_megabytes: 6.55,
        width: 3072,
        height: 5472,
        primary: "#d19970",
        secondary: "#1e191b",
        tertiary: "#847475",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#806050",
        hex_5: "#585e67",
        hex_6: "#40505d",
        hex_7: "#4f3125",
        hex_8: "#a4543e",
        hex_9: "#9a8c80"
      }
    ]
  },
  Timeless_Beauty: {
    environment_title: "Timeless_Beauty",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Timeless_Beauty (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5476386,
        file_size_megabytes: 5.22,
        width: 3072,
        height: 5472,
        primary: "#a68c78",
        secondary: "#604d3e",
        tertiary: "#0c0907",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#7a7d74",
        hex_5: "#34261d",
        hex_6: "#43443d",
        hex_7: "#747374",
        hex_8: "#3f3c3c",
        hex_9: "#863a38"
      },
      {
        original_file_name: "Timeless_Beauty (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6012298,
        file_size_megabytes: 5.73,
        width: 3072,
        height: 5472,
        primary: "#b9896e",
        secondary: "#845841",
        tertiary: "#150d0a",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#523425",
        hex_5: "#5c5957",
        hex_6: "#92918e",
        hex_7: "#4f4b4c",
        hex_8: "#a45c47",
        hex_9: "#86848c"
      },
      {
        original_file_name: "Timeless_Beauty (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 5642087,
        file_size_megabytes: 5.38,
        width: 3072,
        height: 5472,
        primary: "#b69580",
        secondary: "#150c08",
        tertiary: "#724e3c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#462d20",
        hex_5: "#898f88",
        hex_6: "#7f827d",
        hex_7: "#4e5248",
        hex_8: "#944c49",
        hex_9: "#464445"
      },
      {
        original_file_name: "Timeless_Beauty (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6234078,
        file_size_megabytes: 5.95,
        width: 3072,
        height: 5472,
        primary: "#c18d6f",
        secondary: "#1b0f0b",
        tertiary: "#764e3c",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#4d3124",
        hex_5: "#90776c",
        hex_6: "#584539",
        hex_7: "#886b65",
        hex_8: "#9c544c",
        hex_9: "#3b3434"
      }
    ]
  },
  Urban_Chic: {
    environment_title: "Urban_Chic",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Urban_Chic (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6638219,
        file_size_megabytes: 6.33,
        width: 3072,
        height: 5472,
        primary: "#322d2c",
        secondary: "#d3c7bd",
        tertiary: "#958173",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#586b72",
        hex_5: "#8c9fa7",
        hex_6: "#a3b0b4",
        hex_7: "#6e584a",
        hex_8: "#70848a",
        hex_9: "#bc6c40"
      },
      {
        original_file_name: "Urban_Chic (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6607279,
        file_size_megabytes: 6.3,
        width: 3072,
        height: 5472,
        primary: "#cba384",
        secondary: "#171c22",
        tertiary: "#7ca3b3",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#734e3f",
        hex_5: "#5d889a",
        hex_6: "#b04719",
        hex_7: "#44312d",
        hex_8: "#446870",
        hex_9: "#32505e"
      },
      {
        original_file_name: "Urban_Chic (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7130309,
        file_size_megabytes: 6.8,
        width: 3072,
        height: 5472,
        primary: "#2d3336",
        secondary: "#c7c4bd",
        tertiary: "#8d7d72",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#96b1b5",
        hex_5: "#516e78",
        hex_6: "#65868b",
        hex_7: "#66564c",
        hex_8: "#8ca3ad",
        hex_9: "#c34244"
      },
      {
        original_file_name: "Urban_Chic (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 6910453,
        file_size_megabytes: 6.59,
        width: 3072,
        height: 5472,
        primary: "#d2beaf",
        secondary: "#1f282e",
        tertiary: "#77655e",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#8ca3a0",
        hex_5: "#4d3d39",
        hex_6: "#516a72",
        hex_7: "#315765",
        hex_8: "#79909e",
        hex_9: "#a05031"
      }
    ]
  },
  Vibrant_Confidence: {
    environment_title: "Vibrant_Confidence",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Vibrant_Confidence (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7583716,
        file_size_megabytes: 7.23,
        width: 3072,
        height: 5472,
        primary: "#d1565d",
        secondary: "#26161b",
        tertiary: "#903e32",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#33af9a",
        hex_5: "#37643e",
        hex_6: "#672325",
        hex_7: "#451b63",
        hex_8: "#167998",
        hex_9: "#e3c782"
      },
      {
        original_file_name: "Vibrant_Confidence (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7903387,
        file_size_megabytes: 7.54,
        width: 3072,
        height: 5472,
        primary: "#cc674a",
        secondary: "#532223",
        tertiary: "#a04c42",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#879f9b",
        hex_5: "#13181b",
        hex_6: "#1c7894",
        hex_7: "#5d6d6a",
        hex_8: "#e5b190",
        hex_9: "#53345f"
      },
      {
        original_file_name: "Vibrant_Confidence (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7986923,
        file_size_megabytes: 7.62,
        width: 3072,
        height: 5472,
        primary: "#cd5b37",
        secondary: "#271616",
        tertiary: "#9f3a30",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#989b79",
        hex_5: "#782d2e",
        hex_6: "#144d7c",
        hex_7: "#5b271c",
        hex_8: "#d4b073",
        hex_9: "#306240"
      },
      {
        original_file_name: "Vibrant_Confidence (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7822282,
        file_size_megabytes: 7.46,
        width: 3072,
        height: 5472,
        primary: "#6e2827",
        secondary: "#24100d",
        tertiary: "#e56e3f",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#b8404c",
        hex_5: "#d58198",
        hex_6: "#bd845e",
        hex_7: "#935e3e",
        hex_8: "#972860",
        hex_9: "#11678c"
      }
    ]
  },
  Youthful_Joy: {
    environment_title: "Youthful_Joy",
    environment_moral: "Velit fugiat voluptate labore laboris consequat enim.",
    environment_prompt: "Duis pariatur reprehenderit sit culpa duis. Duis anim sit ea anim cupidatat pariatur nisi excepteur laboris anim officia enim irure fugiat. Sunt do aliqua Lorem commodo laborum in nulla do.",
    images: [
      {
        original_file_name: "Youthful_Joy (1).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7737838,
        file_size_megabytes: 7.38,
        width: 3072,
        height: 5472,
        primary: "#164d56",
        secondary: "#9b462e",
        tertiary: "#cfc5b8",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#e88472",
        hex_5: "#ae8d6f",
        hex_6: "#82a0a7",
        hex_7: "#542317",
        hex_8: "#80726f",
        hex_9: "#24acb8"
      },
      {
        original_file_name: "Youthful_Joy (2).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7264677,
        file_size_megabytes: 6.93,
        width: 3072,
        height: 5472,
        primary: "#252e2f",
        secondary: "#a16349",
        tertiary: "#d7cec3",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#e49057",
        hex_5: "#abafb2",
        hex_6: "#721e1e",
        hex_7: "#9c9993",
        hex_8: "#5e4a41",
        hex_9: "#2e969c"
      },
      {
        original_file_name: "Youthful_Joy (3).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7654642,
        file_size_megabytes: 7.3,
        width: 3072,
        height: 5472,
        primary: "#4fa5b7",
        secondary: "#d36e31",
        tertiary: "#8e2f15",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#104157",
        hex_5: "#6f637a",
        hex_6: "#dacac6",
        hex_7: "#77a199",
        hex_8: "#45222a",
        hex_9: "#a66e38"
      },
      {
        original_file_name: "Youthful_Joy (4).jpg",
        format: "JPEG",
        mode: "RGB",
        file_size_bytes: 7432270,
        file_size_megabytes: 7.09,
        width: 3072,
        height: 5472,
        primary: "#aebdc2",
        secondary: "#222729",
        tertiary: "#cf6e37",
        downloadLink: "https://github.com/yt-dlx/picbook/blob/",
        previewLink: "https://raw.githubusercontent.com/yt-dlx/picbook/",
        hex_4: "#552a1d",
        hex_5: "#0b8cab",
        hex_6: "#eeb274",
        hex_7: "#9c1421",
        hex_8: "#854d2d",
        hex_9: "#c89583"
      }
    ]
  }
};
export default PortraitDatabase;
